alter table public.crm_activities add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table public.crm_activities add column if not exists source_type text;
alter table public.crm_activities add column if not exists source_ref_id bigint;

create table if not exists public.crm_interest_states (
  person_id bigint not null references public.people(id) on delete cascade,
  interest_type text not null check (interest_type in ('in_person_classes','online_content','teacher_training','wedding','online_feedback','other')),
  status text not null default 'unknown' check (status in ('unknown','interested','not_interested')),
  note text,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (person_id, interest_type)
);

create table if not exists public.crm_no_booking_reasons (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.people(id) on delete cascade,
  reason_key text not null check (reason_key in ('price','own_availability','cya_availability','incompatible_schedules','location_distance','temporary_stay','later','thinking','no_longer_interested','no_response','other')),
  is_primary boolean not null default false,
  note text,
  source_type text not null default 'manual' check (source_type in ('manual','class_cancellation','system')),
  source_class_id bigint references public.classes(id) on delete set null,
  active boolean not null default true,
  first_noted_at timestamptz not null default now(),
  last_confirmed_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);
create unique index if not exists crm_no_booking_reason_active_unique on public.crm_no_booking_reasons(person_id, reason_key) where active;
create unique index if not exists crm_no_booking_primary_unique on public.crm_no_booking_reasons(person_id) where active and is_primary;

create table if not exists public.crm_saved_views (
  id bigint generated by default as identity primary key,
  owner_user_id uuid references auth.users(id) on delete cascade,
  view_key text,
  name text not null,
  filters jsonb not null default '{}'::jsonb,
  columns jsonb not null default '[]'::jsonb,
  sort jsonb not null default '[]'::jsonb,
  is_system boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((is_system and owner_user_id is null and view_key is not null) or (not is_system))
);
create unique index if not exists crm_saved_views_system_key_unique on public.crm_saved_views(view_key) where is_system and active;

alter table public.crm_interest_states enable row level security;
alter table public.crm_no_booking_reasons enable row level security;
alter table public.crm_saved_views enable row level security;

drop policy if exists crm_interest_states_staff_all on public.crm_interest_states;
create policy crm_interest_states_staff_all on public.crm_interest_states for all to authenticated using (private.is_staff()) with check (private.is_staff());
drop policy if exists crm_no_booking_reasons_staff_all on public.crm_no_booking_reasons;
create policy crm_no_booking_reasons_staff_all on public.crm_no_booking_reasons for all to authenticated using (private.is_staff()) with check (private.is_staff());
drop policy if exists crm_saved_views_staff_read on public.crm_saved_views;
create policy crm_saved_views_staff_read on public.crm_saved_views for select to authenticated using (private.is_staff() and (is_system or owner_user_id = auth.uid()));
drop policy if exists crm_saved_views_staff_insert on public.crm_saved_views;
create policy crm_saved_views_staff_insert on public.crm_saved_views for insert to authenticated with check (private.is_staff() and not is_system and owner_user_id = auth.uid());
drop policy if exists crm_saved_views_staff_update on public.crm_saved_views;
create policy crm_saved_views_staff_update on public.crm_saved_views for update to authenticated using (private.is_staff() and not is_system and owner_user_id = auth.uid()) with check (private.is_staff() and not is_system and owner_user_id = auth.uid());
drop policy if exists crm_saved_views_staff_delete on public.crm_saved_views;
create policy crm_saved_views_staff_delete on public.crm_saved_views for delete to authenticated using (private.is_staff() and not is_system and owner_user_id = auth.uid());

create or replace function public.set_crm_interest_state(p_person_id bigint, p_interest_type text, p_status text, p_note text default null)
returns public.crm_interest_states
language plpgsql security definer set search_path=public,private
as $$
declare v_old text; v_row public.crm_interest_states;
begin
  if not private.is_staff() then raise exception 'staff_required'; end if;
  if p_interest_type not in ('in_person_classes','online_content','teacher_training','wedding','online_feedback','other') then raise exception 'invalid_interest_type'; end if;
  if p_status not in ('unknown','interested','not_interested') then raise exception 'invalid_interest_status'; end if;
  select status into v_old from public.crm_interest_states where person_id=p_person_id and interest_type=p_interest_type;
  insert into public.crm_interest_states(person_id,interest_type,status,note,updated_by)
  values(p_person_id,p_interest_type,p_status,nullif(btrim(p_note),''),auth.uid())
  on conflict(person_id,interest_type) do update set status=excluded.status,note=excluded.note,updated_by=auth.uid(),updated_at=now()
  returning * into v_row;
  if v_old is distinct from p_status then
    insert into public.crm_activities(person_id,activity_type,summary,occurred_at,created_by,metadata,source_type)
    values(p_person_id,'interest_changed','Interés actualizado',now(),auth.uid(),jsonb_build_object('interest_type',p_interest_type,'from',v_old,'to',p_status),'crm_interest');
  end if;
  return v_row;
end $$;

create or replace function public.set_crm_no_booking_reason(p_person_id bigint, p_reason_key text, p_active boolean default true, p_is_primary boolean default false, p_note text default null, p_source_type text default 'manual', p_source_class_id bigint default null)
returns public.crm_no_booking_reasons
language plpgsql security definer set search_path=public,private
as $$
declare v_row public.crm_no_booking_reasons;
begin
  if not private.is_staff() then raise exception 'staff_required'; end if;
  if p_reason_key not in ('price','own_availability','cya_availability','incompatible_schedules','location_distance','temporary_stay','later','thinking','no_longer_interested','no_response','other') then raise exception 'invalid_no_booking_reason'; end if;
  if p_source_type not in ('manual','class_cancellation','system') then raise exception 'invalid_source_type'; end if;
  if p_is_primary and p_active then update public.crm_no_booking_reasons set is_primary=false,updated_at=now() where person_id=p_person_id and active and is_primary; end if;
  select * into v_row from public.crm_no_booking_reasons where person_id=p_person_id and reason_key=p_reason_key and active limit 1;
  if found then
    update public.crm_no_booking_reasons set active=p_active,is_primary=(p_is_primary and p_active),note=nullif(btrim(p_note),''),source_type=p_source_type,source_class_id=p_source_class_id,last_confirmed_at=now(),updated_at=now() where id=v_row.id returning * into v_row;
  elsif p_active then
    insert into public.crm_no_booking_reasons(person_id,reason_key,is_primary,note,source_type,source_class_id,created_by)
    values(p_person_id,p_reason_key,p_is_primary,nullif(btrim(p_note),''),p_source_type,p_source_class_id,auth.uid()) returning * into v_row;
  else
    raise exception 'reason_not_found';
  end if;
  insert into public.crm_activities(person_id,activity_type,summary,occurred_at,created_by,metadata,source_type,source_ref_id)
  values(p_person_id,case when p_active then 'no_booking_reason_set' else 'no_booking_reason_cleared' end,'Motivo de no reserva actualizado',now(),auth.uid(),jsonb_build_object('reason',p_reason_key,'active',p_active,'primary',p_is_primary,'note',nullif(btrim(p_note),'')),p_source_type,p_source_class_id);
  return v_row;
end $$;

revoke all on function public.set_crm_interest_state(bigint,text,text,text) from public, anon;
grant execute on function public.set_crm_interest_state(bigint,text,text,text) to authenticated;
revoke all on function public.set_crm_no_booking_reason(bigint,text,boolean,boolean,text,text,bigint) from public, anon;
grant execute on function public.set_crm_no_booking_reason(bigint,text,boolean,boolean,text,text,bigint) to authenticated;

create or replace view public.crm_person_explorer_v with (security_invoker=true) as
with class_facts as (
  select cp.person_id,
    count(*) filter (where c.status <> 'cancelled')::int as reservation_count,
    min(c.scheduled_start_at) filter (where c.status <> 'cancelled' and c.scheduled_start_at >= now()) as next_class_at,
    max(c.scheduled_start_at) filter (where c.status in ('active','finished') or (c.status='scheduled' and c.scheduled_start_at < now())) as last_class_at,
    count(*) filter (where c.status='cancelled')::int as cancelled_count
  from public.class_participants cp join public.classes c on c.id=cp.class_id group by cp.person_id
), interests as (
  select person_id,
    jsonb_object_agg(interest_type,status) as interest_states,
    bool_or(status='interested') as has_any_interest,
    bool_or(interest_type='in_person_classes' and status='interested') as interested_in_person_classes
  from public.crm_interest_states group by person_id
), reasons as (
  select person_id,
    jsonb_agg(jsonb_build_object('reason_key',reason_key,'is_primary',is_primary,'note',note,'source_type',source_type,'source_class_id',source_class_id,'last_confirmed_at',last_confirmed_at) order by is_primary desc,last_confirmed_at desc) filter (where active) as no_booking_reasons,
    max(reason_key) filter (where active and is_primary) as primary_no_booking_reason
  from public.crm_no_booking_reasons group by person_id
)
select p.id as person_id,p.display_name,p.first_name,p.last_name,p.internal_alias,p.email,p.phone,p.country_code,p.instagram_handle,p.crm_stage,p.source,p.auth_user_id is not null as is_registered,p.created_at as person_created_at,
  sp.city,sp.birth_date,
  case when sp.birth_date is null then null else extract(year from age(current_date,sp.birth_date))::int end as age,
  coalesce(cf.reservation_count,0) as reservation_count,coalesce(cf.reservation_count,0)>0 as has_reserved,cf.next_class_at,cf.last_class_at,coalesce(cf.cancelled_count,0) as cancelled_count,
  coalesce(i.interest_states,'{}'::jsonb) as interest_states,coalesce(i.has_any_interest,false) as has_any_interest,coalesce(i.interested_in_person_classes,false) as interested_in_person_classes,
  coalesce(r.no_booking_reasons,'[]'::jsonb) as no_booking_reasons,r.primary_no_booking_reason,
  (coalesce(i.interested_in_person_classes,false) and coalesce(cf.reservation_count,0)=0) as interested_without_booking,
  (coalesce(i.interested_in_person_classes,false) and coalesce(cf.reservation_count,0)=0 and r.primary_no_booking_reason is null) as no_booking_reason_missing
from public.people p
left join public.student_profiles sp on sp.person_id=p.id
left join class_facts cf on cf.person_id=p.id
left join interests i on i.person_id=p.id
left join reasons r on r.person_id=p.id
where p.active;

insert into public.crm_saved_views(view_key,name,filters,columns,sort,is_system)
values
('new_unclassified','Nuevos registros por clasificar','{"registered":true,"interest_classified":false}'::jsonb,'["display_name","phone","email","person_created_at"]'::jsonb,'[{"field":"person_created_at","direction":"desc"}]'::jsonb,true),
('interested_no_booking','Interesados sin reserva','{"interested_in_person_classes":true,"has_reserved":false}'::jsonb,'["display_name","phone","primary_no_booking_reason","person_created_at"]'::jsonb,'[{"field":"person_created_at","direction":"asc"}]'::jsonb,true),
('interested_no_booking_missing_reason','Sin reserva · falta motivo','{"interested_in_person_classes":true,"has_reserved":false,"no_booking_reason_missing":true}'::jsonb,'["display_name","phone","person_created_at"]'::jsonb,'[{"field":"person_created_at","direction":"asc"}]'::jsonb,true),
('lost_price','Sin reserva · precio','{"has_reserved":false,"primary_no_booking_reason":"price"}'::jsonb,'["display_name","phone","primary_no_booking_reason"]'::jsonb,'[{"field":"display_name","direction":"asc"}]'::jsonb,true),
('lost_schedule','Sin reserva · horarios','{"has_reserved":false,"primary_no_booking_reason":"incompatible_schedules"}'::jsonb,'["display_name","phone","primary_no_booking_reason"]'::jsonb,'[{"field":"display_name","direction":"asc"}]'::jsonb,true),
('lost_location','Sin reserva · localidad/distancia','{"has_reserved":false,"primary_no_booking_reason":"location_distance"}'::jsonb,'["display_name","phone","city","primary_no_booking_reason"]'::jsonb,'[{"field":"display_name","direction":"asc"}]'::jsonb,true)
on conflict do nothing;
