create table if not exists public.crm_stat_panels (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null default auth.uid(),
  title text not null,
  description text,
  metric_key text not null,
  filters jsonb not null default '{}'::jsonb,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint crm_stat_panels_title_check check (char_length(btrim(title)) between 1 and 120),
  constraint crm_stat_panels_metric_check check (metric_key in ('people_count','percentage_total','average_age','reserved_count','reservation_rate','next_class_count','questionnaire_pending_count')),
  constraint crm_stat_panels_filters_object_check check (jsonb_typeof(filters) = 'object')
);

create index if not exists crm_stat_panels_owner_order_idx on public.crm_stat_panels(owner_user_id, display_order, id);

alter table public.crm_stat_panels enable row level security;

drop policy if exists crm_stat_panels_staff_select on public.crm_stat_panels;
create policy crm_stat_panels_staff_select on public.crm_stat_panels for select to authenticated using (private.is_staff() and owner_user_id = auth.uid());
drop policy if exists crm_stat_panels_staff_insert on public.crm_stat_panels;
create policy crm_stat_panels_staff_insert on public.crm_stat_panels for insert to authenticated with check (private.is_staff() and owner_user_id = auth.uid());
drop policy if exists crm_stat_panels_staff_update on public.crm_stat_panels;
create policy crm_stat_panels_staff_update on public.crm_stat_panels for update to authenticated using (private.is_staff() and owner_user_id = auth.uid()) with check (private.is_staff() and owner_user_id = auth.uid());
drop policy if exists crm_stat_panels_staff_delete on public.crm_stat_panels;
create policy crm_stat_panels_staff_delete on public.crm_stat_panels for delete to authenticated using (private.is_staff() and owner_user_id = auth.uid());

create or replace function public.crm_stat_panels_snapshot()
returns setof public.crm_stat_panels
language sql
security definer
set search_path = public, private
as $$
  select p.* from public.crm_stat_panels p
  where private.is_staff() and p.owner_user_id = auth.uid()
  order by p.display_order, p.id;
$$;

create or replace function public.save_crm_stat_panel(
  p_panel_id bigint,
  p_title text,
  p_description text,
  p_metric_key text,
  p_filters jsonb,
  p_display_order integer default 0
)
returns bigint
language plpgsql
security definer
set search_path = public, private
as $$
declare
  v_id bigint;
begin
  if not private.is_staff() then raise exception 'staff only'; end if;
  if btrim(coalesce(p_title,'')) = '' then raise exception 'title required'; end if;
  if p_metric_key not in ('people_count','percentage_total','average_age','reserved_count','reservation_rate','next_class_count','questionnaire_pending_count') then raise exception 'invalid metric'; end if;
  if jsonb_typeof(coalesce(p_filters,'{}'::jsonb)) <> 'object' then raise exception 'invalid filters'; end if;

  if p_panel_id is null then
    insert into public.crm_stat_panels(owner_user_id,title,description,metric_key,filters,display_order)
    values(auth.uid(), btrim(p_title), nullif(btrim(coalesce(p_description,'')),''), p_metric_key, coalesce(p_filters,'{}'::jsonb), greatest(coalesce(p_display_order,0),0))
    returning id into v_id;
  else
    update public.crm_stat_panels
      set title=btrim(p_title), description=nullif(btrim(coalesce(p_description,'')),''), metric_key=p_metric_key,
          filters=coalesce(p_filters,'{}'::jsonb), display_order=greatest(coalesce(p_display_order,0),0), updated_at=now()
    where id=p_panel_id and owner_user_id=auth.uid()
    returning id into v_id;
    if v_id is null then raise exception 'panel not found'; end if;
  end if;
  return v_id;
end;
$$;

create or replace function public.delete_crm_stat_panel(p_panel_id bigint)
returns void
language plpgsql
security definer
set search_path = public, private
as $$
begin
  if not private.is_staff() then raise exception 'staff only'; end if;
  delete from public.crm_stat_panels where id=p_panel_id and owner_user_id=auth.uid();
end;
$$;

revoke all on function public.crm_stat_panels_snapshot() from public, anon;
revoke all on function public.save_crm_stat_panel(bigint,text,text,text,jsonb,integer) from public, anon;
revoke all on function public.delete_crm_stat_panel(bigint) from public, anon;
grant execute on function public.crm_stat_panels_snapshot() to authenticated;
grant execute on function public.save_crm_stat_panel(bigint,text,text,text,jsonb,integer) to authenticated;
grant execute on function public.delete_crm_stat_panel(bigint) to authenticated;
