-- P30A — Esquema de paneles estadísticos configurables.

create table if not exists public.statistics_dashboards (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 1 and 80),
  description text,
  scope text not null default 'global' check (scope in ('global','teacher','personal')),
  target_user_id uuid references auth.users(id) on delete cascade,
  active boolean not null default true,
  is_default boolean not null default false,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((scope='global' and target_user_id is null) or (scope in ('teacher','personal') and target_user_id is not null))
);

create table if not exists public.statistics_dashboard_cards (
  id bigint generated by default as identity primary key,
  dashboard_id bigint not null references public.statistics_dashboards(id) on delete cascade,
  title text not null check (char_length(btrim(title)) between 1 and 100),
  metric_key text not null,
  period_kind text not null default 'rolling_days' check (period_kind in ('today','this_week','this_month','this_year','rolling_days','custom')),
  period_days integer check (period_days is null or period_days between 1 and 3650),
  filters jsonb not null default '{}'::jsonb check (jsonb_typeof(filters)='object'),
  comparison_kind text not null default 'previous_period' check (comparison_kind in ('none','previous_period','previous_year')),
  display_kind text not null default 'number' check (display_kind in ('number','currency','minutes','percentage','trend')),
  position integer not null default 0 check (position between 0 and 999),
  width text not null default 'small' check (width in ('small','medium','large','full')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists statistics_dashboards_target_idx on public.statistics_dashboards(scope,target_user_id,active);
create index if not exists statistics_dashboard_cards_dashboard_idx on public.statistics_dashboard_cards(dashboard_id,position) where active;

alter table public.statistics_dashboards enable row level security;
alter table public.statistics_dashboard_cards enable row level security;

drop policy if exists statistics_dashboards_staff_read on public.statistics_dashboards;
create policy statistics_dashboards_staff_read on public.statistics_dashboards for select to authenticated using (private.is_staff());
drop policy if exists statistics_dashboards_admin_write on public.statistics_dashboards;
create policy statistics_dashboards_admin_write on public.statistics_dashboards for all to authenticated using (private.is_admin()) with check (private.is_admin());
drop policy if exists statistics_dashboard_cards_staff_read on public.statistics_dashboard_cards;
create policy statistics_dashboard_cards_staff_read on public.statistics_dashboard_cards for select to authenticated using (private.is_staff());
drop policy if exists statistics_dashboard_cards_admin_write on public.statistics_dashboard_cards;
create policy statistics_dashboard_cards_admin_write on public.statistics_dashboard_cards for all to authenticated using (private.is_admin()) with check (private.is_admin());

comment on table public.statistics_dashboards is 'P30 configurable dashboards: global, teacher-assigned or personal.';
comment on table public.statistics_dashboard_cards is 'P30 declarative statistic cards. No SQL expressions are stored.';
