-- PR-B / v76 — BZ Points and rewards.
-- Separate from pedagogical evaluation points. All balances derive from an immutable ledger.
-- No historical class/credit/exercise backfill: rule active_from gates automatic reconciliation.

create table if not exists public.bz_point_rules (
  rule_key text primary key,
  label text not null,
  description text,
  points integer not null check (points between 0 and 1000000),
  trigger_mode text not null check (trigger_mode in ('automatic','student_action')),
  active boolean not null default true,
  active_from timestamptz not null default now(),
  sort_order integer not null default 100,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bz_point_ledger (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.people(id) on delete restrict,
  rule_key text references public.bz_point_rules(rule_key) on delete restrict,
  entry_type text not null check (entry_type in ('earn','redeem','adjustment','reversal')),
  points_delta integer not null check (points_delta <> 0 and points_delta between -1000000 and 1000000),
  source_type text not null,
  source_id text,
  idempotency_key text not null unique,
  detail jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists bz_point_ledger_person_created_idx on public.bz_point_ledger(person_id,created_at desc,id desc);
create index if not exists bz_point_ledger_rule_idx on public.bz_point_ledger(rule_key,created_at desc);

create table if not exists public.bz_action_events (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.people(id) on delete cascade,
  action_key text not null check (action_key in ('daily_login','previous_class_review','next_class_content_choice')),
  local_date date not null,
  class_id bigint references public.classes(id) on delete cascade,
  content_id bigint references public.teaching_contents(id) on delete set null,
  idempotency_key text not null unique,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists bz_action_events_person_date_idx on public.bz_action_events(person_id,local_date desc,action_key);

create table if not exists public.bz_rewards (
  id bigint generated by default as identity primary key,
  reward_key text not null unique,
  name text not null,
  description text,
  reward_type text not null default 'discount_coupon' check (reward_type='discount_coupon'),
  cost_points integer not null check (cost_points > 0),
  discount_kind text not null check (discount_kind in ('fixed_cents','percent')),
  discount_value integer not null check (discount_value > 0),
  currency text not null default 'EUR' check (char_length(currency)=3),
  active boolean not null default true,
  sort_order integer not null default 100,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((discount_kind='percent' and discount_value <= 100) or discount_kind='fixed_cents')
);

create table if not exists public.bz_reward_redemptions (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.people(id) on delete restrict,
  reward_id bigint not null references public.bz_rewards(id) on delete restrict,
  reward_name text not null,
  cost_points integer not null check (cost_points > 0),
  discount_kind text not null check (discount_kind in ('fixed_cents','percent')),
  discount_value integer not null check (discount_value > 0),
  currency text not null,
  coupon_code text not null unique,
  status text not null default 'issued' check (status in ('issued','redeemed','cancelled')),
  redeemed_at timestamptz,
  cancelled_at timestamptz,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists bz_reward_redemptions_person_created_idx on public.bz_reward_redemptions(person_id,created_at desc,id desc);

insert into public.bz_point_rules(rule_key,label,description,points,trigger_mode,active,sort_order)
values
  ('registration','Registrarse','Se concede una sola vez cuando una persona queda registrada como alumno.',100,'automatic',true,10),
  ('daily_login','Entrar en CYA','Una vez por día local al entrar en CYA Hub.',5,'student_action',true,20),
  ('bonus_purchase','Comprar un bono','Una vez por bono pagado con importe superior a cero.',100,'automatic',true,30),
  ('class_attended','Realizar una clase','Una vez por clase finalizada con asistencia presente.',50,'automatic',true,40),
  ('exercise_completed','Realizar un ejercicio','Una vez por ejercicio distinto completado por el alumno.',25,'automatic',true,50),
  ('previous_class_review','Repasar la clase anterior','Una vez al día antes de la próxima clase.',10,'student_action',true,60),
  ('next_class_content_choice','Elegir contenido para la siguiente clase','Una vez por próxima clase, aunque el alumno cambie después su elección.',10,'student_action',true,70)
on conflict(rule_key) do nothing;

alter table public.bz_point_rules enable row level security;
alter table public.bz_point_ledger enable row level security;
alter table public.bz_action_events enable row level security;
alter table public.bz_rewards enable row level security;
alter table public.bz_reward_redemptions enable row level security;

drop policy if exists bz_point_rules_read on public.bz_point_rules;
create policy bz_point_rules_read on public.bz_point_rules for select to authenticated using (true);

drop policy if exists bz_point_ledger_read on public.bz_point_ledger;
create policy bz_point_ledger_read on public.bz_point_ledger for select to authenticated
using (person_id=(select private.current_person_id()) or (select private.is_staff()));

drop policy if exists bz_action_events_read on public.bz_action_events;
create policy bz_action_events_read on public.bz_action_events for select to authenticated
using (person_id=(select private.current_person_id()) or (select private.is_staff()));

drop policy if exists bz_rewards_read on public.bz_rewards;
create policy bz_rewards_read on public.bz_rewards for select to authenticated
using (active or (select private.is_admin()));

drop policy if exists bz_reward_redemptions_read on public.bz_reward_redemptions;
create policy bz_reward_redemptions_read on public.bz_reward_redemptions for select to authenticated
using (person_id=(select private.current_person_id()) or (select private.is_staff()));

revoke insert,update,delete on public.bz_point_rules from authenticated;
revoke insert,update,delete on public.bz_point_ledger from authenticated;
revoke insert,update,delete on public.bz_action_events from authenticated;
revoke insert,update,delete on public.bz_rewards from authenticated;
revoke insert,update,delete on public.bz_reward_redemptions from authenticated;
grant select on public.bz_point_rules,public.bz_point_ledger,public.bz_action_events,public.bz_rewards,public.bz_reward_redemptions to authenticated;

create or replace function private.bz_local_date()
returns date
language plpgsql
stable
security definer
set search_path=''
as $$
declare
  v_timezone text;
begin
  select coalesce(p.timezone,'Europe/Madrid') into v_timezone
  from public.user_preferences p
  where p.user_id=(select auth.uid());
  v_timezone:=coalesce(v_timezone,'Europe/Madrid');
  begin
    return (now() at time zone v_timezone)::date;
  exception when invalid_parameter_value then
    return (now() at time zone 'Europe/Madrid')::date;
  end;
end;
$$;

create or replace function private.bz_award(
  p_person_id bigint,
  p_rule_key text,
  p_source_type text,
  p_source_id text,
  p_idempotency_key text,
  p_detail jsonb default '{}'::jsonb,
  p_event_at timestamptz default now()
)
returns bigint
language plpgsql
security definer
set search_path=''
as $$
declare
  v_rule public.bz_point_rules;
  v_id bigint;
begin
  if p_person_id is null or p_idempotency_key is null or nullif(btrim(p_idempotency_key),'') is null then
    return null;
  end if;
  select * into v_rule from public.bz_point_rules where rule_key=p_rule_key;
  if not found or not v_rule.active or v_rule.points<=0 or coalesce(p_event_at,now()) < v_rule.active_from then
    return null;
  end if;
  if not exists(select 1 from public.people p where p.id=p_person_id and p.active) then return null; end if;
  insert into public.bz_point_ledger(person_id,rule_key,entry_type,points_delta,source_type,source_id,idempotency_key,detail,created_by)
  values(p_person_id,p_rule_key,'earn',v_rule.points,p_source_type,p_source_id,p_idempotency_key,
         coalesce(p_detail,'{}'::jsonb)||jsonb_build_object('rule_label',v_rule.label,'rule_points',v_rule.points),
         (select auth.uid()))
  on conflict(idempotency_key) do nothing
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function private.bz_reconcile_registration(p_person_id bigint)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare v_event_at timestamptz;
begin
  select greatest(p.updated_at,sp.created_at) into v_event_at
  from public.people p join public.student_profiles sp on sp.person_id=p.id and sp.active
  where p.id=p_person_id and p.active and p.auth_user_id is not null;
  if v_event_at is null then return; end if;
  perform private.bz_award(p_person_id,'registration','person',p_person_id::text,'bz:registration:'||p_person_id,
    jsonb_build_object('person_id',p_person_id),v_event_at);
end;
$$;

create or replace function private.bz_reconcile_credit_grant(p_grant_id bigint)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare v_grant public.credit_grants; v_member record;
begin
  select * into v_grant from public.credit_grants where id=p_grant_id;
  if not found or v_grant.payment_status<>'paid' or v_grant.price_cents<=0 then return; end if;
  for v_member in select person_id from public.credit_grant_members where grant_id=p_grant_id loop
    perform private.bz_award(v_member.person_id,'bonus_purchase','credit_grant',p_grant_id::text,
      'bz:bonus:'||p_grant_id||':'||v_member.person_id,
      jsonb_build_object('grant_id',p_grant_id,'price_cents',v_grant.price_cents,'modality',v_grant.modality),v_grant.purchased_at);
  end loop;
end;
$$;

create or replace function private.bz_reconcile_class(p_class_id bigint)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare v_class public.classes; v_participant record;
begin
  select * into v_class from public.classes where id=p_class_id;
  if not found or v_class.status<>'finished' or v_class.administrative_finished_at is null then return; end if;
  for v_participant in select person_id from public.class_participants where class_id=p_class_id and attendance_status='present' loop
    perform private.bz_award(v_participant.person_id,'class_attended','class',p_class_id::text,
      'bz:class:'||p_class_id||':'||v_participant.person_id,
      jsonb_build_object('class_id',p_class_id,'duration_minutes',v_class.actual_duration_minutes),v_class.administrative_finished_at);
  end loop;
end;
$$;

create or replace function private.bz_reconcile_exercise(p_person_id bigint,p_content_id bigint)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare v_event_at timestamptz;
begin
  if not exists(select 1 from public.teaching_contents t where t.id=p_content_id and t.active and t.content_type='exercise') then return; end if;
  select max(event_at) into v_event_at from (
    select a.completed_at as event_at
    from public.student_content_assignments a
    where a.person_id=p_person_id and a.content_id=p_content_id and a.assignment_status='completed' and a.completed_at is not null
    union all
    select e.created_at
    from public.class_content_events e
    where e.person_id=p_person_id and e.content_id=p_content_id and e.event_type='exercise_completed'
  ) q;
  if v_event_at is null then return; end if;
  perform private.bz_award(p_person_id,'exercise_completed','teaching_content',p_content_id::text,
    'bz:exercise:'||p_person_id||':'||p_content_id,
    jsonb_build_object('person_id',p_person_id,'content_id',p_content_id),v_event_at);
end;
$$;

create or replace function private.bz_registration_trigger()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  perform private.bz_reconcile_registration(case when tg_table_name='people' then new.id else new.person_id end);
  return new;
end;
$$;

drop trigger if exists bz_people_registration on public.people;
create trigger bz_people_registration after insert or update of auth_user_id,active,updated_at on public.people
for each row execute function private.bz_registration_trigger();

drop trigger if exists bz_student_profile_registration on public.student_profiles;
create trigger bz_student_profile_registration after insert or update of active on public.student_profiles
for each row execute function private.bz_registration_trigger();

create or replace function private.bz_credit_grant_trigger()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  perform private.bz_reconcile_credit_grant(case when tg_table_name='credit_grants' then new.id else new.grant_id end);
  return new;
end;
$$;

drop trigger if exists bz_credit_grant_award on public.credit_grants;
create trigger bz_credit_grant_award after insert or update of payment_status,price_cents,purchased_at,status on public.credit_grants
for each row execute function private.bz_credit_grant_trigger();

drop trigger if exists bz_credit_grant_member_award on public.credit_grant_members;
create trigger bz_credit_grant_member_award after insert or update of person_id,grant_id on public.credit_grant_members
for each row execute function private.bz_credit_grant_trigger();

create or replace function private.bz_class_trigger()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  perform private.bz_reconcile_class(case when tg_table_name='classes' then new.id else new.class_id end);
  return new;
end;
$$;

drop trigger if exists bz_class_award on public.classes;
create trigger bz_class_award after insert or update of status,administrative_finished_at on public.classes
for each row execute function private.bz_class_trigger();

drop trigger if exists bz_class_participant_award on public.class_participants;
create trigger bz_class_participant_award after insert or update of attendance_status,person_id,class_id on public.class_participants
for each row execute function private.bz_class_trigger();

create or replace function private.bz_assignment_trigger()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  perform private.bz_reconcile_exercise(new.person_id,new.content_id);
  return new;
end;
$$;

drop trigger if exists bz_assignment_exercise_award on public.student_content_assignments;
create trigger bz_assignment_exercise_award after insert or update of assignment_status,completed_at on public.student_content_assignments
for each row execute function private.bz_assignment_trigger();

create or replace function private.bz_class_content_event_trigger()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  if new.event_type='exercise_completed' then perform private.bz_reconcile_exercise(new.person_id,new.content_id); end if;
  return new;
end;
$$;

drop trigger if exists bz_class_content_exercise_award on public.class_content_events;
create trigger bz_class_content_exercise_award after insert on public.class_content_events
for each row execute function private.bz_class_content_event_trigger();

create or replace function public.bz_record_daily_login()
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_person bigint:=(select private.current_person_id()); v_date date:=(select private.bz_local_date()); v_action_id bigint; v_ledger_id bigint;
begin
  if v_person is null then raise exception 'Necesitas un perfil de alumno activo.' using errcode='42501'; end if;
  insert into public.bz_action_events(person_id,action_key,local_date,idempotency_key,evidence)
  values(v_person,'daily_login',v_date,'bz-action:daily-login:'||v_person||':'||v_date,jsonb_build_object('local_date',v_date))
  on conflict(idempotency_key) do nothing returning id into v_action_id;
  v_ledger_id:=private.bz_award(v_person,'daily_login','daily_login',v_date::text,
    'bz:daily-login:'||v_person||':'||v_date,jsonb_build_object('local_date',v_date),now());
  return jsonb_build_object('person_id',v_person,'local_date',v_date,'action_created',v_action_id is not null,'points_awarded',v_ledger_id is not null);
end;
$$;

create or replace function private.bz_validate_next_class(p_person_id bigint,p_class_id bigint)
returns public.classes
language plpgsql
stable
security definer
set search_path=''
as $$
declare v_class public.classes;
begin
  select c.* into v_class
  from public.classes c join public.class_participants cp on cp.class_id=c.id and cp.person_id=p_person_id
  where c.id=p_class_id and c.scheduled_start_at>now() and c.status not in ('finished','cancelled') and cp.attendance_status<>'absent';
  if not found then raise exception 'La clase indicada no es una próxima clase disponible.' using errcode='42501'; end if;
  if exists(
    select 1 from public.classes earlier join public.class_participants ep on ep.class_id=earlier.id and ep.person_id=p_person_id
    where earlier.scheduled_start_at>now() and earlier.scheduled_start_at<v_class.scheduled_start_at
      and earlier.status not in ('finished','cancelled') and ep.attendance_status<>'absent'
  ) then raise exception 'Solo puedes preparar tu próxima clase.' using errcode='42501'; end if;
  return v_class;
end;
$$;

create or replace function public.bz_confirm_previous_class_review(p_class_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_person bigint:=(select private.current_person_id());
  v_date date:=(select private.bz_local_date());
  v_class public.classes;
  v_previous_id bigint;
  v_action_id bigint;
  v_ledger_id bigint;
begin
  if v_person is null then raise exception 'Necesitas un perfil de alumno activo.' using errcode='42501'; end if;
  v_class:=private.bz_validate_next_class(v_person,p_class_id);
  select c.id into v_previous_id
  from public.classes c join public.class_participants cp on cp.class_id=c.id and cp.person_id=v_person
  where c.status='finished' and cp.attendance_status='present' and c.scheduled_start_at<v_class.scheduled_start_at
  order by c.scheduled_start_at desc limit 1;
  if v_previous_id is null then raise exception 'Todavía no hay una clase anterior que repasar.' using errcode='22023'; end if;
  insert into public.bz_action_events(person_id,action_key,local_date,class_id,idempotency_key,evidence)
  values(v_person,'previous_class_review',v_date,p_class_id,'bz-action:review:'||v_person||':'||v_date,
    jsonb_build_object('next_class_id',p_class_id,'previous_class_id',v_previous_id))
  on conflict(idempotency_key) do nothing returning id into v_action_id;
  v_ledger_id:=private.bz_award(v_person,'previous_class_review','class',p_class_id::text,
    'bz:review:'||v_person||':'||v_date,jsonb_build_object('next_class_id',p_class_id,'previous_class_id',v_previous_id,'local_date',v_date),now());
  return jsonb_build_object('class_id',p_class_id,'previous_class_id',v_previous_id,'local_date',v_date,'action_created',v_action_id is not null,'points_awarded',v_ledger_id is not null);
end;
$$;

create or replace function public.bz_choose_next_class_content(p_class_id bigint,p_content_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_person bigint:=(select private.current_person_id());
  v_date date:=(select private.bz_local_date());
  v_class public.classes;
  v_content public.teaching_contents;
  v_action_id bigint;
  v_ledger_id bigint;
  v_request_id bigint;
begin
  if v_person is null then raise exception 'Necesitas un perfil de alumno activo.' using errcode='42501'; end if;
  v_class:=private.bz_validate_next_class(v_person,p_class_id);
  select * into v_content from public.teaching_contents
  where id=p_content_id and active and completion_status='complete' and publication_status='published' and visibility='student';
  if not found then raise exception 'Ese contenido no está disponible para el alumno.' using errcode='42501'; end if;

  select id into v_request_id from public.class_preparation_requests
  where class_id=p_class_id and person_id=v_person and request_type='content'
  order by created_at desc limit 1 for update;
  if v_request_id is null then
    insert into public.class_preparation_requests(class_id,person_id,request_type,content_id,body,created_by)
    values(p_class_id,v_person,'content',p_content_id,v_content.title,(select auth.uid())) returning id into v_request_id;
  else
    update public.class_preparation_requests set content_id=p_content_id,body=v_content.title,updated_at=now(),created_by=(select auth.uid())
    where id=v_request_id;
  end if;

  insert into public.bz_action_events(person_id,action_key,local_date,class_id,content_id,idempotency_key,evidence)
  values(v_person,'next_class_content_choice',v_date,p_class_id,p_content_id,
    'bz-action:content-choice:'||v_person||':'||p_class_id,jsonb_build_object('class_id',p_class_id,'content_id',p_content_id))
  on conflict(idempotency_key) do update set content_id=excluded.content_id,evidence=excluded.evidence,updated_at=now()
  returning id into v_action_id;

  v_ledger_id:=private.bz_award(v_person,'next_class_content_choice','class',p_class_id::text,
    'bz:content-choice:'||v_person||':'||p_class_id,jsonb_build_object('class_id',p_class_id,'content_id',p_content_id),now());
  return jsonb_build_object('class_id',p_class_id,'content_id',p_content_id,'request_id',v_request_id,'action_id',v_action_id,'points_awarded',v_ledger_id is not null);
end;
$$;

create or replace function public.bz_snapshot()
returns jsonb
language plpgsql
stable
security definer
set search_path=''
as $$
declare
  v_person bigint:=(select private.current_person_id());
  v_date date:=(select private.bz_local_date());
  v_next_class bigint;
  v_next_start timestamptz;
  v_selected_content bigint;
begin
  if v_person is null then raise exception 'Necesitas un perfil de alumno activo.' using errcode='42501'; end if;
  select c.id,c.scheduled_start_at into v_next_class,v_next_start
  from public.classes c join public.class_participants cp on cp.class_id=c.id and cp.person_id=v_person
  where c.scheduled_start_at>now() and c.status not in ('finished','cancelled') and cp.attendance_status<>'absent'
  order by c.scheduled_start_at limit 1;
  if v_next_class is not null then
    select r.content_id into v_selected_content from public.class_preparation_requests r
    where r.class_id=v_next_class and r.person_id=v_person and r.request_type='content'
    order by r.updated_at desc limit 1;
  end if;
  return jsonb_build_object(
    'person_id',v_person,
    'balance_points',coalesce((select sum(l.points_delta) from public.bz_point_ledger l where l.person_id=v_person),0),
    'earned_points',coalesce((select sum(l.points_delta) from public.bz_point_ledger l where l.person_id=v_person and l.points_delta>0),0),
    'spent_points',coalesce((select -sum(l.points_delta) from public.bz_point_ledger l where l.person_id=v_person and l.points_delta<0),0),
    'today',v_date,
    'daily_login_recorded',exists(select 1 from public.bz_action_events a where a.person_id=v_person and a.action_key='daily_login' and a.local_date=v_date),
    'previous_review_recorded',exists(select 1 from public.bz_action_events a where a.person_id=v_person and a.action_key='previous_class_review' and a.local_date=v_date),
    'next_class',case when v_next_class is null then null else jsonb_build_object('id',v_next_class,'scheduled_start_at',v_next_start,'selected_content_id',v_selected_content) end,
    'rules',(select coalesce(jsonb_agg(jsonb_build_object('rule_key',r.rule_key,'label',r.label,'description',r.description,'points',r.points,'active',r.active) order by r.sort_order,r.rule_key),'[]'::jsonb) from public.bz_point_rules r),
    'recent_ledger',(select coalesce(jsonb_agg(x order by x.created_at desc,x.id desc),'[]'::jsonb) from (select l.id,l.rule_key,l.entry_type,l.points_delta,l.source_type,l.source_id,l.detail,l.created_at from public.bz_point_ledger l where l.person_id=v_person order by l.created_at desc,l.id desc limit 30) x),
    'rewards',(select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'name',r.name,'description',r.description,'cost_points',r.cost_points,'discount_kind',r.discount_kind,'discount_value',r.discount_value,'currency',r.currency) order by r.sort_order,r.id),'[]'::jsonb) from public.bz_rewards r where r.active),
    'redemptions',(select coalesce(jsonb_agg(x order by x.created_at desc,x.id desc),'[]'::jsonb) from (select d.id,d.reward_id,d.reward_name,d.cost_points,d.discount_kind,d.discount_value,d.currency,d.coupon_code,d.status,d.created_at from public.bz_reward_redemptions d where d.person_id=v_person order by d.created_at desc,d.id desc limit 20) x)
  );
end;
$$;

create or replace function public.bz_redeem_reward(p_reward_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_person bigint:=(select private.current_person_id());
  v_reward public.bz_rewards;
  v_balance bigint;
  v_redemption_id bigint;
  v_code text;
begin
  if v_person is null then raise exception 'Necesitas un perfil de alumno activo.' using errcode='42501'; end if;
  perform pg_advisory_xact_lock(hashtextextended('bz-person:'||v_person,0));
  select * into v_reward from public.bz_rewards where id=p_reward_id and active for share;
  if not found then raise exception 'La recompensa ya no está disponible.' using errcode='P0002'; end if;
  select coalesce(sum(points_delta),0) into v_balance from public.bz_point_ledger where person_id=v_person;
  if v_balance<v_reward.cost_points then raise exception 'No tienes suficientes BZ Points para esta recompensa.' using errcode='22023'; end if;
  v_code:='CYA-'||upper(substr(md5(v_person::text||':'||p_reward_id||':'||clock_timestamp()::text||':'||random()::text),1,10));
  insert into public.bz_reward_redemptions(person_id,reward_id,reward_name,cost_points,discount_kind,discount_value,currency,coupon_code)
  values(v_person,v_reward.id,v_reward.name,v_reward.cost_points,v_reward.discount_kind,v_reward.discount_value,v_reward.currency,v_code)
  returning id into v_redemption_id;
  insert into public.bz_point_ledger(person_id,rule_key,entry_type,points_delta,source_type,source_id,idempotency_key,detail,created_by)
  values(v_person,null,'redeem',-v_reward.cost_points,'reward_redemption',v_redemption_id::text,'bz:redemption:'||v_redemption_id,
    jsonb_build_object('reward_id',v_reward.id,'reward_name',v_reward.name,'coupon_code',v_code),(select auth.uid()));
  return jsonb_build_object('redemption_id',v_redemption_id,'coupon_code',v_code,'reward_name',v_reward.name,'cost_points',v_reward.cost_points,'balance_points',v_balance-v_reward.cost_points);
end;
$$;

create or replace function public.admin_bz_save_rule(p_rule_key text,p_points integer,p_active boolean)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_rule public.bz_point_rules;
begin
  if not (select private.is_admin()) then raise exception 'Solo administración puede configurar BZ Points.' using errcode='42501'; end if;
  if p_points is null or p_points<0 or p_points>1000000 then raise exception 'Los puntos no son válidos.' using errcode='22023'; end if;
  update public.bz_point_rules set points=p_points,active=coalesce(p_active,false),updated_by=(select auth.uid()),updated_at=now()
  where rule_key=p_rule_key returning * into v_rule;
  if not found then raise exception 'La regla BZ no existe.' using errcode='P0002'; end if;
  return to_jsonb(v_rule);
end;
$$;

create or replace function public.admin_bz_save_reward(
  p_reward_id bigint,
  p_name text,
  p_description text,
  p_cost_points integer,
  p_discount_kind text,
  p_discount_value integer,
  p_active boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_reward public.bz_rewards; v_name text:=nullif(btrim(coalesce(p_name,'')),'');
begin
  if not (select private.is_admin()) then raise exception 'Solo administración puede configurar recompensas.' using errcode='42501'; end if;
  if v_name is null then raise exception 'El nombre es obligatorio.' using errcode='22023'; end if;
  if coalesce(p_cost_points,0)<=0 then raise exception 'El coste en puntos debe ser mayor que cero.' using errcode='22023'; end if;
  if p_discount_kind not in ('fixed_cents','percent') or coalesce(p_discount_value,0)<=0 or (p_discount_kind='percent' and p_discount_value>100) then
    raise exception 'Configura un descuento válido.' using errcode='22023';
  end if;
  if p_reward_id is null then
    insert into public.bz_rewards(reward_key,name,description,cost_points,discount_kind,discount_value,active,created_by,updated_by)
    values('reward-'||substr(md5(clock_timestamp()::text||random()::text),1,16),v_name,nullif(btrim(coalesce(p_description,'')),''),p_cost_points,p_discount_kind,p_discount_value,coalesce(p_active,true),(select auth.uid()),(select auth.uid()))
    returning * into v_reward;
  else
    update public.bz_rewards set name=v_name,description=nullif(btrim(coalesce(p_description,'')),''),cost_points=p_cost_points,
      discount_kind=p_discount_kind,discount_value=p_discount_value,active=coalesce(p_active,false),updated_by=(select auth.uid()),updated_at=now()
    where id=p_reward_id returning * into v_reward;
    if not found then raise exception 'La recompensa no existe.' using errcode='P0002'; end if;
  end if;
  return to_jsonb(v_reward);
end;
$$;

create or replace function public.admin_bz_adjust_points(p_person_id bigint,p_points integer,p_note text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_id bigint; v_key text;
begin
  if not (select private.is_admin()) then raise exception 'Solo administración puede ajustar BZ Points.' using errcode='42501'; end if;
  if p_points is null or p_points=0 or abs(p_points)>1000000 then raise exception 'El ajuste no es válido.' using errcode='22023'; end if;
  if not exists(select 1 from public.people where id=p_person_id and active) then raise exception 'La persona no existe.' using errcode='P0002'; end if;
  v_key:='bz:adjustment:'||p_person_id||':'||md5(clock_timestamp()::text||random()::text);
  insert into public.bz_point_ledger(person_id,entry_type,points_delta,source_type,idempotency_key,detail,created_by)
  values(p_person_id,'adjustment',p_points,'admin_adjustment',v_key,jsonb_build_object('note',nullif(btrim(coalesce(p_note,'')),'')),(select auth.uid()))
  returning id into v_id;
  return jsonb_build_object('ledger_id',v_id,'person_id',p_person_id,'points_delta',p_points);
end;
$$;

create or replace view public.bz_person_statistics with (security_invoker=true) as
select l.person_id,
       coalesce(sum(l.points_delta),0)::bigint as balance_points,
       coalesce(sum(l.points_delta) filter(where l.points_delta>0),0)::bigint as earned_points,
       coalesce(-sum(l.points_delta) filter(where l.points_delta<0),0)::bigint as spent_points,
       count(*) filter(where l.entry_type='earn')::bigint as earn_events,
       max(l.created_at) as last_movement_at
from public.bz_point_ledger l
group by l.person_id;
grant select on public.bz_person_statistics to authenticated;

revoke all on function private.bz_local_date() from public,anon,authenticated;
revoke all on function private.bz_award(bigint,text,text,text,text,jsonb,timestamptz) from public,anon,authenticated;
revoke all on function private.bz_reconcile_registration(bigint) from public,anon,authenticated;
revoke all on function private.bz_reconcile_credit_grant(bigint) from public,anon,authenticated;
revoke all on function private.bz_reconcile_class(bigint) from public,anon,authenticated;
revoke all on function private.bz_reconcile_exercise(bigint,bigint) from public,anon,authenticated;
revoke all on function private.bz_validate_next_class(bigint,bigint) from public,anon,authenticated;

revoke all on function public.bz_record_daily_login() from public,anon;
revoke all on function public.bz_confirm_previous_class_review(bigint) from public,anon;
revoke all on function public.bz_choose_next_class_content(bigint,bigint) from public,anon;
revoke all on function public.bz_snapshot() from public,anon;
revoke all on function public.bz_redeem_reward(bigint) from public,anon;
revoke all on function public.admin_bz_save_rule(text,integer,boolean) from public,anon;
revoke all on function public.admin_bz_save_reward(bigint,text,text,integer,text,integer,boolean) from public,anon;
revoke all on function public.admin_bz_adjust_points(bigint,integer,text) from public,anon;

grant execute on function public.bz_record_daily_login() to authenticated;
grant execute on function public.bz_confirm_previous_class_review(bigint) to authenticated;
grant execute on function public.bz_choose_next_class_content(bigint,bigint) to authenticated;
grant execute on function public.bz_snapshot() to authenticated;
grant execute on function public.bz_redeem_reward(bigint) to authenticated;
grant execute on function public.admin_bz_save_rule(text,integer,boolean) to authenticated;
grant execute on function public.admin_bz_save_reward(bigint,text,text,integer,text,integer,boolean) to authenticated;
grant execute on function public.admin_bz_adjust_points(bigint,integer,text) to authenticated;
