-- PR-C · Feedback Online
-- Separate discrete-credit domain. Feedback never consumes class minutes and never creates fake classes.

create table if not exists public.feedback_products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price_cents integer,
  currency text not null default 'EUR',
  credits_per_purchase integer not null default 1,
  target_response_hours integer,
  active boolean not null default false,
  sort_order integer not null default 0,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint feedback_products_name_check check (length(btrim(name)) > 0),
  constraint feedback_products_price_check check (price_cents is null or price_cents >= 0),
  constraint feedback_products_currency_check check (currency ~ '^[A-Z]{3}$'),
  constraint feedback_products_single_credit_check check (credits_per_purchase = 1),
  constraint feedback_products_sla_check check (target_response_hours is null or target_response_hours between 1 and 720),
  constraint feedback_products_active_price_check check (not active or price_cents is not null)
);

create table if not exists public.feedback_credit_orders (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.people(id) on delete cascade,
  product_id bigint not null references public.feedback_products(id) on delete restrict,
  credits integer not null default 1,
  unit_price_cents integer not null,
  total_price_cents integer not null,
  currency text not null,
  payment_status text not null default 'pending',
  requested_by uuid references auth.users(id) on delete set null,
  confirmed_by uuid references auth.users(id) on delete set null,
  requested_at timestamptz not null default now(),
  paid_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint feedback_credit_orders_credits_check check (credits = 1),
  constraint feedback_credit_orders_price_check check (unit_price_cents >= 0 and total_price_cents >= 0),
  constraint feedback_credit_orders_currency_check check (currency ~ '^[A-Z]{3}$'),
  constraint feedback_credit_orders_status_check check (payment_status in ('pending','paid','cancelled')),
  constraint feedback_credit_orders_paid_at_check check ((payment_status='paid' and paid_at is not null) or payment_status<>'paid'),
  constraint feedback_credit_orders_cancelled_at_check check ((payment_status='cancelled' and cancelled_at is not null) or payment_status<>'cancelled')
);

create unique index if not exists feedback_credit_orders_one_pending_idx
  on public.feedback_credit_orders(person_id, product_id)
  where payment_status='pending';
create index if not exists feedback_credit_orders_person_idx on public.feedback_credit_orders(person_id, requested_at desc);
create index if not exists feedback_credit_orders_status_idx on public.feedback_credit_orders(payment_status, requested_at);

create table if not exists public.feedback_credit_ledger (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.people(id) on delete cascade,
  order_id bigint references public.feedback_credit_orders(id) on delete set null,
  movement_type text not null,
  delta_credits integer not null,
  idempotency_key text not null unique,
  note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint feedback_credit_ledger_type_check check (movement_type in ('purchase','consumption','refund','adjustment')),
  constraint feedback_credit_ledger_delta_check check (delta_credits <> 0),
  constraint feedback_credit_ledger_key_check check (length(btrim(idempotency_key)) > 0)
);
create index if not exists feedback_credit_ledger_person_idx on public.feedback_credit_ledger(person_id, created_at desc);
create index if not exists feedback_credit_ledger_order_idx on public.feedback_credit_ledger(order_id) where order_id is not null;

create table if not exists public.feedback_requests (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.people(id) on delete cascade,
  product_id bigint not null references public.feedback_products(id) on delete restrict,
  status text not null default 'draft',
  style_term_id bigint references public.catalog_terms(id) on delete set null,
  role_term_id bigint references public.catalog_terms(id) on delete set null,
  level_term_id bigint references public.catalog_terms(id) on delete set null,
  student_note text,
  external_file_id text,
  upload_proof text,
  video_title text,
  mime_type text,
  size_bytes bigint,
  assigned_teacher_user_id uuid references auth.users(id) on delete set null,
  teacher_summary text,
  evaluation_session_id bigint references public.evaluation_sessions(id) on delete set null,
  target_response_hours integer,
  due_at timestamptz,
  submitted_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint feedback_requests_status_check check (status in ('draft','submitted','in_review','completed','cancelled')),
  constraint feedback_requests_file_check check (external_file_id is null or length(btrim(external_file_id)) > 5),
  constraint feedback_requests_proof_check check (upload_proof is null or length(btrim(upload_proof)) >= 32),
  constraint feedback_requests_mime_check check (mime_type is null or mime_type like 'video/%'),
  constraint feedback_requests_size_check check (size_bytes is null or (size_bytes > 0 and size_bytes <= 1073741824)),
  constraint feedback_requests_sla_check check (target_response_hours is null or target_response_hours between 1 and 720),
  constraint feedback_requests_submitted_check check ((status in ('submitted','in_review','completed') and submitted_at is not null) or status in ('draft','cancelled')),
  constraint feedback_requests_started_check check ((status in ('in_review','completed') and started_at is not null) or status in ('draft','submitted','cancelled')),
  constraint feedback_requests_completed_check check ((status='completed' and completed_at is not null) or status<>'completed'),
  constraint feedback_requests_cancelled_check check ((status='cancelled' and cancelled_at is not null) or status<>'cancelled')
);
create index if not exists feedback_requests_person_idx on public.feedback_requests(person_id, created_at desc);
create index if not exists feedback_requests_queue_idx on public.feedback_requests(status, submitted_at) where status in ('submitted','in_review');
create index if not exists feedback_requests_due_idx on public.feedback_requests(due_at) where status in ('submitted','in_review') and due_at is not null;
create unique index if not exists feedback_requests_file_idx on public.feedback_requests(external_file_id) where external_file_id is not null;

alter table public.feedback_credit_ledger
  add column if not exists request_id bigint references public.feedback_requests(id) on delete set null;
create index if not exists feedback_credit_ledger_request_idx on public.feedback_credit_ledger(request_id) where request_id is not null;

create table if not exists public.feedback_request_events (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.feedback_requests(id) on delete cascade,
  person_id bigint not null references public.people(id) on delete cascade,
  event_type text not null,
  from_status text,
  to_status text,
  payload jsonb not null default '{}'::jsonb,
  actor_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint feedback_request_events_type_check check (event_type in ('created','video_attached','submitted','review_started','content_assigned','evaluation_started','completed','cancelled','credit_refunded'))
);
create index if not exists feedback_request_events_request_idx on public.feedback_request_events(request_id, created_at);
create index if not exists feedback_request_events_person_idx on public.feedback_request_events(person_id, created_at desc);

create table if not exists public.feedback_request_contents (
  request_id bigint not null references public.feedback_requests(id) on delete cascade,
  content_id bigint not null references public.teaching_contents(id) on delete cascade,
  assignment_id bigint references public.student_content_assignments(id) on delete set null,
  assigned_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key(request_id, content_id)
);
create index if not exists feedback_request_contents_assignment_idx on public.feedback_request_contents(assignment_id) where assignment_id is not null;

-- Explicit API exposure. Current Supabase projects do not guarantee automatic public-schema exposure.
grant select on public.feedback_products, public.feedback_credit_orders, public.feedback_credit_ledger,
  public.feedback_requests, public.feedback_request_events, public.feedback_request_contents to authenticated;
revoke insert, update, delete on public.feedback_products, public.feedback_credit_orders, public.feedback_credit_ledger,
  public.feedback_requests, public.feedback_request_events, public.feedback_request_contents from anon, authenticated;

alter table public.feedback_products enable row level security;
alter table public.feedback_credit_orders enable row level security;
alter table public.feedback_credit_ledger enable row level security;
alter table public.feedback_requests enable row level security;
alter table public.feedback_request_events enable row level security;
alter table public.feedback_request_contents enable row level security;

drop policy if exists feedback_products_read on public.feedback_products;
create policy feedback_products_read on public.feedback_products for select to authenticated
  using (active or (select private.is_staff()));

drop policy if exists feedback_orders_read on public.feedback_credit_orders;
create policy feedback_orders_read on public.feedback_credit_orders for select to authenticated
  using ((select private.is_staff()) or person_id=(select private.current_person_id()));

drop policy if exists feedback_ledger_read on public.feedback_credit_ledger;
create policy feedback_ledger_read on public.feedback_credit_ledger for select to authenticated
  using ((select private.is_staff()) or person_id=(select private.current_person_id()));

drop policy if exists feedback_requests_read on public.feedback_requests;
create policy feedback_requests_read on public.feedback_requests for select to authenticated
  using ((select private.is_staff()) or person_id=(select private.current_person_id()));

drop policy if exists feedback_events_read on public.feedback_request_events;
create policy feedback_events_read on public.feedback_request_events for select to authenticated
  using ((select private.is_staff()) or person_id=(select private.current_person_id()));

drop policy if exists feedback_contents_read on public.feedback_request_contents;
create policy feedback_contents_read on public.feedback_request_contents for select to authenticated
  using ((select private.is_staff()) or exists(
    select 1 from public.feedback_requests r
    where r.id=request_id and r.person_id=(select private.current_person_id())
  ));

-- Keep updated_at consistent with the rest of CYA Hub.
drop trigger if exists feedback_products_touch_updated_at on public.feedback_products;
create trigger feedback_products_touch_updated_at before update on public.feedback_products
for each row execute function private.touch_updated_at();
drop trigger if exists feedback_credit_orders_touch_updated_at on public.feedback_credit_orders;
create trigger feedback_credit_orders_touch_updated_at before update on public.feedback_credit_orders
for each row execute function private.touch_updated_at();
drop trigger if exists feedback_requests_touch_updated_at on public.feedback_requests;
create trigger feedback_requests_touch_updated_at before update on public.feedback_requests
for each row execute function private.touch_updated_at();

create or replace function private.feedback_activate_student(p_person_id bigint)
returns void language plpgsql security definer set search_path=''
as $$
declare v_auth uuid;
begin
  if not exists(select 1 from public.people where id=p_person_id and active) then
    raise exception 'La persona no está disponible.' using errcode='22023';
  end if;
  insert into public.student_profiles(person_id,student_since,active,created_by)
  values(p_person_id,current_date,true,(select auth.uid()))
  on conflict(person_id) do update set active=true, updated_at=now();
  select auth_user_id into v_auth from public.people where id=p_person_id;
  if v_auth is not null then
    insert into public.app_member_roles(user_id,role,active,granted_by)
    values(v_auth,'student',true,(select auth.uid()))
    on conflict(user_id,role) do update set active=true, updated_at=now();
  end if;
end;
$$;
revoke all on function private.feedback_activate_student(bigint) from public, anon, authenticated;

create or replace function private.feedback_add_ledger(
  p_person_id bigint,
  p_order_id bigint,
  p_request_id bigint,
  p_movement_type text,
  p_delta integer,
  p_idempotency_key text,
  p_note text default null
) returns public.feedback_credit_ledger
language plpgsql security definer set search_path=''
as $$
declare v_row public.feedback_credit_ledger;
begin
  insert into public.feedback_credit_ledger(person_id,order_id,request_id,movement_type,delta_credits,idempotency_key,note,created_by)
  values(p_person_id,p_order_id,p_request_id,p_movement_type,p_delta,p_idempotency_key,nullif(btrim(coalesce(p_note,'')),''),(select auth.uid()))
  on conflict(idempotency_key) do nothing returning * into v_row;
  if v_row.id is null then
    select * into v_row from public.feedback_credit_ledger where idempotency_key=p_idempotency_key;
  end if;
  return v_row;
end;
$$;
revoke all on function private.feedback_add_ledger(bigint,bigint,bigint,text,integer,text,text) from public, anon, authenticated;

create or replace function public.feedback_credit_balance(p_person_id bigint default null)
returns integer language plpgsql stable security definer set search_path=''
as $$
declare v_person bigint:=coalesce(p_person_id,(select private.current_person_id())); v_balance integer;
begin
  if v_person is null then raise exception 'No hemos podido vincular esta cuenta con una persona.' using errcode='22023'; end if;
  if not (select private.is_staff()) and v_person<>(select private.current_person_id()) then
    raise exception 'No tienes permiso para consultar este saldo.' using errcode='42501';
  end if;
  select coalesce(sum(delta_credits),0)::integer into v_balance from public.feedback_credit_ledger where person_id=v_person;
  return v_balance;
end;
$$;
revoke all on function public.feedback_credit_balance(bigint) from public, anon;
grant execute on function public.feedback_credit_balance(bigint) to authenticated;

create or replace function public.feedback_request_purchase(p_product_id bigint)
returns public.feedback_credit_orders language plpgsql security definer set search_path=''
as $$
declare v_person bigint; v_product public.feedback_products; v_order public.feedback_credit_orders;
begin
  select private.current_person_id() into v_person;
  if v_person is null then raise exception 'Necesitas una cuenta de alumno vinculada para solicitar Feedback Online.' using errcode='42501'; end if;
  select * into v_product from public.feedback_products where id=p_product_id and active and price_cents is not null;
  if not found then raise exception 'Este Feedback Online no está disponible para compra.' using errcode='22023'; end if;
  insert into public.feedback_credit_orders(person_id,product_id,credits,unit_price_cents,total_price_cents,currency,payment_status,requested_by)
  values(v_person,v_product.id,1,v_product.price_cents,v_product.price_cents,v_product.currency,'pending',(select auth.uid()))
  on conflict(person_id,product_id) where payment_status='pending'
  do update set updated_at=now()
  returning * into v_order;
  return v_order;
end;
$$;
revoke all on function public.feedback_request_purchase(bigint) from public, anon;
grant execute on function public.feedback_request_purchase(bigint) to authenticated;

create or replace function public.admin_feedback_save_product(
  p_product_id bigint,
  p_name text,
  p_description text,
  p_price_cents integer,
  p_currency text,
  p_target_response_hours integer,
  p_active boolean
) returns public.feedback_products language plpgsql security definer set search_path=''
as $$
declare v_row public.feedback_products;
begin
  if not (select private.is_admin()) then raise exception 'Solo Administración puede configurar Feedback Online.' using errcode='42501'; end if;
  if nullif(btrim(coalesce(p_name,'')),'') is null then raise exception 'Indica un nombre.' using errcode='22023'; end if;
  if p_price_cents is not null and p_price_cents<0 then raise exception 'El precio no es válido.' using errcode='22023'; end if;
  if p_active and p_price_cents is null then raise exception 'Configura el precio antes de activar el producto.' using errcode='22023'; end if;
  if p_product_id is null then
    insert into public.feedback_products(name,description,price_cents,currency,target_response_hours,active,created_by)
    values(btrim(p_name),nullif(btrim(coalesce(p_description,'')),''),p_price_cents,upper(coalesce(nullif(btrim(p_currency),''),'EUR')),p_target_response_hours,p_active,(select auth.uid()))
    returning * into v_row;
  else
    update public.feedback_products set name=btrim(p_name),description=nullif(btrim(coalesce(p_description,'')),''),price_cents=p_price_cents,
      currency=upper(coalesce(nullif(btrim(p_currency),''),'EUR')),target_response_hours=p_target_response_hours,active=p_active
    where id=p_product_id returning * into v_row;
    if v_row.id is null then raise exception 'No se ha encontrado el producto de Feedback Online.' using errcode='22023'; end if;
  end if;
  return v_row;
end;
$$;
revoke all on function public.admin_feedback_save_product(bigint,text,text,integer,text,integer,boolean) from public, anon;
grant execute on function public.admin_feedback_save_product(bigint,text,text,integer,text,integer,boolean) to authenticated;

create or replace function public.admin_feedback_confirm_purchase(p_order_id bigint)
returns public.feedback_credit_orders language plpgsql security definer set search_path=''
as $$
declare v_order public.feedback_credit_orders;
begin
  if not (select private.is_admin()) then raise exception 'Solo Administración puede confirmar un pago.' using errcode='42501'; end if;
  select * into v_order from public.feedback_credit_orders where id=p_order_id for update;
  if not found then raise exception 'No se ha encontrado la compra.' using errcode='22023'; end if;
  if v_order.payment_status='paid' then return v_order; end if;
  if v_order.payment_status<>'pending' then raise exception 'Esta compra ya no está pendiente.' using errcode='22023'; end if;
  perform private.feedback_activate_student(v_order.person_id);
  update public.feedback_credit_orders set payment_status='paid',paid_at=now(),confirmed_by=(select auth.uid()) where id=v_order.id returning * into v_order;
  perform private.feedback_add_ledger(v_order.person_id,v_order.id,null,'purchase',v_order.credits,'feedback:order:'||v_order.id||':purchase','Compra de Feedback Online');
  return v_order;
end;
$$;
revoke all on function public.admin_feedback_confirm_purchase(bigint) from public, anon;
grant execute on function public.admin_feedback_confirm_purchase(bigint) to authenticated;

create or replace function public.admin_feedback_create_paid_purchase(p_person_id bigint,p_product_id bigint,p_note text default null)
returns public.feedback_credit_orders language plpgsql security definer set search_path=''
as $$
declare v_product public.feedback_products; v_order public.feedback_credit_orders;
begin
  if not (select private.is_admin()) then raise exception 'Solo Administración puede registrar una compra.' using errcode='42501'; end if;
  if not exists(select 1 from public.people where id=p_person_id and active) then raise exception 'La persona no está disponible.' using errcode='22023'; end if;
  select * into v_product from public.feedback_products where id=p_product_id and price_cents is not null;
  if not found then raise exception 'Configura primero el producto de Feedback Online.' using errcode='22023'; end if;
  perform private.feedback_activate_student(p_person_id);
  insert into public.feedback_credit_orders(person_id,product_id,credits,unit_price_cents,total_price_cents,currency,payment_status,requested_by,confirmed_by,paid_at)
  values(p_person_id,v_product.id,1,v_product.price_cents,v_product.price_cents,v_product.currency,'paid',(select auth.uid()),(select auth.uid()),now())
  returning * into v_order;
  perform private.feedback_add_ledger(p_person_id,v_order.id,null,'purchase',1,'feedback:order:'||v_order.id||':purchase',coalesce(nullif(btrim(coalesce(p_note,'')),''),'Compra de Feedback Online'));
  return v_order;
end;
$$;
revoke all on function public.admin_feedback_create_paid_purchase(bigint,bigint,text) from public, anon;
grant execute on function public.admin_feedback_create_paid_purchase(bigint,bigint,text) to authenticated;

create or replace function public.admin_feedback_adjust_credits(p_person_id bigint,p_delta integer,p_note text)
returns public.feedback_credit_ledger language plpgsql security definer set search_path=''
as $$
declare v_balance integer; v_row public.feedback_credit_ledger; v_key text;
begin
  if not (select private.is_admin()) then raise exception 'Solo Administración puede ajustar créditos de Feedback.' using errcode='42501'; end if;
  if p_delta=0 then raise exception 'El ajuste debe sumar o restar al menos un crédito.' using errcode='22023'; end if;
  if nullif(btrim(coalesce(p_note,'')),'') is null then raise exception 'Indica el motivo del ajuste.' using errcode='22023'; end if;
  perform 1 from public.people where id=p_person_id and active for update;
  if not found then raise exception 'La persona no está disponible.' using errcode='22023'; end if;
  select coalesce(sum(delta_credits),0)::integer into v_balance from public.feedback_credit_ledger where person_id=p_person_id;
  if v_balance+p_delta<0 then raise exception 'El ajuste dejaría un saldo de Feedback negativo.' using errcode='22023'; end if;
  perform private.feedback_activate_student(p_person_id);
  v_key:='feedback:adjust:'||p_person_id||':'||gen_random_uuid()::text;
  select * into v_row from private.feedback_add_ledger(p_person_id,null,null,'adjustment',p_delta,v_key,p_note);
  return v_row;
end;
$$;
revoke all on function public.admin_feedback_adjust_credits(bigint,integer,text) from public, anon;
grant execute on function public.admin_feedback_adjust_credits(bigint,integer,text) to authenticated;

create or replace function public.feedback_create_draft(
  p_product_id bigint,
  p_style_term_id bigint default null,
  p_role_term_id bigint default null,
  p_level_term_id bigint default null,
  p_student_note text default null
) returns public.feedback_requests language plpgsql security definer set search_path=''
as $$
declare v_person bigint; v_product public.feedback_products; v_balance integer; v_request public.feedback_requests;
begin
  select private.current_person_id() into v_person;
  if v_person is null then raise exception 'Necesitas una cuenta de alumno vinculada.' using errcode='42501'; end if;
  select * into v_product from public.feedback_products where id=p_product_id and active;
  if not found then raise exception 'Este Feedback Online no está disponible.' using errcode='22023'; end if;
  perform 1 from public.people where id=v_person and active for update;
  select coalesce(sum(delta_credits),0)::integer into v_balance from public.feedback_credit_ledger where person_id=v_person;
  if v_balance<1 then raise exception 'Necesitas un crédito de Feedback Online disponible.' using errcode='22023'; end if;
  if p_style_term_id is not null and not exists(select 1 from public.catalog_terms where id=p_style_term_id and taxonomy='dance_style' and active) then raise exception 'El estilo no es válido.' using errcode='22023'; end if;
  if p_role_term_id is not null and not exists(select 1 from public.catalog_terms where id=p_role_term_id and taxonomy='dance_role' and active) then raise exception 'El rol no es válido.' using errcode='22023'; end if;
  if p_level_term_id is not null and not exists(select 1 from public.catalog_terms where id=p_level_term_id and taxonomy='dance_level' and active) then raise exception 'El nivel no es válido.' using errcode='22023'; end if;
  insert into public.feedback_requests(person_id,product_id,status,style_term_id,role_term_id,level_term_id,student_note,created_by,updated_by)
  values(v_person,v_product.id,'draft',p_style_term_id,p_role_term_id,p_level_term_id,nullif(btrim(coalesce(p_student_note,'')),''),(select auth.uid()),(select auth.uid()))
  returning * into v_request;
  insert into public.feedback_request_events(request_id,person_id,event_type,to_status,actor_user_id)
  values(v_request.id,v_person,'created','draft',(select auth.uid()));
  return v_request;
end;
$$;
revoke all on function public.feedback_create_draft(bigint,bigint,bigint,bigint,text) from public, anon;
grant execute on function public.feedback_create_draft(bigint,bigint,bigint,bigint,text) to authenticated;

create or replace function public.feedback_upload_context(p_request_id bigint)
returns table(request_id bigint,person_id bigint)
language sql stable security invoker set search_path=''
as $$
  select r.id,r.person_id from public.feedback_requests r where r.id=p_request_id and r.status='draft' limit 1;
$$;
revoke all on function public.feedback_upload_context(bigint) from public, anon;
grant execute on function public.feedback_upload_context(bigint) to authenticated;

create or replace function public.feedback_attach_video(
  p_request_id bigint,
  p_external_file_id text,
  p_upload_proof text,
  p_video_title text,
  p_mime_type text,
  p_size_bytes bigint
) returns public.feedback_requests language plpgsql security definer set search_path=''
as $$
declare v_person bigint; v_request public.feedback_requests;
begin
  select private.current_person_id() into v_person;
  if v_person is null then raise exception 'No hemos podido vincular esta cuenta.' using errcode='42501'; end if;
  select * into v_request from public.feedback_requests where id=p_request_id and person_id=v_person for update;
  if not found then raise exception 'No se ha encontrado la solicitud.' using errcode='22023'; end if;
  if v_request.status<>'draft' then raise exception 'El vídeo ya no se puede cambiar.' using errcode='22023'; end if;
  if length(btrim(coalesce(p_external_file_id,'')))<=5 or length(btrim(coalesce(p_upload_proof,'')))<32 then raise exception 'La subida del vídeo no es válida.' using errcode='22023'; end if;
  if p_mime_type is null or p_mime_type not like 'video/%' then raise exception 'Feedback Online solo admite vídeo.' using errcode='22023'; end if;
  if p_size_bytes is null or p_size_bytes<=0 or p_size_bytes>1073741824 then raise exception 'El vídeo debe ser menor de 1 GB.' using errcode='22023'; end if;
  update public.feedback_requests set external_file_id=btrim(p_external_file_id),upload_proof=btrim(p_upload_proof),video_title=nullif(btrim(coalesce(p_video_title,'')),''),
    mime_type=p_mime_type,size_bytes=p_size_bytes,updated_by=(select auth.uid()) where id=p_request_id returning * into v_request;
  insert into public.feedback_request_events(request_id,person_id,event_type,from_status,to_status,payload,actor_user_id)
  values(v_request.id,v_person,'video_attached','draft','draft',jsonb_build_object('size_bytes',p_size_bytes,'mime_type',p_mime_type),(select auth.uid()));
  return v_request;
end;
$$;
revoke all on function public.feedback_attach_video(bigint,text,text,text,text,bigint) from public, anon;
grant execute on function public.feedback_attach_video(bigint,text,text,text,text,bigint) to authenticated;

create or replace function public.feedback_media_access_context(p_external_file_id text)
returns table(request_id bigint,person_id bigint,upload_proof text)
language sql stable security invoker set search_path=''
as $$
  select r.id,r.person_id,r.upload_proof from public.feedback_requests r
  where r.external_file_id=p_external_file_id and r.upload_proof is not null and r.status<>'cancelled' limit 1;
$$;
revoke all on function public.feedback_media_access_context(text) from public, anon;
grant execute on function public.feedback_media_access_context(text) to authenticated;

insert into public.notification_rules(event_key,label,enabled,channels,recipients,template,settings)
values
  ('feedback.online.pending','Feedback Online pendiente',true,array['internal']::text[],'["staff"]'::jsonb,'Hay un nuevo Feedback Online pendiente de revisar.','{"groupable":true}'::jsonb),
  ('feedback.online.completed','Feedback Online listo',true,array['internal']::text[],'["student"]'::jsonb,'Tu Feedback Online ya está listo.','{"groupable":true}'::jsonb)
on conflict(event_key) do nothing;

create or replace function public.feedback_submit_request(p_request_id bigint)
returns public.feedback_requests language plpgsql security definer set search_path=''
as $$
declare v_person bigint; v_request public.feedback_requests; v_product public.feedback_products; v_balance integer; v_user uuid;
begin
  select private.current_person_id() into v_person;
  if v_person is null then raise exception 'No hemos podido vincular esta cuenta.' using errcode='42501'; end if;
  select * into v_request from public.feedback_requests where id=p_request_id and person_id=v_person for update;
  if not found then raise exception 'No se ha encontrado la solicitud.' using errcode='22023'; end if;
  if v_request.status='submitted' or v_request.status='in_review' or v_request.status='completed' then return v_request; end if;
  if v_request.status<>'draft' then raise exception 'La solicitud ya no se puede enviar.' using errcode='22023'; end if;
  if v_request.external_file_id is null or v_request.upload_proof is null then raise exception 'Sube el vídeo antes de enviarlo.' using errcode='22023'; end if;
  perform 1 from public.people where id=v_person and active for update;
  select coalesce(sum(delta_credits),0)::integer into v_balance from public.feedback_credit_ledger where person_id=v_person;
  if v_balance<1 then raise exception 'No tienes créditos de Feedback Online disponibles.' using errcode='22023'; end if;
  select * into v_product from public.feedback_products where id=v_request.product_id;
  perform private.feedback_add_ledger(v_person,null,v_request.id,'consumption',-1,'feedback:request:'||v_request.id||':consume','Feedback Online enviado');
  update public.feedback_requests set status='submitted',submitted_at=now(),target_response_hours=v_product.target_response_hours,
    due_at=case when v_product.target_response_hours is null then null else now() + make_interval(hours=>v_product.target_response_hours) end,
    updated_by=(select auth.uid()) where id=v_request.id returning * into v_request;
  insert into public.feedback_request_events(request_id,person_id,event_type,from_status,to_status,actor_user_id)
  values(v_request.id,v_person,'submitted','draft','submitted',(select auth.uid()));
  for v_user in select distinct user_id from public.app_member_roles where active and role in ('admin','teacher_admin','teacher') loop
    perform private.enqueue_notification('feedback.online.pending',v_user,'Nuevo Feedback Online','Hay un vídeo pendiente de revisar.','live:feedback','feedback_online',v_request.id::text,jsonb_build_object('person_id',v_person,'request_id',v_request.id));
  end loop;
  return v_request;
end;
$$;
revoke all on function public.feedback_submit_request(bigint) from public, anon;
grant execute on function public.feedback_submit_request(bigint) to authenticated;

create or replace function public.feedback_cancel_request(p_request_id bigint)
returns public.feedback_requests language plpgsql security definer set search_path=''
as $$
declare v_person bigint; v_request public.feedback_requests;
begin
  select private.current_person_id() into v_person;
  select * into v_request from public.feedback_requests where id=p_request_id and person_id=v_person for update;
  if not found then raise exception 'No se ha encontrado la solicitud.' using errcode='22023'; end if;
  if v_request.status='cancelled' then return v_request; end if;
  if v_request.status not in ('draft','submitted') or v_request.started_at is not null then raise exception 'Este Feedback ya está siendo revisado y no se puede cancelar.' using errcode='22023'; end if;
  if v_request.status='submitted' then
    perform 1 from public.people where id=v_person for update;
    perform private.feedback_add_ledger(v_person,null,v_request.id,'refund',1,'feedback:request:'||v_request.id||':refund','Feedback cancelado antes de revisión');
    insert into public.feedback_request_events(request_id,person_id,event_type,from_status,to_status,actor_user_id)
    values(v_request.id,v_person,'credit_refunded','submitted','submitted',(select auth.uid()));
  end if;
  update public.feedback_requests set status='cancelled',cancelled_at=now(),updated_by=(select auth.uid()) where id=v_request.id returning * into v_request;
  insert into public.feedback_request_events(request_id,person_id,event_type,from_status,to_status,actor_user_id)
  values(v_request.id,v_person,'cancelled',case when v_request.submitted_at is null then 'draft' else 'submitted' end,'cancelled',(select auth.uid()));
  return v_request;
end;
$$;
revoke all on function public.feedback_cancel_request(bigint) from public, anon;
grant execute on function public.feedback_cancel_request(bigint) to authenticated;

create or replace function public.feedback_start_review(p_request_id bigint)
returns public.feedback_requests language plpgsql security definer set search_path=''
as $$
declare v_request public.feedback_requests; v_from text;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para revisar Feedback Online.' using errcode='42501'; end if;
  select * into v_request from public.feedback_requests where id=p_request_id for update;
  if not found then raise exception 'No se ha encontrado la solicitud.' using errcode='22023'; end if;
  if v_request.status='in_review' then return v_request; end if;
  if v_request.status<>'submitted' then raise exception 'Solo se puede iniciar un Feedback pendiente.' using errcode='22023'; end if;
  v_from:=v_request.status;
  update public.feedback_requests set status='in_review',started_at=now(),assigned_teacher_user_id=(select auth.uid()),updated_by=(select auth.uid())
  where id=v_request.id returning * into v_request;
  insert into public.feedback_request_events(request_id,person_id,event_type,from_status,to_status,actor_user_id)
  values(v_request.id,v_request.person_id,'review_started',v_from,'in_review',(select auth.uid()));
  return v_request;
end;
$$;
revoke all on function public.feedback_start_review(bigint) from public, anon;
grant execute on function public.feedback_start_review(bigint) to authenticated;

create or replace function public.feedback_assign_content(p_request_id bigint,p_content_id bigint)
returns public.feedback_request_contents language plpgsql security definer set search_path=''
as $$
declare v_request public.feedback_requests; v_assignment public.student_content_assignments; v_link public.feedback_request_contents;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para asignar contenido desde Feedback.' using errcode='42501'; end if;
  select * into v_request from public.feedback_requests where id=p_request_id for update;
  if not found or v_request.status not in ('submitted','in_review') then raise exception 'El Feedback no está abierto para revisión.' using errcode='22023'; end if;
  if v_request.style_term_id is null or v_request.role_term_id is null or v_request.level_term_id is null then raise exception 'Completa estilo, rol y nivel antes de asignar contenido.' using errcode='22023'; end if;
  if v_request.status='submitted' then perform public.feedback_start_review(v_request.id); select * into v_request from public.feedback_requests where id=v_request.id; end if;
  select * into v_assignment from public.assign_teaching_content(v_request.person_id,p_content_id,v_request.style_term_id,v_request.role_term_id,v_request.level_term_id,null);
  insert into public.feedback_request_contents(request_id,content_id,assignment_id,assigned_by)
  values(v_request.id,p_content_id,v_assignment.id,(select auth.uid()))
  on conflict(request_id,content_id) do update set assignment_id=excluded.assignment_id
  returning * into v_link;
  insert into public.feedback_request_events(request_id,person_id,event_type,from_status,to_status,payload,actor_user_id)
  values(v_request.id,v_request.person_id,'content_assigned','in_review','in_review',jsonb_build_object('content_id',p_content_id,'assignment_id',v_assignment.id),(select auth.uid()));
  return v_link;
end;
$$;
revoke all on function public.feedback_assign_content(bigint,bigint) from public, anon;
grant execute on function public.feedback_assign_content(bigint,bigint) to authenticated;

create or replace function public.feedback_start_evaluation(p_request_id bigint)
returns public.evaluation_sessions language plpgsql security definer set search_path=''
as $$
declare v_request public.feedback_requests; v_session public.evaluation_sessions;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para evaluar desde Feedback.' using errcode='42501'; end if;
  select * into v_request from public.feedback_requests where id=p_request_id for update;
  if not found or v_request.status not in ('submitted','in_review') then raise exception 'El Feedback no está abierto para revisión.' using errcode='22023'; end if;
  if v_request.style_term_id is null or v_request.role_term_id is null or v_request.level_term_id is null then raise exception 'Completa estilo, rol y nivel antes de evaluar.' using errcode='22023'; end if;
  if v_request.evaluation_session_id is not null then select * into v_session from public.evaluation_sessions where id=v_request.evaluation_session_id; return v_session; end if;
  if v_request.status='submitted' then perform public.feedback_start_review(v_request.id); end if;
  select * into v_session from public.start_student_evaluation(v_request.person_id,v_request.level_term_id,'manual',v_request.style_term_id,v_request.role_term_id,null,'Feedback Online #'||v_request.id);
  update public.feedback_requests set evaluation_session_id=v_session.id,updated_by=(select auth.uid()) where id=v_request.id;
  insert into public.feedback_request_events(request_id,person_id,event_type,from_status,to_status,payload,actor_user_id)
  values(v_request.id,v_request.person_id,'evaluation_started','in_review','in_review',jsonb_build_object('session_id',v_session.id),(select auth.uid()));
  return v_session;
end;
$$;
revoke all on function public.feedback_start_evaluation(bigint) from public, anon;
grant execute on function public.feedback_start_evaluation(bigint) to authenticated;

create or replace function public.feedback_complete_request(p_request_id bigint,p_teacher_summary text)
returns public.feedback_requests language plpgsql security definer set search_path=''
as $$
declare v_request public.feedback_requests; v_user uuid; v_from text;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para cerrar Feedback Online.' using errcode='42501'; end if;
  if nullif(btrim(coalesce(p_teacher_summary,'')),'') is null then raise exception 'Escribe el feedback para el alumno antes de terminar.' using errcode='22023'; end if;
  select * into v_request from public.feedback_requests where id=p_request_id for update;
  if not found then raise exception 'No se ha encontrado la solicitud.' using errcode='22023'; end if;
  if v_request.status='completed' then return v_request; end if;
  if v_request.status not in ('submitted','in_review') then raise exception 'Este Feedback no se puede cerrar.' using errcode='22023'; end if;
  if v_request.evaluation_session_id is not null and exists(select 1 from public.evaluation_sessions where id=v_request.evaluation_session_id and status<>'completed') then
    raise exception 'Termina o elimina la evaluación abierta antes de cerrar el Feedback.' using errcode='22023';
  end if;
  v_from:=v_request.status;
  if v_request.status='submitted' then
    update public.feedback_requests set started_at=coalesce(started_at,now()),assigned_teacher_user_id=coalesce(assigned_teacher_user_id,(select auth.uid())) where id=v_request.id;
  end if;
  update public.feedback_requests set status='completed',teacher_summary=btrim(p_teacher_summary),completed_at=now(),started_at=coalesce(started_at,now()),
    assigned_teacher_user_id=coalesce(assigned_teacher_user_id,(select auth.uid())),updated_by=(select auth.uid()) where id=v_request.id returning * into v_request;
  update public.student_content_assignments a set student_visible_at=coalesce(a.student_visible_at,now()),updated_at=now()
  from public.feedback_request_contents frc join public.teaching_contents tc on tc.id=frc.content_id
  where frc.request_id=v_request.id and frc.assignment_id=a.id and private.assignment_is_student_releasable(tc.content_type,a.assignment_status);
  insert into public.feedback_request_events(request_id,person_id,event_type,from_status,to_status,actor_user_id)
  values(v_request.id,v_request.person_id,'completed',v_from,'completed',(select auth.uid()));
  select auth_user_id into v_user from public.people where id=v_request.person_id;
  if v_user is not null then
    perform private.enqueue_notification('feedback.online.completed',v_user,'Tu Feedback Online está listo','Ya puedes abrirlo y revisar las indicaciones.','student:feedback','feedback_online',v_request.id::text,jsonb_build_object('request_id',v_request.id));
  end if;
  return v_request;
end;
$$;
revoke all on function public.feedback_complete_request(bigint,text) from public, anon;
grant execute on function public.feedback_complete_request(bigint,text) to authenticated;

-- No product is activated with an invented price. Administration must set a real price before launch.
insert into public.feedback_products(name,description,price_cents,currency,credits_per_purchase,target_response_hours,active,sort_order)
select 'Feedback Online','Envía un vídeo y recibe una revisión pedagógica.',null,'EUR',1,null,false,10
where not exists(select 1 from public.feedback_products);
