-- PR-D · Academia Online
-- Academia reuses canonical teaching content and canonical people.
-- Course consumption progress is intentionally separate from pedagogical assignment/mastery state.

create table if not exists public.app_module_settings (
  module_key text primary key,
  label text not null,
  sort_order integer not null,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  constraint app_module_settings_key_check check (module_key in ('home','students','teaching','marketing','statistics','academy')),
  constraint app_module_settings_label_check check (length(btrim(label)) > 0),
  constraint app_module_settings_order_check check (sort_order between 0 and 1000)
);

create table if not exists public.academy_programs (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  style_term_id bigint not null references public.catalog_terms(id) on delete restrict,
  role_term_id bigint not null references public.catalog_terms(id) on delete restrict,
  level_term_id bigint not null references public.catalog_terms(id) on delete restrict,
  price_cents integer,
  currency text not null default 'EUR',
  publication_status text not null default 'draft',
  active boolean not null default false,
  sort_order integer not null default 0,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  constraint academy_programs_title_check check (length(btrim(title)) > 0),
  constraint academy_programs_price_check check (price_cents is null or price_cents >= 0),
  constraint academy_programs_currency_check check (currency ~ '^[A-Z]{3}$'),
  constraint academy_programs_publication_check check (publication_status in ('draft','published','archived')),
  constraint academy_programs_active_check check (not active or publication_status='published'),
  constraint academy_programs_published_price_check check (publication_status<>'published' or price_cents is not null),
  constraint academy_programs_published_at_check check ((publication_status='published' and published_at is not null) or publication_status<>'published')
);
create index if not exists academy_programs_context_idx on public.academy_programs(style_term_id,role_term_id,level_term_id,publication_status,active);
create index if not exists academy_programs_order_idx on public.academy_programs(sort_order,id);

create table if not exists public.academy_program_contents (
  id bigint generated by default as identity primary key,
  program_id bigint not null references public.academy_programs(id) on delete cascade,
  content_id bigint not null references public.teaching_contents(id) on delete cascade,
  position integer not null,
  required boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint academy_program_contents_position_check check (position between 1 and 10000),
  unique(program_id,content_id),
  unique(program_id,position)
);
create index if not exists academy_program_contents_content_idx on public.academy_program_contents(content_id);

create table if not exists public.academy_enrollments (
  id bigint generated by default as identity primary key,
  program_id bigint not null references public.academy_programs(id) on delete restrict,
  person_id bigint not null references public.people(id) on delete cascade,
  status text not null default 'active',
  access_source text not null default 'admin',
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  completed_at timestamptz,
  granted_by uuid references auth.users(id) on delete set null,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint academy_enrollments_status_check check (status in ('active','completed','cancelled')),
  constraint academy_enrollments_source_check check (access_source in ('admin','purchase','promotion','migration')),
  constraint academy_enrollments_expiry_check check (expires_at is null or expires_at > starts_at),
  constraint academy_enrollments_completed_check check ((status='completed' and completed_at is not null) or status<>'completed'),
  unique(program_id,person_id)
);
create index if not exists academy_enrollments_person_idx on public.academy_enrollments(person_id,status);
create index if not exists academy_enrollments_program_idx on public.academy_enrollments(program_id,status);

create table if not exists public.academy_progress (
  enrollment_id bigint not null references public.academy_enrollments(id) on delete cascade,
  program_content_id bigint not null references public.academy_program_contents(id) on delete cascade,
  status text not null default 'not_started',
  started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key(enrollment_id,program_content_id),
  constraint academy_progress_status_check check (status in ('not_started','in_progress','completed')),
  constraint academy_progress_started_check check ((status in ('in_progress','completed') and started_at is not null) or status='not_started'),
  constraint academy_progress_completed_check check ((status='completed' and completed_at is not null) or status<>'completed')
);
create index if not exists academy_progress_content_idx on public.academy_progress(program_content_id,status);

insert into public.app_module_settings(module_key,label,sort_order)
values
  ('home','Inicio',10),
  ('students','Alumnado',20),
  ('teaching','Enseñanza',30),
  ('marketing','Marketing',40),
  ('statistics','Estadísticas',50),
  ('academy','Academia Online',60)
on conflict(module_key) do nothing;

-- Explicit Data API surface. RLS remains the authorization boundary.
grant select on public.app_module_settings, public.academy_programs, public.academy_program_contents,
  public.academy_enrollments, public.academy_progress to authenticated;
revoke insert, update, delete on public.app_module_settings, public.academy_programs, public.academy_program_contents,
  public.academy_enrollments, public.academy_progress from anon, authenticated;

alter table public.app_module_settings enable row level security;
alter table public.academy_programs enable row level security;
alter table public.academy_program_contents enable row level security;
alter table public.academy_enrollments enable row level security;
alter table public.academy_progress enable row level security;

drop policy if exists app_module_settings_read on public.app_module_settings;
create policy app_module_settings_read on public.app_module_settings for select to authenticated using (true);

drop policy if exists academy_programs_read on public.academy_programs;
create policy academy_programs_read on public.academy_programs for select to authenticated
using (
  (select private.is_staff())
  or (
    active and publication_status='published'
    and exists(
      select 1 from public.academy_enrollments e
      where e.program_id=id
        and e.person_id=(select private.current_person_id())
        and e.status in ('active','completed')
        and e.starts_at<=now()
        and (e.expires_at is null or e.expires_at>now())
    )
  )
);

drop policy if exists academy_program_contents_read on public.academy_program_contents;
create policy academy_program_contents_read on public.academy_program_contents for select to authenticated
using (
  (select private.is_staff())
  or exists(
    select 1
    from public.academy_enrollments e
    join public.academy_programs p on p.id=e.program_id
    where e.program_id=academy_program_contents.program_id
      and e.person_id=(select private.current_person_id())
      and e.status in ('active','completed')
      and e.starts_at<=now()
      and (e.expires_at is null or e.expires_at>now())
      and p.active and p.publication_status='published'
  )
);

drop policy if exists academy_enrollments_read on public.academy_enrollments;
create policy academy_enrollments_read on public.academy_enrollments for select to authenticated
using ((select private.is_staff()) or person_id=(select private.current_person_id()));

drop policy if exists academy_progress_read on public.academy_progress;
create policy academy_progress_read on public.academy_progress for select to authenticated
using (
  (select private.is_staff())
  or exists(
    select 1 from public.academy_enrollments e
    where e.id=enrollment_id and e.person_id=(select private.current_person_id())
  )
);

drop trigger if exists app_module_settings_touch_updated_at on public.app_module_settings;
create trigger app_module_settings_touch_updated_at before update on public.app_module_settings
for each row execute function private.touch_updated_at();
drop trigger if exists academy_programs_touch_updated_at on public.academy_programs;
create trigger academy_programs_touch_updated_at before update on public.academy_programs
for each row execute function private.touch_updated_at();
drop trigger if exists academy_enrollments_touch_updated_at on public.academy_enrollments;
create trigger academy_enrollments_touch_updated_at before update on public.academy_enrollments
for each row execute function private.touch_updated_at();

create or replace function private.academy_activate_student(p_person_id bigint)
returns void language plpgsql security definer set search_path=''
as $$
declare v_auth uuid;
begin
  select auth_user_id into v_auth from public.people where id=p_person_id and active;
  if not found then raise exception 'La persona no está disponible.' using errcode='22023'; end if;

  insert into public.student_profiles(person_id,student_since,active,created_by)
  values(p_person_id,current_date,true,(select auth.uid()))
  on conflict(person_id) do update set active=true,updated_at=now();

  if v_auth is not null then
    insert into public.app_member_roles(user_id,role,active,granted_by)
    values(v_auth,'student',true,(select auth.uid()))
    on conflict(user_id,role) do update set active=true,updated_at=now();
  end if;
end;
$$;
revoke all on function private.academy_activate_student(bigint) from public,anon,authenticated;

create or replace function private.academy_validate_context(p_style_term_id bigint,p_role_term_id bigint,p_level_term_id bigint)
returns void language plpgsql stable security definer set search_path=''
as $$
begin
  if not exists(select 1 from public.catalog_terms where id=p_style_term_id and taxonomy='dance_style' and active) then
    raise exception 'Selecciona un estilo válido.' using errcode='22023';
  end if;
  if not exists(select 1 from public.catalog_terms where id=p_role_term_id and taxonomy='dance_role' and active) then
    raise exception 'Selecciona un rol válido.' using errcode='22023';
  end if;
  if not exists(select 1 from public.catalog_terms where id=p_level_term_id and taxonomy='dance_level' and active) then
    raise exception 'Selecciona un nivel válido.' using errcode='22023';
  end if;
end;
$$;
revoke all on function private.academy_validate_context(bigint,bigint,bigint) from public,anon,authenticated;

create or replace function public.academy_save_program(
  p_program_id bigint,
  p_title text,
  p_description text,
  p_style_term_id bigint,
  p_role_term_id bigint,
  p_level_term_id bigint
) returns public.academy_programs
language plpgsql security definer set search_path=''
as $$
declare v_row public.academy_programs;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para editar Academia Online.' using errcode='42501'; end if;
  if nullif(btrim(coalesce(p_title,'')),'') is null then raise exception 'Indica un título para el programa.' using errcode='22023'; end if;
  perform private.academy_validate_context(p_style_term_id,p_role_term_id,p_level_term_id);

  if p_program_id is null then
    insert into public.academy_programs(title,description,style_term_id,role_term_id,level_term_id,created_by,updated_by)
    values(btrim(p_title),nullif(btrim(coalesce(p_description,'')),''),p_style_term_id,p_role_term_id,p_level_term_id,(select auth.uid()),(select auth.uid()))
    returning * into v_row;
  else
    update public.academy_programs
    set title=btrim(p_title),description=nullif(btrim(coalesce(p_description,'')),''),style_term_id=p_style_term_id,
        role_term_id=p_role_term_id,level_term_id=p_level_term_id,updated_by=(select auth.uid())
    where id=p_program_id and publication_status<>'archived'
    returning * into v_row;
    if v_row.id is null then raise exception 'No se ha encontrado un programa editable.' using errcode='22023'; end if;
  end if;
  return v_row;
end;
$$;
revoke all on function public.academy_save_program(bigint,text,text,bigint,bigint,bigint) from public,anon;
grant execute on function public.academy_save_program(bigint,text,text,bigint,bigint,bigint) to authenticated;

create or replace function public.academy_set_program_content(
  p_program_id bigint,
  p_content_id bigint,
  p_position integer,
  p_required boolean default true
) returns public.academy_program_contents
language plpgsql security definer set search_path=''
as $$
declare v_program public.academy_programs; v_row public.academy_program_contents;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para organizar Academia Online.' using errcode='42501'; end if;
  if p_position is null or p_position<1 or p_position>10000 then raise exception 'La posición no es válida.' using errcode='22023'; end if;

  select * into v_program from public.academy_programs where id=p_program_id and publication_status<>'archived' for update;
  if not found then raise exception 'No se ha encontrado el programa.' using errcode='22023'; end if;

  if not exists(
    select 1 from public.teaching_contents t
    where t.id=p_content_id and t.active and t.completion_status='complete' and t.publication_status='published' and t.visibility='student'
      and exists(select 1 from public.teaching_content_styles s where s.content_id=t.id and s.style_term_id=v_program.style_term_id)
      and exists(select 1 from public.teaching_content_roles r where r.content_id=t.id and r.role_term_id=v_program.role_term_id)
      and exists(select 1 from public.teaching_content_levels l where l.content_id=t.id and l.level_term_id=v_program.level_term_id)
  ) then
    raise exception 'El contenido debe estar completo, publicado para alumnos y ser compatible con el contexto del programa.' using errcode='22023';
  end if;

  if exists(select 1 from public.academy_program_contents where program_id=p_program_id and position=p_position and content_id<>p_content_id) then
    raise exception 'Ya existe otro contenido en esa posición.' using errcode='23505';
  end if;

  insert into public.academy_program_contents(program_id,content_id,position,required,created_by)
  values(p_program_id,p_content_id,p_position,coalesce(p_required,true),(select auth.uid()))
  on conflict(program_id,content_id) do update set position=excluded.position,required=excluded.required
  returning * into v_row;

  insert into public.academy_progress(enrollment_id,program_content_id)
  select e.id,v_row.id from public.academy_enrollments e
  where e.program_id=p_program_id and e.status in ('active','completed')
  on conflict(enrollment_id,program_content_id) do nothing;

  return v_row;
end;
$$;
revoke all on function public.academy_set_program_content(bigint,bigint,integer,boolean) from public,anon;
grant execute on function public.academy_set_program_content(bigint,bigint,integer,boolean) to authenticated;

create or replace function public.academy_remove_program_content(p_program_content_id bigint)
returns void language plpgsql security definer set search_path=''
as $$
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para organizar Academia Online.' using errcode='42501'; end if;
  delete from public.academy_program_contents where id=p_program_content_id;
  if not found then raise exception 'No se ha encontrado el contenido del programa.' using errcode='22023'; end if;
end;
$$;
revoke all on function public.academy_remove_program_content(bigint) from public,anon;
grant execute on function public.academy_remove_program_content(bigint) to authenticated;

create or replace function public.admin_academy_publish_program(
  p_program_id bigint,
  p_price_cents integer,
  p_currency text,
  p_active boolean,
  p_publication_status text
) returns public.academy_programs
language plpgsql security definer set search_path=''
as $$
declare v_row public.academy_programs;
begin
  if not (select private.is_admin()) then raise exception 'Solo Administración puede publicar y fijar el precio de Academia Online.' using errcode='42501'; end if;
  if p_publication_status not in ('draft','published','archived') then raise exception 'El estado de publicación no es válido.' using errcode='22023'; end if;
  if p_price_cents is not null and p_price_cents<0 then raise exception 'El precio no es válido.' using errcode='22023'; end if;
  if p_publication_status='published' then
    if p_price_cents is null then raise exception 'Configura el precio antes de publicar.' using errcode='22023'; end if;
    if not exists(select 1 from public.academy_program_contents where program_id=p_program_id) then raise exception 'Añade contenido antes de publicar el programa.' using errcode='22023'; end if;
  end if;
  if p_active and p_publication_status<>'published' then raise exception 'Solo un programa publicado puede estar activo.' using errcode='22023'; end if;

  update public.academy_programs
  set price_cents=p_price_cents,
      currency=upper(coalesce(nullif(btrim(coalesce(p_currency,'')),''),'EUR')),
      active=coalesce(p_active,false),
      publication_status=p_publication_status,
      published_at=case when p_publication_status='published' then coalesce(published_at,now()) else null end,
      updated_by=(select auth.uid())
  where id=p_program_id
  returning * into v_row;
  if v_row.id is null then raise exception 'No se ha encontrado el programa.' using errcode='22023'; end if;
  return v_row;
end;
$$;
revoke all on function public.admin_academy_publish_program(bigint,integer,text,boolean,text) from public,anon;
grant execute on function public.admin_academy_publish_program(bigint,integer,text,boolean,text) to authenticated;

create or replace function public.admin_academy_enroll(
  p_person_id bigint,
  p_program_id bigint,
  p_starts_at timestamptz default null,
  p_expires_at timestamptz default null,
  p_note text default null
) returns public.academy_enrollments
language plpgsql security definer set search_path=''
as $$
declare v_program public.academy_programs; v_row public.academy_enrollments; v_start timestamptz:=coalesce(p_starts_at,now());
begin
  if not (select private.is_admin()) then raise exception 'Solo Administración puede conceder acceso a Academia Online.' using errcode='42501'; end if;
  select * into v_program from public.academy_programs where id=p_program_id and active and publication_status='published';
  if not found then raise exception 'El programa debe estar publicado y activo antes de matricular.' using errcode='22023'; end if;
  if p_expires_at is not null and p_expires_at<=v_start then raise exception 'La fecha de fin debe ser posterior al inicio.' using errcode='22023'; end if;

  perform private.academy_activate_student(p_person_id);

  insert into public.academy_enrollments(program_id,person_id,status,access_source,starts_at,expires_at,granted_by,note)
  values(p_program_id,p_person_id,'active','admin',v_start,p_expires_at,(select auth.uid()),nullif(btrim(coalesce(p_note,'')),''))
  on conflict(program_id,person_id) do update
    set status='active',access_source='admin',starts_at=excluded.starts_at,expires_at=excluded.expires_at,
        completed_at=null,granted_by=(select auth.uid()),note=excluded.note,updated_at=now()
  returning * into v_row;

  insert into public.academy_progress(enrollment_id,program_content_id)
  select v_row.id,c.id from public.academy_program_contents c where c.program_id=p_program_id
  on conflict(enrollment_id,program_content_id) do nothing;

  return v_row;
end;
$$;
revoke all on function public.admin_academy_enroll(bigint,bigint,timestamptz,timestamptz,text) from public,anon;
grant execute on function public.admin_academy_enroll(bigint,bigint,timestamptz,timestamptz,text) to authenticated;

create or replace function public.admin_academy_cancel_enrollment(p_enrollment_id bigint,p_note text default null)
returns public.academy_enrollments
language plpgsql security definer set search_path=''
as $$
declare v_row public.academy_enrollments;
begin
  if not (select private.is_admin()) then raise exception 'Solo Administración puede cancelar matrículas de Academia Online.' using errcode='42501'; end if;
  update public.academy_enrollments
  set status='cancelled',completed_at=null,note=coalesce(nullif(btrim(coalesce(p_note,'')),''),note),updated_at=now()
  where id=p_enrollment_id
  returning * into v_row;
  if v_row.id is null then raise exception 'No se ha encontrado la matrícula.' using errcode='22023'; end if;
  return v_row;
end;
$$;
revoke all on function public.admin_academy_cancel_enrollment(bigint,text) from public,anon;
grant execute on function public.admin_academy_cancel_enrollment(bigint,text) to authenticated;

create or replace function public.admin_save_module_order(p_module_key text,p_sort_order integer)
returns public.app_module_settings
language plpgsql security definer set search_path=''
as $$
declare v_row public.app_module_settings;
begin
  if not (select private.is_admin()) then raise exception 'Solo Administración puede ordenar los módulos.' using errcode='42501'; end if;
  if p_sort_order is null or p_sort_order<0 or p_sort_order>1000 then raise exception 'El orden no es válido.' using errcode='22023'; end if;
  update public.app_module_settings set sort_order=p_sort_order,updated_by=(select auth.uid()) where module_key=p_module_key returning * into v_row;
  if v_row.module_key is null then raise exception 'El módulo no existe.' using errcode='22023'; end if;
  return v_row;
end;
$$;
revoke all on function public.admin_save_module_order(text,integer) from public,anon;
grant execute on function public.admin_save_module_order(text,integer) to authenticated;
