-- CYA Hub v97 · Mandatory curriculum is scoped by pedagogical tree (style + role).
-- `teaching_contents.is_mandatory` remains only as backwards-compatible “mandatory somewhere”.

create table if not exists public.teaching_trees (
  id bigint generated by default as identity primary key,
  style_term_id bigint not null references public.catalog_terms(id) on delete restrict,
  role_term_id bigint not null references public.catalog_terms(id) on delete restrict,
  active boolean not null default true,
  created_by uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(style_term_id, role_term_id)
);

create table if not exists public.teaching_tree_content_settings (
  tree_id bigint not null references public.teaching_trees(id) on delete cascade,
  content_id bigint not null references public.teaching_contents(id) on delete cascade,
  is_mandatory boolean not null default false,
  created_by uuid null references auth.users(id) on delete set null,
  updated_by uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key(tree_id, content_id)
);

create table if not exists public.student_tree_content_mastery (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.student_profiles(person_id) on delete cascade,
  tree_id bigint not null references public.teaching_trees(id) on delete cascade,
  content_id bigint not null references public.teaching_contents(id) on delete cascade,
  mastery_status text not null default 'pending' check (mastery_status in ('pending','certified','review')),
  certification_source text null check (certification_source is null or certification_source in ('manual','class','evaluation','derived_evaluation')),
  source_evaluation_session_id bigint null references public.evaluation_sessions(id) on delete set null,
  source_class_id bigint null references public.classes(id) on delete set null,
  certified_by uuid null references auth.users(id) on delete set null,
  certified_at timestamptz null,
  review_note text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(person_id, tree_id, content_id)
);

create index if not exists teaching_tree_settings_mandatory_idx on public.teaching_tree_content_settings(tree_id, is_mandatory, content_id);
create index if not exists student_tree_mastery_lookup_idx on public.student_tree_content_mastery(person_id, tree_id, mastery_status, content_id);

alter table public.teaching_trees enable row level security;
alter table public.teaching_tree_content_settings enable row level security;
alter table public.student_tree_content_mastery enable row level security;

drop policy if exists teaching_trees_staff_select on public.teaching_trees;
create policy teaching_trees_staff_select on public.teaching_trees for select using ((select private.is_staff()));
drop policy if exists teaching_trees_staff_insert on public.teaching_trees;
create policy teaching_trees_staff_insert on public.teaching_trees for insert with check ((select private.is_staff()));
drop policy if exists teaching_trees_staff_update on public.teaching_trees;
create policy teaching_trees_staff_update on public.teaching_trees for update using ((select private.is_staff())) with check ((select private.is_staff()));

drop policy if exists teaching_tree_settings_staff_select on public.teaching_tree_content_settings;
create policy teaching_tree_settings_staff_select on public.teaching_tree_content_settings for select using ((select private.is_staff()));
drop policy if exists teaching_tree_settings_staff_insert on public.teaching_tree_content_settings;
create policy teaching_tree_settings_staff_insert on public.teaching_tree_content_settings for insert with check ((select private.is_staff()));
drop policy if exists teaching_tree_settings_staff_update on public.teaching_tree_content_settings;
create policy teaching_tree_settings_staff_update on public.teaching_tree_content_settings for update using ((select private.is_staff())) with check ((select private.is_staff()));
drop policy if exists teaching_tree_settings_staff_delete on public.teaching_tree_content_settings;
create policy teaching_tree_settings_staff_delete on public.teaching_tree_content_settings for delete using ((select private.is_staff()));

drop policy if exists student_tree_mastery_staff_select on public.student_tree_content_mastery;
create policy student_tree_mastery_staff_select on public.student_tree_content_mastery for select using ((select private.is_staff()));
drop policy if exists student_tree_mastery_staff_insert on public.student_tree_content_mastery;
create policy student_tree_mastery_staff_insert on public.student_tree_content_mastery for insert with check ((select private.is_staff()));
drop policy if exists student_tree_mastery_staff_update on public.student_tree_content_mastery;
create policy student_tree_mastery_staff_update on public.student_tree_content_mastery for update using ((select private.is_staff())) with check ((select private.is_staff()));

insert into public.teaching_trees(style_term_id, role_term_id, created_by)
select distinct s.style_term_id, r.role_term_id, null::uuid
from public.teaching_contents c
join public.teaching_content_styles s on s.content_id=c.id
join public.teaching_content_roles r on r.content_id=c.id
where c.active=true
on conflict(style_term_id,role_term_id) do nothing;

insert into public.teaching_tree_content_settings(tree_id,content_id,is_mandatory,created_by,updated_by)
select t.id,c.id,true,null::uuid,null::uuid
from public.teaching_contents c
join public.teaching_content_styles s on s.content_id=c.id
join public.teaching_content_roles r on r.content_id=c.id
join public.teaching_trees t on t.style_term_id=s.style_term_id and t.role_term_id=r.role_term_id
where c.active=true and c.is_mandatory=true and c.content_type in ('explanation','sequence')
on conflict(tree_id,content_id) do update set is_mandatory=true,updated_at=now();

create or replace function public.set_teaching_tree_content_mandatory(p_style_term_id bigint,p_role_term_id bigint,p_content_id bigint,p_is_mandatory boolean)
returns table(tree_id bigint,content_id bigint,is_mandatory boolean)
language plpgsql security definer set search_path=public,private,auth as $$
declare v_tree_id bigint; v_type text;
begin
  if not private.is_staff() then raise exception 'No autorizado'; end if;
  select content_type into v_type from public.teaching_contents where id=p_content_id and active=true;
  if v_type is null then raise exception 'Contenido no encontrado'; end if;
  if p_is_mandatory and v_type not in ('explanation','sequence') then raise exception 'Solo Explicaciones y Secuencias pueden ser obligatorias'; end if;
  if not exists(select 1 from public.teaching_content_styles where content_id=p_content_id and style_term_id=p_style_term_id) then raise exception 'El contenido no pertenece a este estilo'; end if;
  if not exists(select 1 from public.teaching_content_roles where content_id=p_content_id and role_term_id=p_role_term_id) then raise exception 'El contenido no pertenece a este rol'; end if;
  insert into public.teaching_trees(style_term_id,role_term_id,created_by) values(p_style_term_id,p_role_term_id,auth.uid())
  on conflict(style_term_id,role_term_id) do update set active=true,updated_at=now() returning id into v_tree_id;
  insert into public.teaching_tree_content_settings(tree_id,content_id,is_mandatory,created_by,updated_by)
  values(v_tree_id,p_content_id,p_is_mandatory,auth.uid(),auth.uid())
  on conflict(tree_id,content_id) do update set is_mandatory=excluded.is_mandatory,updated_by=auth.uid(),updated_at=now();
  update public.teaching_contents c set is_mandatory=exists(select 1 from public.teaching_tree_content_settings s where s.content_id=p_content_id and s.is_mandatory),updated_at=now() where c.id=p_content_id;
  return query select v_tree_id,p_content_id,p_is_mandatory;
end $$;

create or replace function public.set_student_tree_content_mastery(p_person_id bigint,p_style_term_id bigint,p_role_term_id bigint,p_content_id bigint,p_mastery_status text,p_source text default 'manual',p_evaluation_session_id bigint default null,p_class_id bigint default null,p_note text default null)
returns public.student_tree_content_mastery language plpgsql security definer set search_path=public,private,auth as $$
declare v_tree_id bigint; v_row public.student_tree_content_mastery;
begin
  if not private.is_staff() then raise exception 'No autorizado'; end if;
  if p_mastery_status not in ('pending','certified','review') then raise exception 'Estado de dominio no válido'; end if;
  if p_source not in ('manual','class','evaluation','derived_evaluation') then raise exception 'Origen de certificación no válido'; end if;
  insert into public.teaching_trees(style_term_id,role_term_id,created_by) values(p_style_term_id,p_role_term_id,auth.uid()) on conflict(style_term_id,role_term_id) do update set active=true,updated_at=now() returning id into v_tree_id;
  if not exists(select 1 from public.teaching_content_styles where content_id=p_content_id and style_term_id=p_style_term_id) or not exists(select 1 from public.teaching_content_roles where content_id=p_content_id and role_term_id=p_role_term_id) then raise exception 'El contenido no pertenece a este árbol'; end if;
  insert into public.student_tree_content_mastery(person_id,tree_id,content_id,mastery_status,certification_source,source_evaluation_session_id,source_class_id,certified_by,certified_at,review_note)
  values(p_person_id,v_tree_id,p_content_id,p_mastery_status,case when p_mastery_status='certified' then p_source else null end,p_evaluation_session_id,p_class_id,case when p_mastery_status='certified' then auth.uid() else null end,case when p_mastery_status='certified' then now() else null end,case when p_mastery_status='review' then p_note else null end)
  on conflict(person_id,tree_id,content_id) do update set mastery_status=excluded.mastery_status,certification_source=excluded.certification_source,source_evaluation_session_id=excluded.source_evaluation_session_id,source_class_id=excluded.source_class_id,certified_by=excluded.certified_by,certified_at=excluded.certified_at,review_note=excluded.review_note,updated_at=now() returning * into v_row;
  return v_row;
end $$;

create or replace function public.accept_tree_evaluation_recommendation(p_person_id bigint,p_style_term_id bigint,p_role_term_id bigint,p_reference_content_id bigint,p_certify_reference boolean default false,p_evaluation_session_id bigint default null,p_class_id bigint default null)
returns table(certified_ancestors integer,reference_certified boolean,tree_id bigint)
language plpgsql security definer set search_path=public,private,auth as $$
declare v_tree_id bigint; v_count integer:=0; v_ref_cert boolean:=false;
begin
  if not private.is_staff() then raise exception 'No autorizado'; end if;
  insert into public.teaching_trees(style_term_id,role_term_id,created_by) values(p_style_term_id,p_role_term_id,auth.uid()) on conflict(style_term_id,role_term_id) do update set active=true,updated_at=now() returning id into v_tree_id;
  if not exists(select 1 from public.teaching_content_styles where content_id=p_reference_content_id and style_term_id=p_style_term_id) or not exists(select 1 from public.teaching_content_roles where content_id=p_reference_content_id and role_term_id=p_role_term_id) then raise exception 'El punto recomendado no pertenece a este árbol'; end if;
  with recursive ancestors(content_id) as (
    select r.target_content_id from public.teaching_content_relations r where r.source_content_id=p_reference_content_id and r.relation_type='prerequisite'
    union select r.target_content_id from public.teaching_content_relations r join ancestors a on r.source_content_id=a.content_id where r.relation_type='prerequisite'
  ), mandatory_ancestors as (
    select distinct a.content_id from ancestors a join public.teaching_tree_content_settings s on s.tree_id=v_tree_id and s.content_id=a.content_id and s.is_mandatory=true
  )
  insert into public.student_tree_content_mastery(person_id,tree_id,content_id,mastery_status,certification_source,source_evaluation_session_id,source_class_id,certified_by,certified_at,review_note)
  select p_person_id,v_tree_id,a.content_id,'certified','derived_evaluation',p_evaluation_session_id,p_class_id,auth.uid(),now(),null from mandatory_ancestors a
  on conflict(person_id,tree_id,content_id) do update set mastery_status='certified',certification_source='derived_evaluation',source_evaluation_session_id=excluded.source_evaluation_session_id,source_class_id=excluded.source_class_id,certified_by=auth.uid(),certified_at=now(),review_note=null,updated_at=now();
  get diagnostics v_count=row_count;
  if p_certify_reference then
    insert into public.student_tree_content_mastery(person_id,tree_id,content_id,mastery_status,certification_source,source_evaluation_session_id,source_class_id,certified_by,certified_at,review_note)
    values(p_person_id,v_tree_id,p_reference_content_id,'certified','evaluation',p_evaluation_session_id,p_class_id,auth.uid(),now(),null)
    on conflict(person_id,tree_id,content_id) do update set mastery_status='certified',certification_source='evaluation',source_evaluation_session_id=excluded.source_evaluation_session_id,source_class_id=excluded.source_class_id,certified_by=auth.uid(),certified_at=now(),review_note=null,updated_at=now();
    v_ref_cert:=true;
  end if;
  return query select v_count,v_ref_cert,v_tree_id;
end $$;

create or replace function public.get_student_tree_mandatory_progress(p_person_id bigint,p_style_term_id bigint,p_role_term_id bigint,p_level_term_id bigint default null)
returns table(content_id bigint,title text,content_type text,level_term_id bigint,mastery_status text,certified_at timestamptz)
language sql security definer set search_path=public,private,auth stable as $$
  select c.id,c.title,c.content_type,l.level_term_id,coalesce(m.mastery_status,'pending'),m.certified_at
  from public.teaching_trees t join public.teaching_tree_content_settings s on s.tree_id=t.id and s.is_mandatory=true join public.teaching_contents c on c.id=s.content_id and c.active=true join public.teaching_content_levels l on l.content_id=c.id left join public.student_tree_content_mastery m on m.person_id=p_person_id and m.tree_id=t.id and m.content_id=c.id
  where private.is_staff() and t.style_term_id=p_style_term_id and t.role_term_id=p_role_term_id and (p_level_term_id is null or l.level_term_id=p_level_term_id)
  order by l.level_term_id,c.title;
$$;

create or replace function public.get_student_tree_recommendations(p_person_id bigint,p_style_term_id bigint,p_role_term_id bigint,p_level_term_id bigint default null)
returns table(content_id bigint,title text,content_type text,level_term_id bigint,is_mandatory boolean,mastery_status text,ready boolean,blocked_prerequisites integer)
language sql security definer set search_path=public,private,auth stable as $$
  with tree as (select id from public.teaching_trees where style_term_id=p_style_term_id and role_term_id=p_role_term_id and active=true limit 1), candidates as (
    select c.id,c.title,c.content_type,l.level_term_id,coalesce(s.is_mandatory,false) is_mandatory,coalesce(m.mastery_status,'pending') mastery_status,t.id tree_id
    from tree t join public.teaching_content_styles cs on cs.style_term_id=p_style_term_id join public.teaching_contents c on c.id=cs.content_id and c.active=true and c.publication_status<>'archived' join public.teaching_content_roles cr on cr.content_id=c.id and cr.role_term_id=p_role_term_id join public.teaching_content_levels l on l.content_id=c.id left join public.teaching_tree_content_settings s on s.tree_id=t.id and s.content_id=c.id left join public.student_tree_content_mastery m on m.person_id=p_person_id and m.tree_id=t.id and m.content_id=c.id
    where (p_level_term_id is null or l.level_term_id=p_level_term_id) and c.content_type in ('explanation','sequence')
  )
  select x.id,x.title,x.content_type,x.level_term_id,x.is_mandatory,x.mastery_status,(x.blocked=0) ready,x.blocked from (
    select c.*,(select count(*)::integer from public.teaching_content_relations r where r.source_content_id=c.id and r.relation_type='prerequisite' and not (exists(select 1 from public.student_tree_content_mastery pm where pm.person_id=p_person_id and pm.tree_id=c.tree_id and pm.content_id=r.target_content_id and pm.mastery_status='certified') or exists(select 1 from public.student_content_assignments a where a.person_id=p_person_id and a.content_id=r.target_content_id and a.assignment_status in ('explained','completed')))) blocked from candidates c where c.mastery_status<>'certified'
  ) x where private.is_staff() order by x.is_mandatory desc,(x.blocked=0) desc,x.level_term_id,x.title;
$$;

create or replace function public.get_student_tree_level_readiness(p_person_id bigint,p_style_term_id bigint,p_role_term_id bigint,p_level_term_id bigint)
returns table(total_mandatory integer,certified_mandatory integer,pending_mandatory integer,ready_for_promotion boolean)
language sql security definer set search_path=public,private,auth stable as $$
  with required as (select s.content_id,t.id tree_id from public.teaching_trees t join public.teaching_tree_content_settings s on s.tree_id=t.id and s.is_mandatory=true join public.teaching_content_levels l on l.content_id=s.content_id and l.level_term_id=p_level_term_id where t.style_term_id=p_style_term_id and t.role_term_id=p_role_term_id), counts as (select count(*)::integer total,count(*) filter(where m.mastery_status='certified')::integer certified from required r left join public.student_tree_content_mastery m on m.person_id=p_person_id and m.tree_id=r.tree_id and m.content_id=r.content_id)
  select total,certified,(total-certified),(total>0 and total=certified) from counts where private.is_staff();
$$;

grant execute on function public.set_teaching_tree_content_mandatory(bigint,bigint,bigint,boolean) to authenticated;
grant execute on function public.set_student_tree_content_mastery(bigint,bigint,bigint,bigint,text,text,bigint,bigint,text) to authenticated;
grant execute on function public.accept_tree_evaluation_recommendation(bigint,bigint,bigint,bigint,boolean,bigint,bigint) to authenticated;
grant execute on function public.get_student_tree_mandatory_progress(bigint,bigint,bigint,bigint) to authenticated;
grant execute on function public.get_student_tree_recommendations(bigint,bigint,bigint,bigint) to authenticated;
grant execute on function public.get_student_tree_level_readiness(bigint,bigint,bigint,bigint) to authenticated;
