-- CYA Hub v29
-- Partial payments at class close + class explanatory videos stored in Google Drive.

create table if not exists public.class_financial_accounts (
  class_id bigint primary key references public.classes(id) on delete cascade,
  total_due_cents integer not null default 0 check (total_due_cents >= 0),
  paid_cents integer not null default 0 check (paid_cents >= 0),
  outstanding_cents integer generated always as (greatest(total_due_cents-paid_cents,0)) stored,
  status text not null default 'unpaid' check (status in ('paid','partial','unpaid')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (paid_cents <= total_due_cents)
);

create table if not exists public.class_payment_movements (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.class_financial_accounts(class_id) on delete cascade,
  amount_cents integer not null check (amount_cents > 0),
  note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists class_payment_movements_class_idx on public.class_payment_movements(class_id,created_at);

alter table public.class_financial_accounts enable row level security;
alter table public.class_payment_movements enable row level security;

drop policy if exists class_financial_accounts_staff_all on public.class_financial_accounts;
create policy class_financial_accounts_staff_all on public.class_financial_accounts
for all using ((select private.is_staff())) with check ((select private.is_staff()));

drop policy if exists class_financial_accounts_student_select on public.class_financial_accounts;
create policy class_financial_accounts_student_select on public.class_financial_accounts
for select using (
  exists(
    select 1 from public.class_participants cp
    where cp.class_id=class_financial_accounts.class_id
      and cp.person_id=(select private.current_person_id())
  )
);

drop policy if exists class_payment_movements_staff_all on public.class_payment_movements;
create policy class_payment_movements_staff_all on public.class_payment_movements
for all using ((select private.is_staff())) with check ((select private.is_staff()));

drop policy if exists class_payment_movements_student_select on public.class_payment_movements;
create policy class_payment_movements_student_select on public.class_payment_movements
for select using (
  exists(
    select 1 from public.class_participants cp
    where cp.class_id=class_payment_movements.class_id
      and cp.person_id=(select private.current_person_id())
  )
);

create or replace function public.record_class_payment(
  p_class_id bigint,
  p_amount_cents integer,
  p_note text default null
)
returns public.class_financial_accounts
language plpgsql
set search_path=''
as $$
declare
  v_account public.class_financial_accounts;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para registrar pagos.' using errcode='42501'; end if;
  if p_amount_cents is null or p_amount_cents<=0 then raise exception 'El importe debe ser mayor que cero.' using errcode='22023'; end if;
  select * into v_account from public.class_financial_accounts where class_id=p_class_id for update;
  if not found then raise exception 'La clase no tiene una cuenta económica abierta.' using errcode='P0002'; end if;
  if p_amount_cents>v_account.outstanding_cents then raise exception 'El pago supera el importe pendiente.' using errcode='22023'; end if;
  insert into public.class_payment_movements(class_id,amount_cents,note,created_by)
  values(p_class_id,p_amount_cents,nullif(btrim(p_note),''),(select auth.uid()));
  update public.class_financial_accounts
    set paid_cents=paid_cents+p_amount_cents,
        status=case when paid_cents+p_amount_cents>=total_due_cents then 'paid' else 'partial' end,
        updated_at=now()
    where class_id=p_class_id
    returning * into v_account;
  return v_account;
end;
$$;

create table if not exists public.class_video_resources (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  person_id bigint references public.people(id) on delete cascade,
  visibility_scope text not null check (visibility_scope in ('private_student','reusable')),
  provider text not null default 'google_drive' check (provider='google_drive'),
  external_file_id text not null unique check (external_file_id ~ '^[A-Za-z0-9_-]{10,200}$'),
  title text,
  mime_type text check (mime_type is null or mime_type like 'video/%'),
  size_bytes bigint check (size_bytes is null or (size_bytes>0 and size_bytes<=1073741824)),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  check (
    (visibility_scope='private_student' and person_id is not null)
    or (visibility_scope='reusable' and person_id is null)
  )
);

create index if not exists class_video_resources_class_idx on public.class_video_resources(class_id,created_at desc);
create index if not exists class_video_resources_person_idx on public.class_video_resources(person_id,created_at desc) where person_id is not null;
create index if not exists class_video_resources_reusable_idx on public.class_video_resources(created_at desc) where visibility_scope='reusable';

alter table public.class_video_resources enable row level security;
drop policy if exists class_video_resources_staff_all on public.class_video_resources;
create policy class_video_resources_staff_all on public.class_video_resources
for all using ((select private.is_staff())) with check ((select private.is_staff()));

drop policy if exists class_video_resources_student_select on public.class_video_resources;
create policy class_video_resources_student_select on public.class_video_resources
for select using (
  visibility_scope='private_student'
  and person_id=(select private.current_person_id())
);

create or replace function public.register_class_video_resource(
  p_class_id bigint,
  p_person_id bigint default null,
  p_visibility_scope text default 'private_student',
  p_external_file_id text default null,
  p_title text default null,
  p_mime_type text default null,
  p_size_bytes bigint default null,
  p_content_id bigint default null
)
returns public.class_video_resources
language plpgsql
set search_path=''
as $$
declare
  v_resource public.class_video_resources;
  v_content_type text;
  v_sort integer;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para guardar vídeos de clase.' using errcode='42501'; end if;
  if not exists(select 1 from public.classes where id=p_class_id) then raise exception 'La clase no existe.' using errcode='P0002'; end if;
  if p_visibility_scope not in ('private_student','reusable') then raise exception 'Visibilidad de vídeo no válida.' using errcode='22023'; end if;
  if p_external_file_id is null or p_external_file_id !~ '^[A-Za-z0-9_-]{10,200}$' then raise exception 'El archivo de Drive no es válido.' using errcode='22023'; end if;
  if p_mime_type is not null and p_mime_type not like 'video/%' then raise exception 'El recurso debe ser un vídeo.' using errcode='22023'; end if;
  if p_size_bytes is not null and (p_size_bytes<=0 or p_size_bytes>1073741824) then raise exception 'El vídeo debe ser menor de 1 GB.' using errcode='22023'; end if;

  if p_visibility_scope='private_student' then
    if p_person_id is null or not exists(
      select 1 from public.class_participants where class_id=p_class_id and person_id=p_person_id
    ) then raise exception 'Selecciona un alumno de esta clase.' using errcode='22023'; end if;
    if p_content_id is not null then raise exception 'Un vídeo privado no se vincula a contenido general.' using errcode='22023'; end if;
  else
    p_person_id:=null;
  end if;

  if p_content_id is not null then
    select content_type into v_content_type from public.teaching_contents where id=p_content_id and active;
    if not found or v_content_type not in ('correction','explanation','sequence') then
      raise exception 'El vídeo solo puede añadirse como recurso de una corrección, explicación o secuencia.' using errcode='22023';
    end if;
  end if;

  insert into public.class_video_resources(class_id,person_id,visibility_scope,provider,external_file_id,title,mime_type,size_bytes,created_by)
  values(p_class_id,p_person_id,p_visibility_scope,'google_drive',p_external_file_id,nullif(btrim(p_title),''),p_mime_type,p_size_bytes,(select auth.uid()))
  returning * into v_resource;

  if p_content_id is not null then
    select coalesce(max(sort_order),-1)+1 into v_sort from public.teaching_content_media where content_id=p_content_id;
    insert into public.teaching_content_media(
      content_id,media_type,provider,external_file_id,title,mime_type,sort_order,created_by,group_label,is_cover,is_preview,display_in_resources
    ) values(
      p_content_id,'video','google_drive',p_external_file_id,v_resource.title,p_mime_type,v_sort,(select auth.uid()),'Vídeo de clase',false,false,true
    ) on conflict (content_id,provider,external_file_id) do nothing;
  end if;

  return v_resource;
end;
$$;

create or replace function public.can_access_teaching_media(p_external_file_id text)
returns boolean
language plpgsql
stable
set search_path=''
as $$
declare
  v_person bigint;
begin
  if (select private.is_staff()) then
    return exists(
      select 1 from public.teaching_content_media m
      where m.external_file_id=p_external_file_id or m.thumbnail_external_file_id=p_external_file_id
    ) or exists(
      select 1 from public.class_video_resources v where v.external_file_id=p_external_file_id
    );
  end if;

  select private.current_person_id() into v_person;
  if v_person is null or not (select private.has_app_role('student')) then return false; end if;

  if exists(
    select 1 from public.class_video_resources v
    where v.external_file_id=p_external_file_id
      and v.visibility_scope='private_student'
      and v.person_id=v_person
  ) then return true; end if;

  return exists(
    select 1
    from public.teaching_content_media m
    join public.teaching_contents tc on tc.id=m.content_id
    join public.student_content_assignments a on a.content_id=tc.id and a.person_id=v_person
    where (m.external_file_id=p_external_file_id or m.thumbnail_external_file_id=p_external_file_id)
      and tc.active and tc.completion_status='complete' and tc.publication_status='published' and tc.visibility='student'
  );
end;
$$;

create or replace function public.administratively_finish_class_v5(
  p_class_id bigint,
  p_person_ids bigint[],
  p_grant_ids bigint[] default null,
  p_duration_minutes integer default null,
  p_direct_payment_price_cents integer default null,
  p_pair_transfer_source_grant_id bigint default null,
  p_pair_transfer_fee_cents integer default 0,
  p_supplements jsonb default '[]'::jsonb,
  p_paid_now_cents integer default null,
  p_quick_created_grant_id bigint default null
)
returns public.classes
language plpgsql
set search_path=''
as $$
declare
  v_class public.classes;
  v_result public.classes;
  v_account public.class_financial_accounts;
  v_item_total integer:=0;
  v_quick_price integer:=0;
  v_total integer:=0;
  v_paid integer:=0;
  v_direct_grant_id bigint;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para terminar clases.' using errcode='42501'; end if;
  select * into v_class from public.classes where id=p_class_id for update;
  if not found then raise exception 'La clase no existe.' using errcode='P0002'; end if;

  select * into v_account from public.class_financial_accounts where class_id=p_class_id;
  if found then return v_class; end if;

  if p_quick_created_grant_id is not null then
    if not p_quick_created_grant_id=any(coalesce(p_grant_ids,'{}'::bigint[])) then
      raise exception 'El bono rápido no coincide con el bono usado en la clase.' using errcode='22023';
    end if;
    select price_cents into v_quick_price
      from public.credit_grants
      where id=p_quick_created_grant_id and created_by=(select auth.uid());
    if not found then raise exception 'El bono rápido no pertenece a este cierre.' using errcode='22023'; end if;
  end if;

  v_result:=public.administratively_finish_class_v4(
    p_class_id,
    p_person_ids,
    p_grant_ids,
    p_duration_minutes,
    p_direct_payment_price_cents,
    p_pair_transfer_source_grant_id,
    p_pair_transfer_fee_cents,
    p_supplements
  );

  select coalesce(sum(amount_cents),0)::integer into v_item_total
    from public.class_financial_items where class_id=p_class_id;

  v_total:=v_item_total+coalesce(p_direct_payment_price_cents,0)+coalesce(v_quick_price,0);
  v_paid:=coalesce(p_paid_now_cents,v_total);
  if v_paid<0 or v_paid>v_total then raise exception 'El pago recibido debe estar entre 0 y el total de la clase.' using errcode='22023'; end if;

  insert into public.class_financial_accounts(class_id,total_due_cents,paid_cents,status,created_by)
  values(
    p_class_id,
    v_total,
    v_paid,
    case when v_paid>=v_total then 'paid' when v_paid=0 then 'unpaid' else 'partial' end,
    (select auth.uid())
  ) returning * into v_account;

  if v_paid>0 then
    insert into public.class_payment_movements(class_id,amount_cents,note,created_by)
    values(p_class_id,v_paid,'Pago registrado al terminar la clase',(select auth.uid()));
  end if;

  if p_quick_created_grant_id is not null then
    update public.credit_grants
      set payment_status=case when v_paid>=v_quick_price then 'paid' else 'pending' end,
          updated_at=now()
      where id=p_quick_created_grant_id;
  end if;

  if p_direct_payment_price_cents is not null then
    select min(billing_grant_id) into v_direct_grant_id
      from public.class_participants
      where class_id=p_class_id and billing_grant_id is not null;
    if v_direct_grant_id is not null then
      update public.credit_grants
        set payment_status=case when v_paid>=p_direct_payment_price_cents then 'paid' else 'pending' end,
            updated_at=now()
        where id=v_direct_grant_id;
    end if;
  end if;

  insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
  values(
    'class_payment_status','class',p_class_id::text,'Pago de clase registrado',
    jsonb_build_object('total_due_cents',v_total,'paid_now_cents',v_paid,'outstanding_cents',v_total-v_paid,'status',v_account.status),
    (select auth.uid())
  );

  return v_result;
end;
$$;

update public.integration_settings
set public_config=coalesce(public_config,'{}'::jsonb) || jsonb_build_object('class_videos_folder_id','1QqL1Wt0lNebcTO-2qtUGdgCsOF_IRiV_'),
    updated_at=now()
where integration_key='google_drive';

create or replace function private.backup_tables_for_domain(p_domain text)
returns text[]
language sql
stable
set search_path=''
as $$
  select case p_domain
    when 'people' then array[
      'people','student_profiles','student_dance_profiles','crm_profiles','crm_activities',
      'student_incidents','student_incident_people'
    ]::text[]
    when 'classes' then array[
      'catalog_terms','classes','class_participants','class_notes','student_evaluations',
      'class_financial_items','class_financial_accounts','class_payment_movements','class_video_resources'
    ]::text[]
    when 'credits' then array[
      'people','student_profiles','credit_grants','credit_grant_members','credit_movements',
      'student_incidents','student_incident_people','class_financial_items','class_financial_accounts','class_payment_movements'
    ]::text[]
    when 'teaching' then array[
      'catalog_terms','teaching_contents','teaching_content_styles','teaching_content_roles',
      'teaching_content_levels','teaching_content_tags','teaching_content_relations',
      'teaching_content_media','class_video_resources','student_content_assignments','student_content_measurements',
      'student_evaluations'
    ]::text[]
    when 'missions' then array[
      'mission_engine_settings','mission_rules','missions','mission_comments','mission_evidence'
    ]::text[]
    when 'marketing' then array[
      'marketing_rates','marketing_content','marketing_content_media','marketing_events',
      'marketing_campaigns','marketing_campaign_media','marketing_campaign_metrics',
      'communication_recipients','communication_events'
    ]::text[]
    when 'forms' then array[
      'form_definitions','form_versions','form_fields','form_submissions'
    ]::text[]
    when 'calendar' then array[
      'calendar_connections','calendar_events'
    ]::text[]
    when 'settings' then array[
      'user_profiles','user_preferences','app_members','app_member_roles','catalog_terms',
      'daily_quotes','notification_rules','notification_deliveries','internal_notifications',
      'integration_settings'
    ]::text[]
    when 'complete' then array[
      'user_profiles','user_preferences','app_members','app_member_roles','catalog_terms',
      'marketing_rates',
      'people','student_profiles','crm_profiles','crm_activities','student_dance_profiles',
      'integration_settings','calendar_connections','calendar_events',
      'marketing_events','marketing_content','marketing_content_media','marketing_campaigns',
      'marketing_campaign_media','marketing_campaign_metrics','communication_recipients','communication_events',
      'classes','credit_grants','credit_grant_members','class_participants','credit_movements','class_notes',
      'class_financial_items','class_financial_accounts','class_payment_movements','class_video_resources',
      'student_incidents','student_incident_people',
      'teaching_contents','teaching_content_styles','teaching_content_roles','teaching_content_levels',
      'teaching_content_tags','teaching_content_media','teaching_content_relations',
      'student_content_assignments','student_content_measurements','student_evaluations',
      'mission_engine_settings','mission_rules','missions','mission_comments','mission_evidence',
      'daily_quotes','notification_rules','internal_notifications','notification_deliveries',
      'form_definitions','form_versions','form_fields','form_submissions',
      'audit_events'
    ]::text[]
    else null
  end;
$$;
