-- CYA Hub v30
-- Final Point 8 close: pre-close pair transfers, shortfall regularization, multiple private recipients and safe administrative reopen.

alter table public.class_financial_items drop constraint if exists class_financial_items_item_type_check;
alter table public.class_financial_items
  add constraint class_financial_items_item_type_check
  check (item_type in ('supplement','pair_transfer','regularization'));

alter table public.class_video_resources drop constraint if exists class_video_resources_external_file_id_key;
create unique index if not exists class_video_resources_external_scope_person_uidx
  on public.class_video_resources(external_file_id,visibility_scope,coalesce(person_id,0));

create table if not exists public.class_close_grant_artifacts (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  grant_id bigint not null references public.credit_grants(id) on delete cascade,
  artifact_type text not null check (artifact_type in ('direct_payment','regularization','quick_bonus')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(class_id,grant_id,artifact_type)
);
create index if not exists class_close_grant_artifacts_class_idx on public.class_close_grant_artifacts(class_id,created_at);
alter table public.class_close_grant_artifacts enable row level security;
drop policy if exists class_close_grant_artifacts_staff_all on public.class_close_grant_artifacts;
create policy class_close_grant_artifacts_staff_all on public.class_close_grant_artifacts
for all using ((select private.is_staff())) with check ((select private.is_staff()));

grant select,insert,update,delete on public.class_financial_items to authenticated;
grant select,insert,update,delete on public.class_financial_accounts to authenticated;
grant select,insert,update,delete on public.class_payment_movements to authenticated;
grant select,insert,update,delete on public.class_video_resources to authenticated;
grant select,insert,update,delete on public.class_close_grant_artifacts to authenticated;
grant usage,select on sequence public.class_financial_items_id_seq to authenticated;
grant usage,select on sequence public.class_payment_movements_id_seq to authenticated;
grant usage,select on sequence public.class_video_resources_id_seq to authenticated;
grant usage,select on sequence public.class_close_grant_artifacts_id_seq to authenticated;

create or replace function public.transfer_individual_credit_to_pair(
  p_class_id bigint,
  p_source_grant_id bigint,
  p_minutes integer,
  p_fee_cents integer default 0
)
returns public.credit_grants
language plpgsql
set search_path=''
as $$
declare
  v_class public.classes;
  v_source public.credit_grants;
  v_source_people bigint[];
  v_class_people bigint[];
  v_source_balance integer;
  v_target public.credit_grants;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para transferir saldo.' using errcode='42501'; end if;
  if p_minutes is null or p_minutes<=0 then raise exception 'Indica los minutos que quieres transferir.' using errcode='22023'; end if;
  if coalesce(p_fee_cents,0)<0 then raise exception 'El coste adicional no puede ser negativo.' using errcode='22023'; end if;

  select * into v_class from public.classes where id=p_class_id for update;
  if not found then raise exception 'La clase no existe.' using errcode='P0002'; end if;
  if v_class.class_type<>'pair' then raise exception 'La transferencia solo está disponible en clases en pareja.' using errcode='22023'; end if;
  if v_class.status not in ('scheduled','active') or v_class.administrative_finished_at is not null then
    raise exception 'La clase ya no admite transferencias de saldo.' using errcode='22023';
  end if;
  if exists(select 1 from public.class_financial_accounts where class_id=p_class_id) then
    raise exception 'La clase ya tiene un cierre económico.' using errcode='22023';
  end if;

  select coalesce(array_agg(person_id order by person_id),'{}'::bigint[]) into v_class_people
    from public.class_participants where class_id=p_class_id;
  if cardinality(v_class_people)<>2 then raise exception 'La clase en pareja debe tener dos alumnos.' using errcode='22023'; end if;

  select * into v_source from public.credit_grants
    where id=p_source_grant_id and modality='individual' and status='active'
      and (expires_at is null or expires_at>now())
    for update;
  if not found then raise exception 'El bono individual no está activo o ha caducado.' using errcode='22023'; end if;
  select coalesce(array_agg(person_id order by person_id),'{}'::bigint[]) into v_source_people
    from public.credit_grant_members where grant_id=v_source.id;
  if cardinality(v_source_people)<>1 or not (v_source_people[1]=any(v_class_people)) then
    raise exception 'El bono individual no pertenece a uno de los alumnos de esta clase.' using errcode='22023';
  end if;
  select coalesce(sum(delta_minutes),0)::integer into v_source_balance
    from public.credit_movements where grant_id=v_source.id;
  if p_minutes>v_source_balance then raise exception 'No hay tantos minutos disponibles en el bono individual.' using errcode='22023'; end if;

  select * into v_target from public.create_credit_grant(
    v_class_people,'pair',p_minutes,0,'Transferencia a pareja','paid'
  );
  update public.credit_grants set expires_at=v_source.expires_at,updated_at=now() where id=v_target.id returning * into v_target;

  insert into public.credit_movements(grant_id,person_id,class_id,movement_type,delta_minutes,note,created_by)
  values(v_source.id,v_source_people[1],p_class_id,'adjustment',-p_minutes,
    'Transferencia a bono de pareja '||v_target.id::text,(select auth.uid()));
  if v_source_balance-p_minutes<=0 then
    update public.credit_grants set status='exhausted',updated_at=now() where id=v_source.id;
  end if;

  insert into public.class_financial_items(class_id,item_type,concept,amount_cents,minutes,person_id,source_grant_id,target_grant_id,created_by)
  values(p_class_id,'pair_transfer','Conversión de saldo individual a pareja',coalesce(p_fee_cents,0),p_minutes,v_source_people[1],v_source.id,v_target.id,(select auth.uid()));

  insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
  values('pair_credit_transfer','class',p_class_id::text,'Saldo individual transferido a pareja',
    jsonb_build_object('source_grant_id',v_source.id,'target_grant_id',v_target.id,'minutes',p_minutes,'fee_cents',coalesce(p_fee_cents,0)),
    (select auth.uid()));
  return v_target;
end;
$$;

grant execute on function public.transfer_individual_credit_to_pair(bigint,bigint,integer,integer) to authenticated;

create or replace function public.administratively_finish_class_v6(
  p_class_id bigint,
  p_person_ids bigint[],
  p_grant_ids bigint[] default null,
  p_duration_minutes integer default null,
  p_direct_payment_price_cents integer default null,
  p_supplements jsonb default '[]'::jsonb,
  p_regularizations jsonb default '[]'::jsonb,
  p_paid_now_cents integer default null,
  p_quick_created_grant_id bigint default null
)
returns public.classes
language plpgsql
set search_path=''
as $$
declare
  v_class public.classes;
  v_result public.classes;
  v_account public.class_financial_accounts;
  v_item_total integer:=0;
  v_quick_price integer:=0;
  v_total integer:=0;
  v_paid integer:=0;
  v_direct_grant_id bigint;
  v_reg jsonb;
  v_source_grant_id bigint;
  v_reg_minutes integer;
  v_reg_amount integer;
  v_reg_person_ids bigint[];
  v_source_modality text;
  v_class_people bigint[];
  v_shortfall integer;
  v_new_grant public.credit_grants;
  v_seen_sources bigint[]:='{}'::bigint[];
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para terminar clases.' using errcode='42501'; end if;
  select * into v_class from public.classes where id=p_class_id for update;
  if not found then raise exception 'La clase no existe.' using errcode='P0002'; end if;
  select * into v_account from public.class_financial_accounts where class_id=p_class_id;
  if found then return v_class; end if;

  if p_regularizations is null then p_regularizations:='[]'::jsonb; end if;
  if jsonb_typeof(p_regularizations)<>'array' or jsonb_array_length(p_regularizations)>10 then
    raise exception 'Las regularizaciones no son válidas.' using errcode='22023';
  end if;

  if p_quick_created_grant_id is not null then
    if not p_quick_created_grant_id=any(coalesce(p_grant_ids,'{}'::bigint[])) then
      raise exception 'El bono rápido no coincide con el bono usado en la clase.' using errcode='22023';
    end if;
    select price_cents into v_quick_price from public.credit_grants
      where id=p_quick_created_grant_id and created_by=(select auth.uid());
    if not found then raise exception 'El bono rápido no pertenece a este cierre.' using errcode='22023'; end if;
  end if;

  v_result:=public.administratively_finish_class_v4(
    p_class_id,p_person_ids,p_grant_ids,p_duration_minutes,p_direct_payment_price_cents,
    null,0,p_supplements
  );

  select coalesce(array_agg(person_id order by person_id),'{}'::bigint[]) into v_class_people
    from public.class_participants where class_id=p_class_id;

  for v_reg in select value from jsonb_array_elements(p_regularizations) s(value) loop
    if jsonb_typeof(v_reg)<>'object' then raise exception 'Regularización no válida.' using errcode='22023'; end if;
    if coalesce(v_reg->>'source_grant_id','') !~ '^[0-9]+$'
       or coalesce(v_reg->>'minutes','') !~ '^[0-9]+$'
       or coalesce(v_reg->>'amount_cents','') !~ '^[0-9]+$' then
      raise exception 'Regularización no válida.' using errcode='22023';
    end if;
    v_source_grant_id:=(v_reg->>'source_grant_id')::bigint;
    v_reg_minutes:=(v_reg->>'minutes')::integer;
    v_reg_amount:=(v_reg->>'amount_cents')::integer;
    if v_reg_minutes<=0 or v_reg_minutes>480 or v_reg_amount<0 or v_reg_amount>10000000 then
      raise exception 'Los minutos o el importe de regularización no son válidos.' using errcode='22023';
    end if;
    if v_source_grant_id=any(v_seen_sources) then raise exception 'Un bono no puede regularizarse dos veces en el mismo cierre.' using errcode='22023'; end if;
    v_seen_sources:=array_append(v_seen_sources,v_source_grant_id);

    select modality into v_source_modality from public.credit_grants where id=v_source_grant_id;
    if not found or v_source_modality<>v_class.class_type then raise exception 'El bono de la regularización no es compatible.' using errcode='22023'; end if;

    if v_source_modality='pair' then
      v_reg_person_ids:=v_class_people;
      if (select count(*) from public.class_participants where class_id=p_class_id and billing_grant_id=v_source_grant_id)<>cardinality(v_class_people) then
        raise exception 'El bono de pareja no coincide con el usado en la clase.' using errcode='22023';
      end if;
      select min(uncovered_minutes) into v_shortfall from public.class_participants
        where class_id=p_class_id and billing_grant_id=v_source_grant_id;
    else
      select array[person_id]::bigint[],uncovered_minutes into v_reg_person_ids,v_shortfall
        from public.class_participants
        where class_id=p_class_id and billing_grant_id=v_source_grant_id
        order by person_id limit 1;
      if v_reg_person_ids is null then raise exception 'El bono individual no coincide con el usado en la clase.' using errcode='22023'; end if;
    end if;
    if coalesce(v_shortfall,0)<=0 or v_reg_minutes>v_shortfall then
      raise exception 'La regularización supera los minutos pendientes.' using errcode='22023';
    end if;

    select * into v_new_grant from public.create_credit_grant(
      v_reg_person_ids,v_source_modality,v_reg_minutes,v_reg_amount,'Regularización de clase','pending'
    );
    insert into public.credit_movements(grant_id,person_id,class_id,movement_type,delta_minutes,note,created_by)
    values(v_new_grant.id,case when cardinality(v_reg_person_ids)=1 then v_reg_person_ids[1] else null end,p_class_id,'class',-v_reg_minutes,'Regularización consumida en la clase',(select auth.uid()));
    update public.credit_grants set status='exhausted',updated_at=now() where id=v_new_grant.id;

    update public.class_participants
      set uncovered_minutes=greatest(uncovered_minutes-v_reg_minutes,0),
          billing_status=case when greatest(uncovered_minutes-v_reg_minutes,0)=0 then 'covered' else 'partial' end,
          updated_at=now()
      where class_id=p_class_id and person_id=any(v_reg_person_ids);

    update public.student_incidents
      set remaining_minutes=greatest(remaining_minutes-v_reg_minutes,0),
          status=case when greatest(remaining_minutes-v_reg_minutes,0)=0 then 'resolved' else status end,
          resolution_mode=case when greatest(remaining_minutes-v_reg_minutes,0)=0 then 'regularized_at_close' else resolution_mode end,
          resolution_note=case when greatest(remaining_minutes-v_reg_minutes,0)=0 then 'Regularizado durante el cierre de la clase.' else resolution_note end,
          resolution_grant_id=case when greatest(remaining_minutes-v_reg_minutes,0)=0 then v_new_grant.id else resolution_grant_id end,
          resolved_by=case when greatest(remaining_minutes-v_reg_minutes,0)=0 then (select auth.uid()) else resolved_by end,
          resolved_at=case when greatest(remaining_minutes-v_reg_minutes,0)=0 then now() else resolved_at end,
          updated_at=now()
      where related_class_id=p_class_id and incident_type='negative_balance' and status='open'
        and (related_grant_id=v_source_grant_id or (related_grant_id is null and exists(select 1 from public.student_incident_people sip where sip.incident_id=student_incidents.id and sip.person_id=any(v_reg_person_ids))));

    insert into public.class_financial_items(class_id,item_type,concept,amount_cents,minutes,person_id,source_grant_id,target_grant_id,created_by)
    values(p_class_id,'regularization','Regularización de saldo',v_reg_amount,v_reg_minutes,
      case when cardinality(v_reg_person_ids)=1 then v_reg_person_ids[1] else null end,
      v_source_grant_id,v_new_grant.id,(select auth.uid()));
    insert into public.class_close_grant_artifacts(class_id,grant_id,artifact_type,created_by)
    values(p_class_id,v_new_grant.id,'regularization',(select auth.uid())) on conflict do nothing;
  end loop;

  if p_quick_created_grant_id is not null then
    insert into public.class_close_grant_artifacts(class_id,grant_id,artifact_type,created_by)
    values(p_class_id,p_quick_created_grant_id,'quick_bonus',(select auth.uid())) on conflict do nothing;
  end if;

  if p_direct_payment_price_cents is not null then
    select min(billing_grant_id) into v_direct_grant_id from public.class_participants
      where class_id=p_class_id and billing_grant_id is not null;
    if v_direct_grant_id is not null then
      insert into public.class_close_grant_artifacts(class_id,grant_id,artifact_type,created_by)
      values(p_class_id,v_direct_grant_id,'direct_payment',(select auth.uid())) on conflict do nothing;
    end if;
  end if;

  select coalesce(sum(amount_cents),0)::integer into v_item_total from public.class_financial_items where class_id=p_class_id;
  v_total:=v_item_total+coalesce(p_direct_payment_price_cents,0)+coalesce(v_quick_price,0);
  v_paid:=coalesce(p_paid_now_cents,v_total);
  if v_paid<0 or v_paid>v_total then raise exception 'El pago recibido debe estar entre 0 y el total de la clase.' using errcode='22023'; end if;

  insert into public.class_financial_accounts(class_id,total_due_cents,paid_cents,status,created_by)
  values(p_class_id,v_total,v_paid,
    case when v_paid>=v_total then 'paid' when v_paid=0 then 'unpaid' else 'partial' end,
    (select auth.uid())) returning * into v_account;
  if v_paid>0 then
    insert into public.class_payment_movements(class_id,amount_cents,note,created_by)
    values(p_class_id,v_paid,'Pago registrado al terminar la clase',(select auth.uid()));
  end if;

  update public.credit_grants g
    set payment_status=case when v_paid>=v_total then 'paid' else 'pending' end,updated_at=now()
    where exists(select 1 from public.class_close_grant_artifacts a where a.class_id=p_class_id and a.grant_id=g.id);

  insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
  values('class_payment_status','class',p_class_id::text,'Pago de clase registrado',
    jsonb_build_object('total_due_cents',v_total,'paid_now_cents',v_paid,'outstanding_cents',v_total-v_paid,'status',v_account.status,'regularizations',p_regularizations),
    (select auth.uid()));
  return v_result;
end;
$$;

grant execute on function public.administratively_finish_class_v6(bigint,bigint[],bigint[],integer,integer,jsonb,jsonb,integer,bigint) to authenticated;

create or replace function public.reopen_administratively_finished_class(p_class_id bigint)
returns public.classes
language plpgsql
set search_path=''
as $$
declare
  v_class public.classes;
  v_original_duration integer;
  v_financial_snapshot jsonb;
  v_m record;
  v_item record;
  v_art record;
  v_balance integer;
  v_incident_ids bigint[];
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para reabrir clases.' using errcode='42501'; end if;
  select * into v_class from public.classes where id=p_class_id for update;
  if not found then raise exception 'La clase no existe.' using errcode='P0002'; end if;
  if v_class.status<>'finished' or v_class.administrative_finished_at is null then
    raise exception 'La clase no tiene un cierre administrativo que deshacer.' using errcode='22023';
  end if;

  select case when detail->>'original_scheduled_duration_minutes' ~ '^[0-9]+$' then (detail->>'original_scheduled_duration_minutes')::integer else null end
    into v_original_duration
    from public.audit_events
    where event_type='class_administratively_finished' and entity_type='class' and entity_id=p_class_id::text
    order by created_at desc limit 1;

  select jsonb_build_object(
    'account',(select to_jsonb(a) from public.class_financial_accounts a where a.class_id=p_class_id),
    'items',coalesce((select jsonb_agg(to_jsonb(i) order by i.id) from public.class_financial_items i where i.class_id=p_class_id),'[]'::jsonb),
    'payments',coalesce((select jsonb_agg(to_jsonb(pm) order by pm.id) from public.class_payment_movements pm where pm.class_id=p_class_id),'[]'::jsonb)
  ) into v_financial_snapshot;

  for v_m in
    select grant_id,coalesce(sum(-delta_minutes),0)::integer as minutes
    from public.credit_movements
    where class_id=p_class_id and movement_type='class' and delta_minutes<0
    group by grant_id
  loop
    if v_m.minutes>0 then
      insert into public.credit_movements(grant_id,class_id,movement_type,delta_minutes,note,created_by)
      values(v_m.grant_id,p_class_id,'adjustment',v_m.minutes,'Reapertura de clase · devolución de consumo',(select auth.uid()));
      update public.credit_grants set status='active',updated_at=now() where id=v_m.grant_id;
    end if;
  end loop;

  for v_item in select * from public.class_financial_items where class_id=p_class_id and item_type='pair_transfer' order by id loop
    if v_item.source_grant_id is not null and coalesce(v_item.minutes,0)>0 then
      insert into public.credit_movements(grant_id,person_id,class_id,movement_type,delta_minutes,note,created_by)
      values(v_item.source_grant_id,v_item.person_id,p_class_id,'adjustment',v_item.minutes,'Reapertura de clase · devolución de transferencia',(select auth.uid()));
      update public.credit_grants set status='active',updated_at=now() where id=v_item.source_grant_id;
    end if;
    if v_item.target_grant_id is not null then
      select coalesce(sum(delta_minutes),0)::integer into v_balance from public.credit_movements where grant_id=v_item.target_grant_id;
      if v_balance>0 then
        insert into public.credit_movements(grant_id,class_id,movement_type,delta_minutes,note,created_by)
        values(v_item.target_grant_id,p_class_id,'adjustment',-v_balance,'Reapertura de clase · anulación del saldo transferido',(select auth.uid()));
      end if;
      update public.credit_grants set status='cancelled',updated_at=now() where id=v_item.target_grant_id;
    end if;
  end loop;

  for v_art in select * from public.class_close_grant_artifacts where class_id=p_class_id order by id loop
    select coalesce(sum(delta_minutes),0)::integer into v_balance from public.credit_movements where grant_id=v_art.grant_id;
    if v_art.artifact_type in ('direct_payment','regularization') then
      if v_balance<>0 then
        insert into public.credit_movements(grant_id,class_id,movement_type,delta_minutes,note,created_by)
        values(v_art.grant_id,p_class_id,'adjustment',-v_balance,'Reapertura de clase · anulación de bono generado en el cierre',(select auth.uid()));
      end if;
      update public.credit_grants set status='cancelled',payment_status='pending',updated_at=now() where id=v_art.grant_id;
    elsif v_art.artifact_type='quick_bonus' then
      update public.credit_grants set status=case when v_balance>0 then 'active' else status end,payment_status='pending',updated_at=now() where id=v_art.grant_id;
    end if;
  end loop;

  select coalesce(array_agg(id),'{}'::bigint[]) into v_incident_ids
    from public.student_incidents where related_class_id=p_class_id and incident_type='negative_balance';
  delete from public.student_incident_people where incident_id=any(v_incident_ids);
  delete from public.student_incidents where id=any(v_incident_ids);

  delete from public.class_payment_movements where class_id=p_class_id;
  delete from public.class_financial_accounts where class_id=p_class_id;
  delete from public.class_financial_items where class_id=p_class_id;
  delete from public.class_close_grant_artifacts where class_id=p_class_id;

  update public.class_participants
    set attendance_status='planned',billing_grant_id=null,billed_minutes=0,uncovered_minutes=0,billing_status='planned',updated_at=now()
    where class_id=p_class_id;

  update public.classes
    set status='active',duration_minutes=coalesce(v_original_duration,duration_minutes),
        administrative_finished_at=null,administratively_finished_by=null,pedagogy_closed_at=null,
        billed_duration_minutes=null,duration_source=null,actual_end_at=null,actual_duration_minutes=null,updated_at=now()
    where id=p_class_id returning * into v_class;

  insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
  values('class_administrative_reopened','class',p_class_id::text,'Cierre administrativo deshecho',
    jsonb_build_object('financial_snapshot',v_financial_snapshot,'original_duration_restored',v_original_duration,'incident_ids',v_incident_ids),
    (select auth.uid()));
  return v_class;
end;
$$;

grant execute on function public.reopen_administratively_finished_class(bigint) to authenticated;

create or replace function private.backup_tables_for_domain(p_domain text)
returns text[]
language sql
stable
set search_path=''
as $$
  select case p_domain
    when 'people' then array[
      'people','student_profiles','student_dance_profiles','crm_profiles','crm_activities',
      'student_incidents','student_incident_people'
    ]::text[]
    when 'classes' then array[
      'catalog_terms','classes','class_participants','class_notes','student_evaluations',
      'class_financial_items','class_financial_accounts','class_payment_movements','class_video_resources','class_close_grant_artifacts'
    ]::text[]
    when 'credits' then array[
      'people','student_profiles','credit_grants','credit_grant_members','credit_movements',
      'student_incidents','student_incident_people','class_financial_items','class_financial_accounts','class_payment_movements','class_close_grant_artifacts'
    ]::text[]
    when 'teaching' then array[
      'catalog_terms','teaching_contents','teaching_content_styles','teaching_content_roles',
      'teaching_content_levels','teaching_content_tags','teaching_content_relations',
      'teaching_content_media','class_video_resources','student_content_assignments','student_content_measurements',
      'student_evaluations'
    ]::text[]
    when 'missions' then array['mission_engine_settings','mission_rules','missions','mission_comments','mission_evidence']::text[]
    when 'marketing' then array[
      'marketing_rates','marketing_content','marketing_content_media','marketing_events','marketing_campaigns','marketing_campaign_media','marketing_campaign_metrics','communication_recipients','communication_events'
    ]::text[]
    when 'forms' then array['form_definitions','form_versions','form_fields','form_submissions']::text[]
    when 'calendar' then array['calendar_connections','calendar_events']::text[]
    when 'settings' then array[
      'user_profiles','user_preferences','app_members','app_member_roles','catalog_terms','daily_quotes','notification_rules','notification_deliveries','internal_notifications','integration_settings'
    ]::text[]
    when 'complete' then array[
      'user_profiles','user_preferences','app_members','app_member_roles','catalog_terms','marketing_rates',
      'people','student_profiles','crm_profiles','crm_activities','student_dance_profiles','integration_settings','calendar_connections','calendar_events',
      'marketing_events','marketing_content','marketing_content_media','marketing_campaigns','marketing_campaign_media','marketing_campaign_metrics','communication_recipients','communication_events',
      'classes','credit_grants','credit_grant_members','class_participants','credit_movements','class_notes',
      'class_financial_items','class_financial_accounts','class_payment_movements','class_video_resources','class_close_grant_artifacts',
      'student_incidents','student_incident_people','teaching_contents','teaching_content_styles','teaching_content_roles','teaching_content_levels',
      'teaching_content_tags','teaching_content_media','teaching_content_relations','student_content_assignments','student_content_measurements','student_evaluations',
      'mission_engine_settings','mission_rules','missions','mission_comments','mission_evidence','daily_quotes','notification_rules','internal_notifications','notification_deliveries',
      'form_definitions','form_versions','form_fields','form_submissions','audit_events'
    ]::text[]
    else null
  end;
$$;
