-- CYA Hub · v31 · flujo de clase, colaboración y visibilidad pedagógica

alter table public.classes add column if not exists location_text text;
alter table public.classes add column if not exists workflow_stage text not null default 'data';
update public.classes
set workflow_stage = case
  when pedagogy_closed_at is not null then 'closed'
  when status='finished' then 'administrative'
  when status='active' then 'live'
  else 'data'
end
where workflow_stage='data';
alter table public.classes drop constraint if exists classes_workflow_stage_check;
alter table public.classes add constraint classes_workflow_stage_check check (workflow_stage in ('data','prepare','live','administrative','closed'));

alter table public.class_participants add column if not exists preferred_billing_grant_id bigint references public.credit_grants(id) on delete set null;
alter table public.student_profiles add column if not exists health_notes text;
alter table public.student_content_assignments add column if not exists student_visible_at timestamptz;

-- Modelo pedagógico simplificado: estado persistente != evento de una clase.
update public.student_content_assignments a
set assignment_status='pending'
from public.teaching_contents t
where t.id=a.content_id and t.content_type='correction' and a.assignment_status='in_correction';
update public.student_content_assignments a
set assignment_status=case when a.assignment_status='completed' then 'explained' else 'pending' end
from public.teaching_contents t
where t.id=a.content_id and t.content_type='sequence' and a.assignment_status in ('practicing','completed');
update public.student_content_assignments a
set assignment_status='active'
from public.teaching_contents t
where t.id=a.content_id and t.content_type='exercise' and a.assignment_status='practicing';

alter table public.student_content_assignments drop constraint if exists student_content_assignments_assignment_status_check;
alter table public.student_content_assignments add constraint student_content_assignments_assignment_status_check
  check (assignment_status in ('pending','corrected','explained','active','completed'));

update public.student_content_assignments a
set student_visible_at=coalesce(a.completed_at,a.updated_at)
from public.teaching_contents t
where t.id=a.content_id
  and a.student_visible_at is null
  and t.active and t.completion_status='complete' and t.publication_status='published' and t.visibility='student'
  and ((t.content_type='correction' and a.assignment_status='corrected')
    or (t.content_type in ('explanation','sequence') and a.assignment_status='explained'));

alter table public.class_notes add column if not exists visibility_scope text not null default 'internal';
alter table public.class_notes drop constraint if exists class_notes_visibility_scope_check;
alter table public.class_notes add constraint class_notes_visibility_scope_check check (visibility_scope in ('internal','student'));

create table if not exists public.class_content_events(
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  person_id bigint not null references public.student_profiles(person_id) on delete cascade,
  content_id bigint not null references public.teaching_contents(id) on delete cascade,
  event_type text not null check (event_type in ('added','improved','reviewed','status_changed','measurement_changed','exercise_pending','exercise_active','exercise_completed')),
  previous_status text,
  new_status text,
  payload jsonb not null default '{}'::jsonb,
  visible_to_student boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists class_content_events_class_idx on public.class_content_events(class_id,created_at desc);
create index if not exists class_content_events_person_idx on public.class_content_events(person_id,created_at desc);

create table if not exists public.class_preparation_requests(
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  person_id bigint not null references public.student_profiles(person_id) on delete cascade,
  request_type text not null check (request_type in ('focus','comment','video','content')),
  body text,
  external_file_id text,
  content_id bigint references public.teaching_contents(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (body is not null or external_file_id is not null or content_id is not null)
);
create index if not exists class_preparation_requests_class_idx on public.class_preparation_requests(class_id,created_at);

create table if not exists public.class_pedagogy_summaries(
  class_id bigint primary key references public.classes(id) on delete cascade,
  student_message text,
  internal_note text,
  closed_by uuid references auth.users(id) on delete set null,
  closed_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.class_media_resources(
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  person_id bigint not null references public.student_profiles(person_id) on delete cascade,
  media_kind text not null check (media_kind in ('class_document','final_dance')),
  media_type text not null check (media_type in ('image','video')),
  provider text not null default 'google_drive' check (provider='google_drive'),
  external_file_id text not null check (external_file_id ~ '^[A-Za-z0-9_-]{10,200}$'),
  title text,
  mime_type text,
  size_bytes bigint check (size_bytes is null or (size_bytes>0 and size_bytes<=1073741824)),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(class_id,person_id,external_file_id)
);
create index if not exists class_media_resources_class_idx on public.class_media_resources(class_id,created_at desc);

alter table public.class_content_events enable row level security;
alter table public.class_preparation_requests enable row level security;
alter table public.class_pedagogy_summaries enable row level security;
alter table public.class_media_resources enable row level security;

drop policy if exists class_content_events_staff_all on public.class_content_events;
create policy class_content_events_staff_all on public.class_content_events for all to authenticated
  using ((select private.is_staff())) with check ((select private.is_staff()));
drop policy if exists class_content_events_student_select on public.class_content_events;
create policy class_content_events_student_select on public.class_content_events for select to authenticated
  using (visible_to_student and person_id=(select private.current_person_id()) and exists(select 1 from public.classes c where c.id=class_id and c.pedagogy_closed_at is not null));

drop policy if exists class_preparation_requests_staff_all on public.class_preparation_requests;
create policy class_preparation_requests_staff_all on public.class_preparation_requests for all to authenticated
  using ((select private.is_staff())) with check ((select private.is_staff()));
drop policy if exists class_preparation_requests_student_select on public.class_preparation_requests;
create policy class_preparation_requests_student_select on public.class_preparation_requests for select to authenticated
  using (person_id=(select private.current_person_id()));
drop policy if exists class_preparation_requests_student_insert on public.class_preparation_requests;
create policy class_preparation_requests_student_insert on public.class_preparation_requests for insert to authenticated
  with check (person_id=(select private.current_person_id()) and exists(select 1 from public.classes c join public.class_participants cp on cp.class_id=c.id where c.id=class_id and cp.person_id=person_id and c.status='scheduled'));
drop policy if exists class_preparation_requests_student_update on public.class_preparation_requests;
create policy class_preparation_requests_student_update on public.class_preparation_requests for update to authenticated
  using (person_id=(select private.current_person_id()) and exists(select 1 from public.classes c where c.id=class_id and c.status='scheduled'))
  with check (person_id=(select private.current_person_id()));
drop policy if exists class_preparation_requests_student_delete on public.class_preparation_requests;
create policy class_preparation_requests_student_delete on public.class_preparation_requests for delete to authenticated
  using (person_id=(select private.current_person_id()) and exists(select 1 from public.classes c where c.id=class_id and c.status='scheduled'));

drop policy if exists class_pedagogy_summaries_staff_all on public.class_pedagogy_summaries;
create policy class_pedagogy_summaries_staff_all on public.class_pedagogy_summaries for all to authenticated
  using ((select private.is_staff())) with check ((select private.is_staff()));
drop policy if exists class_pedagogy_summaries_student_select on public.class_pedagogy_summaries;
create policy class_pedagogy_summaries_student_select on public.class_pedagogy_summaries for select to authenticated
  using (exists(select 1 from public.classes c join public.class_participants cp on cp.class_id=c.id where c.id=class_id and cp.person_id=(select private.current_person_id()) and c.pedagogy_closed_at is not null));

drop policy if exists class_media_resources_staff_all on public.class_media_resources;
create policy class_media_resources_staff_all on public.class_media_resources for all to authenticated
  using ((select private.is_staff())) with check ((select private.is_staff()));
drop policy if exists class_media_resources_student_select on public.class_media_resources;
create policy class_media_resources_student_select on public.class_media_resources for select to authenticated
  using (person_id=(select private.current_person_id()) and exists(select 1 from public.classes c where c.id=class_id and c.pedagogy_closed_at is not null));

-- Los vídeos privados de cierre ya existentes tampoco son visibles antes del cierre pedagógico.
drop policy if exists class_video_resources_student_select on public.class_video_resources;
create policy class_video_resources_student_select on public.class_video_resources for select to authenticated
  using (visibility_scope='private_student' and person_id=(select private.current_person_id()) and exists(select 1 from public.classes c where c.id=class_id and c.pedagogy_closed_at is not null));

grant select,insert,update,delete on public.class_content_events,public.class_preparation_requests,public.class_pedagogy_summaries,public.class_media_resources to authenticated;
grant usage,select on all sequences in schema public to authenticated;

-- Realtime para dos profesores/dispositivos sobre la misma clase.
do $$
begin
  if exists(select 1 from pg_publication where pubname='supabase_realtime') then
    if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='class_notes') then alter publication supabase_realtime add table public.class_notes; end if;
    if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='class_content_events') then alter publication supabase_realtime add table public.class_content_events; end if;
    if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='student_content_assignments') then alter publication supabase_realtime add table public.student_content_assignments; end if;
  end if;
end $$;

create or replace function public.create_manual_class_draft(p_class_type text,p_student_ids bigint[])
returns public.classes language plpgsql set search_path='' as $$
declare v_ids bigint[]; v_expected int; v_class public.classes;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para crear clases.' using errcode='42501'; end if;
  if p_class_type not in ('individual','pair') then raise exception 'Tipo de clase no válido.' using errcode='22023'; end if;
  select coalesce(array_agg(id order by id),'{}'::bigint[]) into v_ids from (select distinct unnest(p_student_ids) id) s;
  v_expected:=case when p_class_type='pair' then 2 else 1 end;
  if cardinality(v_ids)<>v_expected then raise exception 'Selecciona % alumno(s) distintos.',v_expected using errcode='22023'; end if;
  if (select count(*) from public.student_profiles sp join public.people p on p.id=sp.person_id where sp.person_id=any(v_ids) and sp.active and p.active)<>v_expected then raise exception 'Hay alumnos no válidos o inactivos.' using errcode='22023'; end if;
  insert into public.classes(teacher_user_id,class_type,status,scheduled_start_at,duration_minutes,style_term_id,location_term_id,notes,created_by,workflow_stage)
  values((select auth.uid()),p_class_type,'scheduled',now(),60,null,null,null,(select auth.uid()),'data') returning * into v_class;
  insert into public.class_participants(class_id,person_id) select v_class.id,unnest(v_ids);
  return v_class;
end $$;

grant execute on function public.create_manual_class_draft(text,bigint[]) to authenticated;

create or replace function public.save_class_setup(
  p_class_id bigint,
  p_scheduled_start_at timestamptz,
  p_duration_minutes integer,
  p_style_term_id bigint,
  p_location_text text,
  p_person_ids bigint[],
  p_role_term_ids bigint[],
  p_level_term_ids bigint[],
  p_preferred_grant_ids bigint[] default null
) returns public.classes language plpgsql set search_path='' as $$
declare v_class public.classes; v_existing bigint[]; v_idx int; v_person bigint; v_role bigint; v_level bigint; v_grant bigint; v_members bigint[]; v_class_people bigint[]; v_balance int;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para preparar clases.' using errcode='42501'; end if;
  select * into v_class from public.classes where id=p_class_id for update;
  if not found then raise exception 'La clase no existe.' using errcode='P0002'; end if;
  if v_class.status not in ('scheduled','active') or v_class.administrative_finished_at is not null then raise exception 'Esta clase ya no admite cambios de preparación.' using errcode='22023'; end if;
  if p_scheduled_start_at is null or p_duration_minutes is null or p_duration_minutes<1 or p_duration_minutes>480 then raise exception 'Fecha y duración no válidas.' using errcode='22023'; end if;
  if not exists(select 1 from public.catalog_terms where id=p_style_term_id and taxonomy='dance_style' and active) then raise exception 'Selecciona un estilo válido.' using errcode='22023'; end if;
  select array_agg(person_id order by person_id) into v_existing from public.class_participants where class_id=p_class_id;
  select array_agg(x order by x) into v_class_people from unnest(p_person_ids) x;
  if v_existing is distinct from v_class_people then raise exception 'Los alumnos no coinciden con esta clase.' using errcode='22023'; end if;
  if cardinality(p_role_term_ids)<>cardinality(p_person_ids) or cardinality(p_level_term_ids)<>cardinality(p_person_ids) then raise exception 'Falta contexto de algún alumno.' using errcode='22023'; end if;
  if p_preferred_grant_ids is not null and cardinality(p_preferred_grant_ids)<>cardinality(p_person_ids) then raise exception 'La selección de bonos no coincide con los alumnos.' using errcode='22023'; end if;
  for v_idx in 1..cardinality(p_person_ids) loop
    v_person:=p_person_ids[v_idx]; v_role:=p_role_term_ids[v_idx]; v_level:=p_level_term_ids[v_idx]; v_grant:=case when p_preferred_grant_ids is null then null else p_preferred_grant_ids[v_idx] end;
    if v_role is not null and not exists(select 1 from public.catalog_terms where id=v_role and taxonomy='dance_role' and active) then raise exception 'Rol no válido.' using errcode='22023'; end if;
    if v_level is not null and not exists(select 1 from public.catalog_terms where id=v_level and taxonomy='dance_level' and active) then raise exception 'Nivel no válido.' using errcode='22023'; end if;
    if v_grant is not null then
      if not exists(select 1 from public.credit_grants g where g.id=v_grant and g.status='active' and (g.expires_at is null or g.expires_at>now())) then raise exception 'El bono seleccionado ya no está activo.' using errcode='22023'; end if;
      select coalesce(sum(delta_minutes),0)::int into v_balance from public.credit_movements where grant_id=v_grant;
      if v_balance<=0 then raise exception 'El bono seleccionado no tiene saldo.' using errcode='22023'; end if;
      select array_agg(person_id order by person_id) into v_members from public.credit_grant_members where grant_id=v_grant;
      if v_class.class_type='pair' then
        if (select modality from public.credit_grants where id=v_grant)<>'pair' or v_members is distinct from v_class_people then raise exception 'El bono de pareja no corresponde exactamente a esta pareja.' using errcode='22023'; end if;
      else
        if (select modality from public.credit_grants where id=v_grant)<>'individual' or v_members is distinct from array[v_person]::bigint[] then raise exception 'El bono individual no corresponde a este alumno.' using errcode='22023'; end if;
      end if;
    end if;
    update public.class_participants set role_term_id=v_role,level_term_id=v_level,preferred_billing_grant_id=v_grant where class_id=p_class_id and person_id=v_person;
  end loop;
  update public.classes set scheduled_start_at=p_scheduled_start_at,duration_minutes=p_duration_minutes,style_term_id=p_style_term_id,location_text=nullif(btrim(p_location_text),''),workflow_stage='prepare' where id=p_class_id returning * into v_class;
  return v_class;
end $$;

grant execute on function public.save_class_setup(bigint,timestamptz,integer,bigint,text,bigint[],bigint[],bigint[],bigint[]) to authenticated;

create or replace function public.start_class(p_class_id bigint)
returns public.classes language plpgsql set search_path='' as $$
declare v_class public.classes;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para iniciar clases.' using errcode='42501'; end if;
  select * into v_class from public.classes where id=p_class_id for update;
  if not found then raise exception 'La clase no existe.' using errcode='P0002'; end if;
  if v_class.status='active' then update public.classes set workflow_stage='live' where id=p_class_id returning * into v_class; return v_class; end if;
  if v_class.status<>'scheduled' then raise exception 'Solo se puede iniciar una clase programada.' using errcode='22023'; end if;
  if v_class.style_term_id is null or not exists(select 1 from public.catalog_terms where id=v_class.style_term_id and taxonomy='dance_style' and active) then raise exception 'Indica el estilo antes de empezar la clase.' using errcode='22023'; end if;
  if exists(select 1 from public.class_participants where class_id=p_class_id and (role_term_id is null or level_term_id is null)) then raise exception 'Confirma rol y nivel antes de empezar.' using errcode='22023'; end if;
  update public.classes set status='active',started_at=coalesce(started_at,now()),workflow_stage='live' where id=p_class_id returning * into v_class;
  return v_class;
end $$;

create or replace function public.add_class_note_v2(p_class_id bigint,p_person_id bigint,p_body text,p_visibility_scope text default 'internal')
returns public.class_notes language plpgsql set search_path='' as $$
declare v_note public.class_notes;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para guardar notas de clase.' using errcode='42501'; end if;
  if p_visibility_scope not in ('internal','student') then raise exception 'Visibilidad no válida.' using errcode='22023'; end if;
  if length(btrim(coalesce(p_body,'')))=0 then raise exception 'La nota está vacía.' using errcode='22023'; end if;
  if not exists(select 1 from public.classes where id=p_class_id and status in ('active','finished') and pedagogy_closed_at is null) then raise exception 'La clase no está abierta.' using errcode='22023'; end if;
  if p_person_id is not null and not exists(select 1 from public.class_participants where class_id=p_class_id and person_id=p_person_id) then raise exception 'El alumno no pertenece a esta clase.' using errcode='22023'; end if;
  insert into public.class_notes(class_id,person_id,note_kind,body,visibility_scope,created_by) values(p_class_id,p_person_id,'quick',btrim(p_body),p_visibility_scope,(select auth.uid())) returning * into v_note;
  return v_note;
end $$;
grant execute on function public.add_class_note_v2(bigint,bigint,text,text) to authenticated;

create or replace function public.create_class_correction(p_class_id bigint,p_person_id bigint,p_title text,p_measurement_mode text,p_frequency smallint,p_importance smallint)
returns public.student_content_assignments language plpgsql set search_path='' as $$
declare v_style_id bigint; v_role_id bigint; v_level_id bigint; v_category_id bigint; v_content public.teaching_contents; v_assignment public.student_content_assignments;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para crear correcciones.' using errcode='42501'; end if;
  if length(btrim(coalesce(p_title,'')))=0 then raise exception 'Escribe el nombre de la corrección.' using errcode='22023'; end if;
  if p_measurement_mode not in ('frequency','importance','both','none') then raise exception 'Modo de medición no válido.' using errcode='22023'; end if;
  if p_frequency is not null and (p_frequency<0 or p_frequency>100) then raise exception 'Frecuencia fuera de rango.' using errcode='22023'; end if;
  if p_importance is not null and (p_importance<0 or p_importance>100) then raise exception 'Importancia fuera de rango.' using errcode='22023'; end if;
  if p_measurement_mode in ('frequency','both') and p_frequency is null then raise exception 'Indica la frecuencia.' using errcode='22023'; end if;
  if p_measurement_mode in ('importance','both') and p_importance is null then raise exception 'Indica la importancia.' using errcode='22023'; end if;
  select c.style_term_id,cp.role_term_id,cp.level_term_id into v_style_id,v_role_id,v_level_id from public.classes c join public.class_participants cp on cp.class_id=c.id where c.id=p_class_id and cp.person_id=p_person_id and c.status in ('active','finished') and c.pedagogy_closed_at is null;
  if not found or v_style_id is null or v_role_id is null or v_level_id is null then raise exception 'Indica primero estilo, rol y nivel del alumno.' using errcode='22023'; end if;
  select id into v_category_id from public.catalog_terms where taxonomy='correction_category' and term_key='general' and active limit 1;
  insert into public.teaching_contents(content_type,title,completion_status,publication_status,visibility,measurement_mode,category_term_id,created_by)
  values('correction',btrim(p_title),'incomplete','draft','staff',p_measurement_mode,v_category_id,(select auth.uid())) returning * into v_content;
  insert into public.teaching_content_styles(content_id,style_term_id) values(v_content.id,v_style_id);
  insert into public.teaching_content_roles(content_id,role_term_id) values(v_content.id,v_role_id);
  insert into public.teaching_content_levels(content_id,level_term_id) values(v_content.id,v_level_id);
  insert into public.student_content_assignments(person_id,content_id,assignment_status,snapshot_style_term_id,snapshot_role_term_id,snapshot_level_term_id,snapshot_measurement_mode,current_frequency,current_importance,source_class_id,assigned_by)
  values(p_person_id,v_content.id,'pending',v_style_id,v_role_id,v_level_id,p_measurement_mode,p_frequency,p_importance,p_class_id,(select auth.uid())) returning * into v_assignment;
  insert into public.student_content_measurements(assignment_id,class_id,assignment_status,frequency_score,importance_score,measured_by) values(v_assignment.id,p_class_id,'pending',p_frequency,p_importance,(select auth.uid()));
  insert into public.class_content_events(class_id,person_id,content_id,event_type,new_status,payload,created_by) values(p_class_id,p_person_id,v_content.id,'added','pending',jsonb_build_object('content_type','correction'),(select auth.uid()));
  return v_assignment;
end $$;

create or replace function public.create_quick_class_content(p_class_id bigint,p_person_id bigint,p_content_type text,p_title text)
returns public.teaching_contents language plpgsql set search_path='' as $$
declare v_style bigint; v_role bigint; v_level bigint; v_category bigint; v_content public.teaching_contents; v_assignment public.student_content_assignments; v_tax text;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para crear contenido.' using errcode='42501'; end if;
  if p_content_type not in ('explanation','exercise','sequence') then raise exception 'Tipo de contenido no válido.' using errcode='22023'; end if;
  if length(btrim(coalesce(p_title,'')))=0 then raise exception 'Escribe un título.' using errcode='22023'; end if;
  select c.style_term_id,cp.role_term_id,cp.level_term_id into v_style,v_role,v_level from public.classes c join public.class_participants cp on cp.class_id=c.id where c.id=p_class_id and cp.person_id=p_person_id and c.status='active' and c.pedagogy_closed_at is null;
  if not found or v_style is null or v_role is null or v_level is null then raise exception 'Falta el contexto del alumno.' using errcode='22023'; end if;
  v_tax:=p_content_type||'_category'; select id into v_category from public.catalog_terms where taxonomy=v_tax and term_key='general' and active limit 1;
  insert into public.teaching_contents(content_type,title,completion_status,publication_status,visibility,measurement_mode,category_term_id,created_by)
  values(p_content_type,btrim(p_title),'incomplete','draft','staff','none',v_category,(select auth.uid())) returning * into v_content;
  insert into public.teaching_content_styles(content_id,style_term_id) values(v_content.id,v_style);
  insert into public.teaching_content_roles(content_id,role_term_id) values(v_content.id,v_role);
  insert into public.teaching_content_levels(content_id,level_term_id) values(v_content.id,v_level);
  if p_content_type='exercise' then
    insert into public.class_content_events(class_id,person_id,content_id,event_type,new_status,payload,created_by) values(p_class_id,p_person_id,v_content.id,'exercise_pending','pending',jsonb_build_object('content_type','exercise'),(select auth.uid()));
  else
    insert into public.student_content_assignments(person_id,content_id,assignment_status,snapshot_style_term_id,snapshot_role_term_id,snapshot_level_term_id,snapshot_measurement_mode,source_class_id,assigned_by)
    values(p_person_id,v_content.id,'pending',v_style,v_role,v_level,'none',p_class_id,(select auth.uid())) returning * into v_assignment;
    insert into public.class_content_events(class_id,person_id,content_id,event_type,new_status,payload,created_by) values(p_class_id,p_person_id,v_content.id,'added','pending',jsonb_build_object('content_type',p_content_type),(select auth.uid()));
  end if;
  return v_content;
end $$;
grant execute on function public.create_quick_class_content(bigint,bigint,text,text) to authenticated;

create or replace function public.assign_teaching_content(p_person_id bigint,p_content_id bigint,p_style_term_id bigint,p_role_term_id bigint,p_level_term_id bigint,p_source_class_id bigint)
returns public.student_content_assignments language plpgsql set search_path='' as $$
declare v_content public.teaching_contents; v_assignment public.student_content_assignments; v_new boolean:=false;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para asignar enseñanza.' using errcode='42501'; end if;
  if not exists(select 1 from public.student_profiles sp join public.people p on p.id=sp.person_id where sp.person_id=p_person_id and sp.active and p.active) then raise exception 'El alumno no está activo.' using errcode='22023'; end if;
  select * into v_content from public.teaching_contents where id=p_content_id and active and completion_status='complete' and publication_status='published';
  if not found then raise exception 'Solo se puede asignar contenido completo y publicado.' using errcode='22023'; end if;
  if not exists(select 1 from public.teaching_content_styles where content_id=p_content_id and style_term_id=p_style_term_id) or not exists(select 1 from public.teaching_content_roles where content_id=p_content_id and role_term_id=p_role_term_id) or not exists(select 1 from public.teaching_content_levels where content_id=p_content_id and level_term_id=p_level_term_id) then raise exception 'El contenido no corresponde al contexto elegido.' using errcode='22023'; end if;
  if p_source_class_id is not null and not exists(select 1 from public.classes c join public.class_participants cp on cp.class_id=c.id where c.id=p_source_class_id and cp.person_id=p_person_id and c.status in ('active','finished') and c.pedagogy_closed_at is null) then raise exception 'La clase no está abierta para este alumno.' using errcode='22023'; end if;
  insert into public.student_content_assignments(person_id,content_id,assignment_status,snapshot_style_term_id,snapshot_role_term_id,snapshot_level_term_id,snapshot_measurement_mode,source_class_id,assigned_by,student_visible_at)
  values(p_person_id,p_content_id,'pending',p_style_term_id,p_role_term_id,p_level_term_id,v_content.measurement_mode,p_source_class_id,(select auth.uid()),null)
  on conflict(person_id,content_id) do nothing returning * into v_assignment;
  if v_assignment.id is null then select * into v_assignment from public.student_content_assignments where person_id=p_person_id and content_id=p_content_id; else v_new:=true; insert into public.student_content_measurements(assignment_id,class_id,assignment_status,measured_by) values(v_assignment.id,p_source_class_id,'pending',(select auth.uid())); end if;
  if p_source_class_id is not null and v_new then insert into public.class_content_events(class_id,person_id,content_id,event_type,new_status,payload,created_by) values(p_source_class_id,p_person_id,p_content_id,'added','pending',jsonb_build_object('content_type',v_content.content_type),(select auth.uid())); end if;
  return v_assignment;
end $$;

create or replace function public.update_correction_assignment(p_assignment_id bigint,p_class_id bigint,p_assignment_status text,p_frequency smallint,p_importance smallint)
returns public.student_content_assignments language plpgsql set search_path='' as $$
declare v_assignment public.student_content_assignments; v_mode text; v_old_status text; v_old_frequency smallint; v_old_importance smallint; v_recent bigint; v_event text;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para actualizar correcciones.' using errcode='42501'; end if;
  if p_assignment_status not in ('pending','corrected') then raise exception 'Estado de corrección no válido.' using errcode='22023'; end if;
  select a.* into v_assignment from public.student_content_assignments a join public.teaching_contents t on t.id=a.content_id where a.id=p_assignment_id and t.content_type='correction' for update of a;
  if not found then raise exception 'La corrección no existe.' using errcode='P0002'; end if;
  if not exists(select 1 from public.class_participants where class_id=p_class_id and person_id=v_assignment.person_id) or not exists(select 1 from public.classes where id=p_class_id and status in ('active','finished') and pedagogy_closed_at is null) then raise exception 'La corrección no pertenece a una clase abierta.' using errcode='22023'; end if;
  v_mode:=v_assignment.snapshot_measurement_mode; v_old_status:=v_assignment.assignment_status; v_old_frequency:=v_assignment.current_frequency; v_old_importance:=v_assignment.current_importance;
  if p_frequency is not null and (p_frequency<0 or p_frequency>100) or p_importance is not null and (p_importance<0 or p_importance>100) then raise exception 'Medición fuera de rango.' using errcode='22023'; end if;
  if v_mode in ('frequency','both') and p_frequency is null then raise exception 'Indica la frecuencia.' using errcode='22023'; end if;
  if v_mode in ('importance','both') and p_importance is null then raise exception 'Indica la importancia.' using errcode='22023'; end if;
  update public.student_content_assignments set assignment_status=p_assignment_status,current_frequency=p_frequency,current_importance=p_importance,completed_at=case when p_assignment_status='corrected' then coalesce(completed_at,now()) else null end,student_visible_at=case when p_assignment_status='pending' then null else student_visible_at end where id=p_assignment_id returning * into v_assignment;
  select id into v_recent from public.student_content_measurements where assignment_id=p_assignment_id and created_at>=now()-interval '120 seconds' order by created_at desc limit 1 for update;
  if v_recent is null then insert into public.student_content_measurements(assignment_id,class_id,assignment_status,frequency_score,importance_score,measured_by) values(p_assignment_id,p_class_id,p_assignment_status,p_frequency,p_importance,(select auth.uid())); else update public.student_content_measurements set class_id=p_class_id,assignment_status=p_assignment_status,frequency_score=p_frequency,importance_score=p_importance,measured_by=(select auth.uid()) where id=v_recent; end if;
  v_event:=case when v_old_status is distinct from p_assignment_status then 'status_changed' else 'measurement_changed' end;
  insert into public.class_content_events(class_id,person_id,content_id,event_type,previous_status,new_status,payload,created_by) values(p_class_id,v_assignment.person_id,v_assignment.content_id,v_event,v_old_status,p_assignment_status,jsonb_build_object('content_type','correction','old_frequency',v_old_frequency,'new_frequency',p_frequency,'old_importance',v_old_importance,'new_importance',p_importance),(select auth.uid()));
  return v_assignment;
end $$;

create or replace function public.update_teaching_assignment_status(p_assignment_id bigint,p_assignment_status text)
returns public.student_content_assignments language plpgsql set search_path='' as $$
declare v_assignment public.student_content_assignments; v_type text; v_done boolean;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para actualizar enseñanza.' using errcode='42501'; end if;
  select a into v_assignment from public.student_content_assignments a where a.id=p_assignment_id for update;
  if not found then raise exception 'La asignación no existe.' using errcode='P0002'; end if;
  select t.content_type into v_type from public.teaching_contents t where t.id=v_assignment.content_id;
  if (v_type='correction' and p_assignment_status not in ('pending','corrected')) or (v_type in ('explanation','sequence') and p_assignment_status not in ('pending','explained')) or (v_type='exercise' and p_assignment_status not in ('pending','active','completed')) then raise exception 'Estado no válido para este tipo de contenido.' using errcode='22023'; end if;
  v_done:=p_assignment_status in ('corrected','explained','completed');
  update public.student_content_assignments set assignment_status=p_assignment_status,completed_at=case when v_done then coalesce(completed_at,now()) else null end,student_visible_at=case when not v_done then null else student_visible_at end where id=p_assignment_id returning * into v_assignment;
  insert into public.student_content_measurements(assignment_id,class_id,assignment_status,frequency_score,importance_score,measured_by) values(v_assignment.id,null,p_assignment_status,v_assignment.current_frequency,v_assignment.current_importance,(select auth.uid()));
  return v_assignment;
end $$;

create or replace function public.update_class_teaching_assignment_status(p_assignment_id bigint,p_class_id bigint,p_assignment_status text)
returns public.student_content_assignments language plpgsql set search_path='' as $$
declare v_assignment public.student_content_assignments; v_old text; v_type text;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para actualizar esta clase.' using errcode='42501'; end if;
  select a.assignment_status,t.content_type into v_old,v_type from public.student_content_assignments a join public.teaching_contents t on t.id=a.content_id where a.id=p_assignment_id;
  if v_type not in ('explanation','sequence') then raise exception 'Este cambio solo corresponde a explicaciones o secuencias.' using errcode='22023'; end if;
  if not exists(select 1 from public.student_content_assignments a join public.class_participants cp on cp.person_id=a.person_id where a.id=p_assignment_id and cp.class_id=p_class_id) then raise exception 'El contenido no pertenece a un alumno de esta clase.' using errcode='22023'; end if;
  select * into v_assignment from public.update_teaching_assignment_status(p_assignment_id,p_assignment_status);
  if v_old is distinct from p_assignment_status then insert into public.class_content_events(class_id,person_id,content_id,event_type,previous_status,new_status,payload,created_by) values(p_class_id,v_assignment.person_id,v_assignment.content_id,'status_changed',v_old,p_assignment_status,jsonb_build_object('content_type',v_type),(select auth.uid())); end if;
  return v_assignment;
end $$;
grant execute on function public.update_class_teaching_assignment_status(bigint,bigint,text) to authenticated;

create or replace function public.record_class_content_event(p_class_id bigint,p_person_id bigint,p_content_id bigint,p_event_type text,p_payload jsonb default '{}'::jsonb)
returns public.class_content_events language plpgsql set search_path='' as $$
declare v_event public.class_content_events; v_type text; v_status text; v_event_type text:=p_event_type;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para registrar actividad.' using errcode='42501'; end if;
  if not exists(select 1 from public.classes c join public.class_participants cp on cp.class_id=c.id where c.id=p_class_id and cp.person_id=p_person_id and c.status in ('active','finished') and c.pedagogy_closed_at is null) then raise exception 'La clase no está abierta para este alumno.' using errcode='22023'; end if;
  select content_type into v_type from public.teaching_contents where id=p_content_id and active;
  if v_type is null then raise exception 'El contenido no existe.' using errcode='P0002'; end if;
  select assignment_status into v_status from public.student_content_assignments where person_id=p_person_id and content_id=p_content_id;
  if p_event_type='improved' and (v_type<>'correction' or v_status is null) then raise exception 'Mejorado solo se usa con correcciones asignadas.' using errcode='22023'; end if;
  if p_event_type='reviewed' and (v_type not in ('explanation','sequence') or v_status<>'explained') then raise exception 'Solo se puede repasar contenido ya explicado.' using errcode='22023'; end if;
  if p_event_type in ('exercise_pending','exercise_active','exercise_completed') and v_type<>'exercise' then raise exception 'Ese estado solo corresponde a ejercicios.' using errcode='22023'; end if;
  if p_event_type not in ('improved','reviewed','exercise_pending','exercise_active','exercise_completed') then raise exception 'Actividad no válida.' using errcode='22023'; end if;
  insert into public.class_content_events(class_id,person_id,content_id,event_type,previous_status,new_status,payload,created_by)
  values(p_class_id,p_person_id,p_content_id,v_event_type,v_status,case when p_event_type like 'exercise_%' then replace(p_event_type,'exercise_','') else v_status end,coalesce(p_payload,'{}'::jsonb)||jsonb_build_object('content_type',v_type),(select auth.uid())) returning * into v_event;
  return v_event;
end $$;
grant execute on function public.record_class_content_event(bigint,bigint,bigint,text,jsonb) to authenticated;

create or replace function public.register_class_media_resource(p_class_id bigint,p_person_id bigint,p_media_kind text,p_external_file_id text,p_title text,p_mime_type text,p_size_bytes bigint)
returns public.class_media_resources language plpgsql set search_path='' as $$
declare v_media public.class_media_resources; v_type text;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para añadir documentación.' using errcode='42501'; end if;
  if p_media_kind not in ('class_document','final_dance') then raise exception 'Tipo de documento no válido.' using errcode='22023'; end if;
  if p_external_file_id is null or p_external_file_id !~ '^[A-Za-z0-9_-]{10,200}$' then raise exception 'Referencia de Drive no válida.' using errcode='22023'; end if;
  if p_mime_type like 'video/%' then v_type:='video'; elsif p_mime_type like 'image/%' then v_type:='image'; else raise exception 'Solo se admiten imágenes o vídeos.' using errcode='22023'; end if;
  if not exists(select 1 from public.class_participants where class_id=p_class_id and person_id=p_person_id) then raise exception 'El alumno no pertenece a esta clase.' using errcode='22023'; end if;
  insert into public.class_media_resources(class_id,person_id,media_kind,media_type,external_file_id,title,mime_type,size_bytes,created_by)
  values(p_class_id,p_person_id,p_media_kind,v_type,p_external_file_id,nullif(btrim(p_title),''),p_mime_type,p_size_bytes,(select auth.uid()))
  on conflict(class_id,person_id,external_file_id) do update set media_kind=excluded.media_kind,title=excluded.title
  returning * into v_media;
  return v_media;
end $$;
grant execute on function public.register_class_media_resource(bigint,bigint,text,text,text,text,bigint) to authenticated;

create or replace function public.close_class_pedagogy_v2(p_class_id bigint,p_student_message text default null,p_internal_note text default null)
returns public.classes language plpgsql set search_path='' as $$
declare v_class public.classes;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para cerrar clases.' using errcode='42501'; end if;
  select * into v_class from public.classes where id=p_class_id for update;
  if not found then raise exception 'La clase no existe.' using errcode='P0002'; end if;
  if v_class.status<>'finished' or v_class.administrative_finished_at is null then raise exception 'Termina primero la parte administrativa.' using errcode='22023'; end if;
  insert into public.class_pedagogy_summaries(class_id,student_message,internal_note,closed_by,closed_at,updated_at)
  values(p_class_id,nullif(btrim(p_student_message),''),nullif(btrim(p_internal_note),''),(select auth.uid()),now(),now())
  on conflict(class_id) do update set student_message=excluded.student_message,internal_note=excluded.internal_note,closed_by=excluded.closed_by,closed_at=now(),updated_at=now();

  update public.student_content_assignments a set student_visible_at=now()
  from public.teaching_contents t
  where t.id=a.content_id and a.person_id in (select person_id from public.class_participants where class_id=p_class_id)
    and exists(select 1 from public.class_content_events e where e.class_id=p_class_id and e.person_id=a.person_id and e.content_id=a.content_id)
    and t.active and t.completion_status='complete' and t.publication_status='published' and t.visibility='student'
    and ((t.content_type='correction' and a.assignment_status='corrected') or (t.content_type in ('explanation','sequence') and a.assignment_status='explained'));

  update public.class_content_events e set visible_to_student=true
  where e.class_id=p_class_id and (
    e.event_type='reviewed'
    or e.event_type in ('exercise_active','exercise_completed')
    or (e.event_type='status_changed' and e.new_status in ('corrected','explained') and exists(
      select 1 from public.teaching_contents t where t.id=e.content_id and t.active and t.completion_status='complete' and t.publication_status='published' and t.visibility='student'
    ))
  );
  update public.classes set pedagogy_closed_at=coalesce(pedagogy_closed_at,now()),workflow_stage='closed' where id=p_class_id returning * into v_class;
  return v_class;
end $$;
grant execute on function public.close_class_pedagogy_v2(bigint,text,text) to authenticated;

create or replace function public.close_class_pedagogy(p_class_id bigint)
returns public.classes language sql set search_path='' as $$ select public.close_class_pedagogy_v2(p_class_id,null,null); $$;

-- El portal solo recibe contenido realmente liberado al alumno.
create or replace function private.student_portal_snapshot_for(p_person_id bigint)
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare v_result jsonb; v_current bigint; v_credit integer; v_debt integer;
begin
  select private.current_person_id() into v_current;
  if not (select private.is_staff()) and not ((select private.has_app_role('student')) and v_current=p_person_id) then raise exception 'No tienes permiso para ver esta experiencia de alumno.' using errcode='42501'; end if;
  if not exists(select 1 from public.student_profiles where person_id=p_person_id and active) then raise exception 'La ficha de alumno no está activa.' using errcode='P0002'; end if;
  select coalesce(sum(greatest(0,coalesce((select sum(m.delta_minutes) from public.credit_movements m where m.grant_id=g.id),0))),0)::integer into v_credit from public.credit_grant_members gm join public.credit_grants g on g.id=gm.grant_id where gm.person_id=p_person_id and g.status='active';
  select coalesce(sum(i.remaining_minutes),0)::integer into v_debt from public.student_incidents i join public.student_incident_people ip on ip.incident_id=i.id where ip.person_id=p_person_id and i.incident_type='negative_balance' and i.status='open';
  select jsonb_build_object(
    'profile',(select jsonb_build_object('id',p.id,'display_name',p.display_name,'first_name',p.first_name,'last_name',p.last_name,'email',p.email,'phone',p.phone,'country_code',p.country_code,'student_since',sp.student_since,'goals',sp.goals) from public.people p join public.student_profiles sp on sp.person_id=p.id where p.id=p_person_id),
    'financial',jsonb_build_object('available_credit_minutes',v_credit,'pending_debt_minutes',v_debt,'net_balance_minutes',v_credit-v_debt,'open_incident_count',(select count(distinct i.id) from public.student_incidents i join public.student_incident_people ip on ip.incident_id=i.id where ip.person_id=p_person_id and i.status='open')),
    'classes',coalesce((select jsonb_agg(jsonb_build_object('id',c.id,'class_type',c.class_type,'status',c.status,'scheduled_start_at',c.scheduled_start_at,'duration_minutes',c.duration_minutes,'style',style.label,'attendance_status',cp.attendance_status,'billing_status',cp.billing_status,'uncovered_minutes',cp.uncovered_minutes,'role',role_term.label,'level',level_term.label) order by c.scheduled_start_at desc) from public.class_participants cp join public.classes c on c.id=cp.class_id left join public.catalog_terms style on style.id=c.style_term_id left join public.catalog_terms role_term on role_term.id=cp.role_term_id left join public.catalog_terms level_term on level_term.id=cp.level_term_id where cp.person_id=p_person_id),'[]'::jsonb),
    'credits',coalesce((select jsonb_agg(jsonb_build_object('id',g.id,'label',g.label,'modality',g.modality,'total_minutes',g.total_minutes,'balance_minutes',coalesce((select sum(m.delta_minutes) from public.credit_movements m where m.grant_id=g.id),0),'status',g.status,'purchased_at',g.purchased_at,'expires_at',g.expires_at) order by g.purchased_at desc) from public.credit_grant_members gm join public.credit_grants g on g.id=gm.grant_id where gm.person_id=p_person_id),'[]'::jsonb),
    'assignments',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'content_id',a.content_id,'title',tc.title,'content_type',tc.content_type,'description',tc.description,'correction_guidance',tc.correction_guidance,'assignment_status',a.assignment_status,'current_frequency',a.current_frequency,'current_importance',a.current_importance,'updated_at',a.updated_at,'media',coalesce((select jsonb_agg(jsonb_build_object('id',media.id,'media_type',media.media_type,'provider',media.provider,'external_file_id',media.external_file_id,'title',media.title,'mime_type',media.mime_type,'group_label',media.group_label,'is_cover',media.is_cover,'is_preview',media.is_preview,'display_in_resources',media.display_in_resources,'thumbnail_external_file_id',media.thumbnail_external_file_id,'thumbnail_mime_type',media.thumbnail_mime_type,'preview_start_seconds',media.preview_start_seconds,'preview_end_seconds',media.preview_end_seconds) order by media.sort_order,media.id) from public.teaching_content_media media where media.content_id=tc.id),'[]'::jsonb)) order by a.updated_at desc) from public.student_content_assignments a join public.teaching_contents tc on tc.id=a.content_id where a.person_id=p_person_id and a.student_visible_at is not null and tc.active and tc.completion_status='complete' and tc.publication_status='published' and tc.visibility='student' and ((tc.content_type='correction' and a.assignment_status='corrected') or (tc.content_type in ('explanation','sequence') and a.assignment_status='explained'))),'[]'::jsonb),
    'class_activity',coalesce((select jsonb_agg(jsonb_build_object('id',e.id,'class_id',e.class_id,'content_id',e.content_id,'title',t.title,'content_type',t.content_type,'event_type',e.event_type,'created_at',e.created_at) order by e.created_at desc) from public.class_content_events e join public.teaching_contents t on t.id=e.content_id join public.classes c on c.id=e.class_id where e.person_id=p_person_id and e.visible_to_student and c.pedagogy_closed_at is not null),'[]'::jsonb),
    'class_summaries',coalesce((select jsonb_agg(jsonb_build_object('class_id',s.class_id,'student_message',s.student_message,'closed_at',s.closed_at) order by s.closed_at desc) from public.class_pedagogy_summaries s join public.class_participants cp on cp.class_id=s.class_id join public.classes c on c.id=s.class_id where cp.person_id=p_person_id and c.pedagogy_closed_at is not null),'[]'::jsonb),
    'class_media',coalesce((select jsonb_agg(jsonb_build_object('id',m.id,'class_id',m.class_id,'media_kind',m.media_kind,'media_type',m.media_type,'external_file_id',m.external_file_id,'title',m.title,'mime_type',m.mime_type,'created_at',m.created_at) order by m.created_at desc) from public.class_media_resources m join public.classes c on c.id=m.class_id where m.person_id=p_person_id and c.pedagogy_closed_at is not null),'[]'::jsonb),
    'evaluations',coalesce((select jsonb_agg(jsonb_build_object('id',e.id,'class_id',e.class_id,'score',e.score,'aptitude',apt.label,'created_at',e.created_at) order by e.created_at desc) from public.student_evaluations e join public.catalog_terms apt on apt.id=e.aptitude_term_id where e.person_id=p_person_id),'[]'::jsonb)
  ) into v_result;
  return v_result;
end $$;
