-- CYA Hub · v44 · adelanto controlado P32/F42 · borrado y reinicio de datos
-- Objetivo:
-- - ofrecer borrados administrativos masivos y selectivos con previsualización;
-- - proteger el acceso técnico y la configuración base;
-- - ejecutar cada borrado de forma atómica y auditada;
-- - no borrar nunca auth.users, migraciones, roles administrativos ni secretos.
--
-- Este archivo crea infraestructura. NO ejecuta ningún borrado por sí mismo.

create table if not exists public.admin_reset_jobs (
  id bigint generated by default as identity primary key,
  scope text not null check (scope in (
    'person','teaching_content','students','teaching','classes','credits',
    'evaluations','marketing','missions_calendar_notifications',
    'operational','full'
  )),
  target_id bigint null,
  target_label text null,
  status text not null default 'validated'
    check (status in ('validated','running','completed','failed','cancelled')),
  preview jsonb not null default '{}'::jsonb,
  confirmation_phrase text not null,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 minutes'),
  completed_at timestamptz null,
  result jsonb not null default '{}'::jsonb
);

alter table public.admin_reset_jobs enable row level security;
revoke all on table public.admin_reset_jobs from public, anon, authenticated;

create index if not exists admin_reset_jobs_created_by_created_idx
  on public.admin_reset_jobs(created_by, created_at desc);

create or replace function private.reset_scope_label(p_scope text)
returns text
language sql
immutable
set search_path=''
as $$
  select case p_scope
    when 'students' then 'Todos los alumnos'
    when 'teaching' then 'Toda la enseñanza'
    when 'classes' then 'Todas las clases'
    when 'credits' then 'Todos los bonos y finanzas'
    when 'evaluations' then 'Todas las evaluaciones, medidas y progreso'
    when 'marketing' then 'Marketing, CRM, campañas y métricas'
    when 'missions_calendar_notifications' then 'Misiones, agenda generada y notificaciones'
    when 'operational' then 'Todos los datos operativos'
    when 'full' then 'Reinicio completo de CYA Hub'
    when 'person' then 'Persona / alumno'
    when 'teaching_content' then 'Contenido pedagógico'
    else 'Borrado de datos'
  end;
$$;

create or replace function private.is_staff_identity_person(p_person_id bigint)
returns boolean
language sql
stable
security definer
set search_path=''
as $$
  select exists(
    select 1
    from public.people p
    join public.app_member_roles r on r.user_id=p.auth_user_id
    where p.id=p_person_id
      and r.active
      and r.role in ('admin','teacher_admin','teacher')
  );
$$;

create or replace function private.count_jsonb_total(p_counts jsonb)
returns bigint
language sql
immutable
set search_path=''
as $$
  select coalesce(sum(value::bigint),0)
  from jsonb_each_text(coalesce(p_counts,'{}'::jsonb));
$$;

create or replace function private.admin_reset_preview_counts(
  p_scope text,
  p_target_id bigint default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path=''
as $$
declare
  v_counts jsonb := '{}'::jsonb;
  v_person bigint;
  v_content bigint;
begin
  if p_scope='person' then
    select id into v_person from public.people where id=p_target_id;
    if not found then
      raise exception 'La persona ya no existe.' using errcode='P0002';
    end if;

    v_counts := jsonb_build_object(
      'personas', 1,
      'perfiles_alumno', (select count(*) from public.student_profiles where person_id=v_person),
      'clases_compartidas', (select count(*) from public.class_participants where person_id=v_person),
      'bonos', (select count(distinct grant_id) from public.credit_grant_members where person_id=v_person),
      'evaluaciones', (select count(*) from public.evaluation_sessions where person_id=v_person),
      'asignaciones', (select count(*) from public.student_content_assignments where person_id=v_person),
      'medidas', (select count(*) from public.student_content_measurements m join public.student_content_assignments a on a.id=m.assignment_id where a.person_id=v_person),
      'incidencias', (select count(*) from public.student_incident_people where person_id=v_person),
      'crm', (select count(*) from public.crm_profiles where person_id=v_person)
             + (select count(*) from public.crm_activities where person_id=v_person)
    );
    return v_counts;
  end if;

  if p_scope='teaching_content' then
    select id into v_content from public.teaching_contents where id=p_target_id;
    if not found then
      raise exception 'El contenido ya no existe.' using errcode='P0002';
    end if;
    v_counts := jsonb_build_object(
      'contenidos', 1,
      'relaciones', (select count(*) from public.teaching_content_relations where source_content_id=v_content or target_content_id=v_content),
      'multimedia', (select count(*) from public.teaching_content_media where content_id=v_content),
      'asignaciones', (select count(*) from public.student_content_assignments where content_id=v_content),
      'medidas', (select count(*) from public.student_content_measurements m join public.student_content_assignments a on a.id=m.assignment_id where a.content_id=v_content),
      'uso_en_clases', (select count(*) from public.class_content_events where content_id=v_content),
      'premios_progreso', (select count(*) from public.evaluation_progress_awards where content_id=v_content)
    );
    return v_counts;
  end if;

  if p_scope='students' then
    return jsonb_build_object(
      'perfiles_alumno',(select count(*) from public.student_profiles),
      'clases',(select count(*) from public.classes),
      'bonos',(select count(*) from public.credit_grants),
      'evaluaciones',(select count(*) from public.evaluation_sessions),
      'medidas',(select count(*) from public.student_content_measurements),
      'asignaciones',(select count(*) from public.student_content_assignments),
      'incidencias',(select count(*) from public.student_incidents)
    );
  end if;

  if p_scope='teaching' then
    return jsonb_build_object(
      'contenidos',(select count(*) from public.teaching_contents),
      'relaciones',(select count(*) from public.teaching_content_relations),
      'multimedia',(select count(*) from public.teaching_content_media),
      'asignaciones',(select count(*) from public.student_content_assignments),
      'medidas',(select count(*) from public.student_content_measurements),
      'uso_en_clases',(select count(*) from public.class_content_events)
    );
  end if;

  if p_scope='classes' then
    return jsonb_build_object(
      'clases',(select count(*) from public.classes),
      'participantes',(select count(*) from public.class_participants),
      'notas',(select count(*) from public.class_notes),
      'contenido_clase',(select count(*) from public.class_content_events),
      'archivos_clase',(select count(*) from public.class_media_resources)+(select count(*) from public.class_video_resources),
      'evaluaciones_clase',(select count(*) from public.evaluation_sessions where class_id is not null),
      'finanzas_clase',(select count(*) from public.class_financial_items)+(select count(*) from public.class_payment_movements)
    );
  end if;

  if p_scope='credits' then
    return jsonb_build_object(
      'bonos',(select count(*) from public.credit_grants),
      'miembros_bono',(select count(*) from public.credit_grant_members),
      'movimientos',(select count(*) from public.credit_movements),
      'referencias_financieras',(select count(*) from public.class_close_grant_artifacts)
    );
  end if;

  if p_scope='evaluations' then
    return jsonb_build_object(
      'sesiones',(select count(*) from public.evaluation_sessions),
      'respuestas',(select count(*) from public.student_evaluations),
      'progreso',(select count(*) from public.student_aptitude_progress),
      'decisiones',(select count(*) from public.evaluation_milestone_decisions),
      'premios',(select count(*) from public.evaluation_progress_awards),
      'medidas_contenido',(select count(*) from public.student_content_measurements)
    );
  end if;

  if p_scope='marketing' then
    return jsonb_build_object(
      'crm',(select count(*) from public.crm_profiles)+(select count(*) from public.crm_activities),
      'contenido',(select count(*) from public.marketing_content)+(select count(*) from public.marketing_content_media),
      'eventos',(select count(*) from public.marketing_events),
      'campanas',(select count(*) from public.marketing_campaigns),
      'metricas',(select count(*) from public.marketing_campaign_metrics),
      'comunicaciones',(select count(*) from public.communication_recipients)+(select count(*) from public.communication_events)
    );
  end if;

  if p_scope='missions_calendar_notifications' then
    return jsonb_build_object(
      'misiones',(select count(*) from public.missions),
      'comentarios_evidencias',(select count(*) from public.mission_comments)+(select count(*) from public.mission_evidence),
      'eventos_calendario',(select count(*) from public.calendar_events),
      'avisos',(select count(*) from public.internal_notifications),
      'entregas_notificacion',(select count(*) from public.notification_deliveries)
    );
  end if;

  if p_scope in ('operational','full') then
    return jsonb_build_object(
      'personas_no_staff',(
        select count(*) from public.people p
        where not exists(
          select 1 from public.app_member_roles r
          where r.user_id=p.auth_user_id and r.active and r.role in ('admin','teacher_admin','teacher')
        )
      ),
      'perfiles_alumno',(select count(*) from public.student_profiles),
      'clases',(select count(*) from public.classes),
      'bonos',(select count(*) from public.credit_grants),
      'evaluaciones',(select count(*) from public.evaluation_sessions),
      'medidas',(select count(*) from public.student_content_measurements),
      'asignaciones',(select count(*) from public.student_content_assignments),
      'incidencias',(select count(*) from public.student_incidents),
      'crm',(select count(*) from public.crm_profiles)+(select count(*) from public.crm_activities),
      'marketing',(select count(*) from public.marketing_content)+(select count(*) from public.marketing_campaigns)+(select count(*) from public.marketing_events),
      'metricas_marketing',(select count(*) from public.marketing_campaign_metrics),
      'misiones',(select count(*) from public.missions),
      'agenda',(select count(*) from public.calendar_events),
      'notificaciones',(select count(*) from public.internal_notifications)+(select count(*) from public.notification_deliveries),
      'formularios_enviados',(select count(*) from public.form_submissions),
      'ensenanza',case when p_scope='full' then (select count(*) from public.teaching_contents) else 0 end,
      'tarifas',case when p_scope='full' then (select count(*) from public.marketing_rates) else 0 end,
      'frases_diarias',case when p_scope='full' then (select count(*) from public.daily_quotes) else 0 end,
      'historial_transferencias',case when p_scope='full' then (select count(*) from public.data_transfer_jobs) else 0 end,
      'auditoria_previa',case when p_scope='full' then (select count(*) from public.audit_events) else 0 end
    );
  end if;

  raise exception 'Alcance de borrado no válido.' using errcode='22023';
end;
$$;

create or replace function public.search_admin_reset_targets(
  p_kind text,
  p_query text default ''
)
returns table(
  kind text,
  id bigint,
  label text,
  subtype text,
  detail text,
  protected boolean
)
language plpgsql
security definer
set search_path=''
as $$
begin
  if not (select private.is_admin()) then
    raise exception 'Solo un administrador puede buscar datos para borrar.' using errcode='42501';
  end if;

  if p_kind='person' then
    return query
    select
      'person'::text,
      p.id,
      p.display_name,
      case when sp.person_id is not null then 'Alumno' else 'Contacto / CRM' end,
      concat_ws(' · ', nullif(p.email,''), nullif(p.phone,''), nullif(p.crm_stage,'')),
      private.is_staff_identity_person(p.id)
    from public.people p
    left join public.student_profiles sp on sp.person_id=p.id
    where coalesce(btrim(p_query),'')=''
       or p.display_name ilike '%'||btrim(p_query)||'%'
       or coalesce(p.email,'') ilike '%'||btrim(p_query)||'%'
       or coalesce(p.phone,'') ilike '%'||btrim(p_query)||'%'
    order by p.display_name
    limit 30;
    return;
  end if;

  if p_kind='teaching_content' then
    return query
    select
      'teaching_content'::text,
      t.id,
      t.title,
      case t.content_type
        when 'correction' then 'Corrección'
        when 'explanation' then 'Explicación'
        when 'exercise' then 'Ejercicio'
        when 'sequence' then 'Secuencia'
        else t.content_type
      end,
      coalesce(nullif(t.description,''), nullif(t.correction_guidance,''), 'Sin descripción'),
      false
    from public.teaching_contents t
    where coalesce(btrim(p_query),'')=''
       or t.title ilike '%'||btrim(p_query)||'%'
       or coalesce(t.description,'') ilike '%'||btrim(p_query)||'%'
       or coalesce(t.correction_guidance,'') ilike '%'||btrim(p_query)||'%'
    order by t.content_type,t.title
    limit 30;
    return;
  end if;

  raise exception 'Tipo de búsqueda no válido.' using errcode='22023';
end;
$$;

create or replace function public.preview_admin_data_reset(
  p_scope text,
  p_target_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_counts jsonb;
  v_total bigint;
  v_target_label text;
  v_phrase text;
  v_job_id bigint;
  v_protected boolean := false;
begin
  if not (select private.is_admin()) then
    raise exception 'Solo un administrador puede preparar un borrado.' using errcode='42501';
  end if;

  if p_scope not in (
    'person','teaching_content','students','teaching','classes','credits',
    'evaluations','marketing','missions_calendar_notifications','operational','full'
  ) then
    raise exception 'Alcance de borrado no válido.' using errcode='22023';
  end if;

  if p_scope in ('person','teaching_content') and p_target_id is null then
    raise exception 'Selecciona primero el registro que quieres borrar.' using errcode='22023';
  end if;

  if p_scope='person' then
    select display_name, private.is_staff_identity_person(id)
      into v_target_label,v_protected
    from public.people where id=p_target_id;
    if not found then raise exception 'La persona ya no existe.' using errcode='P0002'; end if;
    if v_protected then
      raise exception 'Esta persona está vinculada a una identidad activa de profesor/administrador y no puede borrarse por completo. Puedes vaciar sus datos de alumno mediante el borrado de alumnos.' using errcode='42501';
    end if;
    v_phrase := 'BORRAR PERSONA '||p_target_id::text;
  elsif p_scope='teaching_content' then
    select title into v_target_label from public.teaching_contents where id=p_target_id;
    if not found then raise exception 'El contenido ya no existe.' using errcode='P0002'; end if;
    v_phrase := 'BORRAR CONTENIDO '||p_target_id::text;
  else
    v_target_label := private.reset_scope_label(p_scope);
    v_phrase := case p_scope
      when 'students' then 'BORRAR TODOS LOS ALUMNOS'
      when 'teaching' then 'BORRAR TODA LA ENSENANZA'
      when 'classes' then 'BORRAR TODAS LAS CLASES'
      when 'credits' then 'BORRAR TODOS LOS BONOS'
      when 'evaluations' then 'BORRAR TODAS LAS EVALUACIONES'
      when 'marketing' then 'BORRAR TODO MARKETING'
      when 'missions_calendar_notifications' then 'BORRAR MISIONES AGENDA Y AVISOS'
      when 'operational' then 'REINICIAR DATOS OPERATIVOS'
      when 'full' then 'REINICIAR CYA HUB'
    end;
  end if;

  v_counts := private.admin_reset_preview_counts(p_scope,p_target_id);
  v_total := private.count_jsonb_total(v_counts);

  insert into public.admin_reset_jobs(
    scope,target_id,target_label,status,preview,confirmation_phrase,created_by
  )
  values(
    p_scope,p_target_id,v_target_label,'validated',
    jsonb_build_object(
      'counts',v_counts,
      'total',v_total,
      'scope_label',private.reset_scope_label(p_scope),
      'preserves',case
        when p_scope='full' then jsonb_build_array(
          'Supabase Auth','roles de acceso','perfil técnico de miembros del equipo',
          'catálogos base','formularios y configuración','reglas del sistema',
          'integraciones y secretos'
        )
        else jsonb_build_array('configuración y accesos técnicos')
      end
    ),
    v_phrase,(select auth.uid())
  )
  returning id into v_job_id;

  return jsonb_build_object(
    'job_id',v_job_id,
    'scope',p_scope,
    'target_id',p_target_id,
    'target_label',v_target_label,
    'confirmation_phrase',v_phrase,
    'expires_at',now()+interval '30 minutes',
    'preview',jsonb_build_object(
      'counts',v_counts,
      'total',v_total,
      'scope_label',private.reset_scope_label(p_scope),
      'preserves',case
        when p_scope='full' then jsonb_build_array(
          'Supabase Auth','roles de acceso','perfil técnico de miembros del equipo',
          'catálogos base','formularios y configuración','reglas del sistema',
          'integraciones y secretos'
        )
        else jsonb_build_array('configuración y accesos técnicos')
      end
    )
  );
end;
$$;

create or replace function private.delete_single_person(p_person_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_removed_classes bigint := 0;
  v_removed_grants bigint := 0;
begin
  if private.is_staff_identity_person(p_person_id) then
    raise exception 'No se puede borrar una identidad activa del equipo.' using errcode='42501';
  end if;

  delete from public.form_submissions where person_id=p_person_id;
  delete from public.class_financial_items where person_id=p_person_id;
  delete from public.credit_movements cm where cm.person_id=p_person_id and (
    cm.grant_id is null or not exists(
      select 1 from public.credit_grant_members gm
      where gm.grant_id=cm.grant_id and gm.person_id<>p_person_id
    )
  );

  delete from public.class_participants where person_id=p_person_id;
  delete from public.credit_grant_members where person_id=p_person_id;
  delete from public.student_incident_people where person_id=p_person_id;

  delete from public.student_incidents i
  where not exists(select 1 from public.student_incident_people ip where ip.incident_id=i.id);

  update public.student_incidents i
  set related_class_id=null
  where i.related_class_id in (
    select c.id from public.classes c
    where not exists(select 1 from public.class_participants cp where cp.class_id=c.id)
  );

  with gone as (
    delete from public.classes c
    where not exists(select 1 from public.class_participants cp where cp.class_id=c.id)
    returning 1
  ) select count(*) into v_removed_classes from gone;

  delete from public.credit_movements cm
  where cm.grant_id in (
    select g.id from public.credit_grants g
    where not exists(select 1 from public.credit_grant_members gm where gm.grant_id=g.id)
  );

  with gone as (
    delete from public.credit_grants g
    where not exists(select 1 from public.credit_grant_members gm where gm.grant_id=g.id)
    returning 1
  ) select count(*) into v_removed_grants from gone;

  delete from public.student_profiles where person_id=p_person_id;
  delete from public.people where id=p_person_id;

  return jsonb_build_object(
    'person_id',p_person_id,
    'empty_classes_removed',v_removed_classes,
    'empty_grants_removed',v_removed_grants
  );
end;
$$;

create or replace function private.execute_admin_data_reset(
  p_scope text,
  p_target_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_before jsonb;
begin
  v_before := private.admin_reset_preview_counts(p_scope,p_target_id);
  perform pg_advisory_xact_lock(90520260811);

  if p_scope='person' then
    return private.delete_single_person(p_target_id);
  end if;

  if p_scope='teaching_content' then
    delete from public.evaluation_progress_awards where content_id=p_target_id;
    delete from public.teaching_contents where id=p_target_id;
    return jsonb_build_object('content_id',p_target_id);
  end if;

  if p_scope='classes' then
    delete from public.student_incident_people
    where incident_id in (select id from public.student_incidents where related_class_id is not null);
    delete from public.student_incidents where related_class_id is not null;
    delete from public.evaluation_sessions where class_id is not null;
    delete from public.classes;
    return jsonb_build_object('before',v_before);
  end if;

  if p_scope='credits' then
    delete from public.credit_movements;
    delete from public.credit_grants;
    return jsonb_build_object('before',v_before);
  end if;

  if p_scope='evaluations' then
    delete from public.evaluation_milestone_decisions;
    delete from public.evaluation_progress_awards;
    delete from public.student_evaluations;
    delete from public.student_aptitude_progress;
    delete from public.evaluation_sessions;
    delete from public.student_content_measurements;
    return jsonb_build_object('before',v_before);
  end if;

  if p_scope='teaching' then
    delete from public.evaluation_progress_awards where content_id is not null;
    delete from public.teaching_contents;
    return jsonb_build_object('before',v_before);
  end if;

  if p_scope='marketing' then
    delete from public.communication_events;
    delete from public.communication_recipients;
    delete from public.marketing_campaign_metrics;
    delete from public.marketing_campaign_media;
    delete from public.marketing_campaigns;
    delete from public.marketing_content_media;
    delete from public.marketing_content;
    delete from public.marketing_events;
    delete from public.crm_activities;
    delete from public.crm_profiles;
    return jsonb_build_object('before',v_before);
  end if;

  if p_scope='missions_calendar_notifications' then
    delete from public.mission_comments;
    delete from public.mission_evidence;
    delete from public.missions;
    delete from public.calendar_events;
    delete from public.internal_notifications;
    delete from public.notification_deliveries;
    return jsonb_build_object('before',v_before);
  end if;

  if p_scope='students' then
    delete from public.evaluation_milestone_decisions;
    delete from public.evaluation_progress_awards;
    delete from public.student_evaluations;
    delete from public.student_aptitude_progress;
    delete from public.evaluation_sessions;
    delete from public.student_content_measurements;
    delete from public.student_content_assignments;
    delete from public.student_incident_people;
    delete from public.student_incidents;
    delete from public.credit_movements;
    delete from public.classes;
    delete from public.credit_grants;
    delete from public.student_dance_profiles;
    delete from public.student_profiles;
    return jsonb_build_object('before',v_before);
  end if;

  if p_scope in ('operational','full') then
    delete from public.evaluation_milestone_decisions;
    delete from public.evaluation_progress_awards;
    delete from public.student_evaluations;
    delete from public.student_aptitude_progress;
    delete from public.evaluation_sessions;

    delete from public.student_content_measurements;
    delete from public.student_content_assignments;

    delete from public.student_incident_people;
    delete from public.student_incidents;

    delete from public.credit_movements;
    delete from public.classes;
    delete from public.credit_grants;

    delete from public.student_dance_profiles;
    delete from public.student_profiles;

    delete from public.communication_events;
    delete from public.communication_recipients;
    delete from public.marketing_campaign_metrics;
    delete from public.marketing_campaign_media;
    delete from public.marketing_campaigns;
    delete from public.marketing_content_media;
    delete from public.marketing_content;
    delete from public.marketing_events;
    delete from public.crm_activities;
    delete from public.crm_profiles;

    delete from public.mission_comments;
    delete from public.mission_evidence;
    delete from public.missions;
    delete from public.calendar_events;
    delete from public.internal_notifications;
    delete from public.notification_deliveries;
    delete from public.form_submissions;

    delete from public.people p
    where not exists(
      select 1
      from public.app_member_roles r
      where r.user_id=p.auth_user_id
        and r.active
        and r.role in ('admin','teacher_admin','teacher')
    );

    if p_scope='full' then
      delete from public.teaching_contents;
      delete from public.marketing_rates;
      delete from public.daily_quotes;
      delete from public.data_transfer_jobs;
      delete from public.audit_events;
    end if;

    return jsonb_build_object('before',v_before);
  end if;

  raise exception 'Alcance de borrado no válido.' using errcode='22023';
end;
$$;

create or replace function public.apply_admin_data_reset(
  p_job_id bigint,
  p_confirmation text
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_job public.admin_reset_jobs;
  v_result jsonb;
  v_after jsonb;
begin
  if not (select private.is_admin()) then
    raise exception 'Solo un administrador puede ejecutar un borrado.' using errcode='42501';
  end if;

  select * into v_job
  from public.admin_reset_jobs
  where id=p_job_id
  for update;

  if not found then
    raise exception 'La preparación de borrado ya no existe.' using errcode='P0002';
  end if;
  if v_job.created_by<>(select auth.uid()) then
    raise exception 'La confirmación pertenece a otra sesión administrativa.' using errcode='42501';
  end if;
  if v_job.status<>'validated' then
    raise exception 'Este borrado ya fue utilizado o cancelado.' using errcode='22023';
  end if;
  if v_job.expires_at<now() then
    update public.admin_reset_jobs set status='cancelled' where id=v_job.id;
    raise exception 'La confirmación ha caducado. Previsualiza el borrado de nuevo.' using errcode='22023';
  end if;
  if btrim(coalesce(p_confirmation,''))<>v_job.confirmation_phrase then
    raise exception 'La frase de confirmación no coincide.' using errcode='22023';
  end if;

  update public.admin_reset_jobs set status='running' where id=v_job.id;

  v_result := private.execute_admin_data_reset(v_job.scope,v_job.target_id);

  begin
    v_after := private.admin_reset_preview_counts(v_job.scope,v_job.target_id);
  exception
    when sqlstate 'P0002' then v_after := '{}'::jsonb;
  end;

  update public.admin_reset_jobs
  set status='completed',
      completed_at=now(),
      result=jsonb_build_object(
        'scope',v_job.scope,
        'target_id',v_job.target_id,
        'before',v_job.preview,
        'after',v_after,
        'detail',v_result
      )
  where id=v_job.id;

  insert into public.audit_events(
    event_type,entity_type,entity_id,summary,detail,actor_user_id
  )
  values(
    'admin_data_reset',
    'admin_reset',
    v_job.id::text,
    case
      when v_job.scope='full' then 'Reinicio completo de datos ejecutado'
      else 'Borrado administrativo ejecutado: '||private.reset_scope_label(v_job.scope)
    end,
    jsonb_build_object(
      'scope',v_job.scope,
      'target_id',v_job.target_id,
      'target_label',v_job.target_label,
      'preview',v_job.preview,
      'result',v_result
    ),
    (select auth.uid())
  );

  return jsonb_build_object(
    'job_id',v_job.id,
    'status','completed',
    'scope',v_job.scope,
    'target_label',v_job.target_label,
    'result',v_result
  );
exception
  when others then
    raise;
end;
$$;

revoke all on function public.search_admin_reset_targets(text,text)
  from public,anon;
revoke all on function public.preview_admin_data_reset(text,bigint)
  from public,anon;
revoke all on function public.apply_admin_data_reset(bigint,text)
  from public,anon;

grant execute on function public.search_admin_reset_targets(text,text)
  to authenticated;
grant execute on function public.preview_admin_data_reset(text,bigint)
  to authenticated;
grant execute on function public.apply_admin_data_reset(bigint,text)
  to authenticated;
