-- CYA Hub · staging · Multimedia personal por alumno
-- Los binarios viven en Google Drive; Supabase conserva vínculo, metadatos y permisos.

begin;

create table if not exists public.student_media_resources (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.people(id) on delete cascade,
  media_type text not null check (media_type in ('image','video')),
  provider text not null default 'google_drive' check (provider='google_drive'),
  external_file_id text not null unique check (external_file_id ~ '^[A-Za-z0-9_-]{10,200}$'),
  title text,
  note text,
  mime_type text check (mime_type is null or mime_type like 'image/%' or mime_type like 'video/%'),
  size_bytes bigint check (size_bytes is null or (size_bytes>0 and size_bytes<=1073741824)),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists student_media_resources_person_idx
  on public.student_media_resources(person_id,created_at desc);

alter table public.student_media_resources enable row level security;

drop policy if exists student_media_resources_staff_all on public.student_media_resources;
create policy student_media_resources_staff_all on public.student_media_resources
for all to authenticated
using ((select private.is_staff()))
with check ((select private.is_staff()));

drop policy if exists student_media_resources_student_select on public.student_media_resources;
create policy student_media_resources_student_select on public.student_media_resources
for select to authenticated
using (
  (select private.has_app_role('student'))
  and person_id=(select private.current_person_id())
);

grant select,insert,update,delete on public.student_media_resources to authenticated;
grant usage,select on sequence public.student_media_resources_id_seq to authenticated;

create or replace function private.can_access_student_portal_media(p_external_file_id text)
returns boolean
language plpgsql
stable
security definer
set search_path=''
as $$
declare
  v_person bigint;
begin
  if p_external_file_id is null
     or p_external_file_id !~ '^[A-Za-z0-9_-]{10,200}$' then
    return false;
  end if;

  if (select private.is_staff()) then
    return exists(
      select 1 from public.teaching_content_media m
      where m.external_file_id=p_external_file_id
         or m.thumbnail_external_file_id=p_external_file_id
    )
    or exists(select 1 from public.class_video_resources v where v.external_file_id=p_external_file_id)
    or exists(select 1 from public.class_media_resources m where m.external_file_id=p_external_file_id)
    or exists(select 1 from public.student_media_resources m where m.external_file_id=p_external_file_id)
    or exists(
      select 1 from public.class_preparation_requests r
      where r.request_type='video' and r.external_file_id=p_external_file_id
    );
  end if;

  if not (select private.has_app_role('student')) then return false; end if;
  select private.current_person_id() into v_person;
  if v_person is null then return false; end if;

  if exists(
    select 1 from public.student_media_resources m
    where m.external_file_id=p_external_file_id and m.person_id=v_person
  ) then return true; end if;

  if exists(
    select 1
    from public.class_preparation_requests r
    join public.class_participants cp on cp.class_id=r.class_id and cp.person_id=r.person_id
    where r.request_type='video' and r.external_file_id=p_external_file_id and r.person_id=v_person
  ) then return true; end if;

  if exists(
    select 1 from public.class_video_resources v
    join public.classes c on c.id=v.class_id
    where v.external_file_id=p_external_file_id
      and v.visibility_scope='private_student'
      and v.person_id=v_person
      and c.pedagogy_closed_at is not null
  ) then return true; end if;

  if exists(
    select 1 from public.class_media_resources m
    join public.classes c on c.id=m.class_id
    where m.external_file_id=p_external_file_id
      and m.person_id=v_person
      and c.pedagogy_closed_at is not null
  ) then return true; end if;

  return exists(
    select 1
    from public.teaching_content_media m
    join public.student_content_assignments a on a.content_id=m.content_id and a.person_id=v_person
    where (m.external_file_id=p_external_file_id or m.thumbnail_external_file_id=p_external_file_id)
      and private.student_can_read_assignment(a.person_id,a.content_id,a.assignment_status,a.student_visible_at)
  );
end;
$$;

create or replace function public.student_portal_snapshot_for(p_person_id bigint default null)
returns jsonb
language plpgsql
stable
set search_path=''
as $$
declare
  v_person bigint:=coalesce(p_person_id,(select private.current_person_id()));
  v_result jsonb;
begin
  if v_person is null then
    raise exception 'No hemos podido vincular esta cuenta con una ficha de alumno.' using errcode='22023';
  end if;
  v_result:=private.student_portal_snapshot_for(v_person);
  v_result:=jsonb_set(v_result,'{assignments}',private.student_visible_assignments_json(v_person),true);
  v_result:=jsonb_set(v_result,'{evaluations}',private.student_visible_evaluations_json(v_person),true);
  v_result:=jsonb_set(v_result,'{personal_media}',coalesce((
    select jsonb_agg(jsonb_build_object(
      'id',m.id,'person_id',m.person_id,'media_type',m.media_type,
      'external_file_id',m.external_file_id,'title',m.title,'note',m.note,
      'mime_type',m.mime_type,'created_at',m.created_at
    ) order by m.created_at desc,m.id desc)
    from public.student_media_resources m
    where m.person_id=v_person
  ),'[]'::jsonb),true);
  return v_result;
end;
$$;

commit;
