"use client";

import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { ArrowLeft, Award, BookOpenCheck, CheckCircle2, CircleUserRound, Gauge, LockKeyhole, TrendingDown, TrendingUp } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./progress-summary.module.css";

type Person={id:number;display_name:string;active:boolean};
type StudentProfile={person_id:number;active:boolean};
type Term={id:number;taxonomy:string;label:string;sort_order:number};
type SessionRow={id:number;person_id:number;class_id:number|null;style_term_id:number;role_term_id:number;level_term_id:number;evaluation_kind:string;status:string;completed_at:string|null;created_at:string};
type EvaluationRow={id:number;session_id:number|null;style_term_id:number;role_term_id:number;level_term_id:number;aptitude_term_id:number;score:number;created_at:string};
type ProgressRow={id:number;person_id:number;style_term_id:number;role_term_id:number;level_term_id:number;aptitude_term_id:number;raw_score:number;effective_score:number;pending_milestone_id:number|null;updated_at:string};
type AwardRow={id:number;class_id:number;person_id:number;style_term_id:number;role_term_id:number;level_term_id:number;aptitude_term_id:number;points:number;created_at:string};
type DecisionRow={id:number;progress_id:number;milestone_id:number;decision:"accepted"|"rejected";created_at:string};
type Milestone={id:number;label:string;threshold_score:number};
type ContextOption={key:string;styleId:number;roleId:number;levelId:number};
type AptitudeMetric={id:number;label:string;baseline:number;current:number;delta:number;latestHistorical:number|null;pendingMilestone:string|null};

const staffRoles=new Set(["admin","teacher_admin","teacher"]);
function contextKey(styleId:number,roleId:number,levelId:number){return `${styleId}:${roleId}:${levelId}`;}
function parseContext(key:string):ContextOption|null{const [styleId,roleId,levelId]=key.split(":").map(Number);return [styleId,roleId,levelId].every(Number.isFinite)?{key,styleId,roleId,levelId}:null;}
function bounded(value:number){return Math.max(0,Math.min(100,Number(value)||0));}
function mean(values:number[]){return values.length?values.reduce((sum,value)=>sum+value,0)/values.length:null;}
function rounded(value:number|null){return value===null?null:Math.round(value*10)/10;}
function dateLabel(value:string|null|undefined){if(!value)return "—";return new Intl.DateTimeFormat("es-ES",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value));}

function EvolutionChart({points}:{points:{id:number;label:string;value:number}[]}){
  if(points.length<2)return <div className={styles.chartEmpty}>Se necesitan al menos dos evaluaciones para calcular una trayectoria temporal.</div>;
  const width=760,height=220,padX=34,padY=24;
  const x=(index:number)=>padX+(index*(width-padX*2))/Math.max(1,points.length-1);
  const y=(value:number)=>height-padY-(bounded(value)*(height-padY*2))/100;
  const path=points.map((point,index)=>`${index?"L":"M"}${x(index)} ${y(point.value)}`).join(" ");
  return <div className={styles.chart}><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Evolución media del alumno">{[0,25,50,75,100].map((value)=><g key={value}><line className={styles.gridLine} x1={padX} y1={y(value)} x2={width-padX} y2={y(value)}/><text className={styles.gridText} x={4} y={y(value)+4}>{value}</text></g>)}<path className={styles.chartPath} d={path}/>{points.map((point,index)=><circle key={point.id} className={styles.chartPoint} cx={x(index)} cy={y(point.value)} r={4.5}/>)}</svg><div className={styles.chartLabels}><span>{points[0]?.label}</span><span>{points.at(-1)?.label}</span></div></div>;
}

export default function ProgressSummaryClient(){
  const [client,setClient]=useState<SupabaseClient|null>(null);
  const [authorized,setAuthorized]=useState<boolean|null>(null);
  const [students,setStudents]=useState<Person[]>([]);
  const [terms,setTerms]=useState<Term[]>([]);
  const [milestones,setMilestones]=useState<Milestone[]>([]);
  const [personId,setPersonId]=useState(0);
  const [sessions,setSessions]=useState<SessionRow[]>([]);
  const [evaluations,setEvaluations]=useState<EvaluationRow[]>([]);
  const [progress,setProgress]=useState<ProgressRow[]>([]);
  const [awards,setAwards]=useState<AwardRow[]>([]);
  const [decisions,setDecisions]=useState<DecisionRow[]>([]);
  const [selectedContext,setSelectedContext]=useState("");
  const [busy,setBusy]=useState("");
  const [error,setError]=useState("");

  useEffect(()=>{let cancelled=false;async function connect(){try{const response=await fetch("/api/runtime-config",{cache:"no-store",headers:{accept:"application/json"}});const config=await response.json().catch(()=>null) as {configured?:boolean;supabaseUrl?:string;supabasePublishableKey?:string}|null;if(!response.ok||!config?.configured||!config.supabaseUrl||!config.supabasePublishableKey)throw new Error("CYA Hub no ha podido conectar con sus datos.");const next=createClient(config.supabaseUrl,config.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const auth=await next.auth.getSession();const userId=auth.data.session?.user.id;if(!userId){if(!cancelled)setAuthorized(false);return;}const roles=await next.from("app_member_roles").select("role,active").eq("user_id",userId).eq("active",true);if(roles.error)throw roles.error;const allowed=(roles.data??[]).some((row)=>staffRoles.has(String(row.role)));if(cancelled)return;setAuthorized(allowed);if(allowed)setClient(next);}catch(cause){if(!cancelled){setAuthorized(false);setError(cause instanceof Error?cause.message:"No se pudo abrir el resumen.");}}}void connect();return()=>{cancelled=true;};},[]);

  const loadBase=useCallback(async()=>{if(!client)return;setBusy("base");setError("");const [profilesResult,peopleResult,termsResult,milestonesResult]=await Promise.all([client.from("student_profiles").select("person_id,active").eq("active",true),client.from("people").select("id,display_name,active").eq("active",true).order("display_name"),client.from("catalog_terms").select("id,taxonomy,label,sort_order").in("taxonomy",["dance_style","dance_role","dance_level","aptitude"]).eq("active",true).order("sort_order"),client.from("evaluation_milestones").select("id,label,threshold_score")]);const firstError=profilesResult.error||peopleResult.error||termsResult.error||milestonesResult.error;if(firstError){setError(firstError.message);setBusy("");return;}const profileIds=new Set(((profilesResult.data??[]) as StudentProfile[]).map((row)=>row.person_id));const nextStudents=((peopleResult.data??[]) as Person[]).filter((row)=>profileIds.has(row.id));setStudents(nextStudents);setTerms((termsResult.data??[]) as Term[]);setMilestones((milestonesResult.data??[]) as Milestone[]);const requested=typeof window!=="undefined"?Number(new URLSearchParams(window.location.search).get("person")||0):0;setPersonId((current)=>current||(nextStudents.some((row)=>row.id===requested)?requested:(nextStudents[0]?.id??0)));setBusy("");},[client]);
  useEffect(()=>{if(!client)return;const timer=window.setTimeout(()=>void loadBase(),0);return()=>window.clearTimeout(timer);},[client,loadBase]);

  const loadPerson=useCallback(async(id:number)=>{if(!client||!id)return;setBusy("person");setError("");const [sessionsResult,evaluationsResult,progressResult,awardsResult]=await Promise.all([client.from("evaluation_sessions").select("id,person_id,class_id,style_term_id,role_term_id,level_term_id,evaluation_kind,status,completed_at,created_at").eq("person_id",id).eq("status","completed").order("completed_at",{ascending:true}),client.from("student_evaluations").select("id,session_id,style_term_id,role_term_id,level_term_id,aptitude_term_id,score,created_at").eq("person_id",id).order("created_at",{ascending:true}),client.from("student_aptitude_progress").select("id,person_id,style_term_id,role_term_id,level_term_id,aptitude_term_id,raw_score,effective_score,pending_milestone_id,updated_at").eq("person_id",id),client.from("evaluation_progress_awards").select("id,class_id,person_id,style_term_id,role_term_id,level_term_id,aptitude_term_id,points,created_at").eq("person_id",id).order("created_at",{ascending:true})]);const firstError=sessionsResult.error||evaluationsResult.error||progressResult.error||awardsResult.error;if(firstError){setError(firstError.message);setBusy("");return;}const nextSessions=(sessionsResult.data??[]) as SessionRow[],nextProgress=(progressResult.data??[]) as ProgressRow[];const progressIds=nextProgress.map((row)=>row.id);const decisionResult=progressIds.length?await client.from("evaluation_milestone_decisions").select("id,progress_id,milestone_id,decision,created_at").in("progress_id",progressIds).order("created_at",{ascending:true}):{data:[],error:null};if(decisionResult.error){setError(decisionResult.error.message);setBusy("");return;}setSessions(nextSessions);setEvaluations((evaluationsResult.data??[]) as EvaluationRow[]);setProgress(nextProgress);setAwards((awardsResult.data??[]) as AwardRow[]);setDecisions((decisionResult.data??[]) as DecisionRow[]);const latest=nextSessions.at(-1);const context=latest?contextKey(latest.style_term_id,latest.role_term_id,latest.level_term_id):(nextProgress[0]?contextKey(nextProgress[0].style_term_id,nextProgress[0].role_term_id,nextProgress[0].level_term_id):"");setSelectedContext(context);setBusy("");},[client]);
  useEffect(()=>{if(!client||!personId)return;const timer=window.setTimeout(()=>void loadPerson(personId),0);return()=>window.clearTimeout(timer);},[client,personId,loadPerson]);

  const termLabel=(id:number)=>terms.find((term)=>term.id===id)?.label??"—";
  const contexts=useMemo(()=>{const map=new Map<string,ContextOption>();sessions.forEach((row)=>{const key=contextKey(row.style_term_id,row.role_term_id,row.level_term_id);map.set(key,{key,styleId:row.style_term_id,roleId:row.role_term_id,levelId:row.level_term_id});});progress.forEach((row)=>{const key=contextKey(row.style_term_id,row.role_term_id,row.level_term_id);if(!map.has(key))map.set(key,{key,styleId:row.style_term_id,roleId:row.role_term_id,levelId:row.level_term_id});});return [...map.values()];},[sessions,progress]);
  const context=parseContext(selectedContext)??contexts[0]??null;
  const contextSessions=context?sessions.filter((row)=>row.style_term_id===context.styleId&&row.role_term_id===context.roleId&&row.level_term_id===context.levelId):[];
  const contextEvaluations=context?evaluations.filter((row)=>row.style_term_id===context.styleId&&row.role_term_id===context.roleId&&row.level_term_id===context.levelId):[];
  const contextProgress=context?progress.filter((row)=>row.style_term_id===context.styleId&&row.role_term_id===context.roleId&&row.level_term_id===context.levelId):[];
  const contextAwards=context?awards.filter((row)=>row.style_term_id===context.styleId&&row.role_term_id===context.roleId&&row.level_term_id===context.levelId):[];
  const aptitudeIds=useMemo(()=>{const ids=new Set<number>();contextEvaluations.forEach((row)=>ids.add(row.aptitude_term_id));contextProgress.forEach((row)=>ids.add(row.aptitude_term_id));return [...ids].sort((a,b)=>(terms.find((term)=>term.id===a)?.sort_order??0)-(terms.find((term)=>term.id===b)?.sort_order??0));},[contextEvaluations,contextProgress,terms]);
  const metrics:AptitudeMetric[]=aptitudeIds.map((aptitudeId)=>{const historical=contextEvaluations.filter((row)=>row.aptitude_term_id===aptitudeId&&row.session_id!==null);const baseline=historical[0]?.score??0;const latestHistorical=historical.at(-1)?.score??null;const currentRow=contextProgress.find((row)=>row.aptitude_term_id===aptitudeId);const current=currentRow?.effective_score??latestHistorical??baseline;return{id:aptitudeId,label:termLabel(aptitudeId),baseline,current,delta:current-baseline,latestHistorical,pendingMilestone:currentRow?.pending_milestone_id?milestones.find((item)=>item.id===currentRow.pending_milestone_id)?.label??"Hito pendiente":null};});
  const baselineAverage=rounded(mean(metrics.map((row)=>row.baseline))),currentAverage=rounded(mean(metrics.map((row)=>row.current))),netImprovement=baselineAverage!==null&&currentAverage!==null?rounded(currentAverage-baselineAverage):null;
  const greatestImprovement=[...metrics].sort((a,b)=>b.delta-a.delta)[0]??null;
  const transitionChanges:number[]=[];let regressionEpisodes=0;let biggestDrop=0;
  for(let index=1;index<contextSessions.length;index++){const previous=contextEvaluations.filter((row)=>row.session_id===contextSessions[index-1].id),current=contextEvaluations.filter((row)=>row.session_id===contextSessions[index].id);const ids=new Set(previous.map((row)=>row.aptitude_term_id));current.forEach((row)=>ids.add(row.aptitude_term_id));ids.forEach((aptitudeId)=>{const before=previous.find((row)=>row.aptitude_term_id===aptitudeId)?.score;const after=current.find((row)=>row.aptitude_term_id===aptitudeId)?.score;if(before===undefined||after===undefined)return;const diff=after-before;transitionChanges.push(Math.abs(diff));if(diff<0){regressionEpisodes+=1;biggestDrop=Math.min(biggestDrop,diff);}});}
  const stability=contextSessions.length<2?null:rounded(Math.max(0,100-(mean(transitionChanges)??0)));
  const acceptedMilestones=decisions.filter((decision)=>decision.decision==="accepted"&&contextProgress.some((row)=>row.id===decision.progress_id)).length;
  const rejectedMilestones=decisions.filter((decision)=>decision.decision==="rejected"&&contextProgress.some((row)=>row.id===decision.progress_id)).length;
  const pendingMilestones=contextProgress.filter((row)=>row.pending_milestone_id!==null).length;
  const chartPoints=contextSessions.map((session)=>{const rows=contextEvaluations.filter((row)=>row.session_id===session.id);const avg=mean(rows.map((row)=>row.score));return avg===null?null:{id:session.id,label:dateLabel(session.completed_at??session.created_at),value:avg};}).filter((row):row is {id:number;label:string;value:number}=>Boolean(row));
  const stagnant=metrics.filter((row)=>row.delta===0).length;
  const improving=metrics.filter((row)=>row.delta>0).length;
  const regressed=metrics.filter((row)=>row.delta<0).length;
  const student=students.find((row)=>row.id===personId)??null;

  function choosePerson(id:number){setPersonId(id);setSelectedContext("");}
  function summarySentence(){if(!metrics.length)return "Todavía no hay datos suficientes para interpretar el progreso.";const improvement=netImprovement===null?"sin referencia media":netImprovement>0?`ha mejorado ${netImprovement} puntos medios desde su línea base`:netImprovement<0?`está ${Math.abs(netImprovement)} puntos medios por debajo de su línea base`:"se mantiene en su línea base";const best=greatestImprovement&&greatestImprovement.delta>0?` La mayor mejora está en ${greatestImprovement.label} (+${greatestImprovement.delta}).`:"";const regressions=regressionEpisodes?` Se detectan ${regressionEpisodes} retroceso${regressionEpisodes===1?"":"s"} entre evaluaciones; el mayor fue de ${Math.abs(biggestDrop)} puntos.`:" No se detectan retrocesos entre evaluaciones comparables.";return `${student?.display_name??"El alumno"} ${improvement}.${best}${regressions}`;}

  if(authorized===null)return <main className={styles.center}><span className={styles.spinner}/><p>Comprobando permisos…</p></main>;
  if(!authorized)return <main className={styles.center}><LockKeyhole/><h1>Resumen real de progreso</h1><p>Esta vista está reservada al equipo docente.</p><Link href="/">Volver a CYA Hub</Link>{error?<small>{error}</small>:null}</main>;

  return <main className={styles.page}><header className={styles.top}><Link href="/" aria-label="Volver"><ArrowLeft/></Link><div><span>Alumnado · Progreso</span><h1>Resumen real de progreso</h1><p>Interpreta evolución, estabilidad y retrocesos. Los puntos son evidencia; no sustituyen la lectura pedagógica.</p></div><Link className={styles.historyLink} href={personId?`/evaluation-history?person=${personId}`:"/evaluation-history"}>Abrir histórico</Link></header>

    <section className={styles.filters}><label><span>Alumno</span><select value={personId||""} onChange={(event)=>choosePerson(Number(event.target.value))}><option value="" disabled>Selecciona alumno</option>{students.map((person)=><option key={person.id} value={person.id}>{person.display_name}</option>)}</select></label><label><span>Contexto</span><select value={context?.key??""} onChange={(event)=>setSelectedContext(event.target.value)} disabled={!contexts.length}>{contexts.length?contexts.map((item)=><option key={item.key} value={item.key}>{termLabel(item.styleId)} · {termLabel(item.roleId)} · {termLabel(item.levelId)}</option>):<option value="">Sin datos</option>}</select></label><div className={styles.identity}><CircleUserRound/><div><span>Alumno</span><strong>{student?.display_name??"—"}</strong></div></div></section>
    {error?<div className={styles.error}>{error}</div>:null}{busy?<div className={styles.loading}><span className={styles.spinner}/><p>Calculando progreso…</p></div>:null}

    {!busy&&context?<><section className={styles.hero}><div><span>Lectura automática</span><h2>{summarySentence()}</h2><p>La línea base es la primera evaluación completada disponible por aptitud; el estado actual usa el progreso efectivo del motor nuevo cuando existe.</p></div><div className={styles.heroScore}><TrendingUp/><strong>{netImprovement===null?"—":`${netImprovement>0?"+":""}${netImprovement}`}</strong><span>mejora media</span></div></section>

      <section className={styles.metricGrid}><article><TrendingUp/><span>Mejora desde línea base</span><strong>{netImprovement===null?"—":`${netImprovement>0?"+":""}${netImprovement}`}</strong><small>{baselineAverage??"—"} → {currentAverage??"—"} de media</small></article><article><Award/><span>Mayor mejora</span><strong>{greatestImprovement?.delta&&greatestImprovement.delta>0?`+${greatestImprovement.delta}`:"—"}</strong><small>{greatestImprovement?.delta&&greatestImprovement.delta>0?greatestImprovement.label:"Sin mejora destacada"}</small></article><article><Gauge/><span>Estabilidad</span><strong>{stability===null?"—":`${stability}/100`}</strong><small>{stability===null?"Faltan evaluaciones":"100 − variación media entre revisiones"}</small></article><article className={regressionEpisodes?styles.warningMetric:""}><TrendingDown/><span>Retrocesos históricos</span><strong>{regressionEpisodes}</strong><small>{regressionEpisodes?`Mayor caída ${Math.abs(biggestDrop)} puntos`:"Ninguno detectado"}</small></article></section>

      <div className={styles.mainGrid}><section className={styles.card}><div className={styles.sectionHead}><div><span>Trayectoria temporal</span><h2>Evolución media</h2></div><b>{contextSessions.length} evaluaciones</b></div><EvolutionChart points={chartPoints}/></section><section className={styles.card}><div className={styles.sectionHead}><div><span>Estado pedagógico</span><h2>Qué está pasando ahora</h2></div></div><div className={styles.statusGrid}><div><strong>{improving}</strong><span>Aptitudes mejorando</span></div><div><strong>{stagnant}</strong><span>Sin cambio neto</span></div><div><strong>{regressed}</strong><span>Por debajo de línea base</span></div><div><strong>{pendingMilestones}</strong><span>Hitos pendientes</span></div></div><div className={styles.evidence}><article><BookOpenCheck/><div><span>Contenido</span><strong>+{contextAwards.reduce((sum,row)=>sum+row.points,0)} puntos aportados</strong></div></article><article><CheckCircle2/><div><span>Hitos</span><strong>{acceptedMilestones} confirmados · {rejectedMilestones} rechazados</strong></div></article></div></section></div>

      <section className={styles.card}><div className={styles.sectionHead}><div><span>Por aptitud</span><h2>De la línea base al estado actual</h2></div><b>{metrics.length}</b></div>{metrics.length?<div className={styles.aptitudeList}>{metrics.map((metric)=><article key={metric.id} className={metric.delta<0?styles.regressionRow:""}><div className={styles.aptitudeHead}><div><strong>{metric.label}</strong><span>{metric.pendingMilestone?`Hito pendiente: ${metric.pendingMilestone}`:"Sin bloqueo de hito"}</span></div><b className={metric.delta>0?styles.positive:metric.delta<0?styles.negative:styles.neutral}>{metric.delta>0?`+${metric.delta}`:metric.delta}</b></div><div className={styles.values}><span>Línea base <strong>{metric.baseline}</strong></span><span>Último histórico <strong>{metric.latestHistorical??"—"}</strong></span><span>Actual <strong>{metric.current}</strong></span></div><div className={styles.track}><i className={styles.baselineMark} style={{left:`${bounded(metric.baseline)}%`}}/><b style={{width:`${bounded(metric.current)}%`}}/></div></article>)}</div>:<div className={styles.empty}>Todavía no hay aptitudes evaluables en este contexto.</div>}</section>

      <section className={styles.method}><strong>Cómo se calcula</strong><p><b>Mejora:</b> estado actual menos primera evaluación disponible. <b>Estabilidad:</b> 100 menos la variación absoluta media entre evaluaciones consecutivas comparables. <b>Retroceso:</b> cualquier descenso entre dos evaluaciones históricas consecutivas; un hito rechazado se cuenta aparte y no se trata automáticamente como pérdida de nivel.</p></section>
    </>:!busy?<section className={styles.noData}><TrendingUp/><h2>Sin datos de progreso</h2><p>Cuando exista una evaluación o progreso del motor nuevo, el resumen se generará automáticamente.</p></section>:null}
  </main>;
}
