-- QA-HARNESS-ATTENDANCE-START-01 ONLY.
-- Disposable local-Supabase PRE-APPLY slice, derived from the live STAGING definitions
-- inspected read-only on 2026-08-22. It intentionally contains only dependencies used by
-- ATTENDANCE-START-01 / CLASS-01-IDEMP-01 runtime probes.
-- NEVER APPLY THIS FILE TO STAGING / MAIN / PRODUCTION.

begin;

-- Multi-role authorization surface currently used by private.is_staff().
create table public.app_member_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('admin','teacher_admin','teacher','student')),
  active boolean not null default true,
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id,role)
);

create or replace function private.has_app_role(p_role text)
returns boolean
language sql
stable
security definer
set search_path=''
as $function$
  select exists(
    select 1
    from public.app_member_roles r
    where r.user_id=(select auth.uid())
      and r.active
      and r.role=p_role
  );
$function$;

create or replace function private.is_staff()
returns boolean
language sql
stable
security definer
set search_path=''
as $function$
  select (select private.has_app_role('admin'))
      or (select private.has_app_role('teacher_admin'))
      or (select private.has_app_role('teacher'));
$function$;

alter function private.has_app_role(text) owner to postgres;
alter function private.is_staff() owner to postgres;
revoke execute on function private.has_app_role(text) from public,anon;
revoke execute on function private.is_staff() from public,anon;
grant execute on function private.has_app_role(text) to authenticated;
grant execute on function private.is_staff() to authenticated;

-- Columns present in the exact PRE-APPLY STAGING class surfaces and referenced by the candidate.
alter table public.classes
  add column actual_end_at timestamptz,
  add column actual_duration_minutes integer check (actual_duration_minutes is null or (actual_duration_minutes > 0 and actual_duration_minutes <= 480)),
  add column billed_duration_minutes integer check (billed_duration_minutes is null or (billed_duration_minutes > 0 and billed_duration_minutes <= 480)),
  add column duration_source text check (duration_source is null or duration_source in ('elapsed','manual','legacy_scheduled','scheduled')),
  add column administratively_finished_by uuid references auth.users(id) on delete set null,
  add column location_text text,
  add column workflow_stage text not null default 'data' check (workflow_stage in ('data','prepare','live','administrative','closed'));

alter table public.class_participants
  add column role_term_id bigint references public.catalog_terms(id) on delete set null,
  add column level_term_id bigint references public.catalog_terms(id) on delete set null,
  add column billed_minutes integer not null default 0 check (billed_minutes >= 0 and billed_minutes <= 480),
  add column uncovered_minutes integer not null default 0 check (uncovered_minutes >= 0 and uncovered_minutes <= 480 and uncovered_minutes <= billed_minutes),
  add column billing_status text not null default 'planned' check (billing_status in ('planned','covered','partial','uncovered','not_billable','accepted_uncovered')),
  add column preferred_billing_grant_id bigint references public.credit_grants(id) on delete set null;

create table public.audit_events (
  id bigint generated always as identity primary key,
  event_type text not null,
  entity_type text,
  entity_id text,
  summary text not null,
  detail jsonb not null default '{}'::jsonb,
  actor_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- Exact PRE-APPLY attendance ledger shape relevant to this candidate.
create table public.class_attendance_events (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete restrict,
  person_id bigint not null references public.people(id) on delete restrict,
  attendance_status text not null check (attendance_status in ('present','absent')),
  absence_reason text check (absence_reason is null or absence_reason in ('no_show','excused','cancelled_by_student','other')),
  effective_at timestamptz not null,
  recorded_at timestamptz not null default now(),
  recorded_by uuid references auth.users(id) on delete set null,
  source text not null check (source in ('administrative_finish','explicit_record','correction')),
  supersedes_event_id bigint references public.class_attendance_events(id) on delete restrict,
  correction_reason text,
  detail jsonb not null default '{}'::jsonb,
  constraint class_attendance_events_present_has_no_absence_reason
    check (attendance_status <> 'present' or absence_reason is null),
  constraint class_attendance_events_correction_contract
    check (
      (source='correction' and supersedes_event_id is not null and nullif(btrim(correction_reason),'') is not null)
      or
      (source<>'correction' and supersedes_event_id is null and correction_reason is null)
    )
);

create index class_attendance_events_class_person_recorded_idx
  on public.class_attendance_events(class_id,person_id,recorded_at desc,id desc);

create or replace function private.class_attendance_latest_event(
  p_class_id bigint,
  p_person_id bigint
)
returns public.class_attendance_events
language sql
stable
security definer
set search_path=''
as $function$
  select e
  from public.class_attendance_events e
  where e.class_id=p_class_id and e.person_id=p_person_id
  order by e.recorded_at desc,e.id desc
  limit 1
$function$;

create or replace function private.record_class_attendance_fact(
  p_class_id bigint,
  p_person_id bigint,
  p_attendance_status text,
  p_absence_reason text,
  p_effective_at timestamptz,
  p_source text,
  p_supersedes_event_id bigint default null,
  p_correction_reason text default null,
  p_detail jsonb default '{}'::jsonb
)
returns public.class_attendance_events
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_existing public.class_attendance_events;
  v_event public.class_attendance_events;
  v_actor uuid:=(select auth.uid());
begin
  if not (select private.is_staff()) then
    raise exception 'No tienes permiso para registrar hechos de asistencia.' using errcode='42501';
  end if;

  if p_attendance_status not in ('present','absent') then
    raise exception 'Asistencia no válida.' using errcode='22023';
  end if;
  if p_attendance_status='present' and p_absence_reason is not null then
    raise exception 'Una asistencia presente no admite motivo de ausencia.' using errcode='22023';
  end if;
  if p_attendance_status='absent' and p_absence_reason is not null
     and p_absence_reason not in ('no_show','excused','cancelled_by_student','other') then
    raise exception 'Motivo de ausencia no válido.' using errcode='22023';
  end if;
  if not exists(
    select 1 from public.class_participants cp
    where cp.class_id=p_class_id and cp.person_id=p_person_id
  ) then
    raise exception 'La persona no participa en esta clase.' using errcode='22023';
  end if;

  select * into v_existing
  from public.class_attendance_events e
  where e.class_id=p_class_id and e.person_id=p_person_id
  order by e.recorded_at desc,e.id desc
  limit 1
  for update;

  if p_source<>'correction' and v_existing.id is not null then
    if v_existing.attendance_status=p_attendance_status
       and (p_absence_reason is null or v_existing.absence_reason is not distinct from p_absence_reason) then
      return v_existing;
    end if;
    raise exception 'La asistencia ya fue registrada; utiliza correct_class_attendance().' using errcode='22023';
  end if;

  if p_source='correction' then
    if v_existing.id is null or p_supersedes_event_id is distinct from v_existing.id then
      raise exception 'La corrección debe superseder el último hecho de asistencia.' using errcode='40001';
    end if;
    if nullif(btrim(p_correction_reason),'') is null then
      raise exception 'La corrección requiere motivo.' using errcode='22023';
    end if;
  elsif p_source not in ('administrative_finish','explicit_record') then
    raise exception 'Origen de asistencia no válido.' using errcode='22023';
  end if;

  insert into public.class_attendance_events(
    class_id,person_id,attendance_status,absence_reason,effective_at,recorded_by,
    source,supersedes_event_id,correction_reason,detail
  ) values(
    p_class_id,p_person_id,p_attendance_status,p_absence_reason,p_effective_at,v_actor,
    p_source,p_supersedes_event_id,nullif(btrim(p_correction_reason),''),coalesce(p_detail,'{}'::jsonb)
  ) returning * into v_event;

  insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
  values(
    case when p_source='correction' then 'class_attendance_corrected' else 'class_attendance_recorded' end,
    'class_attendance',v_event.id::text,
    case when p_source='correction' then 'Asistencia corregida' else 'Asistencia real registrada' end,
    jsonb_build_object(
      'class_id',p_class_id,'person_id',p_person_id,'attendance_status',p_attendance_status,
      'absence_reason',p_absence_reason,'effective_at',p_effective_at,'source',p_source,
      'supersedes_event_id',p_supersedes_event_id,'correction_reason',nullif(btrim(p_correction_reason),'')
    ),v_actor
  );

  return v_event;
end;
$function$;

alter function private.class_attendance_latest_event(bigint,bigint) owner to postgres;
alter function private.record_class_attendance_fact(bigint,bigint,text,text,timestamptz,text,bigint,text,jsonb) owner to postgres;
revoke execute on function private.class_attendance_latest_event(bigint,bigint) from public,anon,authenticated,service_role;
revoke execute on function private.record_class_attendance_fact(bigint,bigint,text,text,timestamptz,text,bigint,text,jsonb) from public,anon,authenticated,service_role;

create or replace function public.correct_class_attendance(
  p_class_id bigint,
  p_person_id bigint,
  p_attendance_status text,
  p_absence_reason text,
  p_reason text
)
returns public.class_attendance_events
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_class public.classes;
  v_previous public.class_attendance_events;
begin
  if not (select private.is_staff()) then
    raise exception 'No tienes permiso para corregir asistencia.' using errcode='42501';
  end if;
  if nullif(btrim(p_reason),'') is null then
    raise exception 'Indica el motivo de la corrección.' using errcode='22023';
  end if;
  select * into v_class from public.classes where id=p_class_id for update;
  if not found then raise exception 'La clase no existe.' using errcode='P0002'; end if;
  if v_class.administrative_finished_at is not null then
    raise exception 'Reabre primero el cierre administrativo antes de corregir asistencia para mantener coherencia económica.' using errcode='22023';
  end if;
  perform 1 from public.class_participants where class_id=p_class_id and person_id=p_person_id for update;
  if not found then raise exception 'La persona no participa en esta clase.' using errcode='22023'; end if;
  select * into v_previous from private.class_attendance_latest_event(p_class_id,p_person_id);
  if v_previous.id is null then
    raise exception 'No existe una asistencia durable que corregir.' using errcode='P0002';
  end if;
  return private.record_class_attendance_fact(
    p_class_id,p_person_id,p_attendance_status,p_absence_reason,v_previous.effective_at,
    'correction',v_previous.id,p_reason,
    jsonb_build_object(
      'before',jsonb_build_object('attendance_status',v_previous.attendance_status,'absence_reason',v_previous.absence_reason),
      'after',jsonb_build_object('attendance_status',p_attendance_status,'absence_reason',p_absence_reason)
    )
  );
end;
$function$;

alter function public.correct_class_attendance(bigint,bigint,text,text,text) owner to postgres;
revoke execute on function public.correct_class_attendance(bigint,bigint,text,text,text) from public,anon;
grant execute on function public.correct_class_attendance(bigint,bigint,text,text,text) to authenticated;
grant execute on function public.correct_class_attendance(bigint,bigint,text,text,text) to service_role;

-- Exact PRE-APPLY scheduled-start behavior used as the replacement target.
create or replace function public.start_class(p_class_id bigint)
returns public.classes
language plpgsql
set search_path=''
as $function$
declare v_class public.classes;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para iniciar clases.' using errcode='42501'; end if;
  select * into v_class from public.classes where id=p_class_id for update;
  if not found then raise exception 'La clase no existe.' using errcode='P0002'; end if;
  if v_class.status='active' then
    update public.classes set workflow_stage='live' where id=p_class_id returning * into v_class;
    return v_class;
  end if;
  if v_class.status<>'scheduled' then raise exception 'Solo se puede iniciar una clase programada.' using errcode='22023'; end if;
  if v_class.style_term_id is null or not exists(
    select 1 from public.catalog_terms where id=v_class.style_term_id and taxonomy='dance_style' and active
  ) then raise exception 'Indica el estilo antes de empezar la clase.' using errcode='22023'; end if;
  if exists(
    select 1 from public.class_participants where class_id=p_class_id and (role_term_id is null or level_term_id is null)
  ) then raise exception 'Confirma rol y nivel antes de empezar.' using errcode='22023'; end if;
  update public.classes set status='active',started_at=coalesce(started_at,now()),workflow_stage='live'
  where id=p_class_id returning * into v_class;
  return v_class;
end;
$function$;

-- Exact retired PRE-APPLY overload. Candidate migration must remove this signature.
create or replace function public.start_manual_class(
  p_class_type text,
  p_student_ids bigint[],
  p_scheduled_start_at timestamptz,
  p_duration_minutes integer,
  p_style_term_id bigint,
  p_location_term_id bigint default null,
  p_notes text default null
)
returns public.classes
language plpgsql
set search_path=''
as $function$
declare clean_ids bigint[]; new_class public.classes; expected_count integer;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para iniciar clases.' using errcode='42501'; end if;
  if p_class_type not in ('individual','pair') then raise exception 'Tipo de clase no valido.' using errcode='22023'; end if;
  select coalesce(array_agg(id order by id),'{}'::bigint[]) into clean_ids from (select distinct unnest(p_student_ids) id) s;
  expected_count:=case when p_class_type='pair' then 2 else 1 end;
  if cardinality(clean_ids)<>expected_count then raise exception 'La clase requiere % alumno(s) distintos.',expected_count using errcode='22023'; end if;
  if p_duration_minutes is null or p_duration_minutes<=0 or p_duration_minutes>480 then raise exception 'Duracion no valida.' using errcode='22023'; end if;
  if p_scheduled_start_at is null then raise exception 'Fecha y hora obligatorias.' using errcode='22023'; end if;
  if not exists(select 1 from public.catalog_terms where id=p_style_term_id and taxonomy='dance_style' and active) then raise exception 'Estilo no valido.' using errcode='22023'; end if;
  if (select count(*) from public.student_profiles sp join public.people p on p.id=sp.person_id where sp.person_id=any(clean_ids) and sp.active and p.active)<>expected_count then raise exception 'Hay alumnos no validos o inactivos.' using errcode='22023'; end if;
  insert into public.classes(teacher_user_id,class_type,status,scheduled_start_at,duration_minutes,style_term_id,location_term_id,notes,started_at,created_by)
  values((select auth.uid()),p_class_type,'active',p_scheduled_start_at,p_duration_minutes,p_style_term_id,p_location_term_id,nullif(btrim(p_notes),''),now(),(select auth.uid()))
  returning * into new_class;
  insert into public.class_participants(class_id,person_id) select new_class.id,unnest(clean_ids);
  return new_class;
end;
$function$;

alter function public.start_class(bigint) owner to postgres;
alter function public.start_manual_class(text,bigint[],timestamptz,integer,bigint,bigint,text) owner to postgres;
revoke execute on function public.start_class(bigint) from public,anon;
revoke execute on function public.start_manual_class(text,bigint[],timestamptz,integer,bigint,bigint,text) from public,anon;
grant execute on function public.start_class(bigint) to authenticated,service_role;
grant execute on function public.start_manual_class(text,bigint[],timestamptz,integer,bigint,bigint,text) to authenticated,service_role;

commit;
