import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { parseNameStatus, validateChanges, validateInventory, validateCanonicalTimestamps, validateProvenanceRecord, validateContextAgainstGitHub } from "../scripts/check-migration-governance.mjs";
import { CORE01_POST_APPLY_WORKFLOW, validateContextualProvenance, verifyPostApplyFacts } from "../scripts/core01-provenance.mjs";

const SCHEMA=JSON.parse(readFileSync(resolve("docs/CORE_01_MIGRATION_PROVENANCE.schema.json"),"utf8"));
const BASE_SHA="9bd740fa9b7dd153e937c1bff2eb32d3828c2954",SOURCE_SHA="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",NONEXISTENT_SHA="1234567890abcdef1234567890abcdef12345678",PATH="supabase/migrations/20260820010101_add_safe_thing.sql",AUTHORIZED_TARGET={environment:"staging",project_ref:"qlngfkzmncihtdzktcmd"};
function baseManifest(){return{canonical_contract:{future_route:"supabase/migrations"},staging_ledger_summary:{source:"supabase_migrations.schema_migrations",last_version:"20260819175828"},inventory:{"db/migrations":{historical_operational_class:"COMPATIBILIDAD",states:{APLICADA:["v1_old.sql"]}},"supabase/migrations":{historical_operational_class:"COMPATIBILIDAD",states:{APLICADA:["v2_old.sql"],DESCONOCIDA:{"20260819002100_old_timestamp.sql":{}}}}}};}
function pendingRecord(path=PATH){return{path,migration_version:path.match(/(\d{14})_/)?.[1],operational_class:"CANONICA",applied_state:"PREPARADA_NO_APLICADA",provenance:{schema_version:2,lifecycle_phase:"AUTHORING",owner:"CORE/Data",func_id:"FUNC-0211",authorship:{repository:"carlosyandybz-bit/cya-hub",base_sha:BASE_SHA,pr_number:123},intended_targets:[structuredClone(AUTHORIZED_TARGET)],recovery:{strategy:"forward_fix",plan:"Correct forward with a later canonical migration; never rewrite applied history."},application_evidence:null}};}
function appliedRecord(path=PATH,sourceSha=SOURCE_SHA){const r=pendingRecord(path);r.applied_state="APLICADA";r.provenance.lifecycle_phase="APPLIED";r.provenance.application_evidence=[{environment:"staging",project_ref:"qlngfkzmncihtdzktcmd",source_commit_sha:sourceSha,ledger:{version:r.migration_version,name:"add_safe_thing"},deployment:{kind:"github_actions",run_id:9001},release_verification:{workflow:CORE01_POST_APPLY_WORKFLOW,run_id:9101},verified_at:"2026-08-20T10:30:00Z"}];return r;}
function registry(records=[]){return{schema_version:2,record_schema:"docs/CORE_01_MIGRATION_PROVENANCE.schema.json",migrations:records};}
function actual(records=[]){return{"db/migrations":["db/migrations/v1_old.sql"],"supabase/migrations":["supabase/migrations/v2_old.sql","supabase/migrations/20260819002100_old_timestamp.sql",...records.map(r=>r.path)]};}
function prContext(overrides={}){return{repository:"carlosyandybz-bit/cya-hub",eventName:"pull_request",prNumber:123,prBaseSha:BASE_SHA,prHeadSha:SOURCE_SHA,authorizedTargets:[structuredClone(AUTHORIZED_TARGET)],githubToken:"fixture-token",githubApiUrl:"https://api.github.test",...overrides};}
function validVerificationRun(record=appliedRecord()){const item=record.provenance.application_evidence[0];return{repository:{full_name:"carlosyandybz-bit/cya-hub"},name:CORE01_POST_APPLY_WORKFLOW,path:".github/workflows/core01-post-apply-verification.yml",event:"workflow_dispatch",status:"completed",conclusion:"success",display_title:`CORE-01 post-apply ${record.path} @ ${item.source_commit_sha}`};}
const gitAdapters={commitExists:async sha=>sha===BASE_SHA||sha===SOURCE_SHA,commitContainsPath:async(sha,path)=>sha===SOURCE_SHA&&path===PATH};

test("parses name-status including renames",()=>assert.deepEqual(parseNameStatus("A\ta.sql\nR100\told.sql\tnew.sql\n"),[{status:"A",paths:["a.sql"]},{status:"R100",paths:["old.sql","new.sql"]}]));
test("POSITIVE: honest AUTHORING record passes real Draft 2020-12 schema + semantic gate",()=>assert.deepEqual(validateProvenanceRecord(pendingRecord(),SCHEMA),[]));
test("NEGATIVE schema: unexpected additionalProperties is actually rejected",()=>{const r=pendingRecord();r.unexpected=true;assert.ok(validateProvenanceRecord(r,SCHEMA).some(e=>e.includes("additionalProperties")));});
test("NEGATIVE schema: wrong pr_number type is rejected",()=>{const r=pendingRecord();r.provenance.authorship.pr_number="123";assert.ok(validateProvenanceRecord(r,SCHEMA).some(e=>e.includes("/provenance/authorship/pr_number")&&e.includes("type")));});
test("NEGATIVE schema: missing required owner is rejected",()=>{const r=pendingRecord();delete r.provenance.owner;assert.ok(validateProvenanceRecord(r,SCHEMA).some(e=>e.includes("required")));});
test("NEGATIVE schema: invalid intended_targets structure is rejected",()=>{const r=pendingRecord();r.provenance.intended_targets=[{environment:"staging"}];assert.ok(validateProvenanceRecord(r,SCHEMA).some(e=>e.includes("intended_targets")&&e.includes("required")));});
test("NEGATIVE: new migration without provenance remains blocked",()=>{const r=pendingRecord();delete r.provenance;assert.ok(validateChanges([{status:"A",paths:[r.path]}],baseManifest(),registry([r]),SCHEMA).some(e=>e.includes("required")||e.includes("provenance")));});
test("NEGATIVE: partial provenance remains blocked",()=>{const r=pendingRecord();delete r.provenance.authorship.pr_number;delete r.provenance.recovery.plan;assert.ok(validateChanges([{status:"A",paths:[r.path]}],baseManifest(),registry([r]),SCHEMA).filter(e=>e.includes("required")).length>=2);});
test("NEGATIVE: PREPARADA_NO_APLICADA cannot contain fabricated future application evidence",()=>{const r=pendingRecord();r.provenance.application_evidence=appliedRecord().provenance.application_evidence;assert.ok(validateProvenanceRecord(r,SCHEMA).some(e=>e.includes("application_evidence")||e.includes("null")));});
test("NEGATIVE: APLICADA without application evidence is structurally rejected",()=>{const r=pendingRecord();r.applied_state="APLICADA";r.provenance.lifecycle_phase="APPLIED";assert.ok(validateProvenanceRecord(r,SCHEMA).some(e=>e.includes("application_evidence")));});
test("POSITIVE: APPLIED representation may be structurally valid without being certified",()=>assert.deepEqual(validateProvenanceRecord(appliedRecord(),SCHEMA),[]));
test("NEGATIVE factual: syntactically valid but nonexistent base_sha fails corroboration",async()=>{const r=pendingRecord();r.provenance.authorship.base_sha=NONEXISTENT_SHA;const errors=await validateContextualProvenance(r,prContext(),{commitExists:async sha=>sha!==NONEXISTENT_SHA,commitContainsPath:gitAdapters.commitContainsPath,isNewMigration:true});assert.ok(errors.some(e=>e.includes("no existe como commit Git")));});
test("NEGATIVE factual: PR number declared different from actual PR fails",async()=>{const r=pendingRecord();r.provenance.authorship.pr_number=999;const errors=await validateContextualProvenance(r,prContext(),{...gitAdapters,isNewMigration:true});assert.ok(errors.some(e=>e.includes("PR real #123")));});
test("NEGATIVE factual: repository different from real workflow repository fails",async()=>{const r=pendingRecord();r.provenance.authorship.repository="otro/repo";assert.ok((await validateContextualProvenance(r,prContext(),{...gitAdapters,isNewMigration:true})).some(e=>e.includes("repositorio real")));});
test("NEGATIVE factual: intended target pattern alone is insufficient when CI does not authorize it",async()=>{const r=pendingRecord();r.provenance.intended_targets=[{environment:"production",project_ref:"abcdefghijklmnopqrst"}];assert.ok((await validateContextualProvenance(r,prContext(),{...gitAdapters,isNewMigration:true})).some(e=>e.includes("no está autorizado/corroborado")));});
test("POSITIVE factual: honest new AUTHORING data corroborable against PR context passes",async()=>assert.deepEqual(await validateContextAgainstGitHub([pendingRecord()],[{status:"A",paths:[PATH]}],prContext(),gitAdapters),[]));
test("NEGATIVE APPLIED: syntactically valid nonexistent source_commit_sha is not corroborated",async()=>{const r=appliedRecord(PATH,NONEXISTENT_SHA);assert.deepEqual(validateProvenanceRecord(r,SCHEMA),[]);const errors=await validateContextualProvenance(r,prContext(),{commitExists:async sha=>sha===BASE_SHA,commitContainsPath:async()=>false,getWorkflowRun:async()=>validVerificationRun(r)});assert.ok(errors.some(e=>e.includes("source_commit_sha")&&e.includes("no existe")));});
test("NEGATIVE APPLIED: self-contained invented JSON cannot pass complete certification",async()=>{const r=appliedRecord(PATH,NONEXISTENT_SHA);assert.deepEqual(validateProvenanceRecord(r,SCHEMA),[]);assert.ok((await validateContextualProvenance(r,prContext(),{commitExists:async sha=>sha===BASE_SHA,commitContainsPath:async()=>false,getWorkflowRun:async()=>{throw new Error("run inexistente");}})).length>=1);});
test("NEGATIVE APPLIED: a successful-looking but unrelated verification run is rejected",async()=>{const r=appliedRecord();assert.ok((await validateContextualProvenance(r,prContext(),{...gitAdapters,getWorkflowRun:async()=>({...validVerificationRun(r),display_title:"otro artefacto"})})).some(e=>e.includes("no corresponde inequívocamente")));});
test("POSITIVE APPLIED: corroborated Git commit and successful exact post-apply run pass contextual gate",async()=>{const r=appliedRecord();assert.deepEqual(await validateContextualProvenance(r,prContext(),{...gitAdapters,getWorkflowRun:async()=>validVerificationRun(r)}),[]);});
test("POSITIVE post-apply: authorized Release verification can produce evidence without applying SQL",async()=>{const evidence=await verifyPostApplyFacts({record:pendingRecord(),environment:"staging",projectRef:"qlngfkzmncihtdzktcmd",sourceCommitSha:SOURCE_SHA,deploymentRunId:9001,verificationRunId:9101},{commitExists:async sha=>sha===SOURCE_SHA,commitContainsPath:async(sha,path)=>sha===SOURCE_SHA&&path===PATH,getDeploymentRun:async()=>({repository:{full_name:"carlosyandybz-bit/cya-hub"},status:"completed",conclusion:"success",head_sha:SOURCE_SHA,workflow_id:77}),authorizedDeploymentWorkflowIds:new Set([77]),queryLedger:async()=>({version:"20260820010101",name:"add_safe_thing"}),now:()=>new Date("2026-08-20T10:30:00Z")});assert.equal(evidence.release_verification.run_id,9101);});
test("NEGATIVE post-apply: unapproved deployment workflow cannot certify an application",async()=>{await assert.rejects(()=>verifyPostApplyFacts({record:pendingRecord(),environment:"staging",projectRef:"qlngfkzmncihtdzktcmd",sourceCommitSha:SOURCE_SHA,deploymentRunId:9001,verificationRunId:9101},{commitExists:async()=>true,commitContainsPath:async()=>true,getDeploymentRun:async()=>({status:"completed",conclusion:"success",head_sha:SOURCE_SHA,workflow_id:88}),authorizedDeploymentWorkflowIds:new Set([77]),queryLedger:async()=>({version:"20260820010101",name:"add_safe_thing"}),now:()=>new Date()}),/no está autorizado por Release/);});
test("NEGATIVE post-apply: mismatching real ledger cannot certify an application",async()=>{await assert.rejects(()=>verifyPostApplyFacts({record:pendingRecord(),environment:"staging",projectRef:"qlngfkzmncihtdzktcmd",sourceCommitSha:SOURCE_SHA,deploymentRunId:9001,verificationRunId:9101},{commitExists:async()=>true,commitContainsPath:async()=>true,getDeploymentRun:async()=>({status:"completed",conclusion:"success",head_sha:SOURCE_SHA,workflow_id:77}),authorizedDeploymentWorkflowIds:new Set([77]),queryLedger:async()=>null,now:()=>new Date()}),/Ledger real no confirma/);});
test("NEGATIVE nominal: new supabase/migrations SQL absent from combined inventory is rejected",()=>assert.ok(validateChanges([{status:"A",paths:[PATH]}],baseManifest(),registry(),SCHEMA).some(e=>e.includes("falta registrar")||e.includes("ausente"))));
test("REGRESSION: grandfathered historical inventory needs no fabricated provenance",()=>assert.deepEqual(validateInventory(actual(),baseManifest(),registry(),SCHEMA),[]));
test("REGRESSION: canonical_pending remains blocked",()=>{const m=baseManifest();m.canonical_pending=[{path:"supabase/migrations/20260820010101_bypass.sql"}];assert.ok(validateInventory(actual(),m,registry(),SCHEMA).some(e=>e.includes("canonical_pending ya no es una vía válida")));});
test("REGRESSION: db/migrations remains frozen",()=>assert.ok(validateChanges([{status:"A",paths:["db/migrations/v999_bad.sql"]}],baseManifest(),registry(),SCHEMA).some(e=>e.includes("db/migrations está congelado"))));
test("REGRESSION: root supabase SQL remains frozen",()=>assert.ok(validateChanges([{status:"M",paths:["supabase/v47_p19_persona_unica.sql"]}],baseManifest(),registry(),SCHEMA).some(e=>e.includes("bootstrap/compatibilidad"))));
test("REGRESSION: applied-history cannot become a second route",()=>assert.ok(validateChanges([{status:"A",paths:["supabase/applied-history/20260820-x.sql"]}],baseManifest(),registry(),SCHEMA).some(e=>e.includes("segunda ruta"))));
test("rejects a new non-timestamped Supabase migration",()=>assert.ok(validateChanges([{status:"A",paths:["supabase/migrations/v999_bad.sql"]}],baseManifest(),registry(),SCHEMA).some(e=>e.includes("YYYYMMDDHHMMSS"))));
test("rejects mutation of existing canonical/legacy migration SQL",()=>assert.ok(validateChanges([{status:"M",paths:["supabase/migrations/v2_old.sql"]}],baseManifest(),registry(),SCHEMA).some(e=>e.includes("inmutables"))));
test("rejects migrations older than the real staging ledger head",()=>{const r=pendingRecord("supabase/migrations/20260819120000_backdated.sql");assert.ok(validateChanges([{status:"A",paths:[r.path]}],baseManifest(),registry([r]),SCHEMA).some(e=>e.includes("retrodatadas")));});
test("rejects an invalid UTC timestamp even when it has 14 digits",()=>{const r=pendingRecord("supabase/migrations/20261332010101_invalid_date.sql");assert.ok(validateChanges([{status:"A",paths:[r.path]}],baseManifest(),registry([r]),SCHEMA).some(e=>e.includes("fecha/hora UTC válida")));});
test("inventory requires every SQL in both governed routes to be declared",()=>assert.ok(validateInventory({"db/migrations":["db/migrations/v1_old.sql","db/migrations/v2_untracked.sql"],"supabase/migrations":["supabase/migrations/v2_old.sql","supabase/migrations/20260819002100_old_timestamp.sql"]},baseManifest(),registry(),SCHEMA).some(e=>e.includes("v2_untracked.sql"))));
test("inventory rejects artifacts without a governed classification",()=>{const b=baseManifest();b.inventory["db/migrations"].historical_operational_class=undefined;assert.ok(validateInventory(actual(),b,registry(),SCHEMA).some(e=>e.includes("operational_class")));});
test("inventory rejects an invalid applied state",()=>{const b=baseManifest();b.inventory["db/migrations"].states={NO_ES_ESTADO:["v1_old.sql"]};assert.ok(validateInventory(actual(),b,registry(),SCHEMA).some(e=>e.includes("applied_state")));});
test("duplicate canonical timestamps are rejected",()=>assert.equal(validateCanonicalTimestamps(["supabase/migrations/20260820010101_first.sql","supabase/migrations/20260820010101_second.sql"]).length,1));
