\set ON_ERROR_STOP on

create role anon nologin;
create role authenticated nologin;
create role service_role nologin;

create schema auth;
create schema private;
create schema qa_transfer;

create or replace function auth.uid()
returns uuid
language sql
stable
set search_path = ''
as $$
  select '11111111-1111-1111-1111-111111111111'::uuid;
$$;

create table public.people (
  id bigint primary key,
  active boolean not null default true
);

create table public.classes (
  id bigint primary key
);

create table public.credit_grants (
  id bigint generated by default as identity primary key,
  modality text not null check (modality in ('individual','pair')),
  label text,
  total_minutes integer not null check (total_minutes > 0 and total_minutes <= 100000),
  price_cents integer not null default 0 check (price_cents >= 0),
  payment_status text not null default 'paid'
    check (payment_status in ('paid','pending','refunded')),
  status text not null default 'active'
    check (status in ('active','exhausted','cancelled')),
  purchased_at timestamptz not null default now(),
  expires_at timestamptz,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  starts_at timestamptz not null default now(),
  purchased_at_approximate boolean not null default false,
  historical_provenance text,
  constraint credit_grants_expires_after_starts_at_check
    check (expires_at is null or expires_at > starts_at)
);

create table public.credit_grant_members (
  grant_id bigint not null references public.credit_grants(id) on delete cascade,
  person_id bigint not null references public.people(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (grant_id,person_id)
);

create table public.credit_grant_pause_periods (
  id bigint generated by default as identity primary key,
  grant_id bigint not null references public.credit_grants(id) on delete cascade,
  paused_at timestamptz not null,
  resumed_at timestamptz,
  pause_reason text not null,
  resume_reason text,
  paused_by uuid,
  resumed_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint credit_grant_pause_periods_interval_check
    check (resumed_at is null or resumed_at > paused_at)
);

create unique index credit_grant_pause_periods_one_open_idx
  on public.credit_grant_pause_periods(grant_id)
  where resumed_at is null;

create table public.credit_movements (
  id bigint generated by default as identity primary key,
  grant_id bigint not null references public.credit_grants(id) on delete restrict,
  person_id bigint references public.people(id) on delete set null,
  class_id bigint references public.classes(id) on delete set null,
  movement_type text not null,
  delta_minutes integer not null check (delta_minutes <> 0),
  note text,
  created_by uuid,
  created_at timestamptz not null default now(),
  occurred_at timestamptz not null default now(),
  date_approximate boolean not null default false,
  reverses_movement_id bigint references public.credit_movements(id) on delete restrict,
  provenance jsonb not null default '{}'::jsonb,
  source_operation_key text,
  constraint credit_movements_movement_type_check
    check (movement_type in ('grant','class','adjustment','refund')),
  constraint credit_movements_no_self_reversal_check
    check (reverses_movement_id is null or reverses_movement_id <> id),
  constraint credit_movements_source_operation_key_nonblank
    check (source_operation_key is null or btrim(source_operation_key) <> '')
);

create unique index credit_movements_source_operation_key_uidx
  on public.credit_movements(source_operation_key)
  where source_operation_key is not null;

alter table public.credit_movements enable row level security;

create table public.audit_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  entity_type text,
  entity_id text,
  summary text not null,
  detail jsonb not null default '{}'::jsonb,
  actor_user_id uuid,
  created_at timestamptz not null default now()
);

create or replace function private.is_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null;
$$;

create or replace function private.credit_grant_balance_minutes_unchecked(
  p_grant_id bigint
)
returns integer
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(sum(cm.delta_minutes),0)::integer
  from public.credit_movements cm
  where cm.grant_id=p_grant_id;
$$;

create or replace function private.credit_grant_effective_expires_at_unchecked(
  p_grant_id bigint,
  p_at timestamptz default now()
)
returns timestamptz
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_expiry timestamptz;
  v_pause record;
  v_pause_end timestamptz;
begin
  select g.expires_at into v_expiry
  from public.credit_grants g
  where g.id=p_grant_id;

  if not found or v_expiry is null then
    return v_expiry;
  end if;

  for v_pause in
    select pp.paused_at,pp.resumed_at
    from public.credit_grant_pause_periods pp
    where pp.grant_id=p_grant_id
      and pp.paused_at<p_at
    order by pp.paused_at,pp.id
  loop
    if v_pause.paused_at>=v_expiry then
      continue;
    end if;

    v_pause_end:=least(coalesce(v_pause.resumed_at,p_at),p_at);
    if v_pause_end>v_pause.paused_at then
      v_expiry:=v_expiry+(v_pause_end-v_pause.paused_at);
    end if;
  end loop;

  return v_expiry;
end;
$$;

create or replace function private.credit_grant_is_paused_unchecked(
  p_grant_id bigint,
  p_at timestamptz default now()
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(
    select 1
    from public.credit_grant_pause_periods pp
    where pp.grant_id=p_grant_id
      and pp.paused_at<=p_at
      and (pp.resumed_at is null or pp.resumed_at>p_at)
  );
$$;

create or replace function public.billing_person_bonus_summary(
  p_person_id bigint,
  p_at timestamptz default now()
)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object('person_id',p_person_id,'at',p_at);
$$;

create policy credit_movements_staff_insert
on public.credit_movements
for insert
to authenticated
with check (
  (select private.is_staff())
  and created_by=(select auth.uid())
  and source_operation_key is null
);

insert into public.people(id,active)
select i,true
from generate_series(1,40) as s(i);

create or replace function qa_transfer.seed_source(
  p_grant_id bigint,
  p_person_id bigint,
  p_minutes integer,
  p_payment_status text default 'paid',
  p_starts_at timestamptz default now(),
  p_expires_at timestamptz default null
)
returns void
language plpgsql
set search_path = ''
as $$
begin
  insert into public.credit_grants(
    id,modality,label,total_minutes,price_cents,payment_status,status,
    purchased_at,expires_at,created_by,starts_at,purchased_at_approximate,historical_provenance
  )
  values(
    p_grant_id,'individual','QA source '||p_grant_id::text,p_minutes,10000,
    p_payment_status,'active',now(),p_expires_at,(select auth.uid()),p_starts_at,false,'qa-disposable'
  );

  insert into public.credit_grant_members(grant_id,person_id)
  values(p_grant_id,p_person_id);

  insert into public.credit_movements(
    grant_id,person_id,movement_type,delta_minutes,note,created_by,provenance
  )
  values(
    p_grant_id,p_person_id,'grant',p_minutes,'QA disposable seed',
    (select auth.uid()),jsonb_build_object('qa','bonus-transfer-preapply')
  );
end;
$$;

create or replace function qa_transfer.assert_eq(
  p_actual bigint,
  p_expected bigint,
  p_label text
)
returns void
language plpgsql
set search_path = ''
as $$
begin
  if p_actual is distinct from p_expected then
    raise exception 'QA_ASSERT_EQ failed: %, actual %, expected %',
      p_label,p_actual,p_expected;
  end if;
end;
$$;
