\set ON_ERROR_STOP on

create role anon nologin;
create role authenticated nologin;
create role service_role nologin;

create schema auth;
create schema private;
create schema qa_transfer;

create or replace function auth.uid()
returns uuid
language sql
stable
as $auth_uid$
  select
  coalesce(
    nullif(current_setting('request.jwt.claim.sub', true), ''),
    (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub')
  )::uuid
$auth_uid$;

grant usage on schema auth to anon, authenticated, service_role;
grant execute on function auth.uid() to anon, authenticated, service_role;

create table auth.users (
  id uuid primary key
);

create table public.app_member_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null
    check (role in ('admin','teacher_admin','teacher','student')),
  active boolean not null default true,
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id,role)
);

create table public.people (
  id bigint primary key,
  active boolean not null default true
);

create table public.classes (
  id bigint primary key
);

create table public.credit_grants (
  id bigint generated by default as identity primary key,
  modality text not null check (modality in ('individual','pair')),
  label text,
  total_minutes integer not null check (total_minutes > 0 and total_minutes <= 100000),
  price_cents integer not null default 0 check (price_cents >= 0),
  payment_status text not null default 'paid'
    check (payment_status in ('paid','pending','refunded')),
  status text not null default 'active'
    check (status in ('active','exhausted','cancelled')),
  purchased_at timestamptz not null default now(),
  expires_at timestamptz,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  starts_at timestamptz not null default now(),
  purchased_at_approximate boolean not null default false,
  historical_provenance text,
  constraint credit_grants_expires_after_starts_at_check
    check (expires_at is null or expires_at > starts_at)
);

create table public.credit_grant_members (
  grant_id bigint not null references public.credit_grants(id) on delete cascade,
  person_id bigint not null references public.people(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (grant_id,person_id)
);

create table public.credit_grant_pause_periods (
  id bigint generated by default as identity primary key,
  grant_id bigint not null references public.credit_grants(id) on delete cascade,
  paused_at timestamptz not null,
  resumed_at timestamptz,
  pause_reason text not null,
  resume_reason text,
  paused_by uuid,
  resumed_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint credit_grant_pause_periods_interval_check
    check (resumed_at is null or resumed_at > paused_at)
);

create unique index credit_grant_pause_periods_one_open_idx
  on public.credit_grant_pause_periods(grant_id)
  where resumed_at is null;

create table public.credit_movements (
  id bigint generated by default as identity primary key,
  grant_id bigint not null references public.credit_grants(id) on delete restrict,
  person_id bigint references public.people(id) on delete set null,
  class_id bigint references public.classes(id) on delete set null,
  movement_type text not null,
  delta_minutes integer not null check (delta_minutes <> 0),
  note text,
  created_by uuid,
  created_at timestamptz not null default now(),
  occurred_at timestamptz not null default now(),
  date_approximate boolean not null default false,
  reverses_movement_id bigint references public.credit_movements(id) on delete restrict,
  provenance jsonb not null default '{}'::jsonb,
  source_operation_key text,
  constraint credit_movements_movement_type_check
    check (movement_type in ('grant','class','adjustment','refund')),
  constraint credit_movements_no_self_reversal_check
    check (reverses_movement_id is null or reverses_movement_id <> id),
  constraint credit_movements_source_operation_key_nonblank
    check (source_operation_key is null or btrim(source_operation_key) <> '')
);

create unique index credit_movements_source_operation_key_uidx
  on public.credit_movements(source_operation_key)
  where source_operation_key is not null;

alter table public.credit_movements enable row level security;

create table public.audit_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  entity_type text,
  entity_id text,
  summary text not null,
  detail jsonb not null default '{}'::jsonb,
  actor_user_id uuid,
  created_at timestamptz not null default now()
);

-- Contract sentinels: these are real STAGING surface names. The Transfer Foundation
-- must leave them untouched; their zero-row state is asserted at runtime.
create table public.class_attendance_events (
  id bigint generated by default as identity primary key
);

create table public.class_financial_accounts (
  id bigint generated by default as identity primary key
);

create table public.class_financial_items (
  id bigint generated by default as identity primary key
);

create table public.class_payment_movements (
  id bigint generated by default as identity primary key
);

create or replace function private.has_app_role(p_role text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $fn$
  select exists(
    select 1
    from public.app_member_roles r
    where r.user_id=(select auth.uid())
      and r.active
      and r.role=p_role
  );
$fn$;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $fn$
  select (select private.has_app_role('admin'))
      or (select private.has_app_role('teacher_admin'));
$fn$;

create or replace function private.is_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $fn$
  select (select private.has_app_role('admin'))
      or (select private.has_app_role('teacher_admin'))
      or (select private.has_app_role('teacher'));
$fn$;

create or replace function private.credit_grant_balance_minutes_unchecked(
  p_grant_id bigint
)
returns integer
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(sum(cm.delta_minutes),0)::integer
  from public.credit_movements cm
  where cm.grant_id=p_grant_id;
$$;

create or replace function private.credit_grant_effective_expires_at_unchecked(
  p_grant_id bigint,
  p_at timestamptz default now()
)
returns timestamptz
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_expiry timestamptz;
  v_pause record;
  v_pause_end timestamptz;
begin
  select g.expires_at into v_expiry
  from public.credit_grants g
  where g.id=p_grant_id;

  if not found or v_expiry is null then
    return v_expiry;
  end if;

  for v_pause in
    select pp.paused_at,pp.resumed_at
    from public.credit_grant_pause_periods pp
    where pp.grant_id=p_grant_id
      and pp.paused_at<p_at
    order by pp.paused_at,pp.id
  loop
    if v_pause.paused_at>=v_expiry then
      continue;
    end if;

    v_pause_end:=least(coalesce(v_pause.resumed_at,p_at),p_at);
    if v_pause_end>v_pause.paused_at then
      v_expiry:=v_expiry+(v_pause_end-v_pause.paused_at);
    end if;
  end loop;

  return v_expiry;
end;
$$;

create or replace function private.credit_grant_is_paused_unchecked(
  p_grant_id bigint,
  p_at timestamptz default now()
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $
  select exists(
    select 1
    from public.credit_grant_pause_periods pp
    where pp.grant_id=p_grant_id
      and pp.paused_at<=p_at
      and (pp.resumed_at is null or pp.resumed_at>p_at)
  );
$;

-- Exact canonical STAGING usability predicate required by QA 05.4.
create or replace function private.credit_grant_is_usable_unchecked(
  p_grant_id bigint,
  p_at timestamptz default now()
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $qa_usable$
  select coalesce((
    select g.status = 'active'
       and g.payment_status in ('paid','pending')
       and g.starts_at <= p_at
       and not private.credit_grant_is_paused_unchecked(g.id,p_at)
       and (
         private.credit_grant_effective_expires_at_unchecked(g.id,p_at) is null
         or private.credit_grant_effective_expires_at_unchecked(g.id,p_at) > p_at
       )
       and private.credit_grant_balance_minutes_unchecked(g.id) > 0
    from public.credit_grants g
    where g.id=p_grant_id
  ),false);
$qa_usable$;

create or replace function public.billing_person_bonus_summary(
  p_person_id bigint,
  p_at timestamptz default now()
)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object('person_id',p_person_id,'at',p_at);
$$;

create policy credit_movements_staff_insert
on public.credit_movements
for insert
to authenticated
with check (
  (select private.is_staff())
  and created_by=(select auth.uid())
  and source_operation_key is null
);

grant usage on schema public to anon, authenticated, service_role;
-- Mirrors current STAGING private-schema reachability: authenticated can resolve
-- private helpers, while function EXECUTE ACL remains authoritative.
grant usage on schema private to authenticated;
grant select, insert on public.credit_movements to authenticated;
grant usage, select on sequence public.credit_movements_id_seq to authenticated;

insert into auth.users(id)
values
  ('11111111-1111-1111-1111-111111111111'),
  ('22222222-2222-2222-2222-222222222222'),
  ('33333333-3333-3333-3333-333333333333'),
  ('44444444-4444-4444-4444-444444444444'),
  ('55555555-5555-5555-5555-555555555555');

insert into public.app_member_roles(user_id,role,active)
values
  ('11111111-1111-1111-1111-111111111111','teacher',true),
  ('22222222-2222-2222-2222-222222222222','teacher_admin',true),
  ('33333333-3333-3333-3333-333333333333','admin',true),
  ('44444444-4444-4444-4444-444444444444','student',true);

insert into public.people(id,active)
select i,true
from generate_series(1,40) as s(i);

create or replace function qa_transfer.seed_source(
  p_grant_id bigint,
  p_person_id bigint,
  p_minutes integer,
  p_payment_status text default 'paid',
  p_starts_at timestamptz default now(),
  p_expires_at timestamptz default null
)
returns void
language plpgsql
set search_path = ''
as $$
begin
  insert into public.credit_grants(
    id,modality,label,total_minutes,price_cents,payment_status,status,
    purchased_at,expires_at,created_by,starts_at,purchased_at_approximate,historical_provenance
  )
  values(
    p_grant_id,'individual','QA source '||p_grant_id::text,p_minutes,10000,
    p_payment_status,'active',now(),p_expires_at,(select auth.uid()),p_starts_at,false,'qa-disposable'
  );

  insert into public.credit_grant_members(grant_id,person_id)
  values(p_grant_id,p_person_id);

  insert into public.credit_movements(
    grant_id,person_id,movement_type,delta_minutes,note,created_by,provenance
  )
  values(
    p_grant_id,p_person_id,'grant',p_minutes,'QA disposable seed',
    (select auth.uid()),jsonb_build_object('qa','bonus-transfer-preapply')
  );
end;
$$;

create or replace function qa_transfer.assert_eq(
  p_actual bigint,
  p_expected bigint,
  p_label text
)
returns void
language plpgsql
set search_path = ''
as $fn$
begin
  if p_actual is distinct from p_expected then
    raise exception 'QA_ASSERT_EQ failed: %, actual %, expected %',
      p_label,p_actual,p_expected;
  end if;
end;
$fn$;


create or replace function qa_transfer.assert_true(
  p_actual boolean,
  p_label text
)
returns void
language plpgsql
set search_path = ''
as $fn$
begin
  if p_actual is distinct from true then
    raise exception 'QA_ASSERT_TRUE failed: %, actual %',p_label,p_actual;
  end if;
end;
$fn$;

create or replace function qa_transfer.assert_text_eq(
  p_actual text,
  p_expected text,
  p_label text
)
returns void
language plpgsql
set search_path = ''
as $fn$
begin
  if p_actual is distinct from p_expected then
    raise exception 'QA_ASSERT_TEXT_EQ failed: %, actual %, expected %',
      p_label,p_actual,p_expected;
  end if;
end;
$fn$;

create or replace function qa_transfer.assert_ts_eq(
  p_actual timestamptz,
  p_expected timestamptz,
  p_label text
)
returns void
language plpgsql
set search_path = ''
as $fn$
begin
  if p_actual is distinct from p_expected then
    raise exception 'QA_ASSERT_TS_EQ failed: %, actual %, expected %',
      p_label,p_actual,p_expected;
  end if;
end;
$fn$;

grant usage on schema qa_transfer to authenticated;
grant execute on all functions in schema qa_transfer to authenticated;
