"use client";

import type { SupabaseClient } from "@supabase/supabase-js";
import { Filter, Plus, RefreshCw, Trash2, UsersRound } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./statistics-view.module.css";

type Assignment={content_id:number;title:string;content_type:string;assignment_status:string};
type Dance={style?:string;style_key?:string;role_mode?:string;role_key?:string;level?:string|null;level_key?:string|null;self_reported_level?:string|null};
type Row={
 person_id:number;display_name:string;internal_alias:string|null;email:string|null;phone:string|null;country_code:string|null;city:string|null;age:number|null;
 is_registered:boolean;reservation_count:number;cancelled_count:number;has_reserved:boolean;has_next_class:boolean;questionnaire_finalized:boolean;questionnaire_pending_with_next_class:boolean;
 interest_states:Record<string,string>;interested_in_online_content:boolean;interested_in_teacher_training:boolean;primary_no_booking_reason:string|null;
 how_found_us:string|null;referred_by:string|null;dance_experience:string|null;has_practice_partner:string|null;onboarding_reasons:string[];class_location_interest:string|null;plans_return:string|null;
 declared_dance_profiles:Dance[];evaluated_dance_profiles:Dance[];
 content_assignments:Assignment[];assigned_content_count?:number;active_content_count?:number;active_corrections_count?:number;active_explanations_count?:number;active_exercises_count?:number;active_sequences_count?:number;
 credit_grant_count?:number;active_credit_grant_count?:number;credit_balance_minutes?:number;has_credit_balance?:boolean;
};
type View={id:number;view_key:string|null;name:string;filters:Record<string,unknown>;is_system:boolean};
type MetricKey="people_count"|"percentage_total"|"average_age"|"registered_count"|"registered_rate"|"reserved_count"|"reservation_rate"|"total_reservations"|"average_reservations"|"next_class_count"|"people_with_cancellations"|"total_cancellations"|"questionnaire_pending_count"|"credit_balance_people"|"credit_balance_total_minutes"|"credit_balance_average_minutes"|"active_correction_people"|"active_content_people"|"total_active_content"|"average_active_content";
type Panel={id:number;title:string;description:string|null;metric_key:MetricKey;filters:Record<string,unknown>;display_order:number};
type Tri="all"|"yes"|"no";
type Builder={title:string;description:string;metric:MetricKey;baseView:string;query:string;registered:Tri;reservation:Tri;classInterest:string;nextClass:Tri;questionnaire:string;online:Tri;teacherTraining:Tri;minAge:string;maxAge:string;location:string;reason:string;howFound:string;referredBy:string;onboardingReason:string;danceExperience:string;practicePartner:string;classLocation:string;plansReturn:string;declaredStyle:string;declaredRole:string;selfLevel:string;evaluatedStyle:string;evaluatedRole:string;evaluatedLevel:string;contentSearch:string;contentType:string;contentStatus:string;hasCredit:Tri;minCredit:string;maxCredit:string};

const empty:Builder={title:"",description:"",metric:"people_count",baseView:"",query:"",registered:"all",reservation:"all",classInterest:"all",nextClass:"all",questionnaire:"all",online:"all",teacherTraining:"all",minAge:"",maxAge:"",location:"",reason:"",howFound:"",referredBy:"",onboardingReason:"",danceExperience:"",practicePartner:"",classLocation:"",plansReturn:"",declaredStyle:"",declaredRole:"",selfLevel:"",evaluatedStyle:"",evaluatedRole:"",evaluatedLevel:"",contentSearch:"",contentType:"",contentStatus:"",hasCredit:"all",minCredit:"",maxCredit:""};
const metrics:Array<{key:MetricKey;label:string}>=[
 {key:"people_count",label:"Cantidad de personas"},{key:"percentage_total",label:"% del total CRM"},{key:"average_age",label:"Edad media"},{key:"registered_count",label:"Personas registradas"},{key:"registered_rate",label:"% registradas"},
 {key:"reserved_count",label:"Personas que han reservado"},{key:"reservation_rate",label:"Tasa de reserva"},{key:"total_reservations",label:"Reservas totales"},{key:"average_reservations",label:"Reservas medias por persona"},{key:"next_class_count",label:"Personas con próxima clase"},
 {key:"people_with_cancellations",label:"Personas con cancelaciones"},{key:"total_cancellations",label:"Cancelaciones totales"},{key:"questionnaire_pending_count",label:"Cuestionario pendiente + próxima clase"},
 {key:"credit_balance_people",label:"Personas con saldo de bono"},{key:"credit_balance_total_minutes",label:"Saldo total de bonos"},{key:"credit_balance_average_minutes",label:"Saldo medio de bonos"},
 {key:"active_correction_people",label:"Personas con correcciones activas"},{key:"active_content_people",label:"Personas con contenido activo"},{key:"total_active_content",label:"Contenidos activos totales"},{key:"average_active_content",label:"Contenidos activos medios por persona"}
];
const howFound:Record<string,string>={instagram:"Instagram",google:"Google",recommendation:"Recomendación",social_event:"Social o evento",student:"Otro alumno",festival:"Festival",other:"Otro"};
const reasons:Record<string,string>={learn_zero:"Aprender desde cero",keep_improving:"Continuar aprendiendo / mejorar",specific_aspects:"Aspectos concretos",wedding:"Baile de boda",teacher_training:"Profesor · formación",online_content:"Contenido online",classes_cya:"Clases con Carlos & Andy",temporary_stay:"Estancia temporal",other:"Otro"};
const noBooking:Record<string,string>={price:"Precio",own_availability:"Disponibilidad del alumno",cya_availability:"Disponibilidad CYA",incompatible_schedules:"Horarios incompatibles",location_distance:"Localidad / distancia",temporary_stay:"Estancia temporal",later:"Más adelante",thinking:"Lo está pensando",no_longer_interested:"Ya no tiene interés",no_response:"No responde",other:"Otro"};

function contains(value:unknown,needle:unknown){const n=String(needle??"").trim().toLocaleLowerCase("es");return !n||String(value??"").toLocaleLowerCase("es").includes(n)}
function searchRow(r:Row,q:string){return [r.display_name,r.internal_alias,r.email,r.phone,r.referred_by].some(v=>contains(v,q))}
function match(r:Row,f:Record<string,unknown>){return Object.entries(f).every(([k,e])=>{
 if(k==="query")return searchRow(r,String(e)); if(k==="registered")return r.is_registered===Boolean(e); if(k==="reservation")return r.has_reserved===(e==="yes"); if(k==="has_reserved")return r.has_reserved===Boolean(e);
 if(k==="class_interest")return (r.interest_states?.in_person_classes??"unknown")===e; if(k==="has_next_class")return r.has_next_class===Boolean(e); if(k==="questionnaire_finalized")return r.questionnaire_finalized===Boolean(e); if(k==="questionnaire_pending_with_next_class")return r.questionnaire_pending_with_next_class===Boolean(e);
 if(k==="interested_in_online_content")return r.interested_in_online_content===Boolean(e); if(k==="interested_in_teacher_training")return r.interested_in_teacher_training===Boolean(e); if(k==="min_age")return r.age!==null&&r.age>=Number(e); if(k==="max_age")return r.age!==null&&r.age<=Number(e);
 if(k==="location")return contains(`${r.city??""} ${r.country_code??""}`,e); if(k==="primary_no_booking_reason")return r.primary_no_booking_reason===e; if(k==="how_found_us")return r.how_found_us===e; if(k==="referred_by")return contains(r.referred_by,e); if(k==="onboarding_reason")return (r.onboarding_reasons??[]).includes(String(e));
 if(k==="dance_experience")return r.dance_experience===e; if(k==="has_practice_partner")return r.has_practice_partner===e; if(k==="class_location_interest")return contains(r.class_location_interest,e); if(k==="plans_return")return r.plans_return===e;
 if(k==="declared_style")return (r.declared_dance_profiles??[]).some(x=>x.style_key===e); if(k==="declared_role")return (r.declared_dance_profiles??[]).some(x=>x.role_mode===e); if(k==="self_reported_level")return (r.declared_dance_profiles??[]).some(x=>x.self_reported_level===e);
 if(k==="evaluated_style")return (r.evaluated_dance_profiles??[]).some(x=>x.style_key===e); if(k==="evaluated_role")return (r.evaluated_dance_profiles??[]).some(x=>x.role_key===e); if(k==="evaluated_level")return (r.evaluated_dance_profiles??[]).some(x=>x.level_key===e);
 if(k==="content_search")return (r.content_assignments??[]).some(x=>contains(x.title,e)); if(k==="content_type")return (r.content_assignments??[]).some(x=>x.content_type===e); if(k==="content_status")return (r.content_assignments??[]).some(x=>x.assignment_status===e);
 if(k==="has_credit_balance")return Boolean(r.has_credit_balance)==Boolean(e); if(k==="min_credit")return Number(r.credit_balance_minutes??0)>=Number(e); if(k==="max_credit")return Number(r.credit_balance_minutes??0)<=Number(e); return true;
})}
function value(metric:MetricKey,segment:Row[],all:Row[]){
 if(metric==="people_count")return segment.length;if(metric==="percentage_total")return all.length?segment.length*100/all.length:null;if(metric==="average_age"){const a=segment.map(x=>x.age).filter((x):x is number=>x!==null);return a.length?a.reduce((s,x)=>s+x,0)/a.length:null}
 if(metric==="registered_count")return segment.filter(x=>x.is_registered).length;if(metric==="registered_rate")return segment.length?segment.filter(x=>x.is_registered).length*100/segment.length:null;if(metric==="reserved_count")return segment.filter(x=>x.has_reserved).length;if(metric==="reservation_rate")return segment.length?segment.filter(x=>x.has_reserved).length*100/segment.length:null;
 if(metric==="total_reservations")return segment.reduce((s,x)=>s+Number(x.reservation_count??0),0);if(metric==="average_reservations")return segment.length?segment.reduce((s,x)=>s+Number(x.reservation_count??0),0)/segment.length:null;if(metric==="next_class_count")return segment.filter(x=>x.has_next_class).length;if(metric==="people_with_cancellations")return segment.filter(x=>Number(x.cancelled_count??0)>0).length;if(metric==="total_cancellations")return segment.reduce((s,x)=>s+Number(x.cancelled_count??0),0);
 if(metric==="questionnaire_pending_count")return segment.filter(x=>x.questionnaire_pending_with_next_class).length;if(metric==="credit_balance_people")return segment.filter(x=>Number(x.credit_balance_minutes??0)>0).length;if(metric==="credit_balance_total_minutes")return segment.reduce((s,x)=>s+Number(x.credit_balance_minutes??0),0);if(metric==="credit_balance_average_minutes")return segment.length?segment.reduce((s,x)=>s+Number(x.credit_balance_minutes??0),0)/segment.length:null;
 if(metric==="active_correction_people")return segment.filter(x=>Number(x.active_corrections_count??0)>0).length;if(metric==="active_content_people")return segment.filter(x=>Number(x.active_content_count??0)>0).length;if(metric==="total_active_content")return segment.reduce((s,x)=>s+Number(x.active_content_count??0),0);if(metric==="average_active_content")return segment.length?segment.reduce((s,x)=>s+Number(x.active_content_count??0),0)/segment.length:null;return null
}
function format(metric:MetricKey,n:number|null){if(n===null)return"Sin datos";if(metric==="percentage_total"||metric==="registered_rate"||metric==="reservation_rate")return`${new Intl.NumberFormat("es-ES",{maximumFractionDigits:1}).format(n)} %`;if(metric==="average_age")return`${new Intl.NumberFormat("es-ES",{maximumFractionDigits:1}).format(n)} años`;if(metric.includes("credit_balance")){const h=Math.floor(n/60),m=Math.round(n%60);return h?`${h} h${m?` ${m} min`:""}`:`${m} min`}return new Intl.NumberFormat("es-ES",{maximumFractionDigits:1}).format(n)}
function label(metric:MetricKey){return metrics.find(x=>x.key===metric)?.label??metric}
function options(rows:Row[],kind:"declaredStyle"|"selfLevel"|"evalStyle"|"evalLevel"){const m=new Map<string,string>();for(const r of rows){const list=kind.startsWith("declared")||kind==="selfLevel"?r.declared_dance_profiles??[]:r.evaluated_dance_profiles??[];for(const p of list){if((kind==="declaredStyle"||kind==="evalStyle")&&p.style_key&&p.style)m.set(p.style_key,p.style);if(kind==="selfLevel"&&p.self_reported_level)m.set(p.self_reported_level,p.self_reported_level);if(kind==="evalLevel"&&p.level_key&&p.level)m.set(p.level_key,p.level)}}return[...m.entries()].sort((a,b)=>a[1].localeCompare(b[1],"es"))}

export function StatisticsCrmDashboard({client,notify}:{client:SupabaseClient;notify:(m:string)=>void}){
 const[rows,setRows]=useState<Row[]>([]),[views,setViews]=useState<View[]>([]),[panels,setPanels]=useState<Panel[]>([]),[b,setB]=useState<Builder>(empty),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");const[a,v,p]=await Promise.all([client.rpc("crm_person_explorer_snapshot"),client.rpc("crm_saved_views_snapshot"),client.rpc("crm_stat_panels_snapshot")]);const e=a.error??v.error??p.error;if(e)setError(e.message);else{setRows((a.data??[])as Row[]);setViews((v.data??[])as View[]);setPanels((p.data??[])as Panel[])}setLoading(false)},[client]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{const f=(e:Event)=>{const p=load();(e as CustomEvent<{waitUntil?:(p:Promise<unknown>)=>void}>).detail?.waitUntil?.(p)};window.addEventListener("cya:refresh",f);return()=>window.removeEventListener("cya:refresh",f)},[load]);
 const base=views.find(v=>`${v.is_system?"system":"personal"}:${v.id}`===b.baseView);const ds=useMemo(()=>options(rows,"declaredStyle"),[rows]),sl=useMemo(()=>options(rows,"selfLevel"),[rows]),es=useMemo(()=>options(rows,"evalStyle"),[rows]),el=useMemo(()=>options(rows,"evalLevel"),[rows]);
 const filters=useMemo<Record<string,unknown>>(()=>({...base?.filters,...(b.query.trim()?{query:b.query.trim()}:{}),...(b.registered!=="all"?{registered:b.registered==="yes"}:{}),...(b.reservation!=="all"?{reservation:b.reservation}:{}),...(b.classInterest!=="all"?{class_interest:b.classInterest}:{}),...(b.nextClass!=="all"?{has_next_class:b.nextClass==="yes"}:{}),...(b.questionnaire==="finished"?{questionnaire_finalized:true}:{}),...(b.questionnaire==="pending"?{questionnaire_pending_with_next_class:true}:{}),...(b.online!=="all"?{interested_in_online_content:b.online==="yes"}:{}),...(b.teacherTraining!=="all"?{interested_in_teacher_training:b.teacherTraining==="yes"}:{}),...(b.minAge?{min_age:Number(b.minAge)}:{}),...(b.maxAge?{max_age:Number(b.maxAge)}:{}),...(b.location.trim()?{location:b.location.trim()}:{}),...(b.reason?{primary_no_booking_reason:b.reason}:{}),...(b.howFound?{how_found_us:b.howFound}:{}),...(b.referredBy.trim()?{referred_by:b.referredBy.trim()}:{}),...(b.onboardingReason?{onboarding_reason:b.onboardingReason}:{}),...(b.danceExperience?{dance_experience:b.danceExperience}:{}),...(b.practicePartner?{has_practice_partner:b.practicePartner}:{}),...(b.classLocation.trim()?{class_location_interest:b.classLocation.trim()}:{}),...(b.plansReturn?{plans_return:b.plansReturn}:{}),...(b.declaredStyle?{declared_style:b.declaredStyle}:{}),...(b.declaredRole?{declared_role:b.declaredRole}:{}),...(b.selfLevel?{self_reported_level:b.selfLevel}:{}),...(b.evaluatedStyle?{evaluated_style:b.evaluatedStyle}:{}),...(b.evaluatedRole?{evaluated_role:b.evaluatedRole}:{}),...(b.evaluatedLevel?{evaluated_level:b.evaluatedLevel}:{}),...(b.contentSearch.trim()?{content_search:b.contentSearch.trim()}:{}),...(b.contentType?{content_type:b.contentType}:{}),...(b.contentStatus?{content_status:b.contentStatus}:{}),...(b.hasCredit!=="all"?{has_credit_balance:b.hasCredit==="yes"}:{}),...(b.minCredit?{min_credit:Number(b.minCredit)}:{}),...(b.maxCredit?{max_credit:Number(b.maxCredit)}:{})}),[b,base]);
 const preview=useMemo(()=>rows.filter(r=>match(r,filters)),[rows,filters]),pv=useMemo(()=>value(b.metric,preview,rows),[b.metric,preview,rows]);
 async function save(){setSaving(true);const r=await client.rpc("save_crm_stat_panel",{p_panel_id:null,p_title:b.title.trim()||label(b.metric),p_description:b.description.trim()||null,p_metric_key:b.metric,p_filters:filters,p_display_order:panels.length});if(r.error)setError(r.error.message);else{notify("Panel de estadísticas guardado");setB(empty);setOpen(false);await load()}setSaving(false)}
 async function del(id:number){const r=await client.rpc("delete_crm_stat_panel",{p_panel_id:id});if(r.error)setError(r.error.message);else{notify("Panel eliminado");await load()}}
 const set=<K extends keyof Builder>(key:K,val:Builder[K])=>setB(x=>({...x,[key]:val}));
 return <section className={styles.crmDashboard}><div className={styles.dashboardHead}><div><span className={styles.sectionEyebrow}>CRM + Estadísticas</span><h2>Mis paneles de estadísticas</h2><p>Combina datos personales, captación, clases, baile, enseñanza y bonos. Cada tarjeta se recalcula con los datos reales.</p></div><div className={styles.dashboardActions}><button type="button" onClick={()=>setOpen(x=>!x)}><Plus/> Crear panel</button><button type="button" className={styles.iconButton} onClick={()=>void load()}><RefreshCw/></button></div></div>{error?<div className={styles.dashboardError}>{error}</div>:null}
 {open?<div className={styles.panelBuilder}><div className={styles.builderHeading}><div><span>Nuevo panel</span><strong>Selecciona valor y filtros.</strong></div><div className={styles.previewValue}><small>Vista previa</small><strong>{format(b.metric,pv)}</strong><span>{preview.length} personas</span></div></div><div className={styles.builderGrid}>
 <label><span>Título</span><input value={b.title} onChange={e=>set("title",e.target.value)}/></label><label><span>Valor</span><select value={b.metric} onChange={e=>set("metric",e.target.value as MetricKey)}>{metrics.map(x=><option key={x.key} value={x.key}>{x.label}</option>)}</select></label><label><span>Partir de lista CRM</span><select value={b.baseView} onChange={e=>set("baseView",e.target.value)}><option value="">Todas</option>{views.map(v=><option key={v.id} value={`${v.is_system?"system":"personal"}:${v.id}`}>{v.name}</option>)}</select></label><label><span>Buscar</span><input value={b.query} onChange={e=>set("query",e.target.value)}/></label>
 <label><span>Registrado</span><select value={b.registered} onChange={e=>set("registered",e.target.value as Tri)}><option value="all">Cualquiera</option><option value="yes">Sí</option><option value="no">No</option></select></label><label><span>Reserva</span><select value={b.reservation} onChange={e=>set("reservation",e.target.value as Tri)}><option value="all">Cualquiera</option><option value="yes">Sí</option><option value="no">No</option></select></label><label><span>Interés clases</span><select value={b.classInterest} onChange={e=>set("classInterest",e.target.value)}><option value="all">Cualquiera</option><option value="interested">Sí</option><option value="not_interested">No</option><option value="unknown">No sabemos</option></select></label><label><span>Próxima clase</span><select value={b.nextClass} onChange={e=>set("nextClass",e.target.value as Tri)}><option value="all">Cualquiera</option><option value="yes">Sí</option><option value="no">No</option></select></label>
 <label><span>Cuestionario</span><select value={b.questionnaire} onChange={e=>set("questionnaire",e.target.value)}><option value="all">Cualquiera</option><option value="finished">Finalizado</option><option value="pending">Pendiente + próxima clase</option></select></label><label><span>Contenido online</span><select value={b.online} onChange={e=>set("online",e.target.value as Tri)}><option value="all">Cualquiera</option><option value="yes">Sí</option><option value="no">No</option></select></label><label><span>Formación profesores</span><select value={b.teacherTraining} onChange={e=>set("teacherTraining",e.target.value as Tri)}><option value="all">Cualquiera</option><option value="yes">Sí</option><option value="no">No</option></select></label><label><span>Cómo nos conoció</span><select value={b.howFound} onChange={e=>set("howFound",e.target.value)}><option value="">Cualquiera</option>{Object.entries(howFound).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label><span>Referido por</span><input value={b.referredBy} onChange={e=>set("referredBy",e.target.value)}/></label>
 <label><span>Motivo declarado</span><select value={b.onboardingReason} onChange={e=>set("onboardingReason",e.target.value)}><option value="">Cualquiera</option>{Object.entries(reasons).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label><span>Experiencia al llegar</span><select value={b.danceExperience} onChange={e=>set("danceExperience",e.target.value)}><option value="">Cualquiera</option><option value="start_zero">Desde 0</option><option value="already_dance">Ya bailaba</option></select></label><label><span>Persona para practicar</span><select value={b.practicePartner} onChange={e=>set("practicePartner",e.target.value)}><option value="">Cualquiera</option><option value="yes">Sí</option><option value="no">No</option><option value="not_sure">No claro</option></select></label><label><span>Localidad deseada</span><input value={b.classLocation} onChange={e=>set("classLocation",e.target.value)}/></label><label><span>Piensa volver</span><select value={b.plansReturn} onChange={e=>set("plansReturn",e.target.value)}><option value="">Cualquiera</option><option value="yes">Sí</option><option value="no">No</option><option value="dont_know">No sabe</option></select></label>
 <label><span>Estilo declarado</span><select value={b.declaredStyle} onChange={e=>set("declaredStyle",e.target.value)}><option value="">Cualquiera</option>{ds.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label><span>Rol declarado</span><select value={b.declaredRole} onChange={e=>set("declaredRole",e.target.value)}><option value="">Cualquiera</option><option value="leader">Leader</option><option value="follower">Follower</option><option value="role_rotation">Role Rotation</option></select></label><label><span>Nivel autodeclarado</span><select value={b.selfLevel} onChange={e=>set("selfLevel",e.target.value)}><option value="">Cualquiera</option>{sl.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label><span>Estilo evaluado</span><select value={b.evaluatedStyle} onChange={e=>set("evaluatedStyle",e.target.value)}><option value="">Cualquiera</option>{es.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label><span>Rol evaluado</span><select value={b.evaluatedRole} onChange={e=>set("evaluatedRole",e.target.value)}><option value="">Cualquiera</option><option value="leader">Leader</option><option value="follower">Follower</option></select></label><label><span>Nivel evaluado</span><select value={b.evaluatedLevel} onChange={e=>set("evaluatedLevel",e.target.value)}><option value="">Cualquiera</option>{el.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label>
 <label><span>Contenido concreto</span><input value={b.contentSearch} onChange={e=>set("contentSearch",e.target.value)} placeholder="Ej. Cadera contraria"/></label><label><span>Tipo de contenido</span><select value={b.contentType} onChange={e=>set("contentType",e.target.value)}><option value="">Cualquiera</option><option value="correction">Corrección</option><option value="explanation">Explicación</option><option value="exercise">Ejercicio</option><option value="sequence">Secuencia</option></select></label><label><span>Estado del contenido</span><input value={b.contentStatus} onChange={e=>set("contentStatus",e.target.value)} placeholder="in_correction, completed…"/></label><label><span>Saldo de bono</span><select value={b.hasCredit} onChange={e=>set("hasCredit",e.target.value as Tri)}><option value="all">Cualquiera</option><option value="yes">Con saldo</option><option value="no">Sin saldo</option></select></label><label><span>Saldo mínimo (min)</span><input type="number" min="0" value={b.minCredit} onChange={e=>set("minCredit",e.target.value)}/></label><label><span>Saldo máximo (min)</span><input type="number" min="0" value={b.maxCredit} onChange={e=>set("maxCredit",e.target.value)}/></label>
 <label><span>Edad mínima</span><input type="number" min="0" max="120" value={b.minAge} onChange={e=>set("minAge",e.target.value)}/></label><label><span>Edad máxima</span><input type="number" min="0" max="120" value={b.maxAge} onChange={e=>set("maxAge",e.target.value)}/></label><label><span>Localidad / país actual</span><input value={b.location} onChange={e=>set("location",e.target.value)}/></label><label><span>Motivo no reserva</span><select value={b.reason} onChange={e=>set("reason",e.target.value)}><option value="">Cualquiera</option>{Object.entries(noBooking).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label className={styles.builderDescription}><span>Descripción</span><input value={b.description} onChange={e=>set("description",e.target.value)}/></label>
 </div><div className={styles.builderFooter}><span><Filter/> {preview.length} personas en la vista previa</span><div><button type="button" className={styles.secondaryButton} onClick={()=>{setB(empty);setOpen(false)}}>Cancelar</button><button type="button" disabled={saving} onClick={()=>void save()}>{saving?"Guardando…":"Guardar panel"}</button></div></div></div>:null}
 {loading?<div className={styles.loading}>Actualizando paneles…</div>:null}{!loading&&!panels.length?<div className={styles.emptyDashboard}><UsersRound/><div><strong>Aún no tienes paneles.</strong><span>Crea uno con cualquier combinación de filtros.</span></div></div>:null}{!loading&&panels.length?<div className={styles.dashboardGrid}>{panels.map(p=>{const segment=rows.filter(r=>match(r,p.filters??{})),n=value(p.metric_key,segment,rows);return <article className={styles.dashboardCard} key={p.id}><div className={styles.cardTop}><span>{label(p.metric_key)}</span><button type="button" onClick={()=>void del(p.id)}><Trash2/></button></div><strong className={styles.cardValue}>{format(p.metric_key,n)}</strong><h3>{p.title}</h3><p>{p.description||`${segment.length} personas cumplen los filtros`}</p><small>{segment.length} personas · datos vivos</small></article>})}</div>:null}
 </section>
}
