"use client";

import type { SupabaseClient } from "@supabase/supabase-js";
import { Plus, RefreshCw, Trash2 } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { statisticCatalog, statisticBlockLabels, type StatisticFilterKey, type StatisticMetric } from "./statistics-catalog";
import { calculateStatistic, type StatisticPeriod } from "./statistics-engine";
import styles from "./statistics-view.module.css";

type Panel={id:number;title:string;description:string|null;metric_key:string;filters:Record<string,unknown>;period:Record<string,unknown>;display_order:number};
type Person={person_id:number;display_name:string};
type Term={id:number;label:string};
type Campaign={id:number;title:string};
type PeriodChoice="today"|"this_week"|"this_month"|"this_year"|"30"|"90"|"365";

function periodFrom(choice:PeriodChoice):StatisticPeriod{
 if(choice==="today"||choice==="this_week"||choice==="this_month"||choice==="this_year")return{kind:choice};
 return{kind:"rolling_days",days:Number(choice)};
}
function periodLabel(choice:PeriodChoice){return choice==="today"?"Hoy":choice==="this_week"?"Esta semana":choice==="this_month"?"Este mes":choice==="this_year"?"Este año":choice==="30"?"30 días":choice==="90"?"90 días":"1 año"}
function storedPeriod(value:Record<string,unknown>|null|undefined):StatisticPeriod{
 const kind=String(value?.kind??"rolling_days") as StatisticPeriod["kind"];
 if(kind==="rolling_days")return{kind,days:Number(value?.days??30)};
 if(kind==="today"||kind==="this_week"||kind==="this_month"||kind==="this_year")return{kind};
 return{kind:"rolling_days",days:30};
}
function format(metric:StatisticMetric,value:number|null){if(value==null)return"Sin datos";if(metric.format==="currency")return new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(value/100);if(metric.format==="percentage")return`${new Intl.NumberFormat("es-ES",{maximumFractionDigits:1}).format(value)} %`;if(metric.format==="minutes"){const h=Math.floor(value/60),m=Math.round(value%60);return h?`${h} h${m?` ${m} min`:""}`:`${m} min`}return new Intl.NumberFormat("es-ES",{maximumFractionDigits:1}).format(value)}
const filterLabels:Record<StatisticFilterKey,string>={teacher:"Profesor",student:"Alumno",class_location:"Ubicación de clase",location_scope:"Ámbito de ubicación",style:"Estilo",class_status:"Estado de clase",country:"País",payment_status:"Estado de pago",content_type:"Tipo de contenido",campaign:"Campaña",mission_type:"Tipo de misión",priority:"Prioridad",channel:"Canal",event_key:"Evento"};

export function StatisticsCatalogPanels({client,notify}:{client:SupabaseClient;notify:(m:string)=>void}){
 const[panels,setPanels]=useState<Panel[]>([]),[people,setPeople]=useState<Person[]>([]),[stylesList,setStylesList]=useState<Term[]>([]),[campaigns,setCampaigns]=useState<Campaign[]>([]),[values,setValues]=useState<Record<number,number|null>>({}),[metricKey,setMetricKey]=useState(statisticCatalog[0]?.key??"classes_count"),[period,setPeriod]=useState<PeriodChoice>("30"),[filters,setFilters]=useState<Record<string,string>>({}),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const metric=statisticCatalog.find(x=>x.key===metricKey)??statisticCatalog[0];
 const load=useCallback(async()=>{setLoading(true);setError("");const[p,persons,terms,camps]=await Promise.all([client.rpc("catalog_stat_panels_snapshot"),client.rpc("crm_person_explorer_snapshot"),client.from("catalog_terms").select("id,label").eq("taxonomy","dance_style").order("sort_order"),client.from("marketing_campaigns").select("id,title").order("created_at",{ascending:false})]);const e=p.error??persons.error??terms.error??camps.error;if(e)setError(e.message);else{setPanels((p.data??[])as Panel[]);setPeople(((persons.data??[])as Array<{person_id:number;display_name:string}>).map(x=>({person_id:x.person_id,display_name:x.display_name})));setStylesList((terms.data??[])as Term[]);setCampaigns((camps.data??[])as Campaign[])}setLoading(false)},[client]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{let cancelled=false;(async()=>{const next:Record<number,number|null>={};await Promise.all(panels.map(async p=>{const m=statisticCatalog.find(x=>x.key===p.metric_key);if(!m){next[p.id]=null;return}try{next[p.id]=(await calculateStatistic(client,p.metric_key,storedPeriod(p.period),p.filters)).value}catch{next[p.id]=null}}));if(!cancelled)setValues(next)})();return()=>{cancelled=true}},[client,panels]);
 useEffect(()=>{setFilters({})},[metricKey]);
 const cleanFilters=useMemo(()=>Object.fromEntries(Object.entries(filters).filter(([,v])=>String(v).trim()!=="").map(([k,v])=>[k,/^[0-9]+$/.test(v)&&["student","style","campaign"].includes(k)?Number(v):v])),[filters]);
 const[preview,setPreview]=useState<number|null>(null);
 useEffect(()=>{let cancelled=false;const timer=window.setTimeout(async()=>{try{const result=await calculateStatistic(client,metric.key,periodFrom(period),cleanFilters);if(!cancelled)setPreview(result.value)}catch{if(!cancelled)setPreview(null)}},150);return()=>{cancelled=true;window.clearTimeout(timer)}},[client,metric.key,period,cleanFilters]);
 function setFilter(key:string,value:string){setFilters(v=>({...v,[key]:value}))}
 async function save(){setSaving(true);setError("");const result=await client.rpc("save_stat_panel",{p_panel_id:null,p_title:title.trim()||metric.label,p_description:description.trim()||null,p_metric_key:metric.key,p_filters:cleanFilters,p_display_order:panels.length,p_source_kind:"catalog",p_period:periodFrom(period)});if(result.error)setError(result.error.message);else{notify("Panel del catálogo guardado");setTitle("");setDescription("");setFilters({});setOpen(false);await load()}setSaving(false)}
 async function del(id:number){const r=await client.rpc("delete_crm_stat_panel",{p_panel_id:id});if(r.error)setError(r.error.message);else{notify("Panel eliminado");await load()}}
 function control(key:StatisticFilterKey){const value=filters[key]??"";if(key==="student")return <select value={value} onChange={e=>setFilter(key,e.target.value)}><option value="">Todos</option>{people.map(p=><option key={p.person_id} value={p.person_id}>{p.display_name}</option>)}</select>;if(key==="style")return <select value={value} onChange={e=>setFilter(key,e.target.value)}><option value="">Todos</option>{stylesList.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select>;if(key==="campaign")return <select value={value} onChange={e=>setFilter(key,e.target.value)}><option value="">Todas</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select>;if(key==="location_scope")return <select value={value} onChange={e=>setFilter(key,e.target.value)}><option value="">Cualquiera</option><option value="inside">Dentro</option><option value="outside">Fuera</option></select>;if(key==="class_status")return <select value={value} onChange={e=>setFilter(key,e.target.value)}><option value="">Cualquiera</option><option value="scheduled">Programada</option><option value="active">Activa</option><option value="finished">Finalizada</option><option value="cancelled">Cancelada</option></select>;if(key==="payment_status")return <select value={value} onChange={e=>setFilter(key,e.target.value)}><option value="">Pagado por defecto</option><option value="paid">Pagado</option><option value="pending">Pendiente</option><option value="refunded">Reembolsado</option></select>;if(key==="content_type")return <select value={value} onChange={e=>setFilter(key,e.target.value)}><option value="">Todos</option><option value="correction">Corrección</option><option value="explanation">Explicación</option><option value="exercise">Ejercicio</option><option value="sequence">Secuencia</option></select>;if(key==="priority")return <select value={value} onChange={e=>setFilter(key,e.target.value)}><option value="">Todas</option><option value="normal">Normal</option><option value="priority">Prioritaria</option><option value="urgent">Urgente</option></select>;return <input value={value} onChange={e=>setFilter(key,e.target.value)} placeholder={filterLabels[key]}/>}
 return <section className={styles.crmDashboard}><div className={styles.dashboardHead}><div><span className={styles.sectionEyebrow}>Catálogo completo</span><h2>Paneles de métricas operativas</h2><p>Guarda cualquier estadística existente con su periodo y filtros. Se recalcula automáticamente.</p></div><div className={styles.dashboardActions}><button type="button" onClick={()=>setOpen(v=>!v)}><Plus/> Añadir métrica</button><button type="button" className={styles.iconButton} onClick={()=>void load()}><RefreshCw/></button></div></div>{error?<div className={styles.dashboardError}>{error}</div>:null}
 {open?<div className={styles.panelBuilder}><div className={styles.builderHeading}><div><span>Nueva métrica</span><strong>{statisticBlockLabels[metric.block]} · {metric.label}</strong></div><div className={styles.previewValue}><small>Vista previa</small><strong>{format(metric,preview)}</strong><span>{periodLabel(period)}</span></div></div><div className={styles.builderGrid}><label><span>Título</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder={metric.label}/></label><label><span>Estadística</span><select value={metricKey} onChange={e=>setMetricKey(e.target.value)}>{Object.entries(statisticBlockLabels).map(([block,blockLabel])=><optgroup key={block} label={blockLabel}>{statisticCatalog.filter(m=>m.block===block).map(m=><option key={m.key} value={m.key}>{m.label}</option>)}</optgroup>)}</select></label><label><span>Periodo</span><select value={period} onChange={e=>setPeriod(e.target.value as PeriodChoice)}><option value="today">Hoy</option><option value="this_week">Esta semana</option><option value="this_month">Este mes</option><option value="this_year">Este año</option><option value="30">Últimos 30 días</option><option value="90">Últimos 90 días</option><option value="365">Último año</option></select></label>{metric.filters.map(key=><label key={key}><span>{filterLabels[key]}</span>{control(key)}</label>)}<label className={styles.builderDescription}><span>Descripción</span><input value={description} onChange={e=>setDescription(e.target.value)}/></label></div><div className={styles.builderFooter}><span>{metric.description}</span><div><button type="button" className={styles.secondaryButton} onClick={()=>setOpen(false)}>Cancelar</button><button type="button" disabled={saving} onClick={()=>void save()}>{saving?"Guardando…":"Guardar panel"}</button></div></div></div>:null}
 {loading?<div className={styles.loading}>Actualizando métricas guardadas…</div>:null}{!loading&&panels.length?<div className={styles.dashboardGrid}>{panels.map(p=>{const m=statisticCatalog.find(x=>x.key===p.metric_key);return <article className={styles.dashboardCard} key={p.id}><div className={styles.cardTop}><span>{m?statisticBlockLabels[m.block]:"Métrica"}</span><button type="button" onClick={()=>void del(p.id)}><Trash2/></button></div><strong className={styles.cardValue}>{m?format(m,values[p.id]??null):"Sin datos"}</strong><h3>{p.title}</h3><p>{p.description||m?.description||p.metric_key}</p></article>})}</div>:null}
 </section>
}
