from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one match, found {count}")
    return text.replace(old, new, 1)

# Remove notifications from Home: Inicio should focus on daily work only.
home_path = Path("app/home-view.tsx")
home = home_path.read_text()
home = replace_once(home, "  Bell,\n", "", "home Bell import")
home = replace_once(home, '''type Notification = {\n  id: number;\n  title: string;\n  body: string | null;\n  action_target: string | null;\n  created_at: string;\n};\n\n''', "", "home notification type")
home = replace_once(home, '  const [notifications, setNotifications] = useState<Notification[]>([]);\n', '', 'home notification state')
home = replace_once(home, '''    const [homeResult, notificationResult] = await Promise.all([\n      client.rpc("home_snapshot"),\n      client.from("internal_notifications")\n        .select("id,title,body,action_target,created_at")\n        .is("read_at", null)\n        .order("created_at", { ascending: false })\n        .limit(4),\n    ]);\n    if (homeResult.error) notify(homeResult.error.message);\n    else setSnapshot(homeResult.data as HomeSnapshot);\n    if (!notificationResult.error) setNotifications((notificationResult.data ?? []) as Notification[]);\n''', '''    const homeResult = await client.rpc("home_snapshot");\n    if (homeResult.error) notify(homeResult.error.message);\n    else setSnapshot(homeResult.data as HomeSnapshot);\n''', 'home notification load')
home = replace_once(home, '''  async function openNotification(item: Notification) {\n    setNotifications((current) => current.filter((notification) => notification.id !== item.id));\n    const result = await client.from("internal_notifications").update({ read_at: new Date().toISOString() }).eq("id", item.id);\n    if (result.error) notify(result.error.message);\n    if (item.action_target) go(item.action_target);\n  }\n\n''', '', 'home notification action')
home = replace_once(home, '''\n        <article className="card pad home-notifications">\n          <div className="card-head"><div><p className="eyebrow">Avisos</p><h2>Notificaciones</h2></div><Bell /></div>\n          {notifications.length ? notifications.map((item) => <button key={item.id} onClick={() => void openNotification(item)}><Bell /><span><strong>{item.title}</strong><small>{item.body}</small></span><ChevronRight /></button>) : <div className="compact-empty"><CheckCircle2 /><span>No hay avisos nuevos.</span></div>}\n        </article>\n''', '\n', 'home notification card')
home_path.write_text(home)

# Integrate dedicated notifications view and header state.
app_path = Path("app/cya-app.tsx")
app = app_path.read_text()
app = replace_once(app, '  AlertTriangle, Archive, ArrowRight, Bell, BookOpen,', '  AlertTriangle, Archive, ArrowRight, Bell, BellRing, BookOpen,', 'BellRing import')
app = replace_once(app, 'import { HomeView } from "./home-view";\n', 'import { HomeView } from "./home-view";\nimport { NotificationsView, type NotificationTargetContext } from "./notifications-view";\n', 'NotificationsView import')
app = replace_once(app, 'type View = "home" | "students" | "classes" | "credits" | "agenda" | "live" | "teaching" | "marketing" | "admin" | "profile" | "preferences";', 'type View = "home" | "students" | "classes" | "credits" | "agenda" | "live" | "teaching" | "marketing" | "admin" | "profile" | "preferences" | "notifications";', 'View notifications')
app = replace_once(app, '  const [toast, setToast] = useState<string>(""), [liveClassId, setLiveClassId] = useState<number | null>(null);\n  const patchIdentity = useCallback((patch: Partial<IdentityContext>) => setIdentity((current) => current ? { ...current, ...patch } : current), []);\n  const loadStudents = useCallback(async () => {', '''  const [toast, setToast] = useState<string>(""), [liveClassId, setLiveClassId] = useState<number | null>(null);\n  const [unreadNotificationCount, setUnreadNotificationCount] = useState(0);\n  const patchIdentity = useCallback((patch: Partial<IdentityContext>) => setIdentity((current) => current ? { ...current, ...patch } : current), []);\n  const loadNotificationCount = useCallback(async () => {\n    if (!db) return;\n    const notificationResult = await db.from("internal_notifications")\n      .select("id,source_type,source_id,read_at")\n      .is("read_at", null)\n      .limit(200);\n    if (notificationResult.error) return;\n    const rows = (notificationResult.data ?? []) as Array<{ id: number; source_type: string | null; source_id: string | null; read_at: string | null }>;\n    const missionIds = rows.filter((item) => item.source_type === "mission" && item.source_id && /^\\d+$/.test(item.source_id)).map((item) => Number(item.source_id));\n    if (!missionIds.length) { setUnreadNotificationCount(rows.length); return; }\n    const missionResult = await db.from("missions").select("id,state").in("id", [...new Set(missionIds)]);\n    if (missionResult.error) { setUnreadNotificationCount(rows.length); return; }\n    const states = new Map(((missionResult.data ?? []) as Array<{ id: number; state: string }>).map((item) => [item.id, item.state]));\n    const resolved = new Set(["completed", "completed_automatically", "cancelled"]);\n    setUnreadNotificationCount(rows.filter((item) => item.source_type !== "mission" || !item.source_id || !resolved.has(states.get(Number(item.source_id)) ?? "")).length);\n  }, []);\n  const loadStudents = useCallback(async () => {''', 'notification count state')
app = replace_once(app, '        try { await Promise.all([loadStudents(), loadOperations(), loadTeaching(), loadMarketing()]); } catch (e) { if (alive) setToast(e instanceof Error ? e.message : "No se pudieron cargar los datos."); }', '        try { await Promise.all([loadStudents(), loadOperations(), loadTeaching(), loadMarketing(), loadNotificationCount()]); } catch (e) { if (alive) setToast(e instanceof Error ? e.message : "No se pudieron cargar los datos."); }', 'boot notification count')
app = replace_once(app, '  }, [session.user.id, loadStudents, loadOperations, loadTeaching, loadMarketing]);', '  }, [session.user.id, loadStudents, loadOperations, loadTeaching, loadMarketing, loadNotificationCount]);', 'boot dependencies')
app = replace_once(app, '    if (["home", "students", "classes", "credits", "agenda", "teaching", "marketing"].includes(target)) navigateView(target as View);\n  }\n  const studentArea', '''    if (["home", "students", "classes", "credits", "agenda", "teaching", "marketing", "notifications"].includes(target)) navigateView(target as View);\n  }\n  function openNotificationTarget(target: string, context: NotificationTargetContext) {\n    if (context.classId) { navigateView("live", { liveClassId: context.classId }); return; }\n    if (context.personId) {\n      const student = students.find((item) => item.id === context.personId);\n      if (student) {\n        const state = historyState("students", { selectedId: student.id });\n        window.history.pushState(state, "", window.location.href);\n        clearTransient();\n        setLiveClassId(null);\n        setView("students");\n        setSelected(student);\n        return;\n      }\n    }\n    goTarget(target);\n  }\n  const studentArea''', 'notification target navigation')
old_head = '<div className="mobile-head-actions"><button className="icon-btn" onClick={() => navigateView("home")} aria-label="Notificaciones"><Bell /></button><AccountMenu'
new_head = '<div className="mobile-head-actions"><button className={`icon-btn notification-trigger ${unreadNotificationCount ? "has-notifications" : ""}`} onClick={() => navigateView("notifications")} aria-label={unreadNotificationCount ? `${unreadNotificationCount} notificaciones pendientes` : "Notificaciones"}>{unreadNotificationCount ? <BellRing /> : <Bell />}{unreadNotificationCount ? <span className="notification-dot" aria-hidden="true" /> : null}</button><AccountMenu'
app = replace_once(app, old_head, new_head, 'header notification trigger')
app = replace_once(app, '        {view === "home" && db ? <HomeView client={db} identity={identity} studentCount={students.length} classes={classes} students={students} go={goTarget} goLive={goLive} addStudent={openNewStudent} scheduleClass={() => openSchedule(null)} notify={setToast} /> : null}\n', '        {view === "home" && db ? <HomeView client={db} identity={identity} studentCount={students.length} classes={classes} students={students} go={goTarget} goLive={goLive} addStudent={openNewStudent} scheduleClass={() => openSchedule(null)} notify={setToast} /> : null}\n        {view === "notifications" && db ? <NotificationsView client={db} timezone={identity.timezone} openTarget={openNotificationTarget} onUnreadChange={setUnreadNotificationCount} notify={setToast} /> : null}\n', 'notifications render')
app_path.write_text(app)

# Header indicator style.
css_path = Path("app/globals.css")
css = css_path.read_text()
marker = '/* CYA notification indicator v25 */'
if marker in css:
    raise SystemExit('notification indicator already present')
css += '''\n\n/* CYA notification indicator v25 */\n.notification-trigger{position:relative}.notification-trigger.has-notifications{background:#f1edff;color:#6d4aff}.notification-trigger.has-notifications svg{stroke-width:2.25}.notification-dot{position:absolute;top:5px;right:5px;width:8px;height:8px;border:2px solid #fff;border-radius:50%;background:#6d4aff;box-sizing:content-box;pointer-events:none}\n'''
css_path.write_text(css)
