import fs from 'node:fs';

const path='app/cya-app.tsx';
let source=fs.readFileSync(path,'utf8');

function replaceExact(from,to,label){
  if(!source.includes(from)) throw new Error(`P0G marker missing: ${label}`);
  source=source.replace(from,to);
}

replaceExact(
`  const [internalText,setInternalText]=useState(""), [studentText,setStudentText]=useState(""), [quickType,setQuickType]=useState<"correction"|"explanation"|"exercise"|"sequence">("correction"), [quickTitle,setQuickTitle]=useState("");\n  const [busy,setBusy]=useState(""), [syncError,setSyncError]=useState(""), [finishOpen,setFinishOpen]=useState(false);`,
`  const [internalText,setInternalText]=useState(""), [studentText,setStudentText]=useState(""), [quickType,setQuickType]=useState<"correction"|"explanation"|"exercise"|"sequence">("correction"), [quickTitle,setQuickTitle]=useState("");\n  const [quickFrequency,setQuickFrequency]=useState<number|null>(null), [quickInfluence,setQuickInfluence]=useState<number|null>(null), [quickObservation,setQuickObservation]=useState(""), [quickObservationVisibility,setQuickObservationVisibility]=useState<"internal"|"student">("internal");\n  const [busy,setBusy]=useState(""), [syncError,setSyncError]=useState(""), [finishOpen,setFinishOpen]=useState(false);`,
'quick-create-state');

replaceExact(
`    const result=quickType==='correction'\n      ? await db.rpc('create_class_correction',{p_class_id:item.id,p_person_id:participant.person_id,p_title:quickTitle.trim(),p_measurement_mode:'both',p_frequency:null,p_importance:null})\n      : await db.rpc('create_quick_class_content',{p_class_id:item.id,p_person_id:participant.person_id,p_content_type:quickType,p_title:quickTitle.trim()});\n    if (result.error) notify(result.error.message);\n    else { const createdType=quickType; setQuickTitle(''); await Promise.all([refresh(),loadLive()]); notify(createdType==='correction'?'Corrección pendiente añadida.':\`${'${'}teachingKindLabels[createdType]} apuntada para completar después.\`); }`,
`    const result=quickType==='correction'\n      ? await db.rpc('create_class_correction_compact',{p_class_id:item.id,p_person_id:participant.person_id,p_title:quickTitle.trim(),p_frequency:quickFrequency,p_importance:quickInfluence,p_observation:quickObservation.trim()||null,p_observation_visibility:quickObservationVisibility})\n      : await db.rpc('create_quick_class_content',{p_class_id:item.id,p_person_id:participant.person_id,p_content_type:quickType,p_title:quickTitle.trim()});\n    if (result.error) notify(result.error.message);\n    else { const createdType=quickType; setQuickTitle(''); if(createdType==='correction'){setQuickFrequency(null);setQuickInfluence(null);setQuickObservation('');setQuickObservationVisibility('internal');} await Promise.all([refresh(),loadLive()]); notify(createdType==='correction'?'Corrección pendiente añadida.':\`${'${'}teachingKindLabels[createdType]} apuntada para completar después.\`); }`,
'atomic-create');

replaceExact(
`  function renderCorrectionControls(assignment:ContentAssignment){ const missingFrequency=assignment.current_frequency===null, missingInfluence=assignment.current_importance===null; return <div className="live-card-quick correction-quick"><select className="p0f-status-chip" data-state={assignment.assignment_status} aria-label={\`Estado de ${'${'}assignment.teaching_contents.title}\`} value={assignment.assignment_status} disabled={busy===\`correction-${'${'}assignment.id}\`} onChange={(event) => void updateCorrection(assignment,{status:event.target.value})}>{correctionStates.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select>{!missingFrequency?<select className="p0f-measure-chip" data-score={assignment.current_frequency??undefined} aria-label={\`Frecuencia de ${'${'}assignment.teaching_contents.title}\`} value={assignment.current_frequency??0} onChange={(event)=>void updateCorrection(assignment,{frequency:Number(event.target.value)})}>{frequencyLevels.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:null}{!missingInfluence?<select className="p0f-measure-chip" data-score={assignment.current_importance??undefined} aria-label={\`Influencia de ${'${'}assignment.teaching_contents.title}\`} value={assignment.current_importance??0} onChange={(event)=>void updateCorrection(assignment,{importance:Number(event.target.value)})}>{influenceLevels.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:null}{missingFrequency||missingInfluence?<details className="p0f-add-measure"><summary>+ Medir</summary><div>{missingFrequency?<select defaultValue="" aria-label="Añadir frecuencia" onChange={(event)=>{if(event.target.value!=='')void updateCorrection(assignment,{frequency:Number(event.target.value)});}}><option value="">Frecuencia</option>{frequencyLevels.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:null}{missingInfluence?<select defaultValue="" aria-label="Añadir influencia" onChange={(event)=>{if(event.target.value!=='')void updateCorrection(assignment,{importance:Number(event.target.value)});}}><option value="">Influencia</option>{influenceLevels.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:null}</div></details>:null}{renderContentNote(assignment.content_id)}</div>; }`,
`  function correctionStateShortLabel(value:string){ return value==='pending'?'Pend.':value==='in_correction'?'En corr.':value==='corrected'?'Corr.':correctionStateLabel(value); }\n  function metricLevel(value:number){ return Math.max(1,Math.min(5,Math.round(value/25)+1)); }\n  function compactMetric(kind:'frequency'|'influence',value:number|null,title:string){ if(value===null)return null; const level=metricLevel(value), full=kind==='frequency'?frequencyLevelLabel(value):influenceLevelLabel(value), short=kind==='frequency'?'F':'I'; return <span className="p0g-metric" data-kind={kind} data-level={level} aria-label={\`${'${'}kind==='frequency'?'Frecuencia':'Influencia'}: ${'${'}full}\`} title={full}><b>{short}</b><span className="p0g-dots" aria-hidden="true">{[1,2,3,4,5].map((dot)=><i key={dot} className={\`p0g-dot ${'${'}dot<=level?'on':''}\`}/>)}</span></span>; }\n  function renderCorrectionSummary(assignment:ContentAssignment){ return <span className="p0g-compact-metrics">{compactMetric('frequency',assignment.current_frequency,assignment.teaching_contents.title)}{compactMetric('influence',assignment.current_importance,assignment.teaching_contents.title)}</span>; }\n  function renderCorrectionControls(assignment:ContentAssignment){ return <div className="p0g-detail-controls"><div className="p0g-detail-row"><label>Estado<select className="p0f-status-chip" data-state={assignment.assignment_status} aria-label={\`Estado de ${'${'}assignment.teaching_contents.title}\`} value={assignment.assignment_status} disabled={busy===\`correction-${'${'}assignment.id}\`} onChange={(event)=>void updateCorrection(assignment,{status:event.target.value})}>{correctionStates.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Frecuencia<select aria-label={\`Frecuencia de ${'${'}assignment.teaching_contents.title}\`} value={assignment.current_frequency??''} onChange={(event)=>void updateCorrection(assignment,{frequency:event.target.value===''?null:Number(event.target.value)})}><option value="">Sin valorar</option>{frequencyLevels.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Influencia<select aria-label={\`Influencia de ${'${'}assignment.teaching_contents.title}\`} value={assignment.current_importance??''} onChange={(event)=>void updateCorrection(assignment,{importance:event.target.value===''?null:Number(event.target.value)})}><option value="">Sin valorar</option>{influenceLevels.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>{renderContentNote(assignment.content_id)}</div>; }`,
'compact-correction-controls');

replaceExact(
`<input value={quickTitle} onChange={(event) => setQuickTitle(event.target.value)} placeholder="Título corto"/>{quickType==='correction'?<p className="p0f-quick-note"><strong>Pendiente de corrección</strong> por defecto. Frecuencia e Influencia quedan disponibles sin valor y solo aparecerán cuando las valores.</p>:null}<button className="btn" onClick={() => void createQuickContent()} disabled={!quickTitle.trim() || busy==='quick-create'}>`,
`<input value={quickTitle} onChange={(event) => setQuickTitle(event.target.value)} placeholder="Título corto"/>{quickType==='correction'?<div className="p0g-create-correction"><div className="p0g-create-measures"><label>Frec.<select aria-label="Frecuencia inicial" value={quickFrequency??''} onChange={(event)=>setQuickFrequency(event.target.value===''?null:Number(event.target.value))}><option value="">Sin valorar</option>{frequencyLevels.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Infl.<select aria-label="Influencia inicial" value={quickInfluence??''} onChange={(event)=>setQuickInfluence(event.target.value===''?null:Number(event.target.value))}><option value="">Sin valorar</option>{influenceLevels.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><div className="p0g-create-observation"><label>Observación opcional<textarea rows={2} value={quickObservation} onChange={(event)=>setQuickObservation(event.target.value)} placeholder="Algo concreto de este alumno…"/></label><select aria-label="Visibilidad de la observación inicial" value={quickObservationVisibility} onChange={(event)=>setQuickObservationVisibility(event.target.value as 'internal'|'student')}><option value="internal">🔒 Profesores</option><option value="student">👁 Alumno</option></select></div><p className="p0g-create-hint"><strong>Pend.</strong> es automático. Si dejas F/I/observación vacíos, permanecen sin valorar.</p></div>:null}<button className="btn" onClick={() => void createQuickContent()} disabled={!quickTitle.trim() || busy==='quick-create'}>`,
'quick-create-ui');

replaceExact(
`statusLabel={null} description={assignment.teaching_contents.description} correctionGuidance={assignment.teaching_contents.correction_guidance} media={content?.teaching_content_media ?? []} actions={renderChangeMarker(assignment.content_id)} quickControls={renderCorrectionControls(assignment)}></TeachingContentCard>`,
`statusLabel={correctionStateShortLabel(assignment.assignment_status)} statusTone={assignment.assignment_status==='corrected'?'success':assignment.assignment_status==='in_correction'?'warning':'default'} description={assignment.teaching_contents.description} correctionGuidance={assignment.teaching_contents.correction_guidance} media={content?.teaching_content_media ?? []} actions={renderChangeMarker(assignment.content_id)} quickControls={renderCorrectionSummary(assignment)}>{renderCorrectionControls(assignment)}</TeachingContentCard>`,
'correction-card');

replaceExact(
`actions={renderChangeMarker(assignment.content_id)} quickControls={<div className="live-card-quick learning-quick"><select aria-label={\`Estado de ${'${'}assignment.teaching_contents.title}\`} value={assignment.assignment_status} disabled={busy===\`guide-${'${'}assignment.id}\`} onChange={(event) => void updateLearning(assignment,event.target.value)}>{assignmentOptions(assignment.teaching_contents.content_type).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select>{assignment.assignment_status==='explained' ? <button className="btn ghost live-mini-action" onClick={() => void recordEvent(assignment.content_id,'reviewed')}>Repasar</button> : null}{renderContentNote(assignment.content_id)}</div>}/>`,
`actions={renderChangeMarker(assignment.content_id)} detailControls={<div className="p0g-detail-controls"><div className="p0g-detail-row"><label>Estado<select aria-label={\`Estado de ${'${'}assignment.teaching_contents.title}\`} value={assignment.assignment_status} disabled={busy===\`guide-${'${'}assignment.id}\`} onChange={(event)=>void updateLearning(assignment,event.target.value)}>{assignmentOptions(assignment.teaching_contents.content_type).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{assignment.assignment_status==='explained'?<button className="btn ghost live-mini-action" onClick={()=>void recordEvent(assignment.content_id,'reviewed')}>Repasar</button>:null}</div>{renderContentNote(assignment.content_id)}</div>}/>` ,
'learning-card-controls');

replaceExact(
`const measurementLabel = ({ frequency: "Frecuencia", importance: "Importancia", both: "Frecuencia + influencia", none: "Sin medición" } as Record<string,string>)[content.measurement_mode] ?? content.measurement_mode;`,
`const measurementLabel = ({ frequency: "Frecuencia", importance: "Influencia", both: "Frecuencia + influencia", none: "Sin medición" } as Record<string,string>)[content.measurement_mode] ?? content.measurement_mode;`,
'teaching-influence-label');

fs.writeFileSync(path,source);
console.log('P0G patch applied');
