import { readFileSync, writeFileSync } from "node:fs";
function replaceOnce(source,before,after,label){const first=source.indexOf(before);if(first<0)throw new Error(`${label}: missing`);if(source.indexOf(before,first+before.length)>=0)throw new Error(`${label}: duplicate`);return source.slice(0,first)+after+source.slice(first+before.length);}
const path="app/admin-data-reset.tsx";
let source=readFileSync(path,"utf8");
source=replaceOnce(source,'description: "Perfiles de alumno, clases, bonos, evaluaciones, medidas, asignaciones e incidencias. Los contactos CRM se conservan.",','description: "Perfiles de alumno, clases, bonos, evaluaciones, medidas, asignaciones, incidencias e historial BZ. Los contactos CRM se conservan.",',"student reset copy");
source=replaceOnce(source,'description: "Clases, participantes, notas, archivos, contenidos trabajados, evaluaciones de clase y cierre financiero de esas clases.",','description: "Clases, participantes, notas, archivos, contenidos trabajados, evaluaciones, cierre financiero y movimientos BZ derivados de esas clases.",',"class reset copy");
source=replaceOnce(source,'description: "Todos los bonos, miembros y movimientos asociados. Las clases permanecen, pero pierden las referencias al bono borrado.",','description: "Todos los bonos, miembros, movimientos y BZ derivados de la compra. Las clases permanecen, pero pierden las referencias al bono borrado.",',"credit reset copy");
source=replaceOnce(source,'description: "Borra personas no vinculadas al equipo, alumnado, clases, bonos, evaluaciones, CRM, marketing, misiones, agenda, avisos y formularios enviados. Conserva la biblioteca de enseñanza y configuración.",','description: "Borra personas no vinculadas al equipo, alumnado, clases, bonos, evaluaciones, CRM, marketing, misiones, agenda, avisos, formularios enviados e historial BZ. Conserva la biblioteca de enseñanza y la configuración de BZ.",',"operational reset copy");
source=replaceOnce(source,'description: "Deja la aplicación vacía de datos de negocio y contenido creado: alumnado, personas de prueba, enseñanza, clases, bonos, evaluaciones, medidas, CRM, marketing, estadísticas, misiones, agenda, formularios enviados, tarifas, frases e historial de pruebas.",','description: "Deja la aplicación vacía de datos de negocio y contenido creado: alumnado, personas de prueba, enseñanza, clases, bonos, evaluaciones, medidas, CRM, marketing, estadísticas, misiones, agenda, formularios enviados, tarifas, frases e historial BZ/de pruebas. Conserva la configuración base de BZ.",',"full reset copy");
source=replaceOnce(source,'  premios_progreso: "premios de progreso",\n  medidas: "medidas",','  premios_progreso: "premios de progreso",\n  bz_points: "movimientos y acciones BZ",\n  medidas: "medidas",',"BZ count label");
writeFileSync(path,source);
console.log("Final BZ reset copy applied.");
