from pathlib import Path
import subprocess


def replace_once(path_name: str, old: str, new: str, label: str) -> None:
    path = Path(path_name)
    text = path.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one match, got {count}")
    path.write_text(text.replace(old, new, 1))


# Harden the already-audited P21.3 transformer before running it.
helper_path = Path("tools/p21_finalize_setup_reopen.py")
helper = helper_path.read_text()
old_sub = "app, setup_count = setup_pattern.subn(setup_replacement, app, count=1)"
new_sub = "app, setup_count = setup_pattern.subn(lambda _match: setup_replacement, app, count=1)"
if helper.count(old_sub) == 1:
    helper = helper.replace(old_sub, new_sub, 1)
elif helper.count(new_sub) != 1:
    raise SystemExit("could not establish literal-safe setup replacement")
old_scope = 'item\\.class_type === "pair".*?'
new_scope = 'item\\.class_type === "pair" && personIds\\[0\\] \\? compatibleCreditsForClass\\(item,credits,personIds\\[0\\]\\) : \\[\\];.*?'
if helper.count(old_scope) == 1:
    helper = helper.replace(old_scope, new_scope, 1)
elif helper.count(new_scope) != 1:
    raise SystemExit("could not scope setup replacement to ClassSetupStage")
helper_path.write_text(helper)

subprocess.run(["python", "tools/p21_finalize_setup_reopen.py"], check=True)

# Stabilize the source assertion generated by the helper.
test_path = Path("tests/p21-dar-clase.test.mjs")
test = test_path.read_text()
old_assert = "  assert.match(setup, /showContextFields=editKnown \\|\\| !roleValue \\|\\| !levelValue/);"
new_assert = "  assert.ok(setup.includes('showContextFields=editKnown || !roleValue || !levelValue'));"
if test.count(old_assert) != 1:
    raise SystemExit(f"expected one fragile setup assertion, got {test.count(old_assert)}")
test_path.write_text(test.replace(old_assert, new_assert, 1))

# G3: evaluation settings use natural numeric text fields, while guided evaluation remains discrete.
settings_path = Path("app/evaluation-settings/evaluation-settings-client.tsx")
settings = settings_path.read_text()
number_token = 'type="number"'
if settings.count(number_token) != 4:
    raise SystemExit(f"expected four evaluation settings number inputs, got {settings.count(number_token)}")
settings = settings.replace(number_token, 'type="text" inputMode="numeric" pattern="[0-9]*"')
export_anchor = "export default function EvaluationSettingsClient() {"
integer_helper = (
    "function integerFormValue(form:FormData,name:string,min:number,max:number) {\n"
    "  const raw=String(form.get(name) ?? \"\").trim();\n"
    "  if (!/^\\d+$/.test(raw)) return null;\n"
    "  const value=Number(raw);\n"
    "  return Number.isInteger(value) && value>=min && value<=max ? value : null;\n"
    "}\n\n"
)
if settings.count(export_anchor) != 1:
    raise SystemExit("evaluation settings export anchor changed")
settings = settings.replace(export_anchor, integer_helper + export_anchor, 1)
if settings.count('threshold=Number(form.get("threshold"));') != 2:
    raise SystemExit("unexpected threshold parser count")
settings = settings.replace('threshold=Number(form.get("threshold"));', 'threshold=integerFormValue(form,"threshold",1,100);')
if settings.count("!Number.isInteger(threshold) || threshold<1 || threshold>100") != 2:
    raise SystemExit("unexpected threshold validation count")
settings = settings.replace("!Number.isInteger(threshold) || threshold<1 || threshold>100", "threshold===null")
if settings.count('score=Number(form.get("score"));') != 2:
    raise SystemExit("unexpected score parser count")
settings = settings.replace('score=Number(form.get("score"));', 'score=integerFormValue(form,"score",0,100);')
if settings.count("!Number.isInteger(score) || score<0 || score>100") != 2:
    raise SystemExit("unexpected score validation count")
settings = settings.replace("!Number.isInteger(score) || score<0 || score>100", "score===null")
settings_path.write_text(settings)

numeric_path = Path("tests/numeric-inputs.test.mjs")
numeric = numeric_path.read_text()
declaration_anchor = 'const evaluationRadar = fs.readFileSync("app/evaluation-radar.tsx", "utf8");\n'
declaration_replacement = declaration_anchor + (
    'const initialEvaluation = fs.readFileSync("app/evaluation-initial-class.tsx", "utf8");\n'
    'const postEvaluation = fs.readFileSync("app/evaluation-post-class.tsx", "utf8");\n'
    'const evaluationSettings = fs.readFileSync("app/evaluation-settings/evaluation-settings-client.tsx", "utf8");\n'
)
if numeric.count(declaration_anchor) != 1:
    raise SystemExit("numeric test declaration anchor changed")
numeric = numeric.replace(declaration_anchor, declaration_replacement, 1)
test_start = numeric.find('test("evaluation keeps five discrete controls instead of a free numeric input", () => {')
if test_start < 0:
    raise SystemExit("legacy numeric evaluation test start not found")
test_end = numeric.find("\n});", test_start)
if test_end < 0:
    raise SystemExit("legacy numeric evaluation test end not found")
test_end += len("\n});")
numeric_replacement = (
    'test("guided evaluation uses observable choices instead of a free numeric input", () => {\n'
    '  assert.match(initialEvaluation, /answerOptions\\.map\\(\\(option\\)=><button/);\n'
    '  assert.match(initialEvaluation, /review_evaluation_question/);\n'
    '  assert.doesNotMatch(initialEvaluation, /<input\\b/);\n'
    '  assert.match(postEvaluation, /review_evaluation_question/);\n'
    '  assert.match(postEvaluation, /<select value=\\{currentValue\\}/);\n'
    '  assert.doesNotMatch(postEvaluation, /type="number"/);\n'
    '  assert.match(evaluationRadar, /scale\\.map\\(\\(option\\) => <button/);\n'
    '  assert.match(evaluationRadar, /onChange\\?\\.\\(selected\\.id, option\\.score\\)/);\n'
    '  assert.doesNotMatch(evaluationRadar, /<input\\b/);\n'
    '  assert.match(evaluationSettings, /inputMode="numeric"/);\n'
    '  assert.doesNotMatch(evaluationSettings, /type="number"/);\n'
    '});'
)
numeric_path.write_text(numeric[:test_start] + numeric_replacement + numeric[test_end:])

# Existing lint blockers exposed by the full P21 gate. These are behavior-preserving derivations.
replace_once(
    "app/account-pages.tsx",
    '''function ProfileAvatar({ src, name }: { src: string | null; name: string }) {
  const [failed, setFailed] = useState(false);
  useEffect(() => setFailed(false), [src]);
  return (
    <span className={styles.avatar} aria-label={`Foto de ${name || "perfil"}`}>
      {src && !failed ? <img src={src} alt="" onError={() => setFailed(true)} /> : <CircleUserRound />}
    </span>
  );
}''',
    '''function ProfileAvatar({ src, name }: { src: string | null; name: string }) {
  const [failedSrc, setFailedSrc] = useState<string | null>(null);
  const visibleSrc = src && failedSrc !== src ? src : null;
  return (
    <span className={styles.avatar} aria-label={`Foto de ${name || "perfil"}`}>
      {visibleSrc ? <img src={visibleSrc} alt="" onError={() => setFailedSrc(visibleSrc)} /> : <CircleUserRound />}
    </span>
  );
}''',
    "profile avatar effect cleanup",
)

replace_once(
    "app/evaluation-radar.tsx",
    'import { useEffect, useMemo, useState } from "react";',
    'import { useMemo, useState } from "react";',
    "evaluation radar import cleanup",
)
replace_once(
    "app/evaluation-radar.tsx",
    '''  const [selectedId, setSelectedId] = useState<number | null>(items[0]?.id ?? null);
  useEffect(() => {
    if (!items.length) setSelectedId(null);
    else if (!items.some((item) => item.id === selectedId)) setSelectedId(items[0].id);
  }, [items, selectedId]);

  const selected = items.find((item) => item.id === selectedId) ?? items[0] ?? null;''',
    '''  const [selectedId, setSelectedId] = useState<number | null>(items[0]?.id ?? null);
  const selected = items.find((item) => item.id === selectedId) ?? items[0] ?? null;''',
    "evaluation radar derived selection",
)

replace_once(
    "app/student-detail.tsx",
    '''  useEffect(() => {
    const primary=danceProfiles.find((item) => item.is_primary) ?? danceProfiles[0];
    if (!primary) return;
    setEvaluationProfileId((current) => current ?? primary.id);
    setEvaluationLevelId((current) => current ?? primary.level_term_id);
  },[danceProfiles]);

''',
    "",
    "student evaluation default effect cleanup",
)
replace_once(
    "app/student-detail.tsx",
    "  const evaluationLevel=terms.find((term) => term.id===evaluationLevelId && term.taxonomy==='dance_level') ?? null;",
    "  const effectiveEvaluationLevelId=evaluationLevelId ?? evaluationProfile?.level_term_id ?? null;\n  const evaluationLevel=terms.find((term) => term.id===effectiveEvaluationLevelId && term.taxonomy==='dance_level') ?? null;",
    "student effective evaluation level",
)
replace_once(
    "app/student-detail.tsx",
    "    if (!evaluationProfile || !evaluationLevelId) return setError('Selecciona primero el nivel y el contexto de baile.');",
    "    if (!evaluationProfile || !effectiveEvaluationLevelId) return setError('Selecciona primero el nivel y el contexto de baile.');",
    "student evaluation start guard",
)
replace_once(
    "app/student-detail.tsx",
    "p_person_id:student.id,p_level_term_id:evaluationLevelId,p_evaluation_kind:kind",
    "p_person_id:student.id,p_level_term_id:effectiveEvaluationLevelId,p_evaluation_kind:kind",
    "student evaluation rpc level",
)
replace_once(
    "app/student-detail.tsx",
    "<select value={evaluationLevelId ?? ''} onChange={(event) => setEvaluationLevelId(event.target.value?Number(event.target.value):null)}>",
    "<select value={effectiveEvaluationLevelId ?? ''} onChange={(event) => setEvaluationLevelId(event.target.value?Number(event.target.value):null)}>",
    "student evaluation level selector",
)
replace_once(
    "app/student-detail.tsx",
    "<select value={evaluationProfileId ?? ''} onChange={(event) => setEvaluationProfileId(Number(event.target.value))}>",
    "<select value={evaluationProfile?.id ?? ''} onChange={(event) => setEvaluationProfileId(Number(event.target.value))}>",
    "student evaluation profile selector",
)
replace_once(
    "app/student-detail.tsx",
    "disabled={!evaluationLevelId || !evaluationProfile || evaluationBusy==='start'}",
    "disabled={!effectiveEvaluationLevelId || !evaluationProfile || evaluationBusy==='start'}",
    "student evaluation continue guard",
)

replace_once(
    "app/teaching-media-editor.tsx",
    '_key: `class-video-${video.id}-${Date.now()}`',
    '_key: `class-video-${video.id}-${video.external_file_id}`',
    "reusable class video deterministic key",
)

print("P21 final transformation prepared")
