-- CLASS-ATTENDANCE-01 — durable real attendance history
-- R1 Wave 1, STAGING-first. No historical attendance backfill is performed here.

create table if not exists public.class_attendance_events (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete restrict,
  person_id bigint not null references public.people(id) on delete restrict,
  attendance_status text not null check (attendance_status in ('present','absent')),
  absence_reason text null check (absence_reason is null or absence_reason in ('no_show','excused','cancelled_by_student','other')),
  effective_at timestamptz not null,
  recorded_at timestamptz not null default now(),
  recorded_by uuid null references auth.users(id) on delete set null,
  source text not null check (source in ('administrative_finish','explicit_record','correction')),
  supersedes_event_id bigint null references public.class_attendance_events(id) on delete restrict,
  correction_reason text null,
  detail jsonb not null default '{}'::jsonb,
  constraint class_attendance_events_present_has_no_absence_reason
    check (attendance_status <> 'present' or absence_reason is null),
  constraint class_attendance_events_correction_contract
    check ((source='correction' and supersedes_event_id is not null and nullif(btrim(correction_reason),'') is not null)
       or (source<>'correction' and supersedes_event_id is null and correction_reason is null))
);

create index if not exists class_attendance_events_person_effective_idx
  on public.class_attendance_events(person_id,effective_at desc,id desc);
create index if not exists class_attendance_events_class_person_latest_idx
  on public.class_attendance_events(class_id,person_id,recorded_at desc,id desc);
create unique index if not exists class_attendance_events_supersedes_once_uidx
  on public.class_attendance_events(supersedes_event_id)
  where supersedes_event_id is not null;

alter table public.class_attendance_events enable row level security;

drop policy if exists class_attendance_events_read on public.class_attendance_events;
create policy class_attendance_events_read
on public.class_attendance_events
for select to authenticated
using (
  (select private.is_staff())
  or person_id=(select private.current_person_id())
);

revoke insert,update,delete,truncate,references,trigger on public.class_attendance_events from anon,authenticated;
grant select on public.class_attendance_events to authenticated;

create or replace function private.prevent_class_attendance_event_mutation()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
begin
  raise exception 'La historia de asistencia es append-only; utiliza la corrección de asistencia.' using errcode='22023';
end;
$function$;

drop trigger if exists class_attendance_events_append_only on public.class_attendance_events;
create trigger class_attendance_events_append_only
before update or delete on public.class_attendance_events
for each row execute function private.prevent_class_attendance_event_mutation();

create or replace function private.protect_durable_attendance_projection()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
begin
  if new.attendance_status is not distinct from old.attendance_status then
    return new;
  end if;
  if exists(
    select 1 from public.class_attendance_events e
    where e.class_id=old.class_id and e.person_id=old.person_id
  ) and pg_trigger_depth()<=1 then
    raise exception 'La asistencia ya tiene historia durable; utiliza correct_class_attendance().' using errcode='22023';
  end if;
  return new;
end;
$function$;

drop trigger if exists class_participants_protect_durable_attendance on public.class_participants;
create trigger class_participants_protect_durable_attendance
before update of attendance_status on public.class_participants
for each row execute function private.protect_durable_attendance_projection();

create or replace function private.sync_class_attendance_projection()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
begin
  update public.class_participants
  set attendance_status=new.attendance_status,updated_at=now()
  where class_id=new.class_id and person_id=new.person_id;
  return new;
end;
$function$;

drop trigger if exists class_attendance_events_sync_projection on public.class_attendance_events;
create trigger class_attendance_events_sync_projection
after insert on public.class_attendance_events
for each row execute function private.sync_class_attendance_projection();

create or replace function private.class_attendance_latest_event(p_class_id bigint,p_person_id bigint)
returns public.class_attendance_events
language sql
stable
security definer
set search_path=''
as $function$
  select e
  from public.class_attendance_events e
  where e.class_id=p_class_id and e.person_id=p_person_id
  order by e.recorded_at desc,e.id desc
  limit 1
$function$;

create or replace function private.record_class_attendance_fact(
  p_class_id bigint,
  p_person_id bigint,
  p_attendance_status text,
  p_absence_reason text,
  p_effective_at timestamptz,
  p_source text,
  p_supersedes_event_id bigint default null,
  p_correction_reason text default null,
  p_detail jsonb default '{}'::jsonb
)
returns public.class_attendance_events
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_existing public.class_attendance_events;
  v_event public.class_attendance_events;
  v_actor uuid:=(select auth.uid());
begin
  if p_attendance_status not in ('present','absent') then
    raise exception 'Asistencia no válida.' using errcode='22023';
  end if;
  if p_attendance_status='present' and p_absence_reason is not null then
    raise exception 'Una asistencia presente no admite motivo de ausencia.' using errcode='22023';
  end if;
  if p_attendance_status='absent' and p_absence_reason is not null
     and p_absence_reason not in ('no_show','excused','cancelled_by_student','other') then
    raise exception 'Motivo de ausencia no válido.' using errcode='22023';
  end if;
  if not exists(
    select 1 from public.class_participants cp
    where cp.class_id=p_class_id and cp.person_id=p_person_id
  ) then
    raise exception 'La persona no participa en esta clase.' using errcode='22023';
  end if;

  select * into v_existing
  from public.class_attendance_events e
  where e.class_id=p_class_id and e.person_id=p_person_id
  order by e.recorded_at desc,e.id desc
  limit 1
  for update;

  if p_source<>'correction' and v_existing.id is not null then
    if v_existing.attendance_status=p_attendance_status
       and v_existing.absence_reason is not distinct from p_absence_reason then
      return v_existing;
    end if;
    raise exception 'La asistencia ya fue registrada; utiliza correct_class_attendance().' using errcode='22023';
  end if;

  if p_source='correction' then
    if v_existing.id is null or p_supersedes_event_id is distinct from v_existing.id then
      raise exception 'La corrección debe superseder el último hecho de asistencia.' using errcode='40001';
    end if;
    if nullif(btrim(p_correction_reason),'') is null then
      raise exception 'La corrección requiere motivo.' using errcode='22023';
    end if;
  elsif p_source not in ('administrative_finish','explicit_record') then
    raise exception 'Origen de asistencia no válido.' using errcode='22023';
  end if;

  insert into public.class_attendance_events(
    class_id,person_id,attendance_status,absence_reason,effective_at,recorded_by,
    source,supersedes_event_id,correction_reason,detail
  ) values(
    p_class_id,p_person_id,p_attendance_status,p_absence_reason,p_effective_at,v_actor,
    p_source,p_supersedes_event_id,nullif(btrim(p_correction_reason),''),coalesce(p_detail,'{}'::jsonb)
  ) returning * into v_event;

  insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
  values(
    case when p_source='correction' then 'class_attendance_corrected' else 'class_attendance_recorded' end,
    'class_attendance',v_event.id::text,
    case when p_source='correction' then 'Asistencia corregida' else 'Asistencia real registrada' end,
    jsonb_build_object(
      'class_id',p_class_id,'person_id',p_person_id,'attendance_status',p_attendance_status,
      'absence_reason',p_absence_reason,'effective_at',p_effective_at,'source',p_source,
      'supersedes_event_id',p_supersedes_event_id,'correction_reason',nullif(btrim(p_correction_reason),'')
    ),v_actor
  );

  return v_event;
end;
$function$;

create or replace function public.record_class_attendance(
  p_class_id bigint,
  p_person_id bigint,
  p_attendance_status text,
  p_absence_reason text default null
)
returns public.class_attendance_events
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_class public.classes;
begin
  if not (select private.is_staff()) then
    raise exception 'No tienes permiso para registrar asistencia.' using errcode='42501';
  end if;
  select * into v_class from public.classes where id=p_class_id for update;
  if not found then raise exception 'La clase no existe.' using errcode='P0002'; end if;
  if v_class.status<>'active' or v_class.administrative_finished_at is not null then
    raise exception 'La asistencia inicial solo puede registrarse durante una clase activa.' using errcode='22023';
  end if;
  perform 1 from public.class_participants where class_id=p_class_id and person_id=p_person_id for update;
  if not found then raise exception 'La persona no participa en esta clase.' using errcode='22023'; end if;
  return private.record_class_attendance_fact(
    p_class_id,p_person_id,p_attendance_status,p_absence_reason,v_class.scheduled_start_at,
    'explicit_record',null,null,jsonb_build_object('class_status',v_class.status)
  );
end;
$function$;

create or replace function public.correct_class_attendance(
  p_class_id bigint,
  p_person_id bigint,
  p_attendance_status text,
  p_absence_reason text,
  p_reason text
)
returns public.class_attendance_events
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_class public.classes;
  v_previous public.class_attendance_events;
begin
  if not (select private.is_staff()) then
    raise exception 'No tienes permiso para corregir asistencia.' using errcode='42501';
  end if;
  if nullif(btrim(p_reason),'') is null then
    raise exception 'Indica el motivo de la corrección.' using errcode='22023';
  end if;
  select * into v_class from public.classes where id=p_class_id for update;
  if not found then raise exception 'La clase no existe.' using errcode='P0002'; end if;
  if v_class.administrative_finished_at is not null then
    raise exception 'Reabre primero el cierre administrativo antes de corregir asistencia para mantener coherencia económica.' using errcode='22023';
  end if;
  perform 1 from public.class_participants where class_id=p_class_id and person_id=p_person_id for update;
  if not found then raise exception 'La persona no participa en esta clase.' using errcode='22023'; end if;
  select * into v_previous from private.class_attendance_latest_event(p_class_id,p_person_id);
  if v_previous.id is null then
    raise exception 'No existe una asistencia durable que corregir.' using errcode='P0002';
  end if;
  return private.record_class_attendance_fact(
    p_class_id,p_person_id,p_attendance_status,p_absence_reason,v_previous.effective_at,
    'correction',v_previous.id,p_reason,
    jsonb_build_object(
      'before',jsonb_build_object('attendance_status',v_previous.attendance_status,'absence_reason',v_previous.absence_reason),
      'after',jsonb_build_object('attendance_status',p_attendance_status,'absence_reason',p_absence_reason)
    )
  );
end;
$function$;

revoke all on function public.record_class_attendance(bigint,bigint,text,text) from public,anon;
grant execute on function public.record_class_attendance(bigint,bigint,text,text) to authenticated,service_role;
revoke all on function public.correct_class_attendance(bigint,bigint,text,text,text) from public,anon;
grant execute on function public.correct_class_attendance(bigint,bigint,text,text,text) to authenticated,service_role;

create or replace function private.person_has_real_attendance_unchecked(p_person_id bigint)
returns boolean
language sql
stable
security definer
set search_path=''
as $function$
  select exists(
    select 1
    from (
      select distinct on (e.class_id) e.class_id,e.attendance_status
      from public.class_attendance_events e
      where e.person_id=p_person_id
      order by e.class_id,e.recorded_at desc,e.id desc
    ) current_attendance
    where current_attendance.attendance_status='present'
  )
$function$;

create or replace function private.person_first_real_attendance_unchecked(p_person_id bigint)
returns timestamptz
language sql
stable
security definer
set search_path=''
as $function$
  select min(x.effective_at)
  from (
    select distinct on (e.class_id) e.class_id,e.attendance_status,e.effective_at
    from public.class_attendance_events e
    where e.person_id=p_person_id
    order by e.class_id,e.recorded_at desc,e.id desc
  ) x
  where x.attendance_status='present'
$function$;

create or replace function private.person_last_real_attendance_unchecked(p_person_id bigint)
returns timestamptz
language sql
stable
security definer
set search_path=''
as $function$
  select max(x.effective_at)
  from (
    select distinct on (e.class_id) e.class_id,e.attendance_status,e.effective_at
    from public.class_attendance_events e
    where e.person_id=p_person_id
    order by e.class_id,e.recorded_at desc,e.id desc
  ) x
  where x.attendance_status='present'
$function$;

create or replace function private.person_has_valid_future_class_unchecked(p_person_id bigint)
returns boolean
language sql
stable
security definer
set search_path=''
as $function$
  select exists(
    select 1
    from public.classes c
    join public.class_participants cp on cp.class_id=c.id and cp.person_id=p_person_id
    where c.status='scheduled'
      and c.cancelled_at is null
      and c.scheduled_start_at>now()
      and cp.attendance_status='planned'
      and not exists(
        select 1 from public.classes replacement
        where replacement.rescheduled_from_id=c.id
          and replacement.status='scheduled'
          and replacement.cancelled_at is null
      )
  )
$function$;

create or replace function private.can_read_person_attendance(p_person_id bigint)
returns boolean
language sql
stable
security definer
set search_path=''
as $function$
  select (select private.is_staff()) or p_person_id=(select private.current_person_id())
$function$;

create or replace function public.has_real_attendance(p_person_id bigint)
returns boolean
language plpgsql
stable
security definer
set search_path=''
as $function$
begin
  if not (select private.can_read_person_attendance(p_person_id)) then
    raise exception 'No tienes permiso para consultar esta asistencia.' using errcode='42501';
  end if;
  return private.person_has_real_attendance_unchecked(p_person_id);
end;
$function$;

create or replace function public.first_real_attendance(p_person_id bigint)
returns timestamptz
language plpgsql
stable
security definer
set search_path=''
as $function$
begin
  if not (select private.can_read_person_attendance(p_person_id)) then
    raise exception 'No tienes permiso para consultar esta asistencia.' using errcode='42501';
  end if;
  return private.person_first_real_attendance_unchecked(p_person_id);
end;
$function$;

create or replace function public.last_real_attendance(p_person_id bigint)
returns timestamptz
language plpgsql
stable
security definer
set search_path=''
as $function$
begin
  if not (select private.can_read_person_attendance(p_person_id)) then
    raise exception 'No tienes permiso para consultar esta asistencia.' using errcode='42501';
  end if;
  return private.person_last_real_attendance_unchecked(p_person_id);
end;
$function$;

create or replace function public.has_valid_future_class(p_person_id bigint)
returns boolean
language plpgsql
stable
security definer
set search_path=''
as $function$
begin
  if not (select private.can_read_person_attendance(p_person_id)) then
    raise exception 'No tienes permiso para consultar próximas clases.' using errcode='42501';
  end if;
  return private.person_has_valid_future_class_unchecked(p_person_id);
end;
$function$;

revoke all on function public.has_real_attendance(bigint) from public,anon;
grant execute on function public.has_real_attendance(bigint) to authenticated,service_role;
revoke all on function public.first_real_attendance(bigint) from public,anon;
grant execute on function public.first_real_attendance(bigint) to authenticated,service_role;
revoke all on function public.last_real_attendance(bigint) from public,anon;
grant execute on function public.last_real_attendance(bigint) to authenticated,service_role;
revoke all on function public.has_valid_future_class(bigint) from public,anon;
grant execute on function public.has_valid_future_class(bigint) to authenticated,service_role;

-- Patch the canonical attendance-aware lower close function. It remains idempotent and records
-- durable facts only for newly closed classes; no legacy finished class is backfilled.
create or replace function public.administratively_finish_class_v2(p_class_id bigint, p_person_ids bigint[], p_attendance text[], p_grant_ids bigint[], p_actual_duration_minutes integer default null::integer)
returns public.classes
language plpgsql
set search_path=''
as $function$
declare
  v_class public.classes;
  v_expected integer;
  v_end_at timestamptz:=now();
  v_original_duration integer;
  v_duration integer;
  v_duration_source text;
  i integer;
  v_person_id bigint;
  v_grant_id bigint;
  v_attendance text;
  v_balance integer;
  v_covered integer;
  v_shortfall integer;
  v_people bigint[];
  v_movement_person bigint;
  v_incident public.student_incidents;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para terminar clases.' using errcode='42501'; end if;
  select * into v_class from public.classes where id=p_class_id for update;
  if not found then raise exception 'La clase no existe.' using errcode='P0002'; end if;
  if v_class.status='finished' and v_class.administrative_finished_at is not null then return v_class; end if;
  if v_class.status<>'active' then raise exception 'Solo se puede terminar una clase activa.' using errcode='22023'; end if;

  select count(*) into v_expected from public.class_participants where class_id=p_class_id;
  if cardinality(coalesce(p_person_ids,'{}'::bigint[]))<>v_expected
     or cardinality(coalesce(p_attendance,'{}'::text[]))<>v_expected
     or cardinality(coalesce(p_grant_ids,'{}'::bigint[]))<>v_expected then
    raise exception 'Faltan datos de asistencia o bono.' using errcode='22023';
  end if;
  if (select count(distinct x) from unnest(p_person_ids) x)<>v_expected
     or (select count(*) from public.class_participants where class_id=p_class_id and person_id=any(p_person_ids))<>v_expected then
    raise exception 'La lista de alumnos no coincide con la clase.' using errcode='22023';
  end if;

  v_original_duration:=v_class.duration_minutes;
  if p_actual_duration_minutes is null then v_duration:=v_original_duration; v_duration_source:='scheduled';
  else
    if p_actual_duration_minutes<=0 or p_actual_duration_minutes>480 then raise exception 'La duración debe estar entre 1 y 480 minutos.' using errcode='22023'; end if;
    v_duration:=p_actual_duration_minutes;
    v_duration_source:=case when p_actual_duration_minutes=v_original_duration then 'scheduled' else 'manual' end;
  end if;
  if v_duration is null or v_duration<=0 or v_duration>480 then raise exception 'La duración de la clase no es válida.' using errcode='22023'; end if;

  for i in 1..v_expected loop
    v_person_id:=p_person_ids[i]; v_attendance:=p_attendance[i]; v_grant_id:=p_grant_ids[i];
    if v_attendance not in ('present','absent') then raise exception 'Asistencia no válida.' using errcode='22023'; end if;
    if v_attendance='absent' and v_grant_id is not null then raise exception 'Un alumno ausente no puede consumir bono.' using errcode='22023'; end if;
    if v_grant_id is not null and not exists(
      select 1 from public.credit_grants g join public.credit_grant_members gm on gm.grant_id=g.id
      where g.id=v_grant_id and gm.person_id=v_person_id and g.status='active'
    ) then raise exception 'El bono seleccionado no está disponible para este alumno.' using errcode='22023'; end if;
  end loop;

  for i in 1..v_expected loop
    v_person_id:=p_person_ids[i]; v_attendance:=p_attendance[i]; v_grant_id:=p_grant_ids[i];
    update public.class_participants
    set attendance_status=v_attendance,
        billing_grant_id=case when v_attendance='present' then v_grant_id else null end,
        billed_minutes=case when v_attendance='present' then v_duration else 0 end,
        uncovered_minutes=0,
        billing_status=case when v_attendance='present' then 'covered' else 'not_billable' end
    where class_id=p_class_id and person_id=v_person_id;
  end loop;

  for v_grant_id in
    select distinct x.grant_id from unnest(p_person_ids,p_attendance,p_grant_ids) as x(person_id,attendance,grant_id)
    where x.attendance='present' and x.grant_id is not null
  loop
    perform 1 from public.credit_grants where id=v_grant_id for update;
    select coalesce(sum(delta_minutes),0)::integer into v_balance from public.credit_movements where grant_id=v_grant_id;
    v_covered:=least(greatest(v_balance,0),v_duration); v_shortfall:=v_duration-v_covered;
    select array_agg(x.person_id order by x.person_id),case when count(*)=1 then min(x.person_id) else null end
      into v_people,v_movement_person
    from unnest(p_person_ids,p_attendance,p_grant_ids) as x(person_id,attendance,grant_id)
    where x.attendance='present' and x.grant_id=v_grant_id;
    if v_covered>0 then
      insert into public.credit_movements(grant_id,person_id,class_id,movement_type,delta_minutes,note,created_by)
      values(v_grant_id,v_movement_person,p_class_id,'class',-v_covered,case when v_shortfall>0 then 'Consumo de clase · saldo parcial' else 'Consumo de clase' end,(select auth.uid()));
    end if;
    if v_balance-v_covered<=0 then update public.credit_grants set status='exhausted',updated_at=now() where id=v_grant_id; end if;
    if v_shortfall>0 then
      update public.class_participants set uncovered_minutes=v_shortfall,billing_status='partial' where class_id=p_class_id and person_id=any(v_people);
      v_incident:=private.upsert_negative_balance_incident(p_class_id,v_grant_id,v_shortfall,v_people,'class:'||p_class_id::text||':grant:'||v_grant_id::text);
      insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
      values('financial_incident_created','student_incident',v_incident.id::text,'Saldo insuficiente al terminar una clase',jsonb_build_object('class_id',p_class_id,'grant_id',v_grant_id,'debt_minutes',v_shortfall,'person_ids',v_people),(select auth.uid()));
    end if;
  end loop;

  for i in 1..v_expected loop
    v_person_id:=p_person_ids[i]; v_attendance:=p_attendance[i]; v_grant_id:=p_grant_ids[i];
    if v_attendance='present' and v_grant_id is null then
      update public.class_participants set uncovered_minutes=v_duration,billing_status='uncovered' where class_id=p_class_id and person_id=v_person_id;
      v_incident:=private.upsert_negative_balance_incident(p_class_id,null,v_duration,array[v_person_id],'class:'||p_class_id::text||':person:'||v_person_id::text);
      insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
      values('financial_incident_created','student_incident',v_incident.id::text,'Clase terminada sin bono: saldo negativo pendiente',jsonb_build_object('class_id',p_class_id,'person_id',v_person_id,'debt_minutes',v_duration),(select auth.uid()));
    end if;
  end loop;

  update public.classes
  set status='finished',duration_minutes=v_duration,actual_end_at=null,actual_duration_minutes=null,
      billed_duration_minutes=v_duration,duration_source=v_duration_source,
      administrative_finished_at=v_end_at,administratively_finished_by=(select auth.uid()),updated_at=now()
  where id=p_class_id returning * into v_class;

  for i in 1..v_expected loop
    perform private.record_class_attendance_fact(
      p_class_id,p_person_ids[i],p_attendance[i],null,v_class.scheduled_start_at,
      'administrative_finish',null,null,jsonb_build_object('administrative_finished_at',v_end_at)
    );
  end loop;

  insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
  values('class_administratively_finished','class',p_class_id::text,'Clase terminada administrativamente',
    jsonb_build_object('original_scheduled_duration_minutes',v_original_duration,'final_duration_minutes',v_duration,'billed_duration_minutes',v_duration,'duration_source',v_duration_source,'administrative_finished_at',v_end_at),(select auth.uid()));
  return v_class;
end;
$function$;

-- Remove blanket-present from v4 without changing its external signature.
create or replace function public.administratively_finish_class_v4(p_class_id bigint, p_person_ids bigint[], p_grant_ids bigint[] default null::bigint[], p_duration_minutes integer default null::integer, p_direct_payment_price_cents integer default null::integer, p_pair_transfer_source_grant_id bigint default null::bigint, p_pair_transfer_fee_cents integer default 0, p_supplements jsonb default '[]'::jsonb)
returns public.classes
language plpgsql
set search_path=''
as $function$
declare
  v_class public.classes; v_result public.classes; v_class_people bigint[]; v_expected integer;
  v_effective_grants bigint[]; v_attendance text[]; v_duration integer; v_source public.credit_grants;
  v_source_people bigint[]; v_source_person bigint; v_source_balance integer; v_transfer_minutes integer;
  v_target public.credit_grants; v_extra jsonb; v_extra_concept text; v_extra_amount integer; v_supplement_total integer:=0;
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para terminar clases.' using errcode='42501'; end if;
  select * into v_class from public.classes where id=p_class_id for update;
  if not found then raise exception 'La clase no existe.' using errcode='P0002'; end if;
  if v_class.status='finished' and v_class.administrative_finished_at is not null then return v_class; end if;
  if v_class.status<>'active' then raise exception 'Solo se puede terminar una clase activa.' using errcode='22023'; end if;
  select coalesce(array_agg(person_id order by person_id),'{}'::bigint[]) into v_class_people from public.class_participants where class_id=p_class_id;
  v_expected:=cardinality(v_class_people);
  if cardinality(coalesce(p_person_ids,'{}'::bigint[]))<>v_expected
     or (select count(distinct x) from unnest(coalesce(p_person_ids,'{}'::bigint[])) x)<>v_expected
     or (select count(*) from unnest(coalesce(p_person_ids,'{}'::bigint[])) x where x=any(v_class_people))<>v_expected then
    raise exception 'La lista de alumnos no coincide con la clase.' using errcode='22023';
  end if;
  v_effective_grants:=coalesce(p_grant_ids,array_fill(null::bigint,array[v_expected]));
  if cardinality(v_effective_grants)<>v_expected then raise exception 'La selección de bonos no coincide con la clase.' using errcode='22023'; end if;
  v_duration:=coalesce(p_duration_minutes,v_class.duration_minutes);
  if v_duration is null or v_duration<=0 or v_duration>480 then raise exception 'La duración debe estar entre 1 y 480 minutos.' using errcode='22023'; end if;

  select array_agg(cp.attendance_status order by u.ord) into v_attendance
  from unnest(p_person_ids) with ordinality as u(person_id,ord)
  join public.class_participants cp on cp.class_id=p_class_id and cp.person_id=u.person_id;
  if cardinality(coalesce(v_attendance,'{}'::text[]))<>v_expected
     or exists(select 1 from unnest(v_attendance) a where a not in ('present','absent')) then
    raise exception 'Confirma la asistencia real (presente o ausente) de todos los alumnos antes de terminar.' using errcode='22023';
  end if;

  if p_supplements is null then p_supplements:='[]'::jsonb; end if;
  if jsonb_typeof(p_supplements)<>'array' then raise exception 'Los suplementos no son válidos.' using errcode='22023'; end if;
  if jsonb_array_length(p_supplements)>20 then raise exception 'No se pueden añadir más de 20 suplementos por clase.' using errcode='22023'; end if;
  if p_direct_payment_price_cents is not null and p_pair_transfer_source_grant_id is not null then raise exception 'Elige pago de clase suelta o transferencia de saldo, no ambos.' using errcode='22023'; end if;
  if (p_direct_payment_price_cents is not null or p_pair_transfer_source_grant_id is not null) and exists(select 1 from unnest(v_effective_grants) g where g is not null) then raise exception 'No se puede combinar un bono seleccionado con esta forma de cobro.' using errcode='22023'; end if;
  if p_pair_transfer_source_grant_id is null and coalesce(p_pair_transfer_fee_cents,0)<>0 then raise exception 'El coste de conversión requiere una transferencia de saldo.' using errcode='22023'; end if;

  if p_pair_transfer_source_grant_id is not null then
    if v_class.class_type<>'pair' then raise exception 'Solo una clase en pareja puede recibir saldo individual.' using errcode='22023'; end if;
    if coalesce(p_pair_transfer_fee_cents,0)<0 then raise exception 'El coste adicional no puede ser negativo.' using errcode='22023'; end if;
    select * into v_source from public.credit_grants where id=p_pair_transfer_source_grant_id and modality='individual' and status='active' and (expires_at is null or expires_at>now()) for update;
    if not found then raise exception 'El bono individual seleccionado no está activo o ha caducado.' using errcode='22023'; end if;
    select coalesce(array_agg(person_id order by person_id),'{}'::bigint[]) into v_source_people from public.credit_grant_members where grant_id=v_source.id;
    if cardinality(v_source_people)<>1 or not (v_source_people[1]=any(v_class_people)) then raise exception 'El bono individual no pertenece a uno de los alumnos de esta clase.' using errcode='22023'; end if;
    v_source_person:=v_source_people[1];
    select coalesce(sum(delta_minutes),0)::integer into v_source_balance from public.credit_movements where grant_id=v_source.id;
    if v_source_balance<=0 then raise exception 'El bono individual no tiene saldo disponible.' using errcode='22023'; end if;
    v_transfer_minutes:=least(v_source_balance,v_duration);
    select * into v_target from public.create_credit_grant(v_class_people,'pair',v_transfer_minutes,0,'Transferencia a pareja','paid');
    insert into public.credit_movements(grant_id,person_id,class_id,movement_type,delta_minutes,note,created_by)
    values(v_source.id,v_source_person,p_class_id,'adjustment',-v_transfer_minutes,'Transferencia a bono de pareja '||v_target.id::text,(select auth.uid()));
    if v_source_balance-v_transfer_minutes<=0 then update public.credit_grants set status='exhausted',updated_at=now() where id=v_source.id; end if;
    v_effective_grants:=array_fill(v_target.id,array[v_expected]);
    insert into public.class_financial_items(class_id,item_type,concept,amount_cents,minutes,person_id,source_grant_id,target_grant_id,created_by)
    values(p_class_id,'pair_transfer','Conversión de saldo individual a pareja',coalesce(p_pair_transfer_fee_cents,0),v_transfer_minutes,v_source_person,v_source.id,v_target.id,(select auth.uid()));
  end if;

  v_result:=public.administratively_finish_class_v3(p_class_id,p_person_ids,v_attendance,v_effective_grants,v_duration,p_direct_payment_price_cents);

  for v_extra in select value from jsonb_array_elements(p_supplements) as s(value) loop
    if jsonb_typeof(v_extra)<>'object' then raise exception 'Suplemento no válido.' using errcode='22023'; end if;
    v_extra_concept:=btrim(coalesce(v_extra->>'concept',''));
    if char_length(v_extra_concept)<1 or char_length(v_extra_concept)>120 then raise exception 'El concepto del suplemento no es válido.' using errcode='22023'; end if;
    if coalesce(v_extra->>'amount_cents','') !~ '^[0-9]+$' then raise exception 'El importe del suplemento no es válido.' using errcode='22023'; end if;
    v_extra_amount:=(v_extra->>'amount_cents')::integer;
    if v_extra_amount<=0 or v_extra_amount>10000000 then raise exception 'El importe del suplemento no es válido.' using errcode='22023'; end if;
    insert into public.class_financial_items(class_id,item_type,concept,amount_cents,created_by) values(p_class_id,'supplement',v_extra_concept,v_extra_amount,(select auth.uid()));
    v_supplement_total:=v_supplement_total+v_extra_amount;
  end loop;

  insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
  values('class_financial_close','class',p_class_id::text,'Cierre económico de clase',jsonb_build_object('duration_minutes',v_duration,'supplement_total_cents',v_supplement_total,'pair_transfer_source_grant_id',p_pair_transfer_source_grant_id,'pair_transfer_minutes',v_transfer_minutes,'pair_transfer_fee_cents',case when p_pair_transfer_source_grant_id is null then 0 else coalesce(p_pair_transfer_fee_cents,0) end,'direct_payment_price_cents',p_direct_payment_price_cents),(select auth.uid()));
  return v_result;
end;
$function$;

-- Administrative reopen reverses billing/admin state but deliberately preserves real attendance.
create or replace function public.reopen_administratively_finished_class(p_class_id bigint)
returns public.classes
language plpgsql
set search_path=''
as $function$
declare
  v_class public.classes; v_original_duration integer; v_financial_snapshot jsonb; v_m record; v_item record; v_art record;
  v_balance integer; v_incident_ids bigint[];
begin
  if not (select private.is_staff()) then raise exception 'No tienes permiso para reabrir clases.' using errcode='42501'; end if;
  select * into v_class from public.classes where id=p_class_id for update;
  if not found then raise exception 'La clase no existe.' using errcode='P0002'; end if;
  if v_class.status<>'finished' or v_class.administrative_finished_at is null then raise exception 'La clase no tiene un cierre administrativo que deshacer.' using errcode='22023'; end if;
  select case when detail->>'original_scheduled_duration_minutes' ~ '^[0-9]+$' then (detail->>'original_scheduled_duration_minutes')::integer else null end
    into v_original_duration from public.audit_events where event_type='class_administratively_finished' and entity_type='class' and entity_id=p_class_id::text order by created_at desc limit 1;
  select jsonb_build_object('account',(select to_jsonb(a) from public.class_financial_accounts a where a.class_id=p_class_id),'items',coalesce((select jsonb_agg(to_jsonb(i) order by i.id) from public.class_financial_items i where i.class_id=p_class_id),'[]'::jsonb),'payments',coalesce((select jsonb_agg(to_jsonb(pm) order by pm.id) from public.class_payment_movements pm where pm.class_id=p_class_id),'[]'::jsonb)) into v_financial_snapshot;

  for v_m in select grant_id,coalesce(sum(-delta_minutes),0)::integer as minutes from public.credit_movements where class_id=p_class_id and movement_type='class' and delta_minutes<0 group by grant_id loop
    if v_m.minutes>0 then
      insert into public.credit_movements(grant_id,class_id,movement_type,delta_minutes,note,created_by) values(v_m.grant_id,p_class_id,'adjustment',v_m.minutes,'Reapertura de clase · devolución de consumo',(select auth.uid()));
      update public.credit_grants set status='active',updated_at=now() where id=v_m.grant_id;
    end if;
  end loop;
  for v_item in select * from public.class_financial_items where class_id=p_class_id and item_type='pair_transfer' order by id loop
    if v_item.source_grant_id is not null and coalesce(v_item.minutes,0)>0 then
      insert into public.credit_movements(grant_id,person_id,class_id,movement_type,delta_minutes,note,created_by) values(v_item.source_grant_id,v_item.person_id,p_class_id,'adjustment',v_item.minutes,'Reapertura de clase · devolución de transferencia',(select auth.uid()));
      update public.credit_grants set status='active',updated_at=now() where id=v_item.source_grant_id;
    end if;
    if v_item.target_grant_id is not null then
      select coalesce(sum(delta_minutes),0)::integer into v_balance from public.credit_movements where grant_id=v_item.target_grant_id;
      if v_balance>0 then insert into public.credit_movements(grant_id,class_id,movement_type,delta_minutes,note,created_by) values(v_item.target_grant_id,p_class_id,'adjustment',-v_balance,'Reapertura de clase · anulación del saldo transferido',(select auth.uid())); end if;
      update public.credit_grants set status='cancelled',updated_at=now() where id=v_item.target_grant_id;
    end if;
  end loop;
  for v_art in select * from public.class_close_grant_artifacts where class_id=p_class_id order by id loop
    select coalesce(sum(delta_minutes),0)::integer into v_balance from public.credit_movements where grant_id=v_art.grant_id;
    if v_art.artifact_type in ('direct_payment','regularization') then
      if v_balance<>0 then insert into public.credit_movements(grant_id,class_id,movement_type,delta_minutes,note,created_by) values(v_art.grant_id,p_class_id,'adjustment',-v_balance,'Reapertura de clase · anulación de bono generado en el cierre',(select auth.uid())); end if;
      update public.credit_grants set status='cancelled',payment_status='pending',updated_at=now() where id=v_art.grant_id;
    elsif v_art.artifact_type='quick_bonus' then
      update public.credit_grants set status=case when v_balance>0 then 'active' else status end,payment_status='pending',updated_at=now() where id=v_art.grant_id;
    end if;
  end loop;
  select coalesce(array_agg(id),'{}'::bigint[]) into v_incident_ids from public.student_incidents where related_class_id=p_class_id and incident_type='negative_balance';
  delete from public.student_incident_people where incident_id=any(v_incident_ids);
  delete from public.student_incidents where id=any(v_incident_ids);
  delete from public.class_payment_movements where class_id=p_class_id;
  delete from public.class_financial_accounts where class_id=p_class_id;
  delete from public.class_financial_items where class_id=p_class_id;
  delete from public.class_close_grant_artifacts where class_id=p_class_id;

  update public.class_participants
  set billing_grant_id=null,billed_minutes=0,uncovered_minutes=0,billing_status='planned',updated_at=now()
  where class_id=p_class_id;

  update public.classes
  set status='active',duration_minutes=coalesce(v_original_duration,duration_minutes),administrative_finished_at=null,
      administratively_finished_by=null,pedagogy_closed_at=null,billed_duration_minutes=null,duration_source=null,
      actual_end_at=null,actual_duration_minutes=null,updated_at=now()
  where id=p_class_id returning * into v_class;

  insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
  values('class_administrative_reopened','class',p_class_id::text,'Cierre administrativo deshecho',jsonb_build_object('financial_snapshot',v_financial_snapshot,'original_duration_restored',v_original_duration,'incident_ids',v_incident_ids,'attendance_history_preserved',true),(select auth.uid()));
  return v_class;
end;
$function$;

-- CLASS-ATTENDANCE-SEC-01 — deny direct execution of all private helpers authored/replaced by M1.
-- Trigger invocation and SECURITY DEFINER public RPC nesting execute as the function owner; no external role needs EXECUTE.
revoke execute on function private.prevent_class_attendance_event_mutation() from public,anon,authenticated,service_role;
revoke execute on function private.protect_durable_attendance_projection() from public,anon,authenticated,service_role;
revoke execute on function private.sync_class_attendance_projection() from public,anon,authenticated,service_role;
revoke execute on function private.class_attendance_latest_event(bigint,bigint) from public,anon,authenticated,service_role;
revoke execute on function private.record_class_attendance_fact(bigint,bigint,text,text,timestamptz,text,bigint,text,jsonb) from public,anon,authenticated,service_role;
revoke execute on function private.person_has_real_attendance_unchecked(bigint) from public,anon,authenticated,service_role;
revoke execute on function private.person_first_real_attendance_unchecked(bigint) from public,anon,authenticated,service_role;
revoke execute on function private.person_last_real_attendance_unchecked(bigint) from public,anon,authenticated,service_role;
revoke execute on function private.person_has_valid_future_class_unchecked(bigint) from public,anon,authenticated,service_role;
revoke execute on function private.can_read_person_attendance(bigint) from public,anon,authenticated,service_role;

-- Fail closed at apply time if an exact helper signature still has effective external EXECUTE.
do $acl_guard$
declare
  v_role text;
  v_signature text;
  v_roles constant text[] := array['public','anon','authenticated','service_role'];
  v_signatures constant text[] := array[
    'private.prevent_class_attendance_event_mutation()',
    'private.protect_durable_attendance_projection()',
    'private.sync_class_attendance_projection()',
    'private.class_attendance_latest_event(bigint,bigint)',
    'private.record_class_attendance_fact(bigint,bigint,text,text,timestamp with time zone,text,bigint,text,jsonb)',
    'private.person_has_real_attendance_unchecked(bigint)',
    'private.person_first_real_attendance_unchecked(bigint)',
    'private.person_last_real_attendance_unchecked(bigint)',
    'private.person_has_valid_future_class_unchecked(bigint)',
    'private.can_read_person_attendance(bigint)'
  ];
begin
  foreach v_signature in array v_signatures loop
    if to_regprocedure(v_signature) is null then
      raise exception 'CLASS-ATTENDANCE-SEC-01: helper esperado no resuelto: %', v_signature using errcode='42704';
    end if;
    foreach v_role in array v_roles loop
      if has_function_privilege(v_role, v_signature, 'EXECUTE') then
        raise exception 'CLASS-ATTENDANCE-SEC-01: EXECUTE externo efectivo: role=% function=%', v_role, v_signature using errcode='42501';
      end if;
    end loop;
  end loop;
end;
$acl_guard$;
