-- BONUS-INDIVIDUAL-TO-PAIR-TRANSFER-01 — Transfer Foundation.
-- STAGING authoring candidate only. DO NOT APPLY from this branch without independent QA PRE-APPLY.
-- Recovery after application: forward-fix only. Never rewrite applied migration history.

do $preflight$
begin
  if to_regprocedure('private.is_staff()') is null
     or to_regprocedure('private.credit_grant_balance_minutes_unchecked(bigint)') is null
     or to_regprocedure('private.credit_grant_effective_expires_at_unchecked(bigint,timestamp with time zone)') is null
     or to_regprocedure('private.credit_grant_is_paused_unchecked(bigint,timestamp with time zone)') is null
     or to_regprocedure('public.billing_person_bonus_summary(bigint,timestamp with time zone)') is null then
    raise exception 'BONUS-INDIVIDUAL-TO-PAIR-TRANSFER-01 requires the applied Billing usability/authority foundation.';
  end if;

  if to_regclass('public.credit_transfer_operations') is not null
     or to_regclass('public.credit_pair_transfer_pools') is not null then
    raise exception 'BONUS-INDIVIDUAL-TO-PAIR-TRANSFER-01 objects already exist; reconcile before applying.';
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema='public'
      and table_name='credit_movements'
      and column_name='transfer_id'
  ) then
    raise exception 'credit_movements.transfer_id already exists; reconcile before applying.';
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid='public.credit_movements'::regclass
      and conname='credit_movements_movement_type_check'
  ) then
    raise exception 'Expected credit_movements_movement_type_check is missing.';
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname='public'
      and tablename='credit_movements'
      and policyname='credit_movements_staff_insert'
      and cmd='INSERT'
  ) then
    raise exception 'Expected credit_movements_staff_insert transitional policy is missing.';
  end if;
end;
$preflight$;

create table public.credit_pair_transfer_pools (
  destination_grant_id bigint primary key
    references public.credit_grants(id) on delete restrict,
  economic_source_grant_id bigint not null
    references public.credit_grants(id) on delete restrict,
  member_person_id_low bigint not null
    references public.people(id) on delete restrict,
  member_person_id_high bigint not null
    references public.people(id) on delete restrict,
  created_by uuid,
  created_at timestamptz not null default now(),
  constraint credit_pair_transfer_pools_member_order_check
    check (member_person_id_low < member_person_id_high)
);

comment on table public.credit_pair_transfer_pools is
  'Marks pair grants created exclusively from canonical individual-to-pair transfers and binds each pool to one economic source grant. Purchased or cross-provenance pair grants are never eligible transfer pools.';

create index credit_pair_transfer_pools_pair_idx
  on public.credit_pair_transfer_pools(
    economic_source_grant_id,
    member_person_id_low,
    member_person_id_high,
    destination_grant_id
  );

alter table public.credit_pair_transfer_pools enable row level security;

revoke all on table public.credit_pair_transfer_pools from public;
revoke all on table public.credit_pair_transfer_pools from anon;
revoke all on table public.credit_pair_transfer_pools from authenticated;
revoke all on table public.credit_pair_transfer_pools from service_role;

create table public.credit_transfer_operations (
  id bigint generated by default as identity primary key,
  operation_type text not null,
  request_key text not null,
  source_grant_id bigint not null
    references public.credit_grants(id) on delete restrict,
  destination_grant_id bigint not null
    references public.credit_grants(id) on delete restrict,
  source_person_id bigint not null
    references public.people(id) on delete restrict,
  partner_person_id bigint not null
    references public.people(id) on delete restrict,
  minutes integer not null,
  class_id bigint references public.classes(id) on delete restrict,
  source_payment_status text not null,
  source_starts_at timestamptz not null,
  source_effective_expires_at timestamptz,
  source_was_paused boolean not null,
  source_provenance jsonb not null default '{}'::jsonb,
  source_balance_before integer not null,
  source_balance_after integer not null,
  destination_balance_before integer not null,
  destination_balance_after integer not null,
  actor_user_id uuid not null,
  reason text,
  reverses_transfer_id bigint
    references public.credit_transfer_operations(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint credit_transfer_operations_operation_type_check
    check (operation_type in ('transfer','reversal')),
  constraint credit_transfer_operations_request_key_check
    check (char_length(btrim(request_key)) between 1 and 200),
  constraint credit_transfer_operations_minutes_check
    check (minutes > 0),
  constraint credit_transfer_operations_pair_check
    check (source_person_id <> partner_person_id),
  constraint credit_transfer_operations_payment_check
    check (source_payment_status in ('paid','pending')),
  constraint credit_transfer_operations_balances_check
    check (
      source_balance_before >= 0
      and source_balance_after >= 0
      and destination_balance_before >= 0
      and destination_balance_after >= 0
    ),
  constraint credit_transfer_operations_balance_delta_check
    check (
      (
        operation_type='transfer'
        and source_balance_after=source_balance_before-minutes
        and destination_balance_after=destination_balance_before+minutes
      )
      or
      (
        operation_type='reversal'
        and source_balance_after=source_balance_before+minutes
        and destination_balance_after=destination_balance_before-minutes
      )
    ),
  constraint credit_transfer_operations_reversal_shape_check
    check (
      (operation_type='transfer' and reverses_transfer_id is null)
      or
      (
        operation_type='reversal'
        and reverses_transfer_id is not null
        and reason is not null
        and char_length(btrim(reason)) between 1 and 500
      )
    ),
  constraint credit_transfer_operations_no_self_reversal_check
    check (reverses_transfer_id is null or reverses_transfer_id <> id)
);

create unique index credit_transfer_operations_request_key_uidx
  on public.credit_transfer_operations(request_key);

create unique index credit_transfer_operations_one_reversal_uidx
  on public.credit_transfer_operations(reverses_transfer_id)
  where reverses_transfer_id is not null;

create index credit_transfer_operations_source_idx
  on public.credit_transfer_operations(source_grant_id, created_at, id);

create index credit_transfer_operations_destination_idx
  on public.credit_transfer_operations(destination_grant_id, created_at, id);

comment on table public.credit_transfer_operations is
  'Append-only canonical transfer/reversal operation. request_key is the authoritative idempotency key and operation rows are immutable history.';

alter table public.credit_transfer_operations enable row level security;

revoke all on table public.credit_transfer_operations from public;
revoke all on table public.credit_transfer_operations from anon;
revoke all on table public.credit_transfer_operations from authenticated;
revoke all on table public.credit_transfer_operations from service_role;

alter table public.credit_movements
  add column transfer_id bigint;

alter table public.credit_movements
  add constraint credit_movements_transfer_id_fkey
  foreign key (transfer_id)
  references public.credit_transfer_operations(id)
  on delete restrict;

alter table public.credit_movements
  drop constraint credit_movements_movement_type_check;

alter table public.credit_movements
  add constraint credit_movements_movement_type_check
  check (
    movement_type in (
      'grant',
      'class',
      'adjustment',
      'refund',
      'transfer_out',
      'transfer_in'
    )
  );

alter table public.credit_movements
  add constraint credit_movements_transfer_link_shape_check
  check (
    (
      movement_type in ('transfer_out','transfer_in')
      and transfer_id is not null
    )
    or
    (
      movement_type not in ('transfer_out','transfer_in')
      and transfer_id is null
    )
  );

create unique index credit_movements_transfer_out_uidx
  on public.credit_movements(transfer_id)
  where movement_type='transfer_out';

create unique index credit_movements_transfer_in_uidx
  on public.credit_movements(transfer_id)
  where movement_type='transfer_in';

create index credit_movements_transfer_id_idx
  on public.credit_movements(transfer_id)
  where transfer_id is not null;

comment on column public.credit_movements.transfer_id is
  'Canonical transfer operation linkage. Required only for transfer_out/transfer_in movements.';

-- Transitional direct-DML compatibility remains open for non-transfer legacy writers,
-- but authenticated Staff can never mint canonical transfer ledger movements directly.
alter policy credit_movements_staff_insert
  on public.credit_movements
  with check (
    (select private.is_staff())
    and created_by = (select auth.uid())
    and source_operation_key is null
    and transfer_id is null
    and movement_type not in ('transfer_out','transfer_in')
  );

create or replace function private.credit_pair_transfer_pool_compatible_unchecked(
  p_grant_id bigint,
  p_economic_source_grant_id bigint,
  p_member_person_id_low bigint,
  p_member_person_id_high bigint,
  p_payment_status text,
  p_starts_at timestamptz,
  p_effective_expires_at timestamptz,
  p_paused boolean,
  p_at timestamptz default now()
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((
    select
      g.modality='pair'
      and g.price_cents=0
      and g.payment_status=p_payment_status
      and g.status in ('active','exhausted')
      and g.starts_at=p_starts_at
      and private.credit_grant_effective_expires_at_unchecked(g.id,p_at)
            is not distinct from p_effective_expires_at
      and private.credit_grant_is_paused_unchecked(g.id,p_at)=p_paused
      and tp.economic_source_grant_id=p_economic_source_grant_id
      and tp.member_person_id_low=p_member_person_id_low
      and tp.member_person_id_high=p_member_person_id_high
      and (
        select coalesce(array_agg(gm.person_id order by gm.person_id),'{}'::bigint[])
        from public.credit_grant_members gm
        where gm.grant_id=g.id
      ) = array[p_member_person_id_low,p_member_person_id_high]::bigint[]
      and not exists (
        select 1
        from public.credit_movements cm
        where cm.grant_id=g.id
          and cm.movement_type='grant'
      )
    from public.credit_pair_transfer_pools tp
    join public.credit_grants g on g.id=tp.destination_grant_id
    where tp.destination_grant_id=p_grant_id
  ),false);
$$;

alter function private.credit_pair_transfer_pool_compatible_unchecked(
  bigint,bigint,bigint,bigint,text,timestamptz,timestamptz,boolean,timestamptz
) owner to postgres;

revoke all on function private.credit_pair_transfer_pool_compatible_unchecked(
  bigint,bigint,bigint,bigint,text,timestamptz,timestamptz,boolean,timestamptz
) from public, anon, authenticated, service_role;

create or replace function private.credit_transfer_source_provenance_unchecked(
  p_grant_id bigint
)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((
    select jsonb_build_object(
      'source_grant_id',g.id,
      'price_cents',g.price_cents,
      'payment_status',g.payment_status,
      'purchased_at',g.purchased_at,
      'purchased_at_approximate',g.purchased_at_approximate,
      'historical_provenance',g.historical_provenance,
      'grant_movements',coalesce((
        select jsonb_agg(
          jsonb_build_object(
            'movement_id',cm.id,
            'occurred_at',cm.occurred_at,
            'note',cm.note,
            'provenance',cm.provenance
          )
          order by cm.occurred_at,cm.id
        )
        from public.credit_movements cm
        where cm.grant_id=g.id
          and cm.movement_type='grant'
      ),'[]'::jsonb)
    )
    from public.credit_grants g
    where g.id=p_grant_id
  ),'{}'::jsonb);
$$;

alter function private.credit_transfer_source_provenance_unchecked(bigint) owner to postgres;
revoke all on function private.credit_transfer_source_provenance_unchecked(bigint)
  from public, anon, authenticated, service_role;

create or replace function private.credit_transfer_result_unchecked(
  p_operation_id bigint,
  p_idempotent_replay boolean default false,
  p_reconciled boolean default false
)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'status','committed',
    'result','committed',
    'operation_id',op.id,
    'operation_type',op.operation_type,
    'transfer_id',case when op.operation_type='transfer' then op.id else op.reverses_transfer_id end,
    'reversal_id',case when op.operation_type='reversal' then op.id else null end,
    'request_key',op.request_key,
    'minutes',op.minutes,
    'class_id',op.class_id,
    'pair',jsonb_build_object(
      'source_person_id',op.source_person_id,
      'partner_person_id',op.partner_person_id,
      'member_person_ids',
        case
          when op.source_person_id < op.partner_person_id
            then jsonb_build_array(op.source_person_id,op.partner_person_id)
          else jsonb_build_array(op.partner_person_id,op.source_person_id)
        end
    ),
    'source',jsonb_build_object(
      'grant_id',op.source_grant_id,
      'balance_before',op.source_balance_before,
      'balance_after',op.source_balance_after,
      'payment_status',op.source_payment_status,
      'starts_at',op.source_starts_at,
      'effective_expires_at',op.source_effective_expires_at,
      'is_paused',op.source_was_paused
    ),
    'destination',jsonb_build_object(
      'grant_id',op.destination_grant_id,
      'balance_before',op.destination_balance_before,
      'balance_after',op.destination_balance_after,
      'transfer_derived',true
    ),
    'idempotent_replay',p_idempotent_replay,
    'reconciled',p_reconciled,
    'reconciliation',jsonb_build_object(
      'status','committed',
      'request_key',op.request_key,
      'retry_with_same_key',true,
      'blind_retry_with_new_key',false
    ),
    'created_at',op.created_at
  )
  from public.credit_transfer_operations op
  where op.id=p_operation_id;
$$;

alter function private.credit_transfer_result_unchecked(bigint,boolean,boolean) owner to postgres;
revoke all on function private.credit_transfer_result_unchecked(bigint,boolean,boolean)
  from public, anon, authenticated, service_role;

create or replace function private.reject_credit_transfer_history_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'Canonical credit transfer history is append-only.'
    using errcode='55000';
end;
$$;

alter function private.reject_credit_transfer_history_mutation() owner to postgres;
revoke all on function private.reject_credit_transfer_history_mutation()
  from public, anon, authenticated, service_role;

create trigger credit_transfer_operations_append_only
before update or delete on public.credit_transfer_operations
for each row execute function private.reject_credit_transfer_history_mutation();

create trigger credit_pair_transfer_pools_append_only
before update or delete on public.credit_pair_transfer_pools
for each row execute function private.reject_credit_transfer_history_mutation();

create trigger credit_transfer_movements_append_only
before update or delete on public.credit_movements
for each row
when (
  old.transfer_id is not null
  or old.movement_type in ('transfer_out','transfer_in')
)
execute function private.reject_credit_transfer_history_mutation();

create or replace function private.assert_credit_transfer_operation_balanced()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_out_count integer;
  v_in_count integer;
  v_out_sum integer;
  v_in_sum integer;
  v_minutes integer;
  v_operation_type text;
  v_reverses_transfer_id bigint;
  v_source_grant_id bigint;
  v_destination_grant_id bigint;
  v_source_balance_after integer;
  v_destination_balance_after integer;
  v_actual_source_balance integer;
  v_actual_destination_balance integer;
begin
  select
    op.minutes,
    op.operation_type,
    op.reverses_transfer_id,
    op.source_grant_id,
    op.destination_grant_id,
    op.source_balance_after,
    op.destination_balance_after
  into
    v_minutes,
    v_operation_type,
    v_reverses_transfer_id,
    v_source_grant_id,
    v_destination_grant_id,
    v_source_balance_after,
    v_destination_balance_after
  from public.credit_transfer_operations op
  where op.id=new.id;

  select
    count(*) filter (where cm.movement_type='transfer_out')::integer,
    count(*) filter (where cm.movement_type='transfer_in')::integer,
    coalesce(sum(cm.delta_minutes) filter (where cm.movement_type='transfer_out'),0)::integer,
    coalesce(sum(cm.delta_minutes) filter (where cm.movement_type='transfer_in'),0)::integer
  into v_out_count,v_in_count,v_out_sum,v_in_sum
  from public.credit_movements cm
  where cm.transfer_id=new.id;

  if v_out_count<>1
     or v_in_count<>1
     or v_out_sum<>-v_minutes
     or v_in_sum<>v_minutes
     or (v_out_sum+v_in_sum)<>0 then
    raise exception 'TRANSFER_LEDGER_INVARIANT_VIOLATION'
      using errcode='23514',
            detail='Each canonical transfer operation must commit exactly one transfer_out=-X and one transfer_in=+X.';
  end if;

  v_actual_source_balance :=
    private.credit_grant_balance_minutes_unchecked(v_source_grant_id);
  v_actual_destination_balance :=
    private.credit_grant_balance_minutes_unchecked(v_destination_grant_id);

  if v_actual_source_balance<>v_source_balance_after
     or v_actual_destination_balance<>v_destination_balance_after then
    raise exception 'TRANSFER_BALANCE_SNAPSHOT_INVARIANT_VIOLATION'
      using errcode='23514',
            detail='Committed ledger balances must equal the canonical operation after-snapshots.';
  end if;

  if v_operation_type='reversal' and not exists (
    select 1
    from public.credit_transfer_operations original
    where original.id=v_reverses_transfer_id
      and original.operation_type='transfer'
  ) then
    raise exception 'TRANSFER_REVERSAL_LINK_INVALID'
      using errcode='23514';
  end if;

  return null;
end;
$$;

alter function private.assert_credit_transfer_operation_balanced() owner to postgres;
revoke all on function private.assert_credit_transfer_operation_balanced()
  from public, anon, authenticated, service_role;

create constraint trigger credit_transfer_operation_balanced
after insert on public.credit_transfer_operations
deferrable initially deferred
for each row execute function private.assert_credit_transfer_operation_balanced();

create or replace function public.preview_individual_credit_to_pair_transfer(
  p_source_grant_id bigint,
  p_partner_person_id bigint,
  p_minutes integer,
  p_class_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_now timestamptz := now();
  v_source public.credit_grants%rowtype;
  v_source_person_id bigint;
  v_source_members bigint[];
  v_pair_low bigint;
  v_pair_high bigint;
  v_balance integer;
  v_effective_expires_at timestamptz;
  v_paused boolean;
  v_destination_id bigint;
  v_destination_balance integer := 0;
begin
  if not (select private.is_staff()) then
    raise exception 'No tienes permiso para transferir saldo de bonos.'
      using errcode='42501';
  end if;

  if p_source_grant_id is null or p_partner_person_id is null then
    raise exception 'Bono origen y segunda persona son obligatorios.'
      using errcode='22023';
  end if;
  if p_minutes is null or p_minutes<=0 then
    raise exception 'Los minutos deben ser mayores que cero.'
      using errcode='22023';
  end if;
  if p_class_id is not null
     and not exists (select 1 from public.classes c where c.id=p_class_id) then
    raise exception 'La clase indicada como contexto no existe.'
      using errcode='22023';
  end if;

  select * into v_source
  from public.credit_grants g
  where g.id=p_source_grant_id;

  if not found then
    raise exception 'El bono origen no existe.'
      using errcode='P0002';
  end if;
  if v_source.modality<>'individual'
     or v_source.status<>'active'
     or v_source.payment_status not in ('paid','pending') then
    raise exception 'El bono origen no admite esta transferencia.'
      using errcode='22023';
  end if;

  select coalesce(array_agg(gm.person_id order by gm.person_id),'{}'::bigint[])
  into v_source_members
  from public.credit_grant_members gm
  where gm.grant_id=v_source.id;

  if cardinality(v_source_members)<>1 then
    raise exception 'El bono individual debe tener exactamente una persona titular.'
      using errcode='23514';
  end if;

  v_source_person_id := v_source_members[1];

  if not exists (
    select 1 from public.people p
    where p.id=v_source_person_id and p.active
  ) then
    raise exception 'La persona titular del bono no está activa.'
      using errcode='22023';
  end if;

  if p_partner_person_id=v_source_person_id
     or not exists (
       select 1 from public.people p
       where p.id=p_partner_person_id and p.active
     ) then
    raise exception 'La segunda persona debe ser distinta y estar activa.'
      using errcode='22023';
  end if;

  v_balance := private.credit_grant_balance_minutes_unchecked(v_source.id);
  if v_balance<=0 or p_minutes>v_balance then
    raise exception 'No hay saldo suficiente para transferir esos minutos.'
      using errcode='22023';
  end if;

  v_effective_expires_at :=
    private.credit_grant_effective_expires_at_unchecked(v_source.id,v_now);
  v_paused := private.credit_grant_is_paused_unchecked(v_source.id,v_now);
  v_pair_low := least(v_source_person_id,p_partner_person_id);
  v_pair_high := greatest(v_source_person_id,p_partner_person_id);

  select g.id
  into v_destination_id
  from public.credit_pair_transfer_pools tp
  join public.credit_grants g on g.id=tp.destination_grant_id
  where tp.economic_source_grant_id=v_source.id
    and tp.member_person_id_low=v_pair_low
    and tp.member_person_id_high=v_pair_high
    and private.credit_pair_transfer_pool_compatible_unchecked(
      g.id,v_source.id,v_pair_low,v_pair_high,v_source.payment_status,
      v_source.starts_at,v_effective_expires_at,v_paused,v_now
    )
  order by g.id
  limit 1;

  if v_destination_id is not null then
    v_destination_balance :=
      private.credit_grant_balance_minutes_unchecked(v_destination_id);
    if v_destination_balance<0 then
      raise exception 'El pool de pareja compatible tiene un saldo inválido.'
        using errcode='23514';
    end if;
  end if;

  return jsonb_build_object(
    'status','preview',
    'authoritative_at',v_now,
    'confirmation_required',true,
    'minutes',p_minutes,
    'all_source_balance',p_minutes=v_balance,
    'class_id',p_class_id,
    'source',jsonb_build_object(
      'grant_id',v_source.id,
      'person_id',v_source_person_id,
      'balance_before',v_balance,
      'balance_after',v_balance-p_minutes,
      'payment_status',v_source.payment_status,
      'starts_at',v_source.starts_at,
      'effective_expires_at',v_effective_expires_at,
      'is_paused',v_paused
    ),
    'pair',jsonb_build_object(
      'source_person_id',v_source_person_id,
      'partner_person_id',p_partner_person_id,
      'member_person_ids',jsonb_build_array(v_pair_low,v_pair_high)
    ),
    'destination',jsonb_build_object(
      'grant_id',v_destination_id,
      'will_create_destination',v_destination_id is null,
      'transfer_derived',true,
      'balance_before',v_destination_balance,
      'balance_after',v_destination_balance+p_minutes,
      'payment_status',v_source.payment_status,
      'starts_at',v_source.starts_at,
      'effective_expires_at',v_effective_expires_at,
      'is_paused',v_paused
    )
  );
end;
$$;

alter function public.preview_individual_credit_to_pair_transfer(bigint,bigint,integer,bigint)
  owner to postgres;
revoke all on function public.preview_individual_credit_to_pair_transfer(bigint,bigint,integer,bigint)
  from public;
revoke execute on function public.preview_individual_credit_to_pair_transfer(bigint,bigint,integer,bigint)
  from anon;
grant execute on function public.preview_individual_credit_to_pair_transfer(bigint,bigint,integer,bigint)
  to authenticated;

create or replace function public.transfer_individual_credit_to_pair_v2(
  p_source_grant_id bigint,
  p_partner_person_id bigint,
  p_minutes integer,
  p_request_key text,
  p_class_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_now timestamptz := now();
  v_actor uuid := (select auth.uid());
  v_request_key text := nullif(btrim(p_request_key),'');
  v_existing public.credit_transfer_operations%rowtype;
  v_source public.credit_grants%rowtype;
  v_destination public.credit_grants%rowtype;
  v_source_members bigint[];
  v_source_person_id bigint;
  v_pair_low bigint;
  v_pair_high bigint;
  v_source_balance_before integer;
  v_source_balance_after integer;
  v_destination_balance_before integer := 0;
  v_destination_balance_after integer;
  v_effective_expires_at timestamptz;
  v_paused boolean;
  v_compatibility_key text;
  v_operation public.credit_transfer_operations%rowtype;
begin
  if not (select private.is_staff()) or v_actor is null then
    raise exception 'No tienes permiso para transferir saldo de bonos.'
      using errcode='42501';
  end if;

  if p_source_grant_id is null or p_partner_person_id is null then
    raise exception 'Bono origen y segunda persona son obligatorios.'
      using errcode='22023';
  end if;
  if p_minutes is null or p_minutes<=0 then
    raise exception 'Los minutos deben ser mayores que cero.'
      using errcode='22023';
  end if;
  if v_request_key is null or char_length(v_request_key)>200 then
    raise exception 'request_key debe contener entre 1 y 200 caracteres.'
      using errcode='22023';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('cya:bonus-pair-transfer:request:'||v_request_key,0)
  );

  select * into v_existing
  from public.credit_transfer_operations op
  where op.request_key=v_request_key;

  if found then
    if v_existing.operation_type='transfer'
       and v_existing.source_grant_id=p_source_grant_id
       and v_existing.partner_person_id=p_partner_person_id
       and v_existing.minutes=p_minutes
       and v_existing.class_id is not distinct from p_class_id
       and v_existing.actor_user_id=v_actor then
      return private.credit_transfer_result_unchecked(v_existing.id,true,false);
    end if;

    raise exception 'IDEMPOTENCY_CONFLICT'
      using errcode='23505',
            detail='request_key already belongs to a different canonical transfer request.';
  end if;

  if p_class_id is not null
     and not exists (select 1 from public.classes c where c.id=p_class_id) then
    raise exception 'La clase indicada como contexto no existe.'
      using errcode='22023';
  end if;

  select * into v_source
  from public.credit_grants g
  where g.id=p_source_grant_id
  for update;

  if not found then
    raise exception 'El bono origen no existe.'
      using errcode='P0002';
  end if;
  if v_source.modality<>'individual'
     or v_source.status<>'active'
     or v_source.payment_status not in ('paid','pending') then
    raise exception 'El bono origen no admite esta transferencia.'
      using errcode='22023';
  end if;

  select coalesce(array_agg(gm.person_id order by gm.person_id),'{}'::bigint[])
  into v_source_members
  from public.credit_grant_members gm
  where gm.grant_id=v_source.id;

  if cardinality(v_source_members)<>1 then
    raise exception 'El bono individual debe tener exactamente una persona titular.'
      using errcode='23514';
  end if;

  v_source_person_id := v_source_members[1];

  if not exists (
    select 1 from public.people p
    where p.id=v_source_person_id and p.active
  ) then
    raise exception 'La persona titular del bono no está activa.'
      using errcode='22023';
  end if;

  if p_partner_person_id=v_source_person_id
     or not exists (
       select 1 from public.people p
       where p.id=p_partner_person_id and p.active
     ) then
    raise exception 'La segunda persona debe ser distinta y estar activa.'
      using errcode='22023';
  end if;

  v_source_balance_before :=
    private.credit_grant_balance_minutes_unchecked(v_source.id);
  if v_source_balance_before<=0 or p_minutes>v_source_balance_before then
    raise exception 'No hay saldo suficiente para transferir esos minutos.'
      using errcode='22023';
  end if;

  v_source_balance_after := v_source_balance_before-p_minutes;
  v_effective_expires_at :=
    private.credit_grant_effective_expires_at_unchecked(v_source.id,v_now);
  v_paused := private.credit_grant_is_paused_unchecked(v_source.id,v_now);
  v_pair_low := least(v_source_person_id,p_partner_person_id);
  v_pair_high := greatest(v_source_person_id,p_partner_person_id);

  v_compatibility_key := jsonb_build_array(
    v_source.id,
    v_pair_low,
    v_pair_high,
    v_source.payment_status,
    v_source.starts_at,
    v_effective_expires_at,
    v_paused
  )::text;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('cya:bonus-pair-transfer:pool:'||v_compatibility_key,0)
  );

  select g.* into v_destination
  from public.credit_pair_transfer_pools tp
  join public.credit_grants g on g.id=tp.destination_grant_id
  where tp.economic_source_grant_id=v_source.id
    and tp.member_person_id_low=v_pair_low
    and tp.member_person_id_high=v_pair_high
    and private.credit_pair_transfer_pool_compatible_unchecked(
      g.id,v_source.id,v_pair_low,v_pair_high,v_source.payment_status,
      v_source.starts_at,v_effective_expires_at,v_paused,v_now
    )
  order by g.id
  limit 1
  for update of g;

  if found then
    v_destination_balance_before :=
      private.credit_grant_balance_minutes_unchecked(v_destination.id);
    if v_destination_balance_before<0 then
      raise exception 'El pool de pareja compatible tiene un saldo inválido.'
        using errcode='23514';
    end if;

    update public.credit_grants
    set total_minutes=total_minutes+p_minutes,
        status='active',
        updated_at=v_now
    where id=v_destination.id
    returning * into v_destination;
  else
    insert into public.credit_grants(
      modality,
      label,
      total_minutes,
      price_cents,
      payment_status,
      status,
      purchased_at,
      expires_at,
      created_by,
      starts_at,
      purchased_at_approximate,
      historical_provenance
    )
    values(
      'pair',
      'Transferencia individual a pareja',
      p_minutes,
      0,
      v_source.payment_status,
      'active',
      v_source.purchased_at,
      v_effective_expires_at,
      v_actor,
      v_source.starts_at,
      v_source.purchased_at_approximate,
      null
    )
    returning * into v_destination;

    insert into public.credit_grant_members(grant_id,person_id)
    values
      (v_destination.id,v_pair_low),
      (v_destination.id,v_pair_high);

    insert into public.credit_pair_transfer_pools(
      destination_grant_id,
      economic_source_grant_id,
      member_person_id_low,
      member_person_id_high,
      created_by
    )
    values(
      v_destination.id,
      v_source.id,
      v_pair_low,
      v_pair_high,
      v_actor
    );

    if v_paused then
      insert into public.credit_grant_pause_periods(
        grant_id,
        paused_at,
        pause_reason,
        paused_by
      )
      values(
        v_destination.id,
        v_now,
        'Transferencia: pausa heredada del bono origen',
        v_actor
      );
    end if;

    v_destination_balance_before := 0;
  end if;

  v_destination_balance_after := v_destination_balance_before+p_minutes;

  insert into public.credit_transfer_operations(
    operation_type,
    request_key,
    source_grant_id,
    destination_grant_id,
    source_person_id,
    partner_person_id,
    minutes,
    class_id,
    source_payment_status,
    source_starts_at,
    source_effective_expires_at,
    source_was_paused,
    source_provenance,
    source_balance_before,
    source_balance_after,
    destination_balance_before,
    destination_balance_after,
    actor_user_id
  )
  values(
    'transfer',
    v_request_key,
    v_source.id,
    v_destination.id,
    v_source_person_id,
    p_partner_person_id,
    p_minutes,
    p_class_id,
    v_source.payment_status,
    v_source.starts_at,
    v_effective_expires_at,
    v_paused,
    private.credit_transfer_source_provenance_unchecked(v_source.id),
    v_source_balance_before,
    v_source_balance_after,
    v_destination_balance_before,
    v_destination_balance_after,
    v_actor
  )
  returning * into v_operation;

  insert into public.credit_movements(
    grant_id,
    person_id,
    class_id,
    movement_type,
    delta_minutes,
    note,
    created_by,
    occurred_at,
    date_approximate,
    provenance,
    source_operation_key,
    transfer_id
  )
  values(
    v_source.id,
    v_source_person_id,
    p_class_id,
    'transfer_out',
    -p_minutes,
    'Transferencia canónica a bono de pareja',
    v_actor,
    v_now,
    false,
    jsonb_build_object(
      'authority','BONUS-INDIVIDUAL-TO-PAIR-TRANSFER-01',
      'operation','individual_to_pair_transfer',
      'direction','out',
      'request_key',v_request_key,
      'transfer_id',v_operation.id,
      'source_grant_id',v_source.id,
      'destination_grant_id',v_destination.id
    ),
    'pair-transfer:'||v_request_key||':out',
    v_operation.id
  );

  insert into public.credit_movements(
    grant_id,
    person_id,
    class_id,
    movement_type,
    delta_minutes,
    note,
    created_by,
    occurred_at,
    date_approximate,
    provenance,
    source_operation_key,
    transfer_id
  )
  values(
    v_destination.id,
    null,
    p_class_id,
    'transfer_in',
    p_minutes,
    'Transferencia canónica desde bono individual',
    v_actor,
    v_now,
    false,
    jsonb_build_object(
      'authority','BONUS-INDIVIDUAL-TO-PAIR-TRANSFER-01',
      'operation','individual_to_pair_transfer',
      'direction','in',
      'request_key',v_request_key,
      'transfer_id',v_operation.id,
      'source_grant_id',v_source.id,
      'destination_grant_id',v_destination.id,
      'economic_provenance',private.credit_transfer_source_provenance_unchecked(v_source.id)
    ),
    'pair-transfer:'||v_request_key||':in',
    v_operation.id
  );

  if v_source_balance_after=0 then
    update public.credit_grants
    set status='exhausted',
        updated_at=v_now
    where id=v_source.id
      and status='active';
  end if;

  insert into public.audit_events(
    event_type,
    entity_type,
    entity_id,
    summary,
    detail,
    actor_user_id
  )
  values(
    'credit_individual_to_pair_transferred',
    'credit_transfer',
    v_operation.id::text,
    'Saldo individual transferido a bono de pareja',
    jsonb_build_object(
      'transfer_id',v_operation.id,
      'request_key',v_request_key,
      'source_grant_id',v_source.id,
      'destination_grant_id',v_destination.id,
      'source_person_id',v_source_person_id,
      'partner_person_id',p_partner_person_id,
      'minutes',p_minutes,
      'class_id',p_class_id,
      'source_balance_before',v_source_balance_before,
      'source_balance_after',v_source_balance_after,
      'destination_balance_before',v_destination_balance_before,
      'destination_balance_after',v_destination_balance_after,
      'payment_status',v_source.payment_status,
      'starts_at',v_source.starts_at,
      'effective_expires_at',v_effective_expires_at,
      'paused',v_paused,
      'revenue_created_cents',0,
      'debt_created_cents',0
    ),
    v_actor
  );

  return private.credit_transfer_result_unchecked(v_operation.id,false,false);
end;
$$;

alter function public.transfer_individual_credit_to_pair_v2(bigint,bigint,integer,text,bigint)
  owner to postgres;
revoke all on function public.transfer_individual_credit_to_pair_v2(bigint,bigint,integer,text,bigint)
  from public;
revoke execute on function public.transfer_individual_credit_to_pair_v2(bigint,bigint,integer,text,bigint)
  from anon;
grant execute on function public.transfer_individual_credit_to_pair_v2(bigint,bigint,integer,text,bigint)
  to authenticated;

create or replace function public.reconcile_individual_credit_to_pair_transfer(
  p_request_key text
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_request_key text := nullif(btrim(p_request_key),'');
  v_operation public.credit_transfer_operations%rowtype;
begin
  if not (select private.is_staff()) then
    raise exception 'No tienes permiso para reconciliar transferencias.'
      using errcode='42501';
  end if;
  if v_request_key is null or char_length(v_request_key)>200 then
    raise exception 'request_key debe contener entre 1 y 200 caracteres.'
      using errcode='22023';
  end if;

  select * into v_operation
  from public.credit_transfer_operations op
  where op.request_key=v_request_key;

  if not found then
    return jsonb_build_object(
      'status','not_found',
      'result','not_found',
      'request_key',v_request_key,
      'reconciliation',jsonb_build_object(
        'status','not_found',
        'safe_to_assume_committed',false,
        'retry_with_same_key',true,
        'blind_retry_with_new_key',false
      )
    );
  end if;

  return private.credit_transfer_result_unchecked(v_operation.id,false,true);
end;
$$;

alter function public.reconcile_individual_credit_to_pair_transfer(text) owner to postgres;
revoke all on function public.reconcile_individual_credit_to_pair_transfer(text) from public;
revoke execute on function public.reconcile_individual_credit_to_pair_transfer(text) from anon;
grant execute on function public.reconcile_individual_credit_to_pair_transfer(text) to authenticated;

create or replace function public.reverse_individual_credit_to_pair_transfer(
  p_transfer_id bigint,
  p_request_key text,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_now timestamptz := now();
  v_actor uuid := (select auth.uid());
  v_request_key text := nullif(btrim(p_request_key),'');
  v_reason text := nullif(btrim(p_reason),'');
  v_existing public.credit_transfer_operations%rowtype;
  v_original public.credit_transfer_operations%rowtype;
  v_source public.credit_grants%rowtype;
  v_destination public.credit_grants%rowtype;
  v_original_out public.credit_movements%rowtype;
  v_original_in public.credit_movements%rowtype;
  v_source_members bigint[];
  v_pair_low bigint;
  v_pair_high bigint;
  v_source_effective_expires_at timestamptz;
  v_source_paused boolean;
  v_source_balance_before integer;
  v_source_balance_after integer;
  v_destination_balance_before integer;
  v_destination_balance_after integer;
  v_operation public.credit_transfer_operations%rowtype;
begin
  if not (select private.is_staff()) or v_actor is null then
    raise exception 'No tienes permiso para revertir transferencias.'
      using errcode='42501';
  end if;
  if p_transfer_id is null then
    raise exception 'transfer_id es obligatorio.'
      using errcode='22023';
  end if;
  if v_request_key is null or char_length(v_request_key)>200 then
    raise exception 'request_key debe contener entre 1 y 200 caracteres.'
      using errcode='22023';
  end if;
  if v_reason is null or char_length(v_reason)>500 then
    raise exception 'La reversión requiere un motivo de entre 1 y 500 caracteres.'
      using errcode='22023';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('cya:bonus-pair-transfer:request:'||v_request_key,0)
  );

  select * into v_existing
  from public.credit_transfer_operations op
  where op.request_key=v_request_key;

  if found then
    if v_existing.operation_type='reversal'
       and v_existing.reverses_transfer_id=p_transfer_id
       and v_existing.reason=v_reason
       and v_existing.actor_user_id=v_actor then
      return private.credit_transfer_result_unchecked(v_existing.id,true,false);
    end if;

    raise exception 'IDEMPOTENCY_CONFLICT'
      using errcode='23505',
            detail='request_key already belongs to a different canonical reversal request.';
  end if;

  select * into v_original
  from public.credit_transfer_operations op
  where op.id=p_transfer_id
    and op.operation_type='transfer';

  if not found then
    raise exception 'La transferencia original no existe.'
      using errcode='P0002';
  end if;

  if exists (
    select 1
    from public.credit_transfer_operations op
    where op.reverses_transfer_id=v_original.id
  ) then
    raise exception 'TRANSFER_ALREADY_REVERSED'
      using errcode='23505';
  end if;

  -- Lock order matches forward semantics: original individual source first,
  -- then transfer-derived pair destination.
  select * into v_source
  from public.credit_grants g
  where g.id=v_original.source_grant_id
  for update;

  select * into v_destination
  from public.credit_grants g
  where g.id=v_original.destination_grant_id
  for update;

  if v_source.id is null or v_destination.id is null then
    raise exception 'TRANSFER_REVERSAL_REQUIRES_ADMIN_CORRECTION'
      using errcode='55000',
            detail='Source or destination grant is no longer available.';
  end if;

  if v_source.modality<>'individual'
     or v_source.status='cancelled'
     or v_source.payment_status not in ('paid','pending') then
    raise exception 'TRANSFER_REVERSAL_REQUIRES_ADMIN_CORRECTION'
      using errcode='55000',
            detail='Source grant semantics no longer permit an ordinary reversal.';
  end if;

  select coalesce(array_agg(gm.person_id order by gm.person_id),'{}'::bigint[])
  into v_source_members
  from public.credit_grant_members gm
  where gm.grant_id=v_source.id;

  if v_source_members<>array[v_original.source_person_id]::bigint[] then
    raise exception 'TRANSFER_REVERSAL_REQUIRES_ADMIN_CORRECTION'
      using errcode='55000',
            detail='Source membership changed after the transfer.';
  end if;

  v_pair_low := least(v_original.source_person_id,v_original.partner_person_id);
  v_pair_high := greatest(v_original.source_person_id,v_original.partner_person_id);
  v_source_effective_expires_at :=
    private.credit_grant_effective_expires_at_unchecked(v_source.id,v_now);
  v_source_paused := private.credit_grant_is_paused_unchecked(v_source.id,v_now);

  if not private.credit_pair_transfer_pool_compatible_unchecked(
    v_destination.id,
    v_source.id,
    v_pair_low,
    v_pair_high,
    v_source.payment_status,
    v_source.starts_at,
    v_source_effective_expires_at,
    v_source_paused,
    v_now
  ) then
    raise exception 'TRANSFER_REVERSAL_REQUIRES_ADMIN_CORRECTION'
      using errcode='55000',
            detail='Destination semantics diverged from the source after the transfer.';
  end if;

  select * into v_original_out
  from public.credit_movements cm
  where cm.transfer_id=v_original.id
    and cm.movement_type='transfer_out';

  select * into v_original_in
  from public.credit_movements cm
  where cm.transfer_id=v_original.id
    and cm.movement_type='transfer_in';

  if v_original_out.id is null or v_original_in.id is null then
    raise exception 'TRANSFER_REVERSAL_REQUIRES_ADMIN_CORRECTION'
      using errcode='55000',
            detail='Canonical transfer movements are incomplete.';
  end if;

  if exists (
    select 1
    from public.credit_movements cm
    where cm.grant_id=v_destination.id
      and cm.delta_minutes<0
      and (
        cm.occurred_at>v_original_in.occurred_at
        or (cm.occurred_at=v_original_in.occurred_at and cm.id>v_original_in.id)
      )
      and not (
        cm.movement_type='transfer_out'
        and cm.transfer_id is not null
        and cm.reverses_movement_id is not null
        and exists (
          select 1
          from public.credit_transfer_operations reversal_op
          join public.credit_transfer_operations reversed_transfer
            on reversed_transfer.id=reversal_op.reverses_transfer_id
           and reversed_transfer.operation_type='transfer'
          join public.credit_movements reversed_in
            on reversed_in.id=cm.reverses_movement_id
           and reversed_in.transfer_id=reversed_transfer.id
           and reversed_in.movement_type='transfer_in'
           and reversed_in.grant_id=v_destination.id
          where reversal_op.id=cm.transfer_id
            and reversal_op.operation_type='reversal'
            and reversal_op.destination_grant_id=v_destination.id
            and reversed_transfer.destination_grant_id=v_destination.id
            and reversal_op.source_grant_id=reversed_transfer.source_grant_id
            and reversal_op.source_person_id=reversed_transfer.source_person_id
            and reversal_op.partner_person_id=reversed_transfer.partner_person_id
            and reversal_op.minutes=reversed_transfer.minutes
            and cm.delta_minutes=-reversal_op.minutes
            and reversed_in.delta_minutes=reversal_op.minutes
        )
      )
  ) then
    raise exception 'TRANSFER_REVERSAL_REQUIRES_ADMIN_CORRECTION'
      using errcode='55000',
            detail='Destination balance has subsequent incompatible negative use; ordinary reversal is unsafe.';
  end if;

  v_source_balance_before :=
    private.credit_grant_balance_minutes_unchecked(v_source.id);
  v_destination_balance_before :=
    private.credit_grant_balance_minutes_unchecked(v_destination.id);

  if v_source_balance_before<0
     or v_destination_balance_before<v_original.minutes then
    raise exception 'TRANSFER_REVERSAL_REQUIRES_ADMIN_CORRECTION'
      using errcode='55000',
            detail='Current balances do not permit an ordinary reversal.';
  end if;

  v_source_balance_after := v_source_balance_before+v_original.minutes;
  v_destination_balance_after := v_destination_balance_before-v_original.minutes;

  insert into public.credit_transfer_operations(
    operation_type,
    request_key,
    source_grant_id,
    destination_grant_id,
    source_person_id,
    partner_person_id,
    minutes,
    class_id,
    source_payment_status,
    source_starts_at,
    source_effective_expires_at,
    source_was_paused,
    source_provenance,
    source_balance_before,
    source_balance_after,
    destination_balance_before,
    destination_balance_after,
    actor_user_id,
    reason,
    reverses_transfer_id
  )
  values(
    'reversal',
    v_request_key,
    v_original.source_grant_id,
    v_original.destination_grant_id,
    v_original.source_person_id,
    v_original.partner_person_id,
    v_original.minutes,
    v_original.class_id,
    v_source.payment_status,
    v_source.starts_at,
    v_source_effective_expires_at,
    v_source_paused,
    v_original.source_provenance,
    v_source_balance_before,
    v_source_balance_after,
    v_destination_balance_before,
    v_destination_balance_after,
    v_actor,
    v_reason,
    v_original.id
  )
  returning * into v_operation;

  insert into public.credit_movements(
    grant_id,
    person_id,
    class_id,
    movement_type,
    delta_minutes,
    note,
    created_by,
    occurred_at,
    date_approximate,
    reverses_movement_id,
    provenance,
    source_operation_key,
    transfer_id
  )
  values(
    v_destination.id,
    null,
    v_original.class_id,
    'transfer_out',
    -v_original.minutes,
    'Reversión canónica de transferencia individual a pareja',
    v_actor,
    v_now,
    false,
    v_original_in.id,
    jsonb_build_object(
      'authority','BONUS-INDIVIDUAL-TO-PAIR-TRANSFER-01',
      'operation','individual_to_pair_transfer_reversal',
      'direction','out',
      'request_key',v_request_key,
      'transfer_id',v_operation.id,
      'reverses_transfer_id',v_original.id,
      'reason',v_reason
    ),
    'pair-transfer-reversal:'||v_request_key||':out',
    v_operation.id
  );

  insert into public.credit_movements(
    grant_id,
    person_id,
    class_id,
    movement_type,
    delta_minutes,
    note,
    created_by,
    occurred_at,
    date_approximate,
    reverses_movement_id,
    provenance,
    source_operation_key,
    transfer_id
  )
  values(
    v_source.id,
    v_original.source_person_id,
    v_original.class_id,
    'transfer_in',
    v_original.minutes,
    'Reversión canónica de transferencia individual a pareja',
    v_actor,
    v_now,
    false,
    v_original_out.id,
    jsonb_build_object(
      'authority','BONUS-INDIVIDUAL-TO-PAIR-TRANSFER-01',
      'operation','individual_to_pair_transfer_reversal',
      'direction','in',
      'request_key',v_request_key,
      'transfer_id',v_operation.id,
      'reverses_transfer_id',v_original.id,
      'reason',v_reason
    ),
    'pair-transfer-reversal:'||v_request_key||':in',
    v_operation.id
  );

  if v_source_balance_after>0 and v_source.status='exhausted' then
    update public.credit_grants
    set status='active',
        updated_at=v_now
    where id=v_source.id
      and status='exhausted';
  end if;

  if v_destination_balance_after=0 then
    update public.credit_grants
    set status='exhausted',
        updated_at=v_now
    where id=v_destination.id
      and status='active';
  elsif v_destination.status='exhausted' then
    update public.credit_grants
    set status='active',
        updated_at=v_now
    where id=v_destination.id
      and status='exhausted';
  end if;

  insert into public.audit_events(
    event_type,
    entity_type,
    entity_id,
    summary,
    detail,
    actor_user_id
  )
  values(
    'credit_individual_to_pair_transfer_reversed',
    'credit_transfer',
    v_operation.id::text,
    'Transferencia individual a pareja revertida',
    jsonb_build_object(
      'reversal_id',v_operation.id,
      'reverses_transfer_id',v_original.id,
      'request_key',v_request_key,
      'source_grant_id',v_source.id,
      'destination_grant_id',v_destination.id,
      'minutes',v_original.minutes,
      'reason',v_reason,
      'source_balance_before',v_source_balance_before,
      'source_balance_after',v_source_balance_after,
      'destination_balance_before',v_destination_balance_before,
      'destination_balance_after',v_destination_balance_after,
      'revenue_created_cents',0,
      'debt_created_cents',0
    ),
    v_actor
  );

  return private.credit_transfer_result_unchecked(v_operation.id,false,false);
end;
$$;

alter function public.reverse_individual_credit_to_pair_transfer(bigint,text,text)
  owner to postgres;
revoke all on function public.reverse_individual_credit_to_pair_transfer(bigint,text,text)
  from public;
revoke execute on function public.reverse_individual_credit_to_pair_transfer(bigint,text,text)
  from anon;
grant execute on function public.reverse_individual_credit_to_pair_transfer(bigint,text,text)
  to authenticated;

-- New public functions are deliberately not executable by PUBLIC/anon/service_role.
-- The authenticated role reaches a SECURITY DEFINER boundary that still performs
-- the canonical private.is_staff() authorization using auth.uid().
revoke execute on function public.preview_individual_credit_to_pair_transfer(bigint,bigint,integer,bigint)
  from service_role;
revoke execute on function public.transfer_individual_credit_to_pair_v2(bigint,bigint,integer,text,bigint)
  from service_role;
revoke execute on function public.reconcile_individual_credit_to_pair_transfer(text)
  from service_role;
revoke execute on function public.reverse_individual_credit_to_pair_transfer(bigint,text,text)
  from service_role;

-- Legacy public.transfer_individual_credit_to_pair(...) is intentionally untouched here.
-- It must be disabled only in the later single caller cutover that activates the new route.
