-- BONUS-USABILITY-01 — canonical Billing predicates and audited bonus lifecycle.
-- STAGING authoring candidate only. Recovery: forward-fix.

-- -----------------------------------------------------------------------------
-- 1. Canonical grant dates + historical metadata
-- -----------------------------------------------------------------------------
alter table public.credit_grants
  add column if not exists starts_at timestamptz,
  add column if not exists purchased_at_approximate boolean not null default false,
  add column if not exists historical_provenance text;

update public.credit_grants
set starts_at = purchased_at
where starts_at is null;

alter table public.credit_grants
  alter column starts_at set default now(),
  alter column starts_at set not null;

alter table public.credit_grants
  drop constraint if exists credit_grants_expires_after_starts_at_check;

alter table public.credit_grants
  add constraint credit_grants_expires_after_starts_at_check
  check (expires_at is null or expires_at > starts_at);

create index if not exists credit_grants_starts_at_idx
  on public.credit_grants(starts_at);

create index if not exists credit_grants_usable_scan_idx
  on public.credit_grants(status, payment_status, starts_at, expires_at, id);

-- Billing membership is a relation to the canonical person, not to a lifecycle/profile row.
alter table public.credit_grant_members
  drop constraint if exists credit_grant_members_person_id_fkey;

alter table public.credit_grant_members
  add constraint credit_grant_members_person_id_fkey
  foreign key (person_id) references public.people(id) on delete cascade;

alter table public.credit_movements
  drop constraint if exists credit_movements_person_id_fkey;

alter table public.credit_movements
  add constraint credit_movements_person_id_fkey
  foreign key (person_id) references public.people(id) on delete set null;

-- Bonus membership must no longer mutate Personas lifecycle/CRM state.
drop trigger if exists credit_members_promote_crm_student on public.credit_grant_members;

-- -----------------------------------------------------------------------------
-- 2. Append-only movement provenance for historical facts/corrections
-- -----------------------------------------------------------------------------
alter table public.credit_movements
  add column if not exists occurred_at timestamptz,
  add column if not exists date_approximate boolean not null default false,
  add column if not exists reverses_movement_id bigint,
  add column if not exists provenance jsonb not null default '{}'::jsonb;

update public.credit_movements
set occurred_at = created_at
where occurred_at is null;

alter table public.credit_movements
  alter column occurred_at set default now(),
  alter column occurred_at set not null;

alter table public.credit_movements
  drop constraint if exists credit_movements_reverses_movement_id_fkey;

alter table public.credit_movements
  add constraint credit_movements_reverses_movement_id_fkey
  foreign key (reverses_movement_id) references public.credit_movements(id) on delete restrict;

alter table public.credit_movements
  drop constraint if exists credit_movements_no_self_reversal_check;

alter table public.credit_movements
  add constraint credit_movements_no_self_reversal_check
  check (reverses_movement_id is null or reverses_movement_id <> id);

create index if not exists credit_movements_grant_occurred_idx
  on public.credit_movements(grant_id, occurred_at, id);

create index if not exists credit_movements_reversal_idx
  on public.credit_movements(reverses_movement_id)
  where reverses_movement_id is not null;

-- -----------------------------------------------------------------------------
-- 3. Auditable pause history + temporary historical-import gate
-- -----------------------------------------------------------------------------
create table if not exists public.credit_grant_pause_periods (
  id bigint generated by default as identity primary key,
  grant_id bigint not null references public.credit_grants(id) on delete cascade,
  paused_at timestamptz not null,
  resumed_at timestamptz,
  pause_reason text not null,
  resume_reason text,
  paused_by uuid references auth.users(id) on delete set null,
  resumed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint credit_grant_pause_periods_interval_check
    check (resumed_at is null or resumed_at > paused_at),
  constraint credit_grant_pause_periods_pause_reason_check
    check (char_length(btrim(pause_reason)) between 1 and 500),
  constraint credit_grant_pause_periods_resume_reason_check
    check (resume_reason is null or char_length(btrim(resume_reason)) between 1 and 500)
);

create unique index if not exists credit_grant_pause_periods_one_open_idx
  on public.credit_grant_pause_periods(grant_id)
  where resumed_at is null;

create index if not exists credit_grant_pause_periods_lookup_idx
  on public.credit_grant_pause_periods(grant_id, paused_at, resumed_at);

alter table public.credit_grant_pause_periods enable row level security;

create table if not exists public.billing_admin_settings (
  singleton boolean primary key default true,
  allow_historical_bonus_import boolean not null default false,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  constraint billing_admin_settings_singleton_check check (singleton)
);

insert into public.billing_admin_settings(singleton, allow_historical_bonus_import)
values (true, false)
on conflict (singleton) do nothing;

alter table public.billing_admin_settings enable row level security;

-- No direct client write surface for the new control tables.
revoke all on public.credit_grant_pause_periods from public, anon, authenticated;
revoke all on public.billing_admin_settings from public, anon, authenticated;

-- -----------------------------------------------------------------------------
-- 4. Canonical private Billing helpers
-- -----------------------------------------------------------------------------
create or replace function private.billing_is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select private.has_app_role('admin'))
      or (select private.has_app_role('teacher_admin'));
$$;

create or replace function private.credit_grant_balance_minutes_unchecked(p_grant_id bigint)
returns integer
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(sum(m.delta_minutes), 0)::integer
  from public.credit_movements m
  where m.grant_id = p_grant_id;
$$;

create or replace function private.credit_grant_is_paused_unchecked(
  p_grant_id bigint,
  p_at timestamptz default now()
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(
    select 1
    from public.credit_grant_pause_periods pp
    where pp.grant_id = p_grant_id
      and pp.paused_at <= p_at
      and (pp.resumed_at is null or pp.resumed_at > p_at)
  );
$$;

create or replace function private.credit_grant_effective_expires_at_unchecked(
  p_grant_id bigint,
  p_at timestamptz default now()
)
returns timestamptz
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_expiry timestamptz;
  v_pause record;
  v_pause_end timestamptz;
begin
  select g.expires_at into v_expiry
  from public.credit_grants g
  where g.id = p_grant_id;

  if not found or v_expiry is null then
    return v_expiry;
  end if;

  -- Process pauses chronologically. A pause only extends validity when it
  -- actually began before the then-current effective expiry; malformed or
  -- privileged data recorded after expiry must never resurrect entitlement.
  for v_pause in
    select pp.paused_at, pp.resumed_at
    from public.credit_grant_pause_periods pp
    where pp.grant_id = p_grant_id
      and pp.paused_at < p_at
    order by pp.paused_at, pp.id
  loop
    if v_pause.paused_at >= v_expiry then
      continue;
    end if;

    v_pause_end := least(coalesce(v_pause.resumed_at, p_at), p_at);
    if v_pause_end > v_pause.paused_at then
      v_expiry := v_expiry + (v_pause_end - v_pause.paused_at);
    end if;
  end loop;

  return v_expiry;
end;
$$;

create or replace function private.credit_grant_is_usable_unchecked(
  p_grant_id bigint,
  p_at timestamptz default now()
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((
    select g.status = 'active'
       and g.payment_status in ('paid','pending')
       and g.starts_at <= p_at
       and not private.credit_grant_is_paused_unchecked(g.id, p_at)
       and (
         private.credit_grant_effective_expires_at_unchecked(g.id, p_at) is null
         or private.credit_grant_effective_expires_at_unchecked(g.id, p_at) > p_at
       )
       and private.credit_grant_balance_minutes_unchecked(g.id) > 0
    from public.credit_grants g
    where g.id = p_grant_id
  ), false);
$$;

create or replace function private.person_has_usable_presential_bonus_unchecked(
  p_person_id bigint,
  p_at timestamptz default now()
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(
    select 1
    from public.credit_grant_members gm
    where gm.person_id = p_person_id
      and private.credit_grant_is_usable_unchecked(gm.grant_id, p_at)
  );
$$;

create or replace function private.person_has_qualifying_presential_billing_intent_unchecked(
  p_person_id bigint,
  p_at timestamptz default now()
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(
    select 1
    from public.credit_grant_members gm
    join public.credit_grants g on g.id = gm.grant_id
    where gm.person_id = p_person_id
      and g.status = 'active'
      and g.payment_status in ('paid','pending')
      and private.credit_grant_balance_minutes_unchecked(g.id) > 0
      and (
        private.credit_grant_effective_expires_at_unchecked(g.id, p_at) is null
        or private.credit_grant_effective_expires_at_unchecked(g.id, p_at) > p_at
      )
  );
$$;

revoke all on function private.billing_is_admin() from public, anon, authenticated;
revoke all on function private.credit_grant_balance_minutes_unchecked(bigint) from public, anon, authenticated;
revoke all on function private.credit_grant_is_paused_unchecked(bigint,timestamptz) from public, anon, authenticated;
revoke all on function private.credit_grant_effective_expires_at_unchecked(bigint,timestamptz) from public, anon, authenticated;
revoke all on function private.credit_grant_is_usable_unchecked(bigint,timestamptz) from public, anon, authenticated;
revoke all on function private.person_has_usable_presential_bonus_unchecked(bigint,timestamptz) from public, anon, authenticated;
revoke all on function private.person_has_qualifying_presential_billing_intent_unchecked(bigint,timestamptz) from public, anon, authenticated;

-- A total refund is terminal, not an "exhausted by use" event. Preserve the
-- existing credit notification producer while preventing a false exhausted notice.
create or replace function private.aud017_notify_student_credit_balance()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_balance integer;
  v_row record;
  v_event text;
  v_title text;
  v_body text;
begin
  if new.movement_type='refund' then return new; end if;
  select coalesce(sum(delta_minutes),0)::integer into v_balance
  from public.credit_movements where grant_id=new.grant_id;
  if v_balance<=0 then
    v_event:='student.credit.exhausted'; v_title:='Tu bono se ha agotado'; v_body:='Ya no quedan minutos disponibles en este bono.';
  elsif v_balance<=60 then
    v_event:='student.credit.low'; v_title:='Te queda poco saldo'; v_body:='Te quedan '||v_balance::text||' minutos disponibles en este bono.';
  else
    return new;
  end if;
  for v_row in
    select distinct p.id as person_id,p.auth_user_id
    from public.credit_grant_members gm
    join public.people p on p.id=gm.person_id
    where gm.grant_id=new.grant_id and p.active and p.auth_user_id is not null
  loop
    perform private.enqueue_notification(
      v_event,v_row.auth_user_id,v_title,v_body,'student:formation','credit_grant',new.grant_id::text,
      jsonb_build_object('audience','student','person_id',v_row.person_id,'grant_id',new.grant_id,'balance_minutes',v_balance)
    );
  end loop;
  return new;
end;
$$;

-- -----------------------------------------------------------------------------
-- 5. Controlled read surfaces
-- -----------------------------------------------------------------------------
create or replace function public.credit_grant_is_usable(
  p_grant_id bigint,
  p_at timestamptz default now()
)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_person_id bigint;
begin
  if (select private.is_staff()) then
    return private.credit_grant_is_usable_unchecked(p_grant_id, p_at);
  end if;

  select private.current_person_id() into v_person_id;
  if v_person_id is null or not exists(
    select 1
    from public.credit_grant_members gm
    where gm.grant_id = p_grant_id and gm.person_id = v_person_id
  ) then
    raise exception 'No tienes permiso para consultar este bono.' using errcode='42501';
  end if;

  return private.credit_grant_is_usable_unchecked(p_grant_id, p_at);
end;
$$;

create or replace function public.billing_person_facts(
  p_person_id bigint,
  p_at timestamptz default now()
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_current_person_id bigint;
begin
  if not (select private.is_staff()) then
    select private.current_person_id() into v_current_person_id;
    if v_current_person_id is distinct from p_person_id then
      raise exception 'No tienes permiso para consultar estos hechos de Billing.' using errcode='42501';
    end if;
  end if;

  if not exists(select 1 from public.people p where p.id = p_person_id and p.active) then
    raise exception 'La persona no existe o no está activa.' using errcode='P0002';
  end if;

  return jsonb_build_object(
    'person_id', p_person_id,
    'at', p_at,
    'has_usable_presential_bonus', private.person_has_usable_presential_bonus_unchecked(p_person_id, p_at),
    'has_qualifying_presential_billing_intent', private.person_has_qualifying_presential_billing_intent_unchecked(p_person_id, p_at)
  );
end;
$$;

revoke all on function public.credit_grant_is_usable(bigint,timestamptz) from public, anon;
grant execute on function public.credit_grant_is_usable(bigint,timestamptz) to authenticated, service_role;
revoke all on function public.billing_person_facts(bigint,timestamptz) from public, anon;
grant execute on function public.billing_person_facts(bigint,timestamptz) to authenticated, service_role;

-- -----------------------------------------------------------------------------
-- 6. Canonical create/edit/pause/resume/refund workflows
-- -----------------------------------------------------------------------------
create or replace function public.create_credit_grant_v2(
  p_person_ids bigint[],
  p_modality text,
  p_minutes integer,
  p_price_cents integer default 0,
  p_label text default null,
  p_payment_status text default 'paid',
  p_starts_at timestamptz default now(),
  p_expires_at timestamptz default null,
  p_reason text default null
)
returns public.credit_grants
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_clean_ids bigint[];
  v_expected integer;
  v_grant public.credit_grants;
  v_reason text := coalesce(nullif(btrim(p_reason),''), 'Alta de bono');
begin
  if not (select private.is_staff()) then
    raise exception 'No tienes permiso para crear bonos.' using errcode='42501';
  end if;
  if p_modality not in ('individual','pair') then
    raise exception 'Modalidad no válida.' using errcode='22023';
  end if;
  if p_minutes is null or p_minutes <= 0 or p_minutes > 100000 then
    raise exception 'La capacidad del bono no es válida.' using errcode='22023';
  end if;
  if coalesce(p_price_cents,0) < 0 then
    raise exception 'El importe no puede ser negativo.' using errcode='22023';
  end if;
  if p_payment_status not in ('paid','pending') then
    raise exception 'Estado de pago no válido.' using errcode='22023';
  end if;
  if p_starts_at is null then
    raise exception 'La fecha de inicio es obligatoria.' using errcode='22023';
  end if;
  if p_expires_at is not null and p_expires_at <= p_starts_at then
    raise exception 'La caducidad debe ser posterior al inicio.' using errcode='22023';
  end if;

  select coalesce(array_agg(id order by id),'{}'::bigint[])
  into v_clean_ids
  from (select distinct unnest(coalesce(p_person_ids,'{}'::bigint[])) id) s;

  v_expected := case when p_modality='pair' then 2 else 1 end;
  if cardinality(v_clean_ids) <> v_expected then
    raise exception 'El bono requiere % persona(s) distintas.', v_expected using errcode='22023';
  end if;
  if (select count(*) from public.people p where p.id=any(v_clean_ids) and p.active) <> v_expected then
    raise exception 'Hay personas no válidas o inactivas.' using errcode='22023';
  end if;

  insert into public.credit_grants(
    modality,label,total_minutes,price_cents,payment_status,status,
    purchased_at,starts_at,expires_at,created_by
  ) values (
    p_modality,nullif(btrim(p_label),''),p_minutes,coalesce(p_price_cents,0),p_payment_status,'active',
    now(),p_starts_at,p_expires_at,(select auth.uid())
  ) returning * into v_grant;

  insert into public.credit_grant_members(grant_id,person_id)
  select v_grant.id, unnest(v_clean_ids);

  insert into public.credit_movements(
    grant_id,movement_type,delta_minutes,note,created_by,occurred_at,provenance
  ) values (
    v_grant.id,'grant',p_minutes,v_reason,(select auth.uid()),now(),
    jsonb_build_object('operation','grant_created')
  );

  insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
  values(
    'credit_grant_created','credit_grant',v_grant.id::text,'Bono creado',
    jsonb_build_object('before',null,'after',to_jsonb(v_grant),'person_ids',v_clean_ids,'reason',v_reason),
    (select auth.uid())
  );

  return v_grant;
end;
$$;

-- Compatibility signature: existing callers keep one source of business truth.
create or replace function public.create_credit_grant(
  p_student_ids bigint[],
  p_modality text,
  p_minutes integer,
  p_price_cents integer default 0,
  p_label text default null,
  p_payment_status text default 'paid'
)
returns public.credit_grants
language plpgsql
set search_path = ''
as $$
begin
  return public.create_credit_grant_v2(
    p_student_ids,p_modality,p_minutes,p_price_cents,p_label,p_payment_status,
    now(),null,'Alta de bono'
  );
end;
$$;

create or replace function public.edit_credit_grant(
  p_grant_id bigint,
  p_label text,
  p_total_minutes integer,
  p_price_cents integer,
  p_purchased_at timestamptz,
  p_starts_at timestamptz,
  p_expires_at timestamptz,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_grant public.credit_grants;
  v_before jsonb;
  v_after jsonb;
  v_balance integer;
  v_balance_without_refunds integer;
  v_consumed integer;
  v_capacity_delta integer;
  v_reason text := nullif(btrim(p_reason),'');
begin
  if not (select private.is_staff()) then
    raise exception 'No tienes permiso para editar bonos.' using errcode='42501';
  end if;
  if v_reason is null then
    raise exception 'Indica el motivo del cambio.' using errcode='22023';
  end if;
  if p_total_minutes is null or p_total_minutes <= 0 or p_total_minutes > 100000 then
    raise exception 'La capacidad del bono no es válida.' using errcode='22023';
  end if;
  if p_price_cents is null or p_price_cents < 0 then
    raise exception 'El importe no puede ser negativo.' using errcode='22023';
  end if;
  if p_purchased_at is null or p_starts_at is null then
    raise exception 'Compra e inicio son obligatorios.' using errcode='22023';
  end if;
  if p_expires_at is not null and p_expires_at <= p_starts_at then
    raise exception 'La caducidad debe ser posterior al inicio.' using errcode='22023';
  end if;

  select * into v_grant
  from public.credit_grants
  where id=p_grant_id
  for update;
  if not found then raise exception 'El bono no existe.' using errcode='P0002'; end if;
  if v_grant.status='cancelled' or v_grant.payment_status='refunded' then
    raise exception 'Este bono está en estado terminal y no puede editarse.' using errcode='22023';
  end if;

  v_before := to_jsonb(v_grant) || jsonb_build_object(
    'balance_minutes', private.credit_grant_balance_minutes_unchecked(p_grant_id)
  );

  select coalesce(sum(m.delta_minutes) filter (where m.movement_type <> 'refund'),0)::integer
  into v_balance_without_refunds
  from public.credit_movements m
  where m.grant_id=p_grant_id;

  v_consumed := greatest(v_grant.total_minutes - v_balance_without_refunds, 0);
  if p_total_minutes < v_consumed then
    raise exception 'La capacidad no puede quedar por debajo del consumo histórico válido (% min).',v_consumed using errcode='22023';
  end if;

  v_capacity_delta := p_total_minutes - v_grant.total_minutes;
  if v_capacity_delta <> 0 then
    insert into public.credit_movements(
      grant_id,movement_type,delta_minutes,note,created_by,occurred_at,provenance
    ) values (
      p_grant_id,'adjustment',v_capacity_delta,
      'Corrección de capacidad · '||v_reason,(select auth.uid()),now(),
      jsonb_build_object('operation','capacity_edit','old_total_minutes',v_grant.total_minutes,'new_total_minutes',p_total_minutes)
    );
  end if;

  update public.credit_grants
  set label=nullif(btrim(p_label),''),
      total_minutes=p_total_minutes,
      price_cents=p_price_cents,
      purchased_at=p_purchased_at,
      starts_at=p_starts_at,
      expires_at=p_expires_at,
      updated_at=now()
  where id=p_grant_id
  returning * into v_grant;

  v_balance := private.credit_grant_balance_minutes_unchecked(p_grant_id);
  v_after := to_jsonb(v_grant) || jsonb_build_object('balance_minutes',v_balance);

  insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
  values(
    'credit_grant_edited','credit_grant',p_grant_id::text,'Bono editado',
    jsonb_build_object('before',v_before,'after',v_after,'reason',v_reason,'valid_consumption_minutes',v_consumed),
    (select auth.uid())
  );

  return jsonb_build_object('grant',to_jsonb(v_grant),'balance_minutes',v_balance,'valid_consumption_minutes',v_consumed);
end;
$$;

create or replace function public.pause_credit_grant(
  p_grant_id bigint,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_grant public.credit_grants;
  v_pause public.credit_grant_pause_periods;
  v_reason text := nullif(btrim(p_reason),'');
  v_before jsonb;
begin
  if not (select private.is_staff()) then
    raise exception 'No tienes permiso para pausar bonos.' using errcode='42501';
  end if;
  if v_reason is null then raise exception 'Indica el motivo de la pausa.' using errcode='22023'; end if;

  select * into v_grant from public.credit_grants where id=p_grant_id for update;
  if not found then raise exception 'El bono no existe.' using errcode='P0002'; end if;
  if v_grant.status <> 'active' or v_grant.payment_status not in ('paid','pending') then
    raise exception 'Este bono está en un estado terminal y no puede pausarse.' using errcode='22023';
  end if;
  if private.credit_grant_balance_minutes_unchecked(p_grant_id) <= 0 then
    raise exception 'Un bono sin saldo no puede pausarse.' using errcode='22023';
  end if;
  if private.credit_grant_effective_expires_at_unchecked(p_grant_id,now()) is not null
     and private.credit_grant_effective_expires_at_unchecked(p_grant_id,now()) <= now() then
    raise exception 'Un bono caducado no puede pausarse.' using errcode='22023';
  end if;
  if private.credit_grant_is_paused_unchecked(p_grant_id,now()) then
    raise exception 'El bono ya está pausado.' using errcode='22023';
  end if;

  v_before := jsonb_build_object(
    'paused',false,
    'effective_expires_at',private.credit_grant_effective_expires_at_unchecked(p_grant_id,now())
  );

  insert into public.credit_grant_pause_periods(grant_id,paused_at,pause_reason,paused_by)
  values(p_grant_id,now(),v_reason,(select auth.uid()))
  returning * into v_pause;

  insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
  values(
    'credit_grant_paused','credit_grant',p_grant_id::text,'Bono pausado',
    jsonb_build_object('before',v_before,'after',jsonb_build_object('paused',true,'pause',to_jsonb(v_pause)),'reason',v_reason),
    (select auth.uid())
  );

  return jsonb_build_object('grant_id',p_grant_id,'paused',true,'pause',to_jsonb(v_pause));
end;
$$;

create or replace function public.resume_credit_grant(
  p_grant_id bigint,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_grant public.credit_grants;
  v_pause public.credit_grant_pause_periods;
  v_reason text := nullif(btrim(p_reason),'');
  v_before_expiry timestamptz;
  v_after_expiry timestamptz;
begin
  if not (select private.is_staff()) then
    raise exception 'No tienes permiso para reanudar bonos.' using errcode='42501';
  end if;
  if v_reason is null then raise exception 'Indica el motivo de la reanudación.' using errcode='22023'; end if;

  select * into v_grant from public.credit_grants where id=p_grant_id for update;
  if not found then raise exception 'El bono no existe.' using errcode='P0002'; end if;

  select * into v_pause
  from public.credit_grant_pause_periods
  where grant_id=p_grant_id and resumed_at is null
  order by paused_at desc
  limit 1
  for update;
  if not found then raise exception 'El bono no está pausado.' using errcode='22023'; end if;

  v_before_expiry := private.credit_grant_effective_expires_at_unchecked(p_grant_id,now());

  update public.credit_grant_pause_periods
  set resumed_at=now(),resume_reason=v_reason,resumed_by=(select auth.uid()),updated_at=now()
  where id=v_pause.id
  returning * into v_pause;

  v_after_expiry := private.credit_grant_effective_expires_at_unchecked(p_grant_id,now());

  insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
  values(
    'credit_grant_resumed','credit_grant',p_grant_id::text,'Bono reanudado',
    jsonb_build_object(
      'before',jsonb_build_object('paused',true,'effective_expires_at',v_before_expiry),
      'after',jsonb_build_object('paused',false,'effective_expires_at',v_after_expiry,'pause',to_jsonb(v_pause)),
      'reason',v_reason
    ),
    (select auth.uid())
  );

  return jsonb_build_object('grant_id',p_grant_id,'paused',false,'effective_expires_at',v_after_expiry,'pause',to_jsonb(v_pause));
end;
$$;

create or replace function public.refund_credit_grant_total(
  p_grant_id bigint,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_grant public.credit_grants;
  v_before jsonb;
  v_after jsonb;
  v_balance integer;
  v_reason text := nullif(btrim(p_reason),'');
begin
  if not (select private.is_staff()) then
    raise exception 'No tienes permiso para reembolsar bonos.' using errcode='42501';
  end if;
  if v_reason is null then raise exception 'Indica el motivo del reembolso.' using errcode='22023'; end if;

  select * into v_grant from public.credit_grants where id=p_grant_id for update;
  if not found then raise exception 'El bono no existe.' using errcode='P0002'; end if;
  if v_grant.payment_status='refunded' then
    return jsonb_build_object('grant_id',p_grant_id,'already_refunded',true,'balance_minutes',private.credit_grant_balance_minutes_unchecked(p_grant_id));
  end if;

  v_balance := private.credit_grant_balance_minutes_unchecked(p_grant_id);
  v_before := to_jsonb(v_grant) || jsonb_build_object('balance_minutes',v_balance);

  if v_balance > 0 then
    insert into public.credit_movements(
      grant_id,movement_type,delta_minutes,note,created_by,occurred_at,provenance
    ) values (
      p_grant_id,'refund',-v_balance,'Reembolso total · '||v_reason,(select auth.uid()),now(),
      jsonb_build_object('operation','total_refund')
    );
  end if;

  update public.credit_grant_pause_periods
  set resumed_at=coalesce(resumed_at,now()),
      resume_reason=case when resumed_at is null then 'Cierre por reembolso total' else resume_reason end,
      resumed_by=case when resumed_at is null then (select auth.uid()) else resumed_by end,
      updated_at=now()
  where grant_id=p_grant_id and resumed_at is null;

  update public.credit_grants
  set payment_status='refunded',status='cancelled',updated_at=now()
  where id=p_grant_id
  returning * into v_grant;

  v_after := to_jsonb(v_grant) || jsonb_build_object('balance_minutes',private.credit_grant_balance_minutes_unchecked(p_grant_id));

  insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
  values(
    'credit_grant_refunded_total','credit_grant',p_grant_id::text,'Bono reembolsado totalmente',
    jsonb_build_object('before',v_before,'after',v_after,'reason',v_reason),
    (select auth.uid())
  );

  return jsonb_build_object('grant',to_jsonb(v_grant),'balance_minutes',private.credit_grant_balance_minutes_unchecked(p_grant_id));
end;
$$;

-- -----------------------------------------------------------------------------
-- 7. Temporary Admin gate + historical import
-- -----------------------------------------------------------------------------
create or replace function public.set_billing_historical_import_enabled(
  p_enabled boolean,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_before public.billing_admin_settings;
  v_after public.billing_admin_settings;
  v_reason text := nullif(btrim(p_reason),'');
begin
  if not (select private.billing_is_admin()) then
    raise exception 'Solo Administración puede cambiar el modo histórico de bonos.' using errcode='42501';
  end if;
  if p_enabled is null then raise exception 'Indica si el modo histórico queda activado o desactivado.' using errcode='22023'; end if;
  if v_reason is null then raise exception 'Indica el motivo del cambio.' using errcode='22023'; end if;

  select * into v_before from public.billing_admin_settings where singleton for update;

  update public.billing_admin_settings
  set allow_historical_bonus_import=p_enabled,updated_by=(select auth.uid()),updated_at=now()
  where singleton
  returning * into v_after;

  insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
  values(
    'billing_historical_import_gate_changed','billing_admin_settings','historical_bonus_import',
    case when p_enabled then 'Alta histórica de bonos activada' else 'Alta histórica de bonos desactivada' end,
    jsonb_build_object('before',to_jsonb(v_before),'after',to_jsonb(v_after),'reason',v_reason),
    (select auth.uid())
  );

  return to_jsonb(v_after);
end;
$$;

create or replace function public.import_historical_credit_grant(
  p_person_ids bigint[],
  p_modality text,
  p_total_minutes integer,
  p_price_cents integer,
  p_label text,
  p_payment_status text,
  p_purchased_at timestamptz,
  p_purchase_date_approximate boolean,
  p_starts_at timestamptz,
  p_expires_at timestamptz,
  p_prior_consumption jsonb,
  p_provenance text,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_grant public.credit_grants;
  v_clean_ids bigint[];
  v_expected integer;
  v_item jsonb;
  v_minutes integer;
  v_consumed integer := 0;
  v_occurred_at timestamptz;
  v_item_provenance text;
  v_reason text := nullif(btrim(p_reason),'');
  v_provenance text := nullif(btrim(p_provenance),'');
begin
  if not (select private.billing_is_admin()) then
    raise exception 'Solo Administración puede importar bonos históricos.' using errcode='42501';
  end if;
  if not coalesce((select s.allow_historical_bonus_import from public.billing_admin_settings s where s.singleton),false) then
    raise exception 'El modo de alta histórica de bonos está desactivado.' using errcode='42501';
  end if;
  if v_reason is null or v_provenance is null then
    raise exception 'Motivo y procedencia histórica son obligatorios.' using errcode='22023';
  end if;
  if p_modality not in ('individual','pair') then raise exception 'Modalidad no válida.' using errcode='22023'; end if;
  if p_total_minutes is null or p_total_minutes<=0 or p_total_minutes>100000 then raise exception 'La capacidad no es válida.' using errcode='22023'; end if;
  if p_price_cents is null or p_price_cents<0 then raise exception 'El importe no puede ser negativo.' using errcode='22023'; end if;
  if p_payment_status not in ('paid','pending') then raise exception 'Estado de pago histórico no válido.' using errcode='22023'; end if;
  if p_purchased_at is null or p_starts_at is null then raise exception 'Compra e inicio históricos son obligatorios.' using errcode='22023'; end if;
  if p_expires_at is not null and p_expires_at<=p_starts_at then raise exception 'La caducidad debe ser posterior al inicio.' using errcode='22023'; end if;
  if p_prior_consumption is null then p_prior_consumption := '[]'::jsonb; end if;
  if jsonb_typeof(p_prior_consumption)<>'array' or jsonb_array_length(p_prior_consumption)>1000 then
    raise exception 'Los consumos históricos no son válidos.' using errcode='22023';
  end if;

  select coalesce(array_agg(id order by id),'{}'::bigint[])
  into v_clean_ids
  from (select distinct unnest(coalesce(p_person_ids,'{}'::bigint[])) id) s;
  v_expected := case when p_modality='pair' then 2 else 1 end;
  if cardinality(v_clean_ids)<>v_expected then raise exception 'Número de personas no válido para el bono.' using errcode='22023'; end if;
  if (select count(*) from public.people p where p.id=any(v_clean_ids) and p.active)<>v_expected then
    raise exception 'Hay personas no válidas o inactivas.' using errcode='22023';
  end if;

  for v_item in select value from jsonb_array_elements(p_prior_consumption) s(value) loop
    if jsonb_typeof(v_item)<>'object' then raise exception 'Consumo histórico no válido.' using errcode='22023'; end if;
    if coalesce(v_item->>'minutes','') !~ '^[0-9]+$' then raise exception 'Minutos históricos no válidos.' using errcode='22023'; end if;
    v_minutes := (v_item->>'minutes')::integer;
    if v_minutes<=0 then raise exception 'Los minutos históricos deben ser positivos.' using errcode='22023'; end if;
    if coalesce(v_item->>'occurred_at','')='' then raise exception 'Falta fecha del consumo histórico.' using errcode='22023'; end if;
    begin
      v_occurred_at := (v_item->>'occurred_at')::timestamptz;
    exception when others then
      raise exception 'Fecha de consumo histórico no válida.' using errcode='22023';
    end;
    v_item_provenance := nullif(btrim(v_item->>'provenance'),'');
    if v_item_provenance is null then raise exception 'Falta procedencia del consumo histórico.' using errcode='22023'; end if;
    v_consumed := v_consumed + v_minutes;
  end loop;

  if v_consumed > p_total_minutes then
    raise exception 'El consumo histórico supera la capacidad del bono.' using errcode='22023';
  end if;

  insert into public.credit_grants(
    modality,label,total_minutes,price_cents,payment_status,status,purchased_at,
    starts_at,expires_at,purchased_at_approximate,historical_provenance,created_by
  ) values (
    p_modality,nullif(btrim(p_label),''),p_total_minutes,p_price_cents,p_payment_status,
    case when v_consumed=p_total_minutes then 'exhausted' else 'active' end,
    p_purchased_at,p_starts_at,p_expires_at,coalesce(p_purchase_date_approximate,false),v_provenance,(select auth.uid())
  ) returning * into v_grant;

  insert into public.credit_grant_members(grant_id,person_id)
  select v_grant.id,unnest(v_clean_ids);

  insert into public.credit_movements(
    grant_id,movement_type,delta_minutes,note,created_by,occurred_at,date_approximate,provenance
  ) values (
    v_grant.id,'grant',p_total_minutes,'Alta histórica de bono',(select auth.uid()),p_purchased_at,
    coalesce(p_purchase_date_approximate,false),jsonb_build_object('origin','historical_import','provenance',v_provenance)
  );

  for v_item in select value from jsonb_array_elements(p_prior_consumption) s(value) loop
    v_minutes := (v_item->>'minutes')::integer;
    v_occurred_at := (v_item->>'occurred_at')::timestamptz;
    v_item_provenance := btrim(v_item->>'provenance');
    insert into public.credit_movements(
      grant_id,movement_type,delta_minutes,note,created_by,occurred_at,date_approximate,provenance
    ) values (
      v_grant.id,'adjustment',-v_minutes,
      coalesce(nullif(btrim(v_item->>'note'),''),'Consumo histórico importado'),
      (select auth.uid()),v_occurred_at,coalesce((v_item->>'date_approximate')::boolean,false),
      jsonb_build_object('origin','historical_import','provenance',v_item_provenance,'grant_provenance',v_provenance)
    );
  end loop;

  insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
  values(
    'credit_grant_historical_imported','credit_grant',v_grant.id::text,'Bono histórico importado',
    jsonb_build_object(
      'before',null,
      'after',to_jsonb(v_grant) || jsonb_build_object('balance_minutes',private.credit_grant_balance_minutes_unchecked(v_grant.id)),
      'person_ids',v_clean_ids,'historical_consumed_minutes',v_consumed,'provenance',v_provenance,'reason',v_reason
    ),
    (select auth.uid())
  );

  return jsonb_build_object('grant',to_jsonb(v_grant),'balance_minutes',private.credit_grant_balance_minutes_unchecked(v_grant.id));
end;
$$;

-- -----------------------------------------------------------------------------
-- 8. Append-only correction contract (DP-BONUS-15 = 15A)
-- -----------------------------------------------------------------------------
create or replace function public.correct_credit_consumption(
  p_original_movement_id bigint,
  p_replacement_consumed_minutes integer,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_original public.credit_movements;
  v_grant public.credit_grants;
  v_correction_sum integer;
  v_current_effective_delta integer;
  v_target_delta integer;
  v_delta integer;
  v_balance_before integer;
  v_balance_after integer;
  v_reason text := nullif(btrim(p_reason),'');
  v_new_movement_id bigint;
begin
  if not (select private.is_staff()) then
    raise exception 'No tienes permiso para corregir consumos de bonos.' using errcode='42501';
  end if;
  if v_reason is null then raise exception 'Indica el motivo de la corrección.' using errcode='22023'; end if;
  if p_replacement_consumed_minutes is null or p_replacement_consumed_minutes < 0 then
    raise exception 'El consumo corregido no puede ser negativo.' using errcode='22023';
  end if;

  select * into v_original
  from public.credit_movements
  where id=p_original_movement_id
  for update;
  if not found then raise exception 'El movimiento original no existe.' using errcode='P0002'; end if;
  if v_original.reverses_movement_id is not null then
    raise exception 'La corrección debe apuntar al movimiento original, no a otra corrección.' using errcode='22023';
  end if;
  if v_original.delta_minutes >= 0 or v_original.movement_type not in ('class','adjustment') then
    raise exception 'Este movimiento no representa un consumo corregible.' using errcode='22023';
  end if;

  select * into v_grant from public.credit_grants where id=v_original.grant_id for update;
  if not found then raise exception 'El bono del movimiento ya no existe.' using errcode='P0002'; end if;
  if p_replacement_consumed_minutes > v_grant.total_minutes then
    raise exception 'El consumo corregido supera la capacidad del bono.' using errcode='22023';
  end if;

  select coalesce(sum(m.delta_minutes),0)::integer
  into v_correction_sum
  from public.credit_movements m
  where m.reverses_movement_id=v_original.id;

  v_current_effective_delta := v_original.delta_minutes + v_correction_sum;
  v_target_delta := -p_replacement_consumed_minutes;
  v_delta := v_target_delta - v_current_effective_delta;
  v_balance_before := private.credit_grant_balance_minutes_unchecked(v_grant.id);
  v_balance_after := v_balance_before + v_delta;

  if v_balance_after < 0 then
    raise exception 'La corrección dejaría el bono con saldo negativo.' using errcode='22023';
  end if;

  if v_delta <> 0 then
    insert into public.credit_movements(
      grant_id,person_id,class_id,movement_type,delta_minutes,note,created_by,
      occurred_at,date_approximate,reverses_movement_id,provenance
    ) values (
      v_original.grant_id,v_original.person_id,v_original.class_id,'adjustment',v_delta,
      'Corrección de consumo · '||v_reason,(select auth.uid()),now(),false,v_original.id,
      jsonb_build_object(
        'operation','consumption_correction',
        'original_movement_id',v_original.id,
        'original_movement_type',v_original.movement_type,
        'original_class_id',v_original.class_id,
        'original_provenance',v_original.provenance,
        'replacement_consumed_minutes',p_replacement_consumed_minutes
      )
    ) returning id into v_new_movement_id;
  end if;

  if v_grant.payment_status <> 'refunded' and v_grant.status <> 'cancelled' then
    update public.credit_grants
    set status=case when v_balance_after<=0 then 'exhausted' else 'active' end,updated_at=now()
    where id=v_grant.id;
  end if;

  insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
  values(
    'credit_consumption_corrected','credit_grant',v_grant.id::text,'Consumo de bono corregido',
    jsonb_build_object(
      'before',jsonb_build_object(
        'original_movement_id',v_original.id,'effective_delta_minutes',v_current_effective_delta,
        'effective_consumed_minutes',greatest(-v_current_effective_delta,0),'balance_minutes',v_balance_before,
        'class_id',v_original.class_id,'source_provenance',v_original.provenance
      ),
      'after',jsonb_build_object(
        'replacement_consumed_minutes',p_replacement_consumed_minutes,'correction_delta_minutes',v_delta,
        'balance_minutes',v_balance_after,'correction_movement_id',v_new_movement_id,
        'class_id',v_original.class_id,'source_provenance',v_original.provenance
      ),
      'reason',v_reason
    ),
    (select auth.uid())
  );

  return jsonb_build_object(
    'grant_id',v_grant.id,
    'original_movement_id',v_original.id,
    'correction_movement_id',v_new_movement_id,
    'replacement_consumed_minutes',p_replacement_consumed_minutes,
    'balance_minutes',v_balance_after,
    'class_id',v_original.class_id
  );
end;
$$;

-- Compatibility endpoint remains append-only but refuses to erase source-linked history.
create or replace function public.set_credit_grant_consumed_minutes(
  p_grant_id bigint,
  p_consumed_minutes integer,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_grant public.credit_grants;
  v_balance integer;
  v_target_balance integer;
  v_delta integer;
  v_before jsonb;
  v_note text := coalesce(nullif(btrim(p_note),''),'Ajuste manual de consumo');
begin
  if not (select private.is_staff()) then
    raise exception 'No tienes permiso para ajustar el consumo de bonos.' using errcode='42501';
  end if;

  select * into v_grant from public.credit_grants where id=p_grant_id for update;
  if not found then raise exception 'El bono no existe.' using errcode='P0002'; end if;
  if v_grant.status='cancelled' or v_grant.payment_status='refunded' then
    raise exception 'Este bono está en estado terminal; utiliza un flujo de corrección explícito.' using errcode='22023';
  end if;
  if exists(
    select 1 from public.credit_movements m
    where m.grant_id=p_grant_id
      and (
        m.class_id is not null
        or m.provenance->>'origin'='historical_import'
        or m.reverses_movement_id is not null
      )
  ) then
    raise exception 'Este bono tiene consumo con origen trazable. Corrige el movimiento original para preservar su fuente.' using errcode='22023';
  end if;
  if p_consumed_minutes is null or p_consumed_minutes<0 or p_consumed_minutes>v_grant.total_minutes then
    raise exception 'Los minutos consumidos deben estar entre 0 y %.',v_grant.total_minutes using errcode='22023';
  end if;

  v_balance := private.credit_grant_balance_minutes_unchecked(p_grant_id);
  v_before := jsonb_build_object('consumed_minutes',greatest(v_grant.total_minutes-v_balance,0),'balance_minutes',v_balance,'status',v_grant.status);
  v_target_balance := v_grant.total_minutes-p_consumed_minutes;
  v_delta := v_target_balance-v_balance;

  if v_delta<>0 then
    insert into public.credit_movements(
      grant_id,movement_type,delta_minutes,note,created_by,occurred_at,provenance
    ) values (
      p_grant_id,'adjustment',v_delta,v_note,(select auth.uid()),now(),
      jsonb_build_object('operation','manual_consumption_target','target_consumed_minutes',p_consumed_minutes)
    );
  end if;

  update public.credit_grants
  set status=case when v_target_balance=0 then 'exhausted' else 'active' end,updated_at=now()
  where id=p_grant_id;

  insert into public.audit_events(event_type,entity_type,entity_id,summary,detail,actor_user_id)
  values(
    'credit_consumption_target_adjusted','credit_grant',p_grant_id::text,'Consumo manual de bono ajustado',
    jsonb_build_object(
      'before',v_before,
      'after',jsonb_build_object('consumed_minutes',p_consumed_minutes,'balance_minutes',v_target_balance,'status',case when v_target_balance=0 then 'exhausted' else 'active' end),
      'reason',v_note
    ),
    (select auth.uid())
  );

  return jsonb_build_object(
    'grant_id',p_grant_id,'total_minutes',v_grant.total_minutes,'consumed_minutes',p_consumed_minutes,
    'remaining_minutes',v_target_balance,'adjustment_minutes',v_delta
  );
end;
$$;

-- -----------------------------------------------------------------------------
-- 9. ACLs — authorization is enforced server-side inside RPCs
-- -----------------------------------------------------------------------------
revoke all on function public.create_credit_grant_v2(bigint[],text,integer,integer,text,text,timestamptz,timestamptz,text) from public, anon;
grant execute on function public.create_credit_grant_v2(bigint[],text,integer,integer,text,text,timestamptz,timestamptz,text) to authenticated, service_role;

revoke all on function public.create_credit_grant(bigint[],text,integer,integer,text,text) from public, anon;
grant execute on function public.create_credit_grant(bigint[],text,integer,integer,text,text) to authenticated, service_role;

revoke all on function public.edit_credit_grant(bigint,text,integer,integer,timestamptz,timestamptz,timestamptz,text) from public, anon;
grant execute on function public.edit_credit_grant(bigint,text,integer,integer,timestamptz,timestamptz,timestamptz,text) to authenticated, service_role;

revoke all on function public.pause_credit_grant(bigint,text) from public, anon;
grant execute on function public.pause_credit_grant(bigint,text) to authenticated, service_role;

revoke all on function public.resume_credit_grant(bigint,text) from public, anon;
grant execute on function public.resume_credit_grant(bigint,text) to authenticated, service_role;

revoke all on function public.refund_credit_grant_total(bigint,text) from public, anon;
grant execute on function public.refund_credit_grant_total(bigint,text) to authenticated, service_role;

revoke all on function public.set_billing_historical_import_enabled(boolean,text) from public, anon;
grant execute on function public.set_billing_historical_import_enabled(boolean,text) to authenticated, service_role;

revoke all on function public.import_historical_credit_grant(bigint[],text,integer,integer,text,text,timestamptz,boolean,timestamptz,timestamptz,jsonb,text,text) from public, anon;
grant execute on function public.import_historical_credit_grant(bigint[],text,integer,integer,text,text,timestamptz,boolean,timestamptz,timestamptz,jsonb,text,text) to authenticated, service_role;

revoke all on function public.correct_credit_consumption(bigint,integer,text) from public, anon;
grant execute on function public.correct_credit_consumption(bigint,integer,text) to authenticated, service_role;

revoke all on function public.set_credit_grant_consumed_minutes(bigint,integer,text) from public, anon;
grant execute on function public.set_credit_grant_consumed_minutes(bigint,integer,text) to authenticated, service_role;

-- Keep helper tables out of anon/authenticated direct DML even if future default grants change.
revoke insert, update, delete, truncate, references, trigger on public.credit_grant_pause_periods from anon, authenticated;
revoke insert, update, delete, truncate, references, trigger on public.billing_admin_settings from anon, authenticated;
